- examples/animation.js
- examples/control.html
- examples/geolocation.html
- examples/interactionbtngroup.html
- examples/interactiontoggle.html
- examples/layermanager.html
- examples/layeropacity.html
- examples/layertree.html
- examples/layertree.js
- examples/layervisibility.html
- examples/permalink.html
- examples/permalink.js
- examples/simple.html
- src/directives/layertree.js
- src/directives/map.js
User may want to change the tree.
> Allow tree property to be changed later

- src/directives/control.js
> Fixes the control directive usage example

- src/services/getbrowserlanguage.js
... when using `ngeo.GetBrowserLanguage`.
> Add note about closure externs file

- .gitignore
- Makefile
- bower.json
- buildtools/example.json
- buildtools/examples-all.json
- buildtools/ngeo.json
- examples/layerorder.html
- examples/layerorder.js
- externs/jqueryui.js
- package.json
- src/directives/sortable.js
- src/services/arraysync.js
- test/spec/services/arraysync.spec.js
With this pull request I want to add a new sortable directive. It allows user to change the order of elements in a list using drag&drop. A new example is added to show how to use this directive to sort the layers on the map.
Please review.
> Sortable layers

- examples/layerorder.html
- examples/layerorder.js
- externs/jqueryui.js
- src/directives/sortable.js
- src/services/arraysync.js
- test/spec/services/arraysync.spec.js
This PR addresses the missing things listed in https://github.com/camptocamp/ngeo/pull/148#issuecomment-71810480. This is WIP at this point.
> Changes to sortable and arraySync

- Makefile
- karma-conf.js
This PR should fix the build failures we're currently seeing in https://github.com/camptocamp/ngeo/pull/153.
> Fix build by adding paths to the ol.ext dir

- src/services/location.js
@asaunier, I added the "mock location provider" function to ngeo, next to the ngeoLocation service. What do you think?
> Document incompat between ngeoLocation and $location

- externs/jqueryui.js
> datepicker

- src/ol-ext/interactions/measureazimut.js
Without this the dragpan interaction doesn't work.
Please review.
> Don't stop event

- src/d3-ext/profile.js
The light profile is more compact and notably does not display axis.
> Light profile

- examples/measure.js
- exports/ol-ext/interactions/measure.js
- externs/ngeox.js
- src/ol-ext/interaction/measure.js
- src/ol-ext/interaction/measureazimut.js
- src/ol-ext/interaction/measurelength.js
The goal of this pull request it to enhance the azimut measure interaction. Distance is now shown. Also the user can add additional information when the measurement is finished.
Please review.
> Azimut distance

- externs/ngeox.js
- src/d3-ext/profile.js
This PR allows embedding inline style in the profile SVG.
It also contains some simplifications of the  `showPois` function.
> Profile inline styling

- externs/d3.js
- externs/ngeox.js
- src/d3-ext/profile.js
Allows to customize:
- number formatting;
- POI title angle;
- X axis ticks.
Also contains some small refactorings.
> More profile customizations

- externs/ngeox.js
- src/d3-ext/profile.js
This function allows constraining the Y domain based on the maximum
value of the X domain.
> Add ratioXYRule option to Profile

- src/services/location.js
- test/spec/services/location.spec.js
Allows checking if a param exists.
> Add location hasParam method

- externs/twbootstrap.js
> New extern for bootstrap's alert

- src/d3-ext/profile.js
#205 should be merged first.
The goal for this pull request is to send the distance and elevation to the hoverCallback so that we can format display on the chart and on the map the same way.
Please review.
> Profile hovercallback

- examples/geolocation.js
> We can't use bindTo anymore

- src/ol-ext/interaction/measurearea.js
This pull request aims to solve the following issue: https://github.com/Geoportail-Luxembourg/geoportailv3/issues/318
Please review.
> Switch to kilometers for larger values and lower precision

- examples/profile.html
- examples/profile.js
- src/d3-ext/profile.js
- src/directives/profile.js
With this pull request I added a way to manage interaction between map and interaction.
When the user hovers the map and the cursor is close to the line, then the corresponding value in the chart is highlighted.
Changes are required in the HTML code:
- `ngeo-profile` attribute is now called `ngeo-profile-data`,
- `ngeo-profile` attribute can now be used to store the D3 profile component.
Please review.
> Interaction map -> profile

- src/directives/profile.js
Google closure didn't detect my mistake.
Please review.
> Fix hoverCallback not being called with correct arguments

- buildtools/example.json
- buildtools/examples-all.json
- buildtools/ngeo.json
- examples/mapfishprint.html
- examples/mapfishprint.js
- exports/services/print.js
- exports/services/printutils.js
- externs/mapfish-print-v3.js
- src/services/print.js
- src/services/printutils.js
- test/spec/services/print.spec.js
See https://github.com/camptocamp/ngeo/pull/204 for details.
> Add support for MapFish Print v3

- src/ol-ext/interaction/measure.js
- src/ol-ext/interaction/measureazimut.js
This is to accomodate the changes done in https://github.com/openlayers/ol3/pull/3720.
> Rename ol.DrawEvent to ol.interaction.DrawEvent

- examples/search.js
- externs/ngeox.js
- src/directives/search.js
> Update code to match closure externs changes (ie. jQuery.Event)

- examples/search.js
- externs/ngeox.js
- src/directives/search.js
This reverts commit 049cfaa7c7630e938988a58356ab69c2f1c66eb8.
> Revert "Update code to match closure externs changes (ie. jQuery.Event)"

- src/services/print.js
I'll merge this when Travis build passes.
> Add missing goog.require

- src/services/print.js
- test/spec/services/print.spec.js
This PR adds a cancel method to the print service. 
Please review.
> Add a print cancel method

- examples/profile.js
- examples/search.js
This PR accomodates for [a change](https://github.com/openlayers/ol3/pull/3865) in OpenLayers 3.
Fixes #259.
> Replace fitExtent and fitGeometry by fit

- Makefile
- examples/animation.html
- examples/animation.js
- package.json
- src/directives/resizemap.js
> Don't use ngAnimate for resizemap directive anymore

- src/services/featureoverlay.js
- test/spec/services/featureoverlay.spec.js
Replaces #257.
Code rebased and tests added.
Please review.
> Add a feature overlay service

- .gitignore
- package.json
> Remove bower from package.json

- examples/backgroundlayer.js
Otherwise the one time binding doesn't work.
fixes #273
> Initialize layers array to 'undefined'

- src/directives/map.js
> Add missing require

- buildtools/example.json
- buildtools/examples-all.json
- buildtools/gmf.json
- contribs/gmf/examples/search.html
- contribs/gmf/examples/search.js
- contribs/gmf/externs/gmfx.js
- contribs/gmf/src/directives/search.js
- examples/search.js
- src/services/creategeojsonbloodhound.js
First draw of the GeoMapFish2's search. It is already able to group results and this, by accepting multiple sources (multiple urls with or without filters).
I've added a "filter" parameter in the src/service/creategeojsonbloodhound.js
> Bases for gmf search

- externs/mapfish-print-v3.js
- src/services/print.js
This supersedes https://github.com/camptocamp/ngeo/pull/302.
> Pass WMS version to MapFish Print

- buildtools/example.json
- buildtools/examples-all.json
- buildtools/gmf.json
- buildtools/ngeo.json
- examples/modal.html
- examples/modal.js
- src/directives/modal.js
> Adding a modal directive

- bower.json
Bower is not used anymore, so remove the unused `bower.json` file.
> Remove bower.json

- contribs/gmf/examples/search.js
- contribs/gmf/externs/gmfx.js
- contribs/gmf/src/directives/search.js
- Better naming for some properties of datasources.
- Different management for the url (more flexible).
Necessary for GMF2.
Can someone review this ?
> gmf-search - Better datasources

- README.md
And provide a link to the gmf examples.
Fixes #315.
> Mention gmf in the README

- contribs/gmf/examples/search.html
- contribs/gmf/examples/simple.html
- examples/animation.html
- examples/backgroundlayer.html
- examples/backgroundlayerdropdown.html
- examples/control.html
- examples/geolocation.html
- examples/interactionbtngroup.html
- examples/interactiontoggle.html
- examples/layeropacity.html
- examples/layerorder.html
- examples/layertree.html
- examples/layervisibility.html
- examples/mapfishprint.html
- examples/measure.html
- examples/modal.html
- examples/permalink.html
- examples/profile.html
- examples/scaleselector.html
- examples/search.html
- examples/simple.html
See http://www.w3.org/TR/html5/syntax.html#the-doctype
> Fix the HTML5 doctype

- contribs/gmf/src/proj/epsg2056projection.js
- contribs/gmf/src/proj/epsg21781projection.js
> Swiss projections

- .gitignore
- Makefile
- contribs/gmf/examples/mobileapp.html
- contribs/gmf/examples/mobileapp.js
- contribs/gmf/examples/style/mobileapp-main.less
- contribs/gmf/examples/style/mobileapp-map.less
- contribs/gmf/examples/style/mobileapp-nav.less
- contribs/gmf/examples/style/mobileapp-vars.less
- contribs/gmf/examples/style/reset.css
- package.json
This PR adds a mobile application to the GMF examples. The goal of this example is to develop a mobile layout for GMF. We'll start from a simple layout, with no functionality, and gradually functionality to the example.
> Add a mobile app GMF example

- Makefile
- contribs/gmf/examples/style/mobileapp-main.less
- contribs/gmf/examples/style/mobileapp-nav.less
- contribs/gmf/examples/style/mobileapp-vars.less
- package.json
With this pull request, we use bootstrap instead of other third-party less mixins.
> Get rid of more-or-less

- contribs/gmf/examples/locationchooser.html
- contribs/gmf/examples/locationchooser.js
- contribs/gmf/src/directives/locationchooser.js
A need to take a special action when a location is selected.
Comments welcome
> Add 'selectedLocation' scope property to gmf.locationchooserDirective

- src/services/featureoverlay.js
See https://github.com/Geoportail-Luxembourg/geoportailv3/issues/917
Comments welcome
> Fix ol.style.StyleFunction type annotation

- contribs/gmf/examples/mobileapp.html
- contribs/gmf/examples/mobileapp.js
- contribs/gmf/examples/style/mobileapp-nav.less
With this pull request we're changing the way the navigation is managed. The DOM structure is more flexible. Also the animations in the navigation bar are easier to handle.
@elemoine It would be nice if you could give the javascript part a more detailed review.
> Mobile app navigation

- src/ol-ext/format/featurehash.js
- src/services/featureoverlay.js
> Update ol.style.StyleFunction return type

- contribs/gmf/examples/search.js
- contribs/gmf/externs/gmfx.js
- contribs/gmf/src/directives/search.js
- src/services/creategeojsonbloodhound.js
My initial aim was to set easily the fetch limit of Typeahead but I've also changed the manner to configure Bloodhound.
> Can pass options to configure Typeahead

- package.json
> Update jsdoc to v3.4.0

- contribs/gmf/examples/style/mobileapp-nav.less
This pull request fixes issues with right sidebar showing up along with the left one.
Please review.
> Fix sidebars superposition on small screens

- Makefile
> `make gh-pages` is broken.

- contribs/gmf/examples/search.html
- contribs/gmf/src/directives/search.js
- examples/search.js
- externs/ngeox.js
- src/directives/search.js
An option to close with a button the search's results dropdown.
I've also adapted events for Typeahead 0.11
> Gmf search close button

- contribs/gmf/apps/mobile/less/nav.less
> Hide the horizontal scrollbar in the side navs

- src/directives/btngroup.js
- src/directives/control.js
- src/directives/layertree.js
- src/directives/profile.js
- src/directives/scaleselector.js
- src/directives/sortable.js
- src/services/creategeojsonbloodhound.js
> Fix example code in apidoc

- externs/ngeox.js
- jsdoc/config.json
- jsdoc/template/publish.js
- jsdoc/template/tmpl/container.tmpl
- jsdoc/template/tmpl/details.tmpl
fix #407, #352, #353,  #354, #349
> Add ngeox, add typedef, add namespaces

- contribs/gmf/apps/mobile/index.html
> Fix broken mobile navigation (sliding boxes)

- contribs/gmf/less/nav.less
> Adding drop shadow to main block.

- contribs/gmf/apps/mobile/js/mobile.js
> Add isMobile value

- src/ol-ext/format/featurehash.js
> Document featurehash

- examples/desktopgeolocation.html
- examples/desktopgeolocation.js
- externs/ngeox.js
- src/directives/desktopgeolocation.js
This PR introduces the `ngeo-desktop-geolocation` directive.
You can wait for #420 to be fully reviewed before reviewing this one as both have lots of things in common.
> [WIP] ngeo-desktop-geolocation

- src/directives/scaleselector.js
> Use the dotted notation for accessing this.scales

- Makefile
- contribs/gmf/apps/mobile/index.html
Fix https://github.com/camptocamp/ngeo/issues/459
> Fix loading of mobile.js in local mode

- docs/developer-guide.md
- docs/guidelines.md
This PR is a work in progress on additionnal guidelines for ngeo and gmf developpers.
It adds a new file, that will be in the end the final guildeline file (it's gonna be merged with the actual guideline.md i think).
The file can be preview here : https://github.com/fgravin/ngeo/blob/guidelines/docs/guidelines.md#development-guidelines
Also, some parts of the developper-guide were moved and extended to this new guideline, the purpose is to have
- a developper-guide that tells about how to get ngeo running, and how to set up your environnement to code and test
- guidelines that will give recommandation on how to code in ngeo and gmf.
@fredj is also working on this PR.
Please give your feedback on the content and the structure of this document and the global ngeo documentation.
> [WIP] - Update guidelines

- src/directives/mobilegeolocation.js
This PR fixes the gmf mobile geolocation controller behaviour with the following rule: when receiving an update of the location while tracking, only recenter the map to this location if the map hadn't been panned (or zoomed).
> Fix NgeoMobileGeolocation controller

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/examples/asitvd.html
- contribs/gmf/examples/locationchooser.html
- contribs/gmf/examples/search.html
- contribs/gmf/examples/simple.html
- examples/animation.html
- examples/backgroundlayer.html
- examples/backgroundlayerdropdown.html
- examples/control.html
- examples/desktopgeolocation.html
- examples/geolocation.html
- examples/importfeatures.html
- examples/interactionbtngroup.html
- examples/interactiontoggle.html
- examples/layeropacity.html
- examples/layerorder.html
- examples/layertree.html
- examples/layervisibility.html
- examples/locationchooser.html
- examples/mapfishprint.html
- examples/measure.html
- examples/mobilegeolocation.html
- examples/modal.html
- examples/permalink.html
- examples/profile.html
- examples/scaleselector.html
- examples/search.html
- examples/simple.html
- examples/toolActivate.html
see: 
https://developer.chrome.com/multidevice/android/installtohomescreen#comparison-to-ios
> Use stadard metadata

- buildtools/example.json
- buildtools/examples-all.json
- buildtools/generate-exports.js
- buildtools/gmf.json
- buildtools/ngeo.json
- buildtools/templatecache.mako.js
- contribs/gmf/apps/mobile/build.json
- contribs/gmf/apps/mobile/js/appmodule.js
- contribs/gmf/src/controllers/abstractmobile.js
- contribs/gmf/src/directives/map.js
- contribs/gmf/src/directives/search.js
- contribs/gmf/src/gmf.js
- externs/ngeox.js
- src/directives/desktopgeolocation.js
- src/directives/mobilegeolocation.js
- src/services/popup.js
- src/services/toolActivateMgr.js
> Add more closure-compiler checks

- package.json
> Set all package version to strict

- Makefile
- contribs/gmf/examples/layertree.html
- contribs/gmf/examples/search.html
Fixes #499.
Thanks @elemoine for the report.
Please review.
> Using local version for proj4js

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/apps/mobile/js/mobile.js
- contribs/gmf/examples/themeselector.html
- contribs/gmf/examples/themeselector.js
- contribs/gmf/less/map.less
- contribs/gmf/src/controllers/abstractmobile.js
- contribs/gmf/src/directives/partials/themeselector.html
- contribs/gmf/src/directives/themeselector.js
- contribs/gmf/src/services/themesservice.js
- contribs/gmf/test/spec/beforeeach.js
- contribs/gmf/test/spec/services/themesservice.spec.js
Replaces #478.
Still in progress.  I just want to see the Travis report.  Please, wait for further details before reviewing.
> [WIP] Add Theme Selector directive for GMF

- contribs/gmf/examples/data/themes.json
- contribs/gmf/src/directives/layertree.js
> Update data/theme.json - Metadata keys use camelcasing now

- contribs/gmf/examples/layertree.html
- contribs/gmf/externs/gmf-themes.js
- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/partials/layertree.html
- src/services/layerHelper.js
Example : http://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/layertree.html
Relative to c2c issue: https://github.com/camptocamp/c2cgeoportal/issues/1707
> Add legend icon and legend in gmf-layertree

- contribs/gmf/less/mobile-nav.less
Related to https://github.com/camptocamp/ngeo/issues/399
> Make sidebar slides scrollable in mobile app

- contribs/gmf/examples/layertree.html
- examples/backgroundlayer.html
- examples/interactionbtngroup.html
- examples/layertree.html
- examples/measure.html
- examples/profile.html
- examples/toolActivate.html
Ref to Issue https://github.com/camptocamp/c2cgeoportal/issues/1937
...And local Font-Awesome
> Use local bootstrap

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/apps/mobile/js/mobile.js
- contribs/gmf/src/controllers/abstractmobile.js
> Update the Localisation constants

- contribs/gmf/src/services/themesservice.js
fix https://github.com/camptocamp/c2cgeoportal/issues/1919
> Use the credentials in the theme request

- Makefile
- contribs/gmf/examples/layertree.html
- contribs/gmf/examples/themeselector.html
- examples/backgroundlayer.html
- examples/interactionbtngroup.html
- examples/layertree.html
- examples/measure.html
- examples/profile.html
- examples/toolActivate.html
* Ref to https://github.com/camptocamp/c2cgeoportal/issues/1937
* Fix #531 
* Following of https://github.com/camptocamp/ngeo/pull/526
* Example: http://ger-benjamin.github.io/ngeo/master/examples (/...)
> Fix built examples's dependances

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/examples/layertree.js
- contribs/gmf/examples/search.js
- contribs/gmf/src/directives/search.js
- externs/typeahead.js
- src/services/creategeojsonbloodhound.js
fix #509 
How to make it configurable?
> Add with credential in search requests

- contribs/gmf/apps/mobile/index.html
Closes https://github.com/camptocamp/c2cgeoportal/issues/1949
> Move login panel to right sidebar (mobile)

- contribs/gmf/src/directives/search.js
- externs/typeahead.js
- src/services/creategeojsonbloodhound.js
c2cgeoportal ref : https://github.com/camptocamp/c2cgeoportal/issues/1840
Exemple: None yet [wip]
> Add lang and interface params in search requests

- Makefile
see result: https://camptocamp.github.io/ngeo/fr/examples/contribs/gmf/apps/mobile/index.html?lang=fr
> Add missing fr language

- contribs/gmf/less/mobile.less
+ some less clean up
Fixes https://github.com/camptocamp/c2cgeoportal/issues/1964
> Move zoom/location buttons a bit up on tablets

- contribs/gmf/src/controllers/abstractmobile.js
fix https://github.com/camptocamp/c2cgeoportal/issues/1954
> Reduced zoom value when recentering. cf c2cgeoportal #1954.

- contribs/gmf/src/directives/layertree.js
Fix: https://github.com/camptocamp/c2cgeoportal/issues/1969
> Use visibility to 'add/remove' layers from layertree

- contribs/gmf/src/directives/search.js
c2cgeoportal ref : https://github.com/camptocamp/c2cgeoportal/issues/1656
ngeo issue: https://github.com/camptocamp/ngeo/issues/495
Example: http://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html
> Search - Blur after select resul

- Makefile
- buildtools/cleanup-ghpages.py
[https://github.com/camptocamp/c2cgeoportal/issues/1937]
> Remove gh-pages folder related of an no more existing branch

- .gitattributes
- Makefile
- buildtools/mako_build.json
- npm.mk
- package.json
related to https://github.com/camptocamp/c2cgeoportal/pull/1978 [https://github.com/camptocamp/c2cgeoportal/pull/1839]
> Some changes requied for c2cgeoportal integration

- Makefile
> Add missing 'contribs/gmf/data' in hosted examples

- contribs/gmf/examples/mobilebackgroundlayerselector.html
> Use node modules version of proj4js

- contribs/gmf/less/desktop.less
- contribs/gmf/src/directives/partials/search.html
Demo: https://pgiraud.github.io/ngeo/desktop_search/examples/contribs/gmf/apps/desktop/?map_zoom=12&map_x=736050&map_y=5867994
> Desktop search styling

- contribs/gmf/src/directives/search.js
> Don't filter out 'actions' results

- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/services/themesservice.js
- src/services/layerHelper.js
Do not use defer.
Reject failed promises.
> Rework ngeo.LayerHelper promise handling

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/apps/mobile/less/main.less
- contribs/gmf/less/desktop.less
- contribs/gmf/less/layertree.less
- contribs/gmf/less/mobile-nav.less
- contribs/gmf/less/mobile.less
- contribs/gmf/src/controllers/abstractdesktop.js
https://pgiraud.github.io/ngeo/desktop_theme/examples/contribs/gmf/apps/desktop/index.html
It still needs some styling.
[https://github.com/camptocamp/c2cgeoportal/issues/1839]
> Adding theme selector + layer tree in desktop app

- contribs/gmf/src/directives/mobilebackgroundlayerselector.js
- contribs/gmf/src/services/authenticationservice.js
- contribs/gmf/src/services/themesservice.js
- contribs/gmf/test/spec/services/themesservice.spec.js
- docs/guidelines.md
- package.json
- src/directives/desktopgeolocation.js
- src/directives/mobilegeolocation.js
- src/directives/scaleselector.js
- src/ol-ext/interaction/measure.js
- src/ol-ext/interaction/measureazimut.js
- src/services/backgroundlayermgr.js
- src/services/featureoverlay.js
> Use ol.events instead of goog.events

- Makefile
[https://github.com/camptocamp/c2cgeoportal/issues/1937]
> Add a cleanallcache make target

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/apps/mobile/js/controller.js
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/controllers/abstractdesktop.js
- contribs/gmf/src/controllers/abstractmobile.js
Create an abstract controller for booth applications
[https://github.com/camptocamp/c2cgeoportal/issues/1839]
> Add localisation in the desktop application

- Makefile
[https://github.com/camptocamp/c2cgeoportal/issues/1937]
> Fix the ghpages deploy

- Makefile
* And a variable with all the apps name
* Just add a statement to make it working...
* Add missing files to make clean and cleanall
> Add a single task to build alls the gmf apps.

- Makefile
> Fix compile-css target typo

- contribs/gmf/src/directives/themeselector.js
The current theme is the theme object
> Fix gmf-themeselector-currenttheme type

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/examples/search.js
- contribs/gmf/src/directives/search.js
- contribs/gmf/src/services/themesservice.js
> Handle add_theme results from search

- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/apps/mobile/js/controller.js
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/controllers/abstractdesktop.js
- contribs/gmf/src/controllers/abstractmobile.js
- src/directives/mobilequery.js
See https://github.com/camptocamp/ngeo/issues/634
Also fix ngeo.query dependency
> Optimize service injection in apps controllers

- Makefile
fix https://github.com/camptocamp/ngeo/issues/640
> Don't remove the fonts on the build

- Makefile
- buildtools/mako_build.json
- package.json
- src/directives/filereader.js
- test/spec/directives/filereader.spec.js
Rel to: camptocamp/c2cgeoportal#1800
Needed by: #582 
Example on: https://ger-benjamin.github.io/ngeo/master/examples
To implement the required animations, the best way I found was to use the new Angluar directive "ngAnimateSwap" see (https://docs.angularjs.org/api/ngAnimate/directive/ngAnimateSwap)
It works really fine but to use it, I had to update angular to 1.5.0.
Angular changelog: https://github.com/angular/angular.js/blob/master/CHANGELOG.md#150-ennoblement-facilitation-2016-02-05 and http://angularjs.blogspot.ch/2016/02/angular-150-ennoblement-facilitation.html
The two small modifications in the filereader.js is also for AngularJS 1.5.
> Update to AngularJS 1.5.0

- contribs/gmf/examples/data/themes.json
- contribs/gmf/externs/gmf-themes.js
- contribs/gmf/src/directives/layertree.js
- exports/services/layerHelper.js
- src/directives/layertree.js
- src/services/layerHelper.js
- test/spec/services/layerHelper.spec.js
Rel to: #576 and https://github.com/camptocamp/c2cgeoportal/issues/1970
Example: https://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/layertree.html
And: https://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html
Please review.
(Ignore coveralls ? I think it is not not happy because I've deleted some tests (but relatives methods too))
> Layertree one wms

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/src/controllers/abstract.js
Constant value(s) in "index.html" should be provided by the back end in the future.
> Dynamic grouping now possible.

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/externs/gmfx.js
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/directives/search.js
Group the search results by actions: "add_theme", "add_group" and "add_layer"
> Group the 'actions' results

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/src/directives/mobilenav.js
Fixes camptocamp/c2cgeoportal#1979.
> Mobile nav remove anchor

- Makefile
> Sed commands compatible with Mac (round 2)

- contribs/gmf/examples/mobilequery.html
- contribs/gmf/examples/mobilequery.js
- contribs/gmf/src/directives/mobiledisplayqueries.js
- contribs/gmf/src/directives/partials/mobiledisplayqueries.html
- contribs/gmf/src/services/querymanager.js
- externs/ngeox.js
- src/services/query.js
Strange issue (reason of the [wip] tag on this PR): 
- The dropdown is empty on smartphone (at least on IOS)... (see #663)
- I must add a ng-swipe-left/right to do actions (but I can't test that because of the first point)
Link to, and current state of work, on: camptocamp/c2cgeoportal#1800
~~Example: https://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/mobilequery.html (try it on "edit" theme layers)~~
> Gmf display queries

- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/directives/search.js
> Remove the 'INTERNAL' prefix in the search group

- contribs/gmf/less/desktop.less
> Hide the search-group for individual search result

- contribs/gmf/src/directives/themeselector.js
> Update theme name in url on add_theme

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/mobile/index.html
> Add the missing limits in the full-text search

- src/services/query.js
> Fix ngeoQueryResult constant typecast

- contribs/gmf/src/directives/authenticationdirective.js
- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/map.js
- contribs/gmf/src/directives/mobilebackgroundlayerselector.js
- contribs/gmf/src/directives/search.js
- contribs/gmf/src/directives/themeselector.js
- src/directives/desktopgeolocation.js
- src/directives/filereader.js
- src/directives/layertree.js
- src/directives/map.js
- src/directives/mobilegeolocation.js
- src/directives/mobilequery.js
- src/directives/popup.js
- src/directives/profile.js
- src/directives/recenter.js
- src/directives/resizemap.js
- src/directives/search.js
- src/services/decorategeolocation.js
- src/services/decorateinteraction.js
- src/services/decoratelayer.js
- src/services/popup.js
> Add an example in the theme selector, Uniformise the examples

- contribs/gmf/less/mobile-nav.less
shadows have now the same size
> Mobile: Small shadows left and right of search box

- .travis.yml
- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/src/directives/mobiledisplayqueries.js
- contribs/gmf/src/directives/mobilemeasurelength.js
- contribs/gmf/src/directives/mobilemeasurepoint.js
- contribs/gmf/src/services/altitude.js
- contribs/gmf/src/services/querymanager.js
> Put the documentation in the service, not on the main page

- jsdoc/config.json
- jsdoc/template/tmpl/details.tmpl
Removes the source copy
related to #539
> Do the source link to github

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/mobile/index.html
> Temporary deactivate 'add_group', 'add_layer' actions

- contribs/gmf/less/mobile-nav.less
Buttons are now square just like other buttons
> Mobile: Buttons left and right of search box

- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/services/querymanager.js
- externs/ngeox.js
- src/services/query.js
Rel to: https://github.com/camptocamp/c2cgeoportal/issues/1800
Little modification on https://github.com/camptocamp/ngeo/pull/692 (new PR so I can merge it faster)
Example on https://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/mobilequery.html (if theme don't load, reload the page, that's a github page issue. One this example, on github too, swisstopo WMTS can't be queried (CORS error))
> Fix query service 2nd

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/examples/asitvd.html
- contribs/gmf/examples/authentication.html
- contribs/gmf/examples/layertree.html
- contribs/gmf/examples/mobilebackgroundlayerselector.html
- contribs/gmf/examples/mobilemeasure.html
- contribs/gmf/examples/mobilequery.html
- contribs/gmf/examples/mobilequery.js
- contribs/gmf/examples/permalink.html
- contribs/gmf/examples/search.html
- contribs/gmf/examples/simple.html
- contribs/gmf/examples/themeselector.html
- contribs/gmf/less/mobile.less
- contribs/gmf/less/mobiledisplayqueries.less
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/controllers/abstractmobile.js
- contribs/gmf/src/directives/mobiledisplayqueries.js
- contribs/gmf/src/directives/partials/mobiledisplayqueries.html
- contribs/gmf/src/gmf.js
- karma-conf.js
Ref to https://github.com/camptocamp/c2cgeoportal/issues/1800
Example: https://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html
I don't currently use ng-swipe (for "gesture" actions) (further PR)
> Display queries in app mobile

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/mobile/index.html
Fix https://github.com/camptocamp/c2cgeoportal/issues/2000
> Set the default theme

- src/directives/layertree.js
Useless with Angular 1.5.0 and further
> Remove useless compile function in layertree

- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/map.js
- contribs/gmf/src/directives/mobilebackgroundlayerselector.js
- contribs/gmf/src/directives/search.js
- docs/guidelines.md
- src/directives/btngroup.js
- src/directives/control.js
- src/directives/desktopgeolocation.js
- src/directives/filereader.js
- src/directives/layertree.js
- src/directives/map.js
- src/directives/mobilegeolocation.js
- src/directives/profile.js
- src/directives/recenter.js
- src/directives/scaleselector.js
- src/directives/search.js
- src/directives/sortable.js
The know part of #679 
Partially fix #539
> Add some missing HTML attributes

- contribs/gmf/examples/mobilebackgroundlayerselector.html
- contribs/gmf/examples/mobilebackgroundlayerselector.js
- contribs/gmf/less/mobile.less
- contribs/gmf/src/controllers/abstractdesktop.js
- contribs/gmf/src/controllers/abstractmobile.js
- contribs/gmf/src/directives/mobilebackgroundlayerselector.js
- contribs/gmf/src/directives/partials/mobilebackgroundlayerselector.html
- docs/guidelines.md
`MobileBackgroundLayerSelector` to `Mobilebackgroundlayerselector` as in all others components.
Can be considered as relatif to #539
> Consistency on mobilebackgroundlayerselector name

- Makefile
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/examples/asitvd.html
- contribs/gmf/examples/authentication.html
- contribs/gmf/examples/layertree.html
- contribs/gmf/examples/mobilebackgroundlayerselector.html
- contribs/gmf/examples/mobilemeasure.html
- contribs/gmf/examples/mobilequery.html
- contribs/gmf/examples/permalink.html
- contribs/gmf/examples/search.html
- contribs/gmf/examples/simple.html
- contribs/gmf/examples/themeselector.html
- contribs/gmf/src/directives/partials/mobiledisplayqueries.html
- contribs/gmf/src/gmf.js
- karma-conf.js
- package.json
Ref to and require to close https://github.com/camptocamp/c2cgeoportal/issues/1800
Example on: https://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html (swipe deactivated for computers mouse)
This behavior is required by GMF v2.**0** but my code is not optimal, because:
- I think we don't need "touch" on desktop and I require this library on all gmf components.
- Angular-Touch support only right-to-left and left-to-right gestures. I'm sur we will need someday a swipe-up or swipe-down support...
I don't know if someone has a better idea to support gestures for GMF 2.0. Perhaps we can use this as is for now and make a better architecture to choose mobile/desktop requierments and to find a better library to support gestures for the v2.1.
---
~same discussion …
> Can swipe to switch betweens query results

- contribs/gmf/src/controllers/abstractmobile.js
- examples/desktopgeolocation.js
- examples/mobilegeolocation.js
- src/directives/desktopgeolocation.js
- src/directives/mobilegeolocation.js
Supersedes #560
Closes #489
Closes #560
> Emit event in case of geolocation error

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/less/map.less
> Use bg-layer-sel directive new name in mobile app

- contribs/gmf/src/directives/authenticationdirective.js
- contribs/gmf/src/directives/mobilemeasurelength.js
- contribs/gmf/src/directives/partials/authentication.html
- contribs/gmf/src/directives/partials/layertree.html
- contribs/gmf/src/directives/partials/mobilebackgroundlayerselector.html
- contribs/gmf/src/directives/partials/mobilemeasurelength.html
- contribs/gmf/src/directives/partials/mobilemeasurepoint.html
- contribs/gmf/src/directives/partials/themeselector.html
Closes https://github.com/camptocamp/ngeo/issues/733
@sbrunner, please check if this includes everything you had in mind with #733.
> Use `translate` filter

- buildtools/compile-catalog.js
- package.json
With one un existing or empty file, and an other
[https://github.com/camptocamp/c2cgeoportal/issues/1937]
> Fix compile catalog

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/src/directives/partials/search.html
Ref to https://github.com/camptocamp/c2cgeoportal/issues/1834
Someone watches others translations issues ?
> Fix some translations for 2.0

- contribs/gmf/src/directives/partials/mobiledisplayqueries.html
Ref to camptocamp/c2cgeoportal#1834
> Translate keys in queries displayer

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/src/directives/partials/mobiledisplayqueries.html
Ref to camptocamp/c2cgeoportal#1834
> Fix some translations for 2.0 round3

- contribs/gmf/apps/mobile/index.html
Ref to camptocamp/c2cgeoportal#1834
> Oups (last translation probleme)

- contribs/gmf/apps/mobile/index.html
Ref to camptocamp/c2cgeoportal#1834
> Very last translation issue for gmf2.0

- contribs/gmf/src/directives/search.js
Rel to https://github.com/camptocamp/c2cgeoportal/issues/1656https://github.com/camptocamp/c2cgeoportal/issues/1656
> Fix search

- buildtools/cleanup-ghpages.py
@sbrunner Something like that ?
> Don't fail on gh-pages cleanup

- examples/search.html
- examples/search.js
> Use GMF fulltext-search web-service for ngeo search example

- contribs/gmf/src/services/themesservice.js
Closes https://github.com/camptocamp/ngeo/issues/767
> Mark label for blank layer as translatable

- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/apps/mobile/js/controller.js
- contribs/gmf/examples/layertree.js
- contribs/gmf/examples/mobilebackgroundlayerselector.js
- contribs/gmf/examples/mobilemeasure.js
- contribs/gmf/examples/mobilequery.js
- contribs/gmf/examples/permalink.js
- contribs/gmf/examples/search.js
- examples/mapfishprint.js
- examples/mobilequery.js
- examples/search.js
- karma-conf.js
- src/proj/epsg2056projection.js
- src/proj/epsg21781projection.js
> Move projections into ngeo module

- docs/guidelines.md
Add example and UI metadata in the guideline
> Add Styling with less in the guidelines

- buildtools/cleanup-ghpages.py
Ignore Travis error on gh pages cleanup
> Catch TypeError not ValueError

- Makefile
> Gets the l10n strings from the demo to the apps

- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/mobilebackgroundlayerselector.js
- contribs/gmf/src/services/querymanager.js
> Add the UI metadata documentation

- examples/layerorder.js
- examples/permalink.js
> Use '!== undefined' instead of angular.isDefined()

- contribs/gmf/less/mobile.less
Demo: https://tsauerwein.github.io/ngeo/ios-center-button/examples/contribs/gmf/apps/mobile/index.html
Closes https://github.com/camptocamp/ngeo/issues/712
> Make sure buttons are centered horizontally on iOS

- src/services/print.js
> Graphic size is scale dependent

- contribs/gmf/apps/desktop/js/controller.js
The value is already defined in desktop/index.html
> Remove authenticationBaseUrl constant in app.DesktopController

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/directives/search.js
- src/services/autoprojection.js
- test/spec/services/autoprojection.spec.js
Ref to: https://github.com/camptocamp/ngeo/issues/696 and https://github.com/camptocamp/c2cgeoportal/issues/2044
Specs:  https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%23696-Search-for-coordinates-with-marker
Example: https://ger-benjamin.github.io/ngeo/search_coordinates/examples/contribs/gmf/apps/mobile
> Search coordinates

- contribs/gmf/src/directives/mobiledisplayqueries.js
- contribs/gmf/src/directives/mobilemeasurelength.js
- contribs/gmf/src/directives/mobilemeasurepoint.js
- contribs/gmf/src/directives/search.js
- src/directives/control.js
- src/directives/layertree.js
- src/directives/sortable.js
> Performed some correction in the documentation.

- src/directives/scaleselector.js
> Use ol.array.numberSafeCompareFunction to sort numbers

- contribs/gmf/examples/data/themes.json
This PR fixes the `"mixed"` values inside the themes.json file that were strings to boolean.
The official theme service returns a boolean for `"mixed"`.
> Fix themes.json - mixed should have a boolean value

- contribs/gmf/examples/themeselector.js
- contribs/gmf/src/services/querymanager.js
- contribs/gmf/src/services/themesservice.js
- contribs/gmf/test/spec/services/themesservice.spec.js
And remove the now unneeded `gmf.ThemesEventType.LOAD` event
fixes #877
> Remove the need to call gmf.Themes#loadThemes before any other functions

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/src/directives/search.js
- contribs/gmf/src/services/themesservice.js
TODO:
* display a notification message if the selected group is already present in the layer tree.
* check if it works in compiled mode
* add_layer: 
* if the layer exists in the current theme, set visibility to true
> Handle add_group and add_layer search result

- contribs/gmf/src/services/themesservice.js
Needed by https://github.com/camptocamp/ngeo/issues/779
> Use 'GmfThemesNode' instead of 'Object' in gmf themesservice

- contribs/gmf/src/directives/mobiledisplayqueries.js
- contribs/gmf/src/directives/partials/mobiledisplayqueries.html
Close https://github.com/camptocamp/ngeo/issues/756
Example: https://ger-benjamin.github.io/ngeo/filter_ol_features/examples/contribs/gmf/mobilequery.html
> Filter ol3 feature's properties before display them

- contribs/gmf/src/directives/partials/layertree.html
> adding ng-if on span.layerIcon to avoid useless DOM node creation

- contribs/gmf/less/layertree.less
- contribs/gmf/src/directives/partials/layertree.html
> Ability to expand/collapse branches in layer tree

- contribs/gmf/examples/data/themes.json
- contribs/gmf/less/layertree.less
- contribs/gmf/src/directives/partials/layertree.html
> Ouverture des noeuds par défaut avec la prop isExpanded

- src/services/decoratelayer.js
To allow ol.layer.Group to be decorated
> Allow ol.layer.Base to be decorated

- contribs/gmf/apps/desktop/index.html
Missing closing tag in previous commit.
> Update bg layer selector directive name

- contribs/gmf/less/search.less
Fix: https://github.com/camptocamp/ngeo/issues/904
Example: https://ger-benjamin.github.io/ngeo/cropped_search/examples/contribs/gmf/apps/desktop (and https://ger-benjamin.github.io/ngeo/cropped_search/examples/contribs/gmf/apps/mobile)
> Search field was cropped

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/less/base.less
Fix #760
I don't figure out what's really happening.
Seems an issue with the `ng-bind`. Definitly a race condition, i only reproduce if i disable the caching from my dev tools.
The fix seems to work. I don't really know what else we could do for the moment.
> Display theme name on page loading.

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/less/desktop.less
> Add bootstrap grid system in tools panel

- contribs/gmf/less/search.less
> Highlight search result on keyboard navigation

- contribs/gmf/src/directives/search.js
Fix: https://github.com/camptocamp/ngeo/issues/868
Example 1:
Config: Any filter, any actions. Search will give you as well for 'osm' layers that for 'district' layer but not for groups or theme (actions)... ). Selecting an osm layer that have "add_layer" action will not add this layer (only recenter).
Link: https://ger-benjamin.github.io/ngeo/disable_search_actions/examples/contribs/gmf/apps/mobile/index.html
Example 2:
Config: filters: 'osm', 'district'. Actions: 'add_theme', 'add_group', 'add_layer'. You can search only for 'osm' and 'district' layers. You can also search for theme, groups and layers... (actions). Selecting an osm layer that have "add_layer" action will add this layer and recenter.
Link: https://ger-benjamin.github.io/ngeo/disable_search_actions/examples/contribs/gmf/ap …
> Can disable search actions

- contribs/gmf/src/services/querymanager.js
fixes #963 
Cherry-pick #938 into the 2.0 branch
> Don't create query sources for WMTS layers without wmsUrl

- contribs/gmf/src/services/themesservice.js
> Only create background layers once

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/directives/mobilebackgroundlayerselector.js
> Get the default basemap from the user functionalities

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/less/mobile-nav.less
Closes https://github.com/camptocamp/ngeo/issues/604
> Add "Back" label to mobile navigation

- contribs/gmf/src/directives/partials/layertree.html
> Bug fixing expanded group

- Makefile
- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/apps/mobile/js/controller.js
> Fix the resolution as it is in the CGXP demo

- contribs/gmf/src/services/permalink.js
- contribs/gmf/test/spec/services/permalinkservice.spec.js
@adube @fgravin related to #1018  comments, I pushed a new version avoiding listeners when layer is a ol.layer.Group
> Permalink service should not add listeners on ol.layer.Group

- contribs/gmf/src/services/permalink.js
- contribs/gmf/test/spec/services/permalinkservice.spec.js
> Layertree state is not consistent with localstorage

- contribs/gmf/src/directives/layertree.js
> fix trailing comma at the end of tree_group_layer_Layers in localStorage

- contribs/gmf/src/services/permalink.js
See https://github.com/camptocamp/ngeo/commit/8fc4bdab4c8121f26e972270c0304be1e584a42d#commitcomment-17212333
> Remove obsolete FIXME comment

- contribs/gmf/less/desktop.less
- contribs/gmf/less/desktoplayertree.less
- contribs/gmf/less/layertree.less
- contribs/gmf/src/controllers/abstractdesktop.js
- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/partials/layertree.html
- contribs/gmf/test/spec/controllers/gmflayertreecontroller.spec.js
- src/directives/popover.js
- src/directives/sortable.js
Closes #819.
Check live example [here](https://oliviersemet.github.io/ngeo/issue-819-group-drag-and-drop/examples/contribs/gmf/apps/desktop/)
> Issue 819 group drag and drop

- .eslintrc
- contribs/gmf/examples/layertree.js
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/directives/search.js
- contribs/gmf/src/services/permalink.js
- contribs/gmf/src/services/themesservice.js
- contribs/gmf/src/services/treemanager.js
- src/directives/layertree.js
- src/directives/measurelength.js
- src/directives/popover.js
- src/ol-ext/interaction/modifyrectangle.js
- src/ol-ext/interaction/translate.js
- src/services/autoprojection.js
- src/services/featurehelper.js
- src/services/features.js
- src/services/print.js
- src/services/query.js
> Add missing semicolons

- contribs/gmf/src/services/permalink.js
- src/directives/sortable.js
- src/ol-ext/format/featurehash.js
- src/ol-ext/interaction/modifyrectangle.js
- src/services/getbrowserlanguage.js
- src/services/print.js
- Use Array.isArray instead of goog.isArray
- Use arr.forEach instead of goog.array.forEach
> Minor goog cleanup

- contribs/gmf/src/directives/partials/search.html
> Hide search's color field temporarily

- contribs/gmf/less/mobilelayertree.less
> Don't display reorder handlers on mobile app

- src/ol-ext/format/featurehash.js
- test/spec/ol-ext/format/featurehash.spec.js
> Fix featurehash without style or attributes

- contribs/gmf/less/desktop.less
- contribs/gmf/less/desktoplayertree.less
- contribs/gmf/less/mobilelayertree.less
- contribs/gmf/less/popover.less
- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/partials/layertree.html
- src/directives/layertree.js
- src/directives/popover.js
Closes #818 
Closes #817 
Live example: [here](https://oliviersemet.github.io/ngeo/818-external-layer-opacity/examples/contribs/gmf/apps/desktop/)
@fredj or @pgiraud could you check please?
> Layer opacity

- Makefile
- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
> Fix path of the controllers

- contribs/gmf/src/controllers/abstractdesktop.js
> Allow BS tooltip to be initialized dynamically

- contribs/gmf/src/directives/drawfeature.js
Fixes #1083 
Fixes #1084.
== Live example
* https://adube.github.io/ngeo/fix-1084/examples/contribs/gmf/drawfeature.html?rl_features
> gmf-drawfeature - do not select feature if already selected

- contribs/gmf/less/desktop.less
- contribs/gmf/src/directives/partials/print.html
- contribs/gmf/src/directives/print.js
Fix: #1108 
Demo: https://ger-benjamin.github.io/ngeo/print_enhancements/examples/contribs/gmf/apps/desktop
(@fredj Finally, I've put the css in the desktop because this rule on textareas is usefull for all tools)
> Print enhancements

- src/ol-ext/interaction/modifyrectangle.js
Fixes #1117.
Ready for review.
> Fix modify rectangle interaction - do not set 'corners' property

- contribs/gmf/src/directives/partials/layertree.html
- src/directives/layertree.js
- src/services/decoratelayerloading.js
Close #820 
live example [here](https://oliviersemet.github.io/ngeo/820-loading-icon-in-layertree/examples/contribs/gmf/apps/desktop/)
ping @fredj
> Loading icon in layertree close #820

- contribs/gmf/src/directives/partials/layertree.html
> Don't display the reorder handle if there's one layer group

- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/partials/layertree.html
- contribs/gmf/test/spec/directives/layertree.spec.js
> Update metadata boolean values

- test/spec/services/decoratelayerloading.spec.js
Test for the ngeo decoratelayerLoading service
ping @fredj
> Add test for the ngeo decoratelayerLoading service

- contribs/gmf/src/directives/drawfeature.js
- contribs/gmf/src/directives/partials/drawfeature.html
> Replace ol.Collection function calls in partial with function in controller

- src/services/print.js
fix https://github.com/camptocamp/c2cgeoportal/issues/1920
> Add withCredentials in print capabilities

- contribs/gmf/src/directives/drawfeature.js
> Fix contextmenu/longpress unlisten

- contribs/gmf/apps/desktop_alt/index.html
> Fix desktop alt

- src/services/decoratelayerloading.js
> Don't decorate layer without source

- package.json
- src/ol-ext/interaction/modify.js
> Don't add a vertex on right click

- package.json
- src/ol-ext/interaction/modify.js
> Fix openlayers build

- src/ol-ext/interaction/translate.js
> Make 'move' icon on top of feature

- contribs/gmf/less/mobile-nav.less
- contribs/gmf/less/vars.less
Also removes unused special-link variable
Fixes #1206.
> All links should have the same color

- contribs/gmf/src/directives/layertree.js
> Constrain the resolution when zooming to resolution

- contribs/gmf/src/directives/partials/layertree.html
demo: https://oliviersemet.github.io/ngeo/pr-dismiss-popover-on-layertree-scroll/examples/contribs/gmf/apps/desktop/index.html
@pgiraud @sbrunner @fredj
> Dismiss popover when a scroll event occurs on the layertree

- .eslintrc
- Makefile
- contribs/gmf/apps/appmodule.js
- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/apps/desktop_alt/js/controller.js
`GMF_APPS_MOBILE_JS_FILES` don't exists anymore ...
> Add the applications files to eslint check

- contribs/gmf/apps/appmodule.js
- contribs/gmf/src/controllers/abstract.js
Make the injector public when we are in debug mode
fix #1120
> Remove debug information when we are not in debug mode

- contribs/gmf/less/desktoplayertree.less
- contribs/gmf/less/mobilelayertree.less
- contribs/gmf/src/directives/partials/layertree.html
Better solution for a larger drag and drop handler 
demo: https://oliviersemet.github.io/ngeo/larger-handler-for-drag-and-drop/examples/contribs/gmf/apps/desktop/index.html
@pgiraud @fredj
> larger handler for drag and drop

- src/services/filters.js
- test/spec/services/filters.spec.js
http://unicode-table.com/en/00A0/
> Use non braking space

- contribs/gmf/src/directives/search.js
> Translate search actions

- Makefile
> Fix typo in transifex-get

- examples/popover.html
- src/directives/popover.js
- We'll need it to embed time slider into the popover
@fredj @pgiraud
> Adding placement property for ngeo popover directive

- contribs/gmf/src/directives/layertree.js
> Temporaty fix for mixed with sub groups

- contribs/gmf/src/directives/print.js
Fix: #1160 
Example: https://ger-benjamin.github.io/ngeo/print_scale/examples/contribs/gmf/apps/desktop/index.html
> Constrain resolution on print set scale

- contribs/gmf/less/mobile.less
- contribs/gmf/src/controllers/abstractmobile.js
This PR introduces the notification service in the mobile app.
Try to login with bad credentials or try to refuse to share your position when using the geolocation tool.
* https://adube.github.io/ngeo/notification-in-mobile-app/examples/contribs/gmf/apps/mobile
> Setup notification service in mobile app

- contribs/gmf/src/directives/authenticationdirective.js
> Fix gmf authentication incorrect login i18n

- src/services/printutils.js
Fix #1213 
Example: 
- http://ger-benjamin.github.io/ngeo/simple_calculation/examples/contribs/gmf/apps/desktop_alt (use rotation)
- http://ger-benjamin.github.io/ngeo/simple_calculation/examples/contribs/gmf/apps/desktop (don't use rotation)
> Simplify the mask calculation if the map rotate

- Makefile
- buildtools/mako_build.json
- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/examples/asitvd.html
- contribs/gmf/examples/authentication.html
- contribs/gmf/examples/drawfeature.html
- contribs/gmf/examples/featurestyle.html
- contribs/gmf/examples/layertree.html
- contribs/gmf/examples/mobilebackgroundlayerselector.html
- contribs/gmf/examples/mobilemeasure.html
- contribs/gmf/examples/mobilequery.html
- contribs/gmf/examples/permalink.html
- contribs/gmf/examples/print.html
- contribs/gmf/examples/search.html
- contribs/gmf/examples/simple.html
- contribs/gmf/examples/themeselector.html
- contribs/gmf/examples/wfs-permalink.html
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/gmf.js
- contribs/gmf/test/spec/beforeeach.js
- externs/angular-dynamic-locale.js
- karma-conf.js
- package.json
- test/spec/services/autoprojection.spec.js
- test/spec/services/filters.spec.js
> Add locales from angular

- Makefile
> Include the angular locales in build-gmf-apps

- contribs/gmf/apps/mobile/index.html
Small simplification
ping @pgiraud
> Remove the div around gmf-mobile-backgroundlayerselector element

- package.json
- src/services/layerHelper.js
> Don't force WMTS encoding to REST

- contribs/gmf/less/desktop.less
> Fixing tools panel layout in IE

- contribs/gmf/less/desktop.less
- contribs/gmf/less/icons.less
- contribs/gmf/less/mobile.less
- contribs/gmf/less/mobiledisplayqueries.less
- contribs/gmf/less/search.less
> Fix syntax for CSS3 pseudo-element

- contribs/gmf/externs/gmfx.js
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/directives/authenticationdirective.js
- contribs/gmf/src/services/authenticationservice.js
Fix: https://github.com/camptocamp/c2cgeoportal/issues/2216
Example:  http://ger-benjamin.github.io/ngeo/user_externs/examples/contribs/gmf/apps/desktop
@sbrunner I currently target the branch "master" but this PR aims a 2.0 bug. It is correct or I should push it on the 2.0 ?
> Use externe file for gmf User

- contribs/gmf/less/desktop.less
- contribs/gmf/less/desktoplayertree.less
- contribs/gmf/less/layertree.less
- contribs/gmf/less/mobile-nav.less
- contribs/gmf/less/mobile.less
- contribs/gmf/less/mobiledisplayqueries.less
- contribs/gmf/less/mobilelayertree.less
- contribs/gmf/less/search.less
Small simplifications in the less files
> less simplifications

- contribs/gmf/src/directives/layertree.js
This PR complete the work done by the PR #1237. 
ping @fredj @sbrunner
> Do not compare node name with layer name

- Makefile
- contribs/gmf/apps/desktop/index.html
- contribs/gmf/examples/asitvd.html
- contribs/gmf/examples/authentication.html
- contribs/gmf/examples/backgroundlayerselector.html
- contribs/gmf/examples/drawfeature.html
- contribs/gmf/examples/featurestyle.html
- contribs/gmf/examples/layertree.html
- contribs/gmf/examples/mobilemeasure.html
- contribs/gmf/examples/mobilequery.html
- contribs/gmf/examples/mouseposition.html
- contribs/gmf/examples/permalink.html
- contribs/gmf/examples/print.html
- contribs/gmf/examples/search.html
- contribs/gmf/examples/simple.html
- contribs/gmf/examples/themeselector.html
- contribs/gmf/examples/wfs-permalink.html
- contribs/gmf/src/gmf.js
- karma-conf.js
@sbrunner @fredj 
I don't now how to add the new folder contribs/gmf/third-party to the build process @sbrunner 
close #1274
> add ui.date and ui.slider modules to gmf

- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/services/querymanager.js
- contribs/gmf/src/services/themesservice.js
- contribs/gmf/test/spec/data/themes.js
- contribs/gmf/test/spec/services/querymanager.spec.js
- contribs/gmf/test/spec/services/themesservice.spec.js
- src/services/query.js
Closes https://github.com/camptocamp/ngeo/issues/1238
Querying WMTS overlays was already supported, I only added a test for it.
> Query WMTS background layers

- src/ol-ext/interaction/modifycircle.js
This typedef is already defined in ol3
fixes #1323 
todo: test in compiled mode
> Remove ol.interaction.SegmentDataType typedef

- contribs/gmf/less/mobile-nav.less
- contribs/gmf/src/controllers/abstractmobile.js
> Closing side navigation when dragging the map in

- externs/mapfish-print-v3.js
- src/services/layerHelper.js
Request high DPI image from the WMS server
> Pass the server type to the ol.source.ImageWMS constructor

- Makefile
demo: https://camptocamp.github.io/ngeo/jquery-images/examples/contribs/gmf/apps/desktop_alt/?lang=fr&baselayer_ref=map
fix: #1351
> Copy the JQuery UI images to the right folder

- contribs/gmf/src/directives/partials/drawfeature.html
With this pull request I remove an extra div element. It doesn't hurt to have it but it's not required anymore.
> Remove extra nesting

- Makefile
> Add Git attributes check in `make check`

- .eslintrc
fix: https://github.com/camptocamp/ngeo/pull/1369#issuecomment-224894583
> From eslint-config-openlayers version 5 semi is no more needed

- contribs/gmf/less/mobilelayertree.less
https://oliviersemet.github.io/ngeo/hide-popover-on-mobile/examples/contribs/gmf/apps/mobile/
Ping @pgiraud
> hide popover on mobile

- contribs/gmf/less/base.less
- contribs/gmf/less/desktop.less
- contribs/gmf/less/input-range.less
- contribs/gmf/less/layertree.less
- contribs/gmf/less/vars.less
- contribs/gmf/src/directives/partials/drawfeature.html
- contribs/gmf/src/directives/partials/featurestyle.html
- contribs/gmf/src/directives/partials/print.html
Some more work on the harmonization.
This time on the tools panels (print & draw).
> Layout harmonization

- contribs/gmf/less/desktop.less
- contribs/gmf/less/desktoplayertree.less
Fixes #1347.
Pure CSS alternative to #1367.
> Drop dashed zone displayed even if dragging far down

- src/services/print.js
> Don't recreate the getCapabilities promise

- contribs/gmf/less/icons.less
- contribs/gmf/less/layertree.less
- contribs/gmf/src/directives/partials/layertree.html
> Prevent name to be in italic in layertree

- contribs/gmf/src/directives/print.js
- externs/mapfish-print-v3.js
Fixes #1260.
This is untested. I'm not able to run a patched version of ngeo in a c2cgeoportal instance. @sbrunner I may need your help.
> Show error if report creation failed even if done

- contribs/gmf/examples/print.html
- contribs/gmf/examples/print.js
- contribs/gmf/src/directives/print.js
- contribs/gmf/src/services/authenticationservice.js
> Add the role in the print requests

- contribs/gmf/examples/asitvd.html
- contribs/gmf/examples/authentication.html
- contribs/gmf/examples/backgroundlayerselector.html
- contribs/gmf/examples/drawfeature.html
- contribs/gmf/examples/elevation.html
- contribs/gmf/examples/featurestyle.html
- contribs/gmf/examples/layertree.html
- contribs/gmf/examples/mobilemeasure.html
- contribs/gmf/examples/mobilequery.html
- contribs/gmf/examples/mouseposition.html
- contribs/gmf/examples/permalink.html
- contribs/gmf/examples/print.html
- contribs/gmf/examples/search.html
- contribs/gmf/examples/simple.html
- contribs/gmf/examples/themeselector.html
- contribs/gmf/examples/wfs-permalink.html
> add jquery and jquery-ui dependencies to all gmf examples

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/apps/desktop_alt/js/controller.js
- contribs/gmf/apps/mobile/js/controller.js
- contribs/gmf/examples/elevation.html
- contribs/gmf/examples/elevation.js
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/controllers/abstractdesktop.js
- contribs/gmf/src/directives/elevation.js
Fix #1363 
Fix #1362 (real issue)
Finally for the 1663, I just move the supported coordinates projection.
Example: https://ger-benjamin.github.io/ngeo/update_controller/examples/contribs/gmf/apps/desktop_alt
> Update controller (1362, 1363)

- buildtools/build.js
- package.json
See https://github.com/openlayers/ol3/pull/5151
> Use fs-extra as fs and remove usage of graceful-fs

- contribs/gmf/less/search.less
> Move typeahead styling inside 'search' css scope

- contribs/gmf/src/controllers/abstractdesktop.js
Helps drawings being printed.
Fixes #1349.
WIP. I could not test it.
Démo: https://pgiraud.github.io/ngeo/print_drawing/examples/contribs/gmf/apps/desktop
> Use the feature overlay manager for drawings

- src/services/print.js
This reverts commit a7e53c966f6294eaa328370feaeb928b5047505d.
fix #1427
> Revert "Don't recreate the getCapabilities promise"

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/examples/mapquery.html
- contribs/gmf/examples/mapquery.js
- contribs/gmf/examples/mobilequery.html
- contribs/gmf/examples/mobilequery.js
- contribs/gmf/examples/wfs-permalink.html
- contribs/gmf/examples/wfs-permalink.js
- contribs/gmf/less/desktop.less
- contribs/gmf/less/displayqueries.less
- contribs/gmf/less/mobile.less
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/controllers/abstractmobile.js
- contribs/gmf/src/directives/displayqueries.js
- contribs/gmf/src/directives/partials/displayqueries.html
- contribs/gmf/test/spec/directives/displayqueries.spec.js
- examples/mapquery.html
- examples/mapquery.js
- externs/ngeox.js
- src/directives/mapquery.js
- src/services/query.js
- src/services/toolActivateMgr.js
- src/services/wfspermalink.js
Closes https://github.com/camptocamp/c2cgeoportal/issues/1773
@pgiraud I gave you access rights to my branch, if you want to do some CSS fine tuning.
> Add query results window

- contribs/gmf/src/directives/mobilenav.js
See https://github.com/camptocamp/ngeo/pull/1446#issuecomment-227744408
> Remove unused gmf.mobileNavBackDirective directive

- contribs/gmf/src/directives/backgroundlayerselector.js
> Update gmf-backgroundlayerselector example in doc

- Makefile
> Fix font copy in Makefile

- contribs/gmf/src/services/permalink.js
- src/ol-ext/format/featurehash.js
The string value used for the feature attribute showMeasure is now turned in to a boolean.
(fixes #1418)
> Convert string value for `m` in to a boolean

- contribs/gmf/src/directives/partials/displayqueries.html
Closes https://github.com/camptocamp/ngeo/issues/1469#event-704678342
> Fix query window collapse

- buildtools/mako_build.json
Needed for https://github.com/camptocamp/c2cgeoportal/pull/2337
> Set the working dir in closure-compiler config file

- contribs/gmf/less/desktop.less
Fixes #1461.
Demo: https://pgiraud.github.io/ngeo/map_bottom_controls/examples/contribs/gmf/apps/desktop
> Prevent interaction stopped at the bottom of the map

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/desktop_alt/js/controller.js
- contribs/gmf/src/directives/elevation.js
- contribs/gmf/src/directives/partials/elevationwidget.html
Fixes #1441.
Please review.
Demos (nothing changes actually):
https://pgiraud.github.io/ngeo/infobar_simplified/examples/contribs/gmf/apps/desktop
https://pgiraud.github.io/ngeo/infobar_simplified/examples/contribs/gmf/apps/desktop_alt
> Infobar simplified

- contribs/gmf/less/displayqueries.less
> Fix position of features window on tablets

- contribs/gmf/src/directives/mobilemeasurelength.js
- examples/measure.js
- externs/closure-compiler.js
- externs/ngeox.js
- src/directives/measurearea.js
- src/directives/measureazimut.js
- src/directives/measurelength.js
- src/ol-ext/interaction/measure.js
- src/ol-ext/interaction/measurearea.js
- src/ol-ext/interaction/measureazimut.js
- src/ol-ext/interaction/measurelength.js
- src/ol-ext/interaction/measurelengthmobile.js
- src/services/featurehelper.js
- src/services/filters.js
- test/spec/services/filters.spec.js
> Correctly format the number in the drawing

- contribs/gmf/src/directives/layertree.js
- examples/mapquery.js
- externs/ngeox.js
- src/services/query.js
- test/spec/services/query.spec.js
See https://github.com/camptocamp/ngeo/issues/1392#issuecomment-228995071
> Remove unused querySourceId layer property

- buildtools/templatecache.mako.js
The key for components is prefix/component/partial.html
> Generate template cache for components

- contribs/gmf/src/directives/search.js
- contribs/gmf/src/services/treemanager.js
> Add parameter showNotification to determin when to call notifyCantAddGroups_

- contribs/gmf/src/services/querymanager.js
- src/services/query.js
> Fix query service

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/apps/mobile/js/controller.js
- contribs/gmf/examples/mobilemeasure.html
- contribs/gmf/examples/mobilemeasure.js
- contribs/gmf/src/controllers/abstractmobile.js
- contribs/gmf/src/directives/mobilemeasurelength.js
- contribs/gmf/src/directives/mobilemeasurepoint.js
Fix: #1343
Example: https://ger-benjamin.github.io/ngeo/measurelayers/examples/contribs/gmf/apps/mobile
Or in examples.
I also added some doc.
> Measurelayers

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/less/desktop.less
- contribs/gmf/less/desktoplayertree.less
- contribs/gmf/less/vars.less
Please review.
https://pgiraud.github.io/ngeo/theme_selector_button/examples/contribs/gmf/apps/desktop
https://pgiraud.github.io/ngeo/theme_selector_button/examples/contribs/gmf/apps/desktop_alt
> Make the theme selector button more visible

- contribs/gmf/src/directives/partials/search.html
Fixes #1420.
`data-original-title` is to be used instead of `data-title`.
> Add tooltip to search color picker

- contribs/gmf/examples/backgroundlayerselector.js
> Fix dependency issue

- contribs/gmf/src/directives/drawfeature.js
> Confirm any feature deletion

- contribs/gmf/examples/editfeature.js
See https://github.com/camptocamp/ngeo/pull/1505#issuecomment-230225282
> Use console.assert instead of goog.asserts.assert in editfeature example

- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/services/themesservice.js
- src/services/layerHelper.js
> Use the WMTS dimensions to build the source

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/src/controllers/abstract.js
fixes #1470 
https://fredj.github.io/ngeo/query_vs_draw/examples/contribs/gmf/apps/desktop/
https://fredj.github.io/ngeo/query_vs_draw/examples/contribs/gmf/apps/desktop_alt/
> Deactivate query tool when the draw panel is open

- contribs/gmf/src/controllers/abstract.js
I need to access the service from a child class
> Make the ngeo.Location service available to child classes

- contribs/gmf/src/services/themesservice.js
Partially fix https://github.com/camptocamp/c2cgeoportal/issues/2361
> Display an error when the themes contains some error

- contribs/gmf/externs/gmfx.js
- contribs/gmf/src/directives/displayquerywindow.js
- contribs/gmf/src/directives/print.js
- externs/ngeox.js
- src/services/featurehelper.js
Close #1104 
**Demo:** 
https://oliviersemet.github.io/ngeo/add-selected-features-to-print-report/examples/contribs/gmf/apps/desktop/
**Test**
@sbrunner @fredj
> Add selected features to print report

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/less/profile.less
Demo: https://pgiraud.github.io/ngeo/profile_layout/examples/contribs/gmf/apps/desktop
> Enlarge profile container

- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/apps/desktop_alt/js/controller.js
- contribs/gmf/examples/mouseposition.js
- src/services/filters.js
- test/spec/services/filters.spec.js
> Number format

- src/services/query.js
Related to #1535 
**Demo**
- https://oliviersemet.github.io/ngeo/avoiding-identical-request/examples/contribs/gmf/apps/desktop/
@ger-benjamin @sbrunner please could you have a look and tell me if this is a step in the right direction?
> Avoid querying identical sources Fix #1535

- contribs/gmf/src/directives/search.js
Fixes https://github.com/camptocamp/c2cgeoportal/issues/2294
Examples: 
- Desktop: https://marionb.github.io/ngeo/coordinate_search_result/examples/contribs/gmf/apps/desktop/
- Mobile: https://marionb.github.io/ngeo/coordinate_search_result/examples/contribs/gmf/apps/mobile/
> Add drop-down for coordinate search results.

- contribs/gmf/examples/datepicker.js
- contribs/gmf/examples/timeslider.js
- examples/measure.js
- src/services/print.js
Related to #1377 
@ger-benjamin @sbrunner
> Fix gmf examples

- contribs/gmf/less/desktop.less
- contribs/gmf/less/share.less
> Don't allow the textarea to grow horizontally

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
https://camptocamp.github.io/ngeo/applications-title/examples/contribs/gmf/apps/desktop_alt
> Fix the applications title

- contribs/gmf/less/displayquerywindow.less
- contribs/gmf/src/directives/partials/displayquerywindow.html
Close #1550 #1549
**Demo**: 
- https://oliviersemet.github.io/ngeo/queryWindow-enhancement/examples/contribs/gmf/apps/desktop/
- https://oliviersemet.github.io/ngeo/queryWindow-enhancement/examples/contribs/gmf/apps/mobile/
> Query window enhancement

- contribs/gmf/examples/profile.html
- src/directives/profile.js
Fixes #1577.
Demo: https://pgiraud.github.io/ngeo/profile_resize/examples/contribs/gmf/apps/desktop
> Resize the profile chart when window is resized

- contribs/gmf/less/datepicker.less
- contribs/gmf/src/directives/partials/layertree.html
- src/directives/partials/datepicker.html
> Use ngeo-date-picker directive instead of gmf-date-picker Close #1591

- contribs/gmf/src/directives/drawfeature.js
fix #1590 
[demo](https://oliviersemet.github.io/ngeo/deactivate-drawing-tools-when-feature-is-selected/examples/contribs/gmf/apps/desktop_alt/index.html?baselayer_ref=map&lang=fr&map_x=568100&map_y=147800&map_zoom=1&rl_features=Fa(dhz2-9b9Fj_dn-rCym-rHwk-pMfj-eRfg-xV1e-807b-84-w7-v7-94-6b-90zd-yVeg-fRej-qMvk-sHxm-sCcn-k_en-j_xm-rCvk-rHej-pMeg-eRzd-xV6b-80v7-84-84-v7-806b-xVzd-eReg-pMej-rHvk-rCxm-j_cn-k_en-sCxm-sHvk-qMej-fReg-yVzd-906b-94-v7-w7-84-7b-801e-xVfg-eRfj-pMwk-rHym-rCfn-j_dn-k_ym-sCwk-sHfj-qMfg-fR1e-yV7b-90w7-94-94-w7-907b-yV1e-fRfg-qMfj-sHwk-sCym-~l*true%27n*Circle%25201%27c*%2523DB4436%27a*0%27o*0.2%27m*false%27s*10%27k*1)a(k6z3-18cEg!u7_cF77_8Mu5_vSu3_cZ51_e5-ww-ab-1t-mg-kn-jn-ng-zs-bb-vw-f5-41_dZt3_wSt5_9M67_dFt7_h!v7_g!67_cFt5_8Mt3_vS41_cZvw-e5-zs-ab-jn-mg-mg-jn-ab-zs-e5-vw- …
> Deactivate drawing tools when a feature is selected

- contribs/gmf/src/services/permalink.js
Fixes #1619.
Please review.
cc @olivierSemet
> Set style before locale is set

- Makefile
Can be tested here:
https://camptocamp.github.io/ngeo/fix-mobile/examples/contribs/gmf/apps/desktop_alt
> Add missing jquery-ui

- contribs/gmf/src/directives/layertree.js
see also: https://github.com/camptocamp/c2cgeoportal/pull/2435
> Be able to have an URL to the layer icon

- contribs/gmf/src/services/treemanager.js
Fix #1596
This little modification should do the work. Unfortunately I cannot make a full test because adding the theme in the URL doesn't work in local or gh-pages demos.
I can provide a kind of proof:
**Empty your localStorage before test**
1. Go to [Desktop_alt app](https://oliviersemet.github.io/ngeo/fix-theme-name-and-layers-not-consistent/examples/contribs/gmf/apps/desktop_alt/)
2. Select another theme in the list (anything except OSM), it must add some groups to the layer tree.
3. Go to the [Desktop](https://oliviersemet.github.io/ngeo/fix-theme-name-and-layers-not-consistent/examples/contribs/gmf/apps/desktop/) 
You should have the correct name of the theme and the groups in the layer tree which correspond exactly to the selected theme (Therefore the group added previously is not …
> Fixing theme name and layers displayed not consistent close #1596

- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/controllers/abstractdesktop.js
fix: #1602
demo: https://camptocamp.github.io/ngeo/fix-mobile77/examples/contribs/gmf/apps/mobile
> Move the ngeoFeatureHelper configuration to the abstract controller

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/directives/layertree.js
> Handle global dimensions

- src/services/featurehelper.js
@ybolognini does it work better for you?
Demo
https://pgiraud.github.io/ngeo/azimut_offset/examples/contribs/gmf/apps/desktop
> Increase azimut label offset

- buildtools/mako_build.json
Related to https://github.com/camptocamp/c2cgeoportal/pull/2411
> Add handle for app components

- contribs/gmf/apps/desktop/js/controller.js
- contribs/gmf/apps/desktop_alt/js/controller.js
- src/directives/partials/scaleselector.html
- src/directives/scaleselector.js
Fixes #1553.
Please review.
Demo:
https://pgiraud.github.io/ngeo/scaleselector_ngeoscalify/examples/contribs/gmf/apps/desktop_alt
> Use ngeoScalify for the scale selector

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
Demo
https://pgiraud.github.io/ngeo/brush_icon/examples/contribs/gmf/apps/desktop
This lets us use the pencil icon for editing which is more appropriate.
> Use paint brush icon for redlining

- contribs/gmf/src/directives/editfeatureselector.js
- contribs/gmf/src/directives/partials/editfeatureselector.html
This pull request enhances the editfeatureselector directive a bit.
@adube please review.
> Rework the edit feature selector partial

- buildtools/mako_build.json
> Set the language_in to ECMASCRIPT6_STRICT

- src/ol-ext/interaction/modifyrectangle.js
> Use hasFeatureAtPixel instead of forEachFeatureAtPixel

- contribs/gmf/examples/search.html
- contribs/gmf/src/directives/partials/search.html
- contribs/gmf/src/directives/search.js
TODO: the `Search…` string is not translated 
edit: it's now fixed
> Make the search placeholder configurable

- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/services/themesservice.js
- src/services/backgroundlayermgr.js
> Update the background layer on dimension change

- contribs/gmf/examples/search.js
- contribs/gmf/src/directives/search.js
Like all others directive, fixes #1682
> Don't initialize the ngeoFeatureOverlayMgr in the directive

- docs/developer-guide.md
> Developer guide

- Makefile
- contribs/gmf/apps/desktop/contextualdata.html
- contribs/gmf/apps/desktop/index.html
- contribs/gmf/examples/contextualdata.html
- contribs/gmf/examples/contextualdata.js
- contribs/gmf/examples/partials/contextualdata.html
- contribs/gmf/less/contextualdata.less
- contribs/gmf/less/desktop.less
- contribs/gmf/src/controllers/abstractdesktop.js
- contribs/gmf/src/directives/contextualdata.js
- contribs/gmf/test/spec/beforeeach.js
- contribs/gmf/test/spec/directives/contextualdata.spec.js
fix https://github.com/camptocamp/c2cgeoportal/issues/2309
> Add contextual data (right click) directive example

- Makefile
- buildtools/templatecache.mako.js
Required for the components structure
First step for https://github.com/camptocamp/c2cgeoportal/issues/2446
> Stronger template cache path generation

- contribs/gmf/src/services/treemanager.js
- contribs/gmf/test/spec/services/treemanager.spec.js
Fix: #1510
Example: https://ger-benjamin.github.io/ngeo/addGroupeOrder/examples/contribs/gmf/apps/desktop_alt
> Add groups at the top

- src/d3-ext/profile.js
Adding missing curly brace + fix indentation
> Fix doc comment for profile

- contribs/gmf/src/directives/partials/editfeatureselector.html
- src/directives/partials/attributes.html
Fixes #1723.  Add missing translations.
> Fix #1723 - Add missing translations

- contribs/gmf/src/controllers/abstract.js
Fix: #1496 
Demo: https://ger-benjamin.github.io/ngeo/userbgLayer/examples/contribs/gmf/apps/desktop
(role admin as a grey bg layer)
(In desktop_alt, theme `OSM` doesn't have a defined background layer. In desktop, it has it)
> Use user defined background layer

- contribs/gmf/src/directives/backgroundlayerselector.js
- contribs/gmf/src/directives/editfeatureselector.js
- contribs/gmf/src/directives/themeselector.js
- contribs/gmf/src/services/querymanager.js
- contribs/gmf/src/services/themesservice.js
- contribs/gmf/src/services/treemanager.js
- contribs/gmf/test/spec/services/themesservice.spec.js
- src/services/query.js
> Add back gmf.ThemesEventType.CHANGE on themes change

- contribs/gmf/src/directives/layertree.js
> Make the dimensions param in gmf-layertree optional

- src/services/featurehelper.js
> Fix file download in firefox

- contribs/gmf/examples/search.html
- contribs/gmf/examples/search.js
- contribs/gmf/src/directives/partials/search.html
- contribs/gmf/src/directives/search.js
To be able to use the value outside of the directive
> Export the gmf-search input value

- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/externs/gmfx.js
- contribs/gmf/src/services/permalink.js
- contribs/gmf/test/spec/services/permalinkservice.spec.js
- src/services/autoprojection.js
Closes https://github.com/camptocamp/ngeo/issues/1719
> Try to reproject coordinates in permalink

- contribs/gmf/src/directives/partials/print.html
> Prevent horizontal scrollbar to appear with dropdown menu

- contribs/gmf/src/directives/displayquerygrid.js
- contribs/gmf/test/spec/directives/displayquerygrid.spec.js
Closes https://github.com/camptocamp/ngeo/issues/1833
> Fix display issue with grid

- Makefile
- buildtools/generate-examples-index.py
- github_versions
- requirements.txt
The ngeo part for https://github.com/camptocamp/c2cgeoportal/issues/2486
> Fix all the versions

- src/directives/sortable.js
> Ensure node comments are not messed up after drop at same location

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/examples/asitvd.html
- contribs/gmf/examples/authentication.html
- contribs/gmf/examples/backgroundlayerselector.html
- contribs/gmf/examples/contextualdata.html
- contribs/gmf/examples/datepicker.html
- contribs/gmf/examples/displayquerygrid.html
- contribs/gmf/examples/displayquerywindow.html
- contribs/gmf/examples/drawfeature.html
- contribs/gmf/examples/editfeature.html
- contribs/gmf/examples/editfeatureselector.html
- contribs/gmf/examples/elevation.html
- contribs/gmf/examples/featurestyle.html
- contribs/gmf/examples/layertree.html
- contribs/gmf/examples/mobilemeasure.html
- contribs/gmf/examples/mouseposition.html
- contribs/gmf/examples/permalink.html
- contribs/gmf/examples/print.html
- contribs/gmf/examples/profile.html
- contribs/gmf/examples/search.html
- contribs/gmf/examples/share.html
- contribs/gmf/examples/simple.html
- contribs/gmf/examples/themeselector.html
- contribs/gmf/examples/timeslider.html
- contribs/gmf/examples/wfs-permalink.html
- contribs/gmf/examples/xsdattributes.html
- examples/datepicker.html
- examples/grid.html
used:
```
git grep --full-name ' type="text/javascript"'|cut -d: -f1|xargs sed -i -e 's/ type="text\/javascript"//g'
```
> Remove unneeded script type

- docs/guidelines.md
Add doc about CSS class names convention.
> Update Guideline - CSS class names convention

- .travis.yml
- Makefile
- buildtools/check-example.js
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/gmf.js
- contribs/gmf/src/services/themesservice.js
Before that this:
`node_modules/.bin/phantomjs buildtools/check-example.js https://testgmf.sig.cloud.camptocamp.net/2.1/wsgi/desktop`
don't report an error...
=> with the new argement:
`node_modules/.bin/phantomjs buildtools/check-example.js --app https://testgmf.sig.cloud.camptocamp.net/2.1/wsgi/desktop`
> Make the application check working

- contribs/gmf/src/directives/editfeature.js
- contribs/gmf/src/directives/editfeatureselector.js
- contribs/gmf/src/directives/partials/editfeatureselector.html
> Manage 'deactivation' with unsaved changes in gmf-editfeature

- .eslintrc
- Makefile
- buildtools/mako_build.json
- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- externs/file-saver.js
- package.json
- src/services/csvdownload.js
- src/services/download.js
- src/services/featurehelper.js
Use the library [file-saver](https://github.com/eligrey/FileSaver.js) to download KML/GPX/CSV files.
Currently I can't test properly, but file-saver has support for all modern browsers.
Closes https://github.com/camptocamp/ngeo/issues/1776
> Download files with `file-saver`

- contribs/gmf/src/directives/partials/editfeature.html
> Unrequired translate

- contribs/gmf/src/directives/drawfeature.js
> Contextual menu for all types of drawn features

- contribs/gmf/less/map.less
fixes #1876 
demo:
- https://fredj.github.io/ngeo/active_theme_css/examples/contribs/gmf/apps/desktop/
- https://fredj.github.io/ngeo/active_theme_css/examples/contribs/gmf/apps/desktop_alt/
- https://fredj.github.io/ngeo/active_theme_css/examples/contribs/gmf/apps/mobile/
> Highlight the selected theme in the theme selector

- Makefile
> Re add locales files in the gitub.io pages

- .tx/config.mako
- Makefile
> Acctivate ngeo i18n

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/src/directives/partials/search.html
- contribs/gmf/src/directives/search.js
This pull request fixes the missing translations for search input and results menu.
The search placeholder will need to be translated in the gmf demo to work.
Please review.
> Missing translations search

- contribs/gmf/src/directives/partials/search.html
In a project, the popover is displayed even if color chooser is disabled
> Don't create the color chooser if the option is false

- contribs/gmf/examples/editfeatureselector.html
- contribs/gmf/externs/gmf-themes.js
- contribs/gmf/src/directives/editfeature.js
- contribs/gmf/src/directives/editfeatureselector.js
- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/map.js
- contribs/gmf/src/services/snapping.js
> Add snapping support in gmf-editfeature

- Makefile
- buildtools/check-example.js
- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/examples/contextualdata.html
- contribs/gmf/examples/displayquerygrid.html
- contribs/gmf/examples/displayquerywindow.html
- contribs/gmf/examples/editfeature.html
- contribs/gmf/examples/editfeatureselector.html
- contribs/gmf/examples/editfeatureselector.js
- contribs/gmf/examples/layertree.html
- contribs/gmf/examples/layertree.js
- contribs/gmf/examples/layertreeadd.html
- contribs/gmf/examples/layertreeadd.js
- contribs/gmf/examples/mouseposition.html
- contribs/gmf/examples/print.html
- contribs/gmf/examples/profile.html
- contribs/gmf/examples/search.html
- contribs/gmf/examples/share.html
- contribs/gmf/examples/themeselector.html
- contribs/gmf/examples/themeselector.js
- contribs/gmf/examples/xsdattributes.html
- contribs/gmf/examples/xsdattributes.js
- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/services/permalink.js
- examples/layerorder.html
- examples/locationchooser.html
- examples/rotate.html
> Fix the examples

- contribs/gmf/src/directives/profile.js
Closes https://github.com/camptocamp/ngeo/issues/1965
> Use download service for profile export

- contribs/gmf/src/directives/layertree.js
work in progress
apps to be tested
> Return parent node iconUrl if defined

- contribs/gmf/src/directives/themeselector.js
- contribs/gmf/src/services/treemanager.js
> Themeselector doc

- contribs/gmf/src/directives/contextualdata.js
- src/directives/bboxquery.js
- src/directives/btngroup.js
- src/directives/control.js
- src/directives/desktopgeolocation.js
- src/directives/filereader.js
- src/directives/layertree.js
- src/directives/map.js
- src/directives/mapquery.js
- src/directives/mobilegeolocation.js
- src/directives/modal.js
- src/directives/profile.js
- src/directives/recenter.js
- src/directives/resizemap.js
- src/directives/scaleselector.js
- src/directives/search.js
- src/directives/sortable.js
- src/ol-ext/interaction/measurearea.js
- src/ol-ext/interaction/measureazimut.js
- src/ol-ext/interaction/measurelength.js
- src/services/backgroundlayermgr.js
- src/services/debounce.js
- src/services/decorategeolocation.js
- src/services/decorateinteraction.js
- src/services/decoratelayer.js
- src/services/location.js
- src/services/print.js
- src/services/toolActivateMgr.js
Closes https://github.com/camptocamp/c2cgeoportal/issues/2406
There was already documentation and a good example, so I only added links.
> Add links to contextualdata directive docs

- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/directives/themeselector.js
- contribs/gmf/src/services/permalink.js
Fix : #1984
Example:  https://ger-benjamin.github.io/ngeo/dont_overwrite_url_theme/examples/contribs/gmf/apps/desktop
(Some tasks was done twice... -> bug)
> Don't overwrite the url theme

- externs/ngeox.js
- src/source/swisstoposource.js
The projection was missing from the main typedef definition.
> Fix and simplify swisstopo source

- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/less/desktop.less
- contribs/gmf/less/fullscreenpopup.less
- contribs/gmf/src/directives/disclaimer.js
- externs/ngeox.js
- src/services/disclaimer.js
> Modal position

- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/less/desktop.less
- contribs/gmf/less/fullscreenpopup.less
- contribs/gmf/src/directives/disclaimer.js
- externs/ngeox.js
- src/services/disclaimer.js
Fix: #1989 
Example: https://ger-benjamin.github.io/ngeo/modal-position/examples/contribs/gmf/apps/desktop_alt/
> Disclaimer in a modal

- contribs/gmf/src/services/querymanager.js
Fix: https://github.com/camptocamp/ngeo/issues/2023
> (Query) Childlayers based on layers for WMTS

- contribs/gmf/less/desktop.less
- contribs/gmf/less/search.less
> Search padding

- Makefile
- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/apps/oeedit/index.html
- contribs/gmf/examples/search.html
- examples/search.html
- karma-conf.js
- package.json
They finally pushed a release!
Closes: https://github.com/camptocamp/ngeo/issues/958.
> Depend on corejs-typeahead

- src/ol-ext/interaction/measure.js
- src/ol-ext/interaction/measurearea.js
- src/ol-ext/interaction/measureazimut.js
- src/ol-ext/interaction/measurelength.js
- src/services/featureoverlay.js
> Even less goog

- contribs/gmf/examples/objecteditinghub.js
> Add missing assert in object editing hub example

- examples/backgroundlayer.js
- examples/backgroundlayerdropdown.js
- examples/layerloading.js
- examples/layerorder.js
- examples/layervisibility.js
To fix the make check
Work done for : #2073
> Use https for boundless services

- src/ol-ext/jstsexports.js
Fixes a copy-paste typo in OL deps for JSTS.
> Typo fix in OL deps for JSTS

- src/services/layerHelper.js
> Only update the WMTS dimensions if the object is not empty

- contribs/gmf/src/directives/layertree.js
- src/directives/desktopgeolocation.js
- src/directives/mobilegeolocation.js
- src/services/filters.js
> Fix spelling and doc typo

- contribs/gmf/src/directives/mobilenav.js
> Fix broken mobile navigation animation

- contribs/gmf/src/directives/partials/print.html
- contribs/gmf/src/directives/print.js
For: https://github.com/camptocamp/epfl_authgeoportail/issues/324
Changes done to use print by a custom print panel directive (usecase: EPFL)
> Print - Event and classes added, print state improved

- contribs/gmf/src/directives/partials/displayquerywindow.html
> Trust values as HTML in query results

- options/ngeox.js
> Fix type definition for jsdoc

- contribs/gmf/src/directives/print.js
Can define custom value for the fields of the print panel.
That was already possible for some fields by doing that on the server side. But not for all fields. That's also impossible without this changes to define the legend checkbox to 'false' by default.
It's a generic change to to that.
(@gberaudo That hurry for EPFL)
There are some issues if the fields are reloaded and the current value equal to "false". I'll open an issue for that
> Print - add custom field values

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/src/controllers/abstractmobile.js
> Move rasterURL constant in html files

- contribs/gmf/src/directives/editfeature.js
- contribs/gmf/src/directives/partials/editfeature.html
> Add error message on server error, re enable the save button

- contribs/gmf/src/services/permalink.js
- src/services/statemanager.js
> Don't add unknown keys in the permalink

- .travis.yml
- Makefile
- buildtools/deploy.sh
- contribs/gmf/examples/objecteditinghub.js
actually they don't works anymore ...
http://camptocamp.github.io/ngeo/master/examples/
> Fix examples build

- src/services/statemanager.js
fix https://travis-ci.org/camptocamp/ngeo/jobs/191217059#L2420
> Fix type error

- contribs/gmf/src/controllers/abstractdesktop.js
demo: https://camptocamp.github.io/ngeo/desktop_touch/examples/contribs/gmf/apps/desktop
> Deactivate tooltips on touch device

- contribs/gmf/src/directives/partials/editfeatureselector.html
> Fix display of the currently editing layer name

- contribs/gmf/src/services/treemanager.js
> Don't restore tree elements that don't exist anymore

- Makefile
> Fix the examples and applications list

- src/services/statemanager.js
> Permalink fix

- contribs/gmf/src/directives/editfeature.js
- src/services/featurehelper.js
> Context menu for multi geometries

- src/services/statemanager.js
see: https://travis-ci.org/camptocamp/c2cgeoportal/builds/194753416#L4777
> For an unknown reason the value can be null

- contribs/gmf/less/fullscreenpopup.less
- contribs/gmf/options/gmfx.js
- contribs/gmf/src/controllers/abstract.js
- src/services/popup.js
Fix: #2195  
Example: https://testgmf.sig.cloud.camptocamp.net/bge
> Can resize popup in static fn openPopup

- contribs/gmf/src/directives/search.js
> Translate results in search

- contribs/gmf/src/controllers/abstractdesktop.js
- contribs/gmf/src/controllers/abstractmobile.js
- contribs/gmf/src/directives/contextualdata.js
- contribs/gmf/src/directives/mobilemeasurepoint.js
- contribs/gmf/src/directives/profile.js
- contribs/gmf/src/directives/search.js
- contribs/gmf/src/services/treemanager.js
- contribs/gmf/test/spec/services/permalinkservice.spec.js
- src/d3-ext/profile.js
- src/directives/profile.js
- src/directives/sortable.js
- src/ol-ext/format/featurehash.js
- src/ol-ext/interaction/measure.js
- src/ol-ext/interaction/measurearea.js
- src/ol-ext/interaction/measureazimut.js
- src/ol-ext/interaction/measurelength.js
- src/ol-ext/interaction/measurelengthmobile.js
- src/ol-ext/interaction/measurepointmobile.js
- src/ol-ext/menu.js
- src/services/location.js
- src/services/print.js
For: #2180
Replaced: 
- goog.object (foreach, clone, extend)
- goog.dom
Still existing: 
- goog.Math
- goog.fx,
- goog.uri
- goog.event
- goog.length (special)
And (goog.asserts, goog.provide, goog.requires)
> Remove some goog

- contribs/gmf/src/services/permalink.js
- src/services/statemanager.js
> Some fix in the permalink

- contribs/gmf/apps/oeview/index.html
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/directives/backgroundlayerselector.js
- contribs/gmf/src/directives/contextualdata.js
- contribs/gmf/src/services/permalink.js
- contribs/gmf/src/services/themesservice.js
- src/services/location.js
- src/services/statemanager.js
GCC allows to cast a `string` into a `number` that's in fact impossible than we shouldn't use it...
> Removes some dangerous typecast

- jsdoc/template/tmpl/details.tmpl
To have shorter patches on gh-pages
Related to #2274
> Put the branch name instance of the commit name

- package.json
Only `clean-css-cli` is needed.
> Remove clean-css dependency

- contribs/gmf/src/directives/layertree.js
> Fix the Zoom to scale display and action!!!

- contribs/gmf/src/controllers/abstractmobile.js
- src/services/query.js
> Set the mobile display query to 10 "low" dpi pixels

- contribs/gmf/src/services/datasourcesmanager.js
> Remove TODO that is now done

- contribs/gmf/src/directives/displayquerygrid.js
- contribs/gmf/src/directives/displayquerywindow.js
- contribs/gmf/src/directives/profile.js
- src/directives/attributes.js
- src/directives/createregularpolygonfromclick.js
> Better onInit for some components

- contribs/gmf/src/directives/filterselector.js
> Filter remove goog provide

- Makefile
> Only pull "reviewed" translations from transifex

- .travis.yml
- buildtools/deploy.sh
Correspondent internal pull request: #2319
> Fix the checks form external pull requests

- contribs/gmf/src/services/permalink.js
Fix #1962 
Question (from the issue):
> Don't crash if an element isn't present.
I can do that but it will crash later... What I'm supposed to do ? Adding if statements everywhere in this file ?
> Use injector in the gmfPermalink service

- contribs/gmf/src/services/themesservice.js
- contribs/gmf/test/spec/data/themes.js
- contribs/gmf/test/spec/services/themesservice.spec.js
> Fix the WMTS layers initialisation

- examples/backgroundlayer.js
- examples/backgroundlayerdropdown.js
- examples/data/backgroundlayers.json
- examples/layerloading.js
- examples/layerorder.js
- examples/layervisibility.js
> Don't use boundlessgeo demo server anymore

- contribs/gmf/less/layertree.less
- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/partials/layertree.html
fixes https://github.com/camptocamp/c2cgeoportal/issues/2801
> Add clear all button in layertree

- contribs/gmf/less/search.less
- contribs/gmf/src/directives/search.js
- options/ngeox.js
- src/modules/search/searchdirective.js
fixes https://github.com/camptocamp/c2cgeoportal/issues/2653
> Display a message in search when no results are found

- contribs/gmf/less/desktoplayertree.less
> Fix always visible scrollbar in the layertree

- contribs/gmf/src/directives/partials/print.html
> Align all the print dropdown menus to the right

- contribs/gmf/less/search.less
fixes #2357 
demo: https://camptocamp.github.io/ngeo/search_valign/examples/contribs/gmf/apps/mobile/
> Fix text in search input vertical align

- contribs/gmf/less/desktop.less
- contribs/gmf/less/search.less
- contribs/gmf/less/searchmobile.less
> Fix gmf-search result list position and border

- contribs/gmf/less/search.less
> Add the magnifier icon back

- contribs/gmf/apps/mobile/js/controller.js
- contribs/gmf/src/directives/mobilemeasurepoint.js
From an Object to an Array to be able to choose the display order.
fixes #2361
> Change gmf.MobileMeasurePointController.LayerConfig structure

- contribs/gmf/src/directives/partials/displayquerywindow.html
- contribs/gmf/src/gmf.js
> Only perform animation on elements that have a gmf-animatable css class

- contribs/gmf/less/displayquerywindow.less
- contribs/gmf/src/directives/partials/displayquerywindow.html
> gmf-displayquerywindow style fixes

- src/directives/mobilegeolocation.js
Missing from the 2.1 merge ...
> Use const instead of var

- contribs/gmf/examples/filterselector.html
- src/directives/partials/rule.html
- src/directives/rule.js
- src/ngeo.js
- src/ol-ext/format/wfsattribute.js
- src/rule/rule.js
- src/rule/text.js
- src/services/rulehelper.js
This PR allows a distinction between the "directed" and "custom" rules. "Custom" rules can have their operator set using a drop down list.  Directed rules always use the same operator.
> Filter custom rules

- buildtools/deploy.sh
> Run npm install before building the hosted examples

- contribs/gmf/src/directives/print.js
> Print layer with undefined legend

- contribs/gmf/src/services/permalink.js
> Don't activate layer set to 'false' in permalink

- contribs/gmf/src/directives/displayquerywindow.js
- contribs/gmf/test/spec/directives/displayquerywindow.spec.js
> Don't display features without properties

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/apps/oeedit/index.html
- contribs/gmf/apps/oeview/index.html
- contribs/gmf/less/desktop.less
- contribs/gmf/less/map.less
- contribs/gmf/less/mobile.less
> Add a tablet redirect

- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/desktop_alt/js/controller.js
> Open print panel on Ctrl-p

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
A tiny modification which will help the user know that he/she's authenticated.
Demo
https://pgiraud.github.io/ngeo/user_icon/examples/contribs/gmf/apps/desktop
> Change user icon when logged in

- contribs/gmf/less/desktop.less
- contribs/gmf/less/search.less
- contribs/gmf/less/searchmobile.less
> Set search results max-height

- contribs/gmf/apps/desktop_alt/js/controller.js
- contribs/gmf/less/desktop.less
- contribs/gmf/less/print.less
- contribs/gmf/src/directives/partials/print.html
- contribs/gmf/src/directives/print.js
- contribs/gmf/test/spec/controllers/gmfprintcontroller.spec.js
- src/services/printutils.js
fixes camptocamp/c2cgeoportal#2802
> Add custom scale input

- contribs/gmf/less/desktop.less
> Set theme selector max-height

- src/services/query.js
> Check query layer against the layer list from the WMS layer

- src/services/query.js
> Fix query condition

- contribs/gmf/apps/mobile/index.html
For: https://github.com/camptocamp/ngeo/issues/2354
Look also at https://github.com/camptocamp/c2cgeoportal/pull/2873
> No redirect on switch to desktop app from mobile

- contribs/gmf/apps/desktop/contextualdata.html
- contribs/gmf/apps/oeedit/contextualdata.html
- contribs/gmf/apps/oeview/contextualdata.html
- contribs/gmf/examples/partials/contextualdata.html
> Better link for google street view

- src/directives/rule.js
This PR adds the contextual menu that is shown on "right click" on a vector feature while editing a spatial rule in the filter tool.
The following items are shown per geometry type:
- circle: move
- line: move, rotate
- polygon: move, rotate
- rectangle: move, rotate
* https://adube.github.io/ngeo/filter-geom-contextual/examples/contribs/gmf/apps/desktop_alt/
> Filter - Support contextual menu in spatial rule

- contribs/gmf/examples/filterselector.html
- contribs/gmf/less/desktop.less
- contribs/gmf/src/directives/filterselector.js
- contribs/gmf/src/directives/partials/filterselector.html
- src/directives/filter.js
- src/directives/partials/filter.html
- src/directives/partials/rule.html
- src/directives/rule.js
This PR features various fixes for the filter tool:
* several CSS fixes
* prevent disabled elements to be clicked
* deactivate draw/edit tools within the filter tool when we switch to an other tool
* https://adube.github.io/ngeo/filter-m-various-fixes/examples/contribs/gmf/apps/desktop_alt/
> Filter - Fix various CSS and other issues

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop/less/main.less
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/desktop_alt/less/main.less
- contribs/gmf/apps/oeedit/index.html
- contribs/gmf/apps/oeedit/less/main.less
- contribs/gmf/apps/oeview/index.html
- contribs/gmf/apps/oeview/less/main.less
- contribs/gmf/less/desktop.less
And make it possible to change the header height without breaking the
image logo position.
> Simplify desktop header styling

- src/directives/mobilegeolocation.js
> Fix GeolocationProperty (was renamed in OL)

- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/partials/layertree.html
> Don't update the legend image is the div is not visible

- contribs/gmf/examples/datepicker.js
- contribs/gmf/examples/timeslider.js
- contribs/gmf/src/directives/layertree.js
- contribs/gmf/src/directives/timeslider.js
- contribs/gmf/src/services/syncLayertreeMap.js
- src/services/wmstime.js
- test/spec/services/wmstime.spec.js
This PR moves the `gmf.WMSTime` service to `ngeo.WMSTime`.
> Move gmf.WMSTime to ngeo.WMSTime

- contribs/gmf/apps/desktop_alt/js/controller.js
- contribs/gmf/src/services/syncLayertreeMap.js
- src/directives/mapquery.js
- src/services/layerHelper.js
replace #2134 
todo: test with an authenticated layer
> Add a query layer pointer if ngeoQueryOptions.hoverCursor is true

- contribs/gmf/src/directives/editfeature.js
This PR fixes the edit feature directive that was no longer working with Angular 1.6.
Fixes #2478 
Coming soon...
> Fix EditFeature directive for Angular 1.6

- src/datasource.js
> Add FeatureNS for qgisserver and geoserver

- contribs/gmf/src/directives/search.js
> Max zoom config

- src/directives/attributes.js
- src/directives/btngroup.js
- src/directives/modal.js
- src/directives/popup.js
- src/directives/profile.js
- src/directives/sortable.js
> Fix code indentation

- contribs/gmf/externs/gmf-themes.js
- contribs/gmf/src/services/syncLayertreeMap.js
Apply opacity to layer or layer group from theme
fixes https://github.com/camptocamp/c2cgeoportal/issues/2804
see #2349
> Apply opacity from theme

- contribs/gmf/src/services/permalink.js
> Don't stop tree traversal after first non mixed group

- contribs/gmf/src/directives/partials/editfeature.html
> Destroy 'Unsaved modifications' modal on hide

- .gitattributes
- .gitignore
- Makefile_windows
- docs/developer-guide.md
Actually this is @sbrunner's work... And it works...
Please review and merge if happy.
>  	Add makefile for Windows

- contribs/gmf/src/directives/authenticationdirective.js
- contribs/gmf/src/directives/profile.js
- contribs/gmf/src/services/permalink.js
- contribs/gmf/src/services/snapping.js
- contribs/gmf/src/services/treemanager.js
- examples/backgroundlayer.js
- examples/backgroundlayerdropdown.js
- jsdoc/template/publish.js
- src/ol-ext/interaction/measureazimut.js
- src/services/featureoverlay.js
- src/services/filters.js
- src/services/message.js
Found by https://pypi.python.org/pypi/codespell/
> Fix spelling

- contribs/gmf/apps/desktop_alt/js/importhelper.js
- options/ngeox.js
- src/modules/import/importonline.js
Fix https://github.com/camptocamp/ngeo/issues/2517
> Makes transformUrl returns a promise

- contribs/gmf/src/services/themesservice.js
> Better error message format for WMTS loading error

- src/services/filters.js
> Fix the ngeoNumberCoordinates filter documentation

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
FIX #2431 
Example: https://ger-benjamin.github.io/ngeo/message_for_android/examples/contribs/gmf/apps/desktop
@tom48484848 or @pfirpfel Can you help me for `TODO DE translation.`. Look inside the commit
> Add Message for outdated browsers

- src/directives/mobilegeolocation.js
> Fix geolocation untrack test

- examples/attributes.html
- src/directives/attributes.js
- src/directives/partials/attributes.html
> Pass the angular form to the ngeo-attributes component

- contribs/gmf/apps/oeedit/index.html
- contribs/gmf/apps/oeview/index.html
- contribs/gmf/examples/objecteditinghub.html
- contribs/gmf/src/directives/objecteditingtools.js
- src/directives/createregularpolygonfromclick.js
There are changes that were made to several components in ngeo and gmf that affected the ObjectEditing project.  This patch fixes some of those issues.
Please, review.
> Fix several regressions in ObjectEditing

- contribs/gmf/examples/search.html
- contribs/gmf/examples/search.js
- contribs/gmf/src/directives/search.js
To be notified when a directive has been created.
comments welcome
> Add new on-init callback to gmf.searchDirective

- contribs/gmf/externs/gmf-themes.js
- contribs/gmf/src/services/syncLayertreeMap.js
- contribs/gmf/src/services/themesservice.js
- src/services/layerHelper.js
> Use credential attribute to set crossOrigin value

- contribs/gmf/less/mobile-nav.less
> Remove shadow in search input

- contribs/gmf/apps/desktop_alt/js/importhelper.js
> Use arrow functions in app.GmfImportHelper

- src/ol-ext/interaction/modifyrectangle.js
can be tested here:
http://camptocamp.github.io/ngeo/modify_rectangle_you_are_not_alone/examples/contribs/gmf/apps/desktop
> Allow ngeo.interaction.ModifyRectangle to be used with other interactions

- package.json
This ngeo_2.1 branch is the previous version (8f6e07b) + this commit:
https://github.com/openlayers/openlayers/commit/85d0e9797cf2fe31c0c3a3198ce3780371d13c6e
fixes #2605
demo: https://camptocamp.github.io/ngeo/update_ol_2.1/examples/contribs/gmf/apps/mobile
> Use git://github.com/camptocamp/ol3#ngeo_2.1

- package.json
> Use latest OpenLayers version

- Makefile
- Makefile_windows
OSX doesn't support it
fixes #2627
> Don't use long option name for cut

- .gitignore
- Makefile
- contribs/gmf/apps/.tx/config.mako
> Add i10n demo file generation

- contribs/gmf/src/directives/authenticationdirective.js
- contribs/gmf/src/directives/drawfeature.js
- contribs/gmf/src/directives/mouseposition.js
- contribs/gmf/src/directives/objectediting.js
- contribs/gmf/src/directives/partials/elevationwidget.html
- contribs/gmf/src/services/themesservice.js
- src/directives/createfeature.js
- src/directives/drawfeature.js
- src/directives/measurearea.js
- src/directives/measureazimut.js
- src/directives/measurelength.js
- src/services/disclaimer.js
fix #2635
fix #2636
fix #2640
fix #2638
> Fix the i18n string collection

- .travis.yml
- buildtools/mako_build.json
And  do simple build on ngeo example, for faster Travis build
> Add pip cache

- contribs/gmf/externs/gmf-themes.js
- contribs/gmf/options/gmfx.js
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/controllers/abstractdesktop.js
- contribs/gmf/src/controllers/abstractmobile.js
- contribs/gmf/src/directives/contextualdata.js
- contribs/gmf/src/directives/displayquerygrid.js
- contribs/gmf/src/directives/displayquerywindow.js
- contribs/gmf/src/directives/elevation.js
- contribs/gmf/src/directives/print.js
- contribs/gmf/src/directives/profile.js
- contribs/gmf/src/services/permalink.js
- contribs/gmf/src/services/querymanager.js
- externs/mapfish-print-v3.js
- jsdoc/template/publish.js
- jsdoc/template/static/styles/jsdoc-default.css
- jsdoc/template/tmpl/details.tmpl
- jsdoc/template/tmpl/members.tmpl
- jsdoc/template/tmpl/params.tmpl
- jsdoc/template/tmpl/returns.tmpl
- src/ol-ext/interaction/measure.js
- src/services/message.js
fix https://github.com/camptocamp/c2cgeoportal/issues/2924
> Fix the API doc generation

- contribs/gmf/src/services/snapping.js
- options/ngeox.js
- src/services/query.js
> Geom works everywhere instancof the_geom

- src/ol-ext/interaction/modifyrectangle.js
> Simplify coordinates computation in ngeo.interaction.ModifyRectangle

- contribs/gmf/apps/desktop/contextualdata.html
- contribs/gmf/apps/oeedit/contextualdata.html
- contribs/gmf/apps/oeview/contextualdata.html
- contribs/gmf/examples/partials/contextualdata.html
- src/services/filters.js
- test/spec/services/filters.spec.js
> Put some order in easting/northing coordinates filter

- src/modules/import/wmsgetcap.js
The good WMS url to use is written in the Capabilities section not in Service
WMS links to test:
https://geoweb.so.ch/wms/isboden?SERVICE=WMS&REQUEST=GetCapabilities
http://services.sentinel-hub.com/v1/wms/570197e0-4b40-4783-b261-30a054d715bb
> Use the good GetMap url from the GetCapabilities

- src/modules/import/importonline.js
Avoid a js error see https://github.com/geoadmin/mf-geoadmin3/issues/3785
> Escape string before using it as a regex

- buildtools/mako_build.json
> Be able to add custom externs

- buildtools/check-example.js
- contribs/gmf/apps/desktop_alt/js/controller.js
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/examples/drawfeature.js
- contribs/gmf/examples/featurestyle.js
- contribs/gmf/examples/mobilemeasure.html
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/directives/displayquerywindow.js
- contribs/gmf/src/directives/drawfeature.js
- contribs/gmf/src/directives/featurestyle.js
- contribs/gmf/src/directives/mobilemeasurelength.js
- contribs/gmf/src/directives/mobilemeasurepoint.js
- contribs/gmf/src/directives/print.js
- contribs/gmf/src/services/permalink.js
- examples/measure.js
- options/ngeox.js
- src/directives/measurearea.js
- src/directives/measureazimut.js
- src/directives/measurelength.js
- src/ol-ext/interaction/measure.js
- src/ol-ext/interaction/measurearea.js
- src/ol-ext/interaction/measureazimut.js
- src/ol-ext/interaction/measurelength.js
- src/ol-ext/interaction/measurepointmobile.js
- src/services/featurehelper.js
- src/services/filters.js
> Fix decimal / precision mixage and unworking

- contribs/gmf/src/services/datasourcesmanager.js
- src/datasource.js
> Select the correct gmlFormat to read features from WFS queries

- contribs/gmf/apps/desktop/contextualdata.html
- contribs/gmf/apps/oeedit/contextualdata.html
- contribs/gmf/apps/oeview/contextualdata.html
- contribs/gmf/examples/partials/contextualdata.html
> Fix the coordinates filters

- contribs/gmf/src/services/themesservice.js
> Fix change theme change background (i18n problem)

- contribs/gmf/src/services/querymanager.js
FIX: #2686 
~~Waiting for some tests by the customer (SITJ)~~
Work fine. I merge.
> Don't query out of resolution childlayers

- contribs/gmf/src/directives/partials/print.html
> Fix css classes

- src/directives/mobilegeolocation.js
> Use i18able message for geoloc errors

- src/directives/mobilegeolocation.js
> Request high accuracy position

- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/apps/oeedit/index.html
- contribs/gmf/apps/oeview/index.html
> Fix curly brackets at pages loading

- contribs/gmf/src/directives/contextualdata.js
> Fix contextual-data class not applied to IE11

- contribs/gmf/src/directives/featurestyle.js
- src/services/featurehelper.js
> Fix recenter when selecting a drawing out of view

- src/directives/mobilegeolocation.js
> Use english for geolocation

- externs/angular-gettext.js
From `node_modules/angular-gettext/dist/angular-gettext.js`.
> Fix angular gettext extern

- contribs/gmf/less/map.less
> Fix theme name in theme selector for IE11

- contribs/gmf/src/directives/partials/layertree.html
Follow up from #1055 (this fixed some performance issues with legends but not the loading)
Fix #2755
> Fix legends loading for mobile

- contribs/gmf/src/directives/drawfeature.js
- contribs/gmf/src/directives/editfeature.js
> Add a tolerance to show contextual menu when editing features

- .travis.yml
- Makefile
> Move ngeox check to a dedicated rule

- src/ol-ext/interaction/modifyrectangle.js
Fixes #2742
When starting to drag a rectangle, the sides vectors are precalculated and used for the duration of the resize operation instead of as the rectangle is resized. If one of the vectors is invalid (i.e. the situation that caused the rectangles to turn into triangles), we can replace it with a vector perpendicular to the other, valid vector. 
In the very unlikely event of both vectors being invalid (which requires all 4 corners of the rectangle to be at the exact same point when the resize starts), the algorithm still maintains a rectangle shape.
> Fix rectangle resize with rotation

- buildtools/deploy.sh
- contribs/gmf/options/gmfx.js
- contribs/gmf/src/controllers/abstract.js
> Add the missing cgxp.tools.openInfoWindow alias

- contribs/gmf/apps/mobile/index.html
- contribs/gmf/less/desktop.less
- contribs/gmf/less/map.less
- contribs/gmf/less/mobile.less
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/controllers/abstractdesktop.js
- contribs/gmf/src/controllers/abstractmobile.js
https://jira.camptocamp.com/browse/GSGMF-6
> Provide rotation interaction and styling

- contribs/gmf/src/controllers/abstract.js
> Finally add missing exports

- contribs/gmf/apps/mobile/js/controller.js
- contribs/gmf/apps/mobile_alt/js/controller.js
- contribs/gmf/options/gmfx.js
- contribs/gmf/src/controllers/abstract.js
- contribs/gmf/src/controllers/abstractmobile.js
- examples/mobilegeolocation.js
- options/ngeox.js
- src/directives/mobilegeolocation.js
https://jira.camptocamp.com/browse/GSGMF-7
This PR is only about the autorotating feature.
> Feature gsgmf 7 provide tracking

- contribs/gmf/src/directives/print.js
> Be able to choose another scale when scale = -1

- buildtools/mako_build.json
This is needed for the build into Docker
> Always give the template cache to Google closure compiler

- src/services/print.js
> Don't send empty WMS param to the print

- src/modules/import/wmtsgetcap.js
> Test if OperationMetadata tag exists

- contribs/gmf/src/services/datasourcesmanager.js
- contribs/gmf/src/services/syncLayertreeMap.js
- contribs/gmf/src/services/themesservice.js
- src/directives/layertree.js
> Use ol.getUid to the gmfLayer to populate the treeCtrlCache

- Makefile
- contribs/gmf/apps/desktop/index.html
- contribs/gmf/apps/desktop_alt/index.html
- contribs/gmf/apps/mobile/index.html
- contribs/gmf/apps/mobile_alt/index.html
- contribs/gmf/apps/oeedit/index.html
- contribs/gmf/apps/oeview/index.html
- src/directives/attributes.js
- src/directives/datepicker.js
Standardize js files in dev mode
Use the non minified js in dev mode
Fix some types
Fix s dependency
fix #2858
> Set the language to the attibutes datepicker

- contribs/gmf/apps/mobile/index.html
> Add missing gmfLayersUrl constant in mobile app
