examples/animation.js, examples/control.html, examples/geolocation.html, examples/interactionbtngroup.html, examples/interactiontoggle.html, examples/layermanager.html, examples/layeropacity.html, examples/layertree.html, examples/layervisibility.html, examples/permalink.html, examples/permalink.js, examples/simple.html, src/directives/map.js
This pull request reverts commit 2dd3937b290f177339bbef292743fcfdacb5b8a7, which was added as part as https://github.com/camptocamp/ngeo/pull/129.
2dd3937b290f177339bbef292743fcfdacb5b8a7 may make sense, but I think it requires more thinking. And if we decide to make the map directive watch map changes we need to do the same in the other directives that use a map, namely `ngeoControl`, `ngeoLayertree`, `ngeoLayertreenode`, and `ngeoResizemap`.
The question is: do we want to support changing the map during the lifetime of the application?
=> Revert "Make map directive watch map expr"

examples/layermanager.html, examples/layermanager.js
This PR simplifies the layermanager example and uses one-time binding where possible for that example.
=> Use one-time binding in layermanager example

src/services/location.js
As for now, IE9 complains about that "Object doesn't support property or method 'replaceState'" when the map is changed (permalink update). This may be observed in http://erilem.net/ngeo/location/permalink.html
IE9 indeed doesn't support the "history" API that is used to update the address bar.
The ngeoLocation service does have a test on the availability of history but it seems this is not enough.
This PR improves the test, making sure that "replaceState" is actually available.
=> Make sure the history API is fully supported before using it

src/directives/layertree.js, src/directives/layertreenode.js
This pull request addresses two goals. It gives the user the opportunity to get for each node:
- the level depth,
- the uid of the parent element. This corresponds to tree uid for the nodes of the first level.
One purpose of this is for example to get only one node expanded at a time for a given level when using bootstrap and collapse/accordion.
Please review.
=> Layertree levels

examples/layertree.js, examples/partials/layertreenode.html, src/directives/layertree.js, src/directives/layertreenode.js, src/directives/partials/layertree.html, src/directives/partials/layertreenode.html
Currently, when using the `ngeoLayertree` and/or `ngeoLayertreenode` directives the `ngeoLayertreeLayerFactory` service should be defined by the application (this service is a function responsible for returning a layer for a tree node). This works well when only one layer tree is used in the page, but it is inflexible when multiple layer trees are used, because the layer factory function is the same for all the layer trees.
This PR fixes the problem by adding a new attribute to the `ngeoLayertree` and `ngeoLayertreenode` directives. This new attribute allows specifying a a layer expression, which, in most cases, will be a function called on the application controller. This does add some complexity to the user of the directive, but it is also more flexible.
I also took the opportunity to …
=> Replace the layer tree layer factory by a layer expression

examples/control.html, examples/control.js, src/directives/control.js
This is WIP depending on https://github.com/openlayers/ol3/pull/3139.
=> Make control directive rely on control.setTarget

examples/layertree.js, src/directives/layertree.js, src/directives/layertreenode.js, src/directives/partials/layertree.html, src/directives/partials/layertreenode.html
As discussed with @pgiraud this PR brings further improvements to the layertree directive. In particular the `ngeo-layertree-layer` attr is renamed to `ngeo-layertree-nodelayer`.
=> Improvements to layertree directive

src/services/decoratelayer.js
This PR fixes a bug where the decorate layer service passed a string rather than a number to `layer.setOpacity` function.
=> Pass a number to layer.setOpacity

examples/layerorder.js, src/services/syncarrays.js, test/spec/services/syncarrays.spec.js
As discussed with @pgiraud this PR renames the `ngeoArraySync` service to `ngeoSyncArrays`. This service is a function so we name it after a verb, just like `ngeoDecorateLayer` and friends.
=> Rename ngeoArraySync to ngeoSyncArrays

examples/partials/backgroundlayerdropdown.html
This PR removes 3 watchers in the `backgroundlayerdropdown` example: 1 watcher par item in the dropdown.
=> Remove unnecessary watchers

examples/backgroundlayerdropdown.html, examples/backgroundlayerdropdown.js, examples/scaleselector.html, examples/scaleselector.js, src/directives/partials/scaleselector.html, src/directives/scaleselector.js
This PR adds a scale selector example. This example creates a "scale selector" directive based on Bootstrap's `dropdown` jQuery plugin. The view resolution changes when a scale is selected in the scale selector. And the selected scale changes in the scale selector when the view resolution changes.
See http://erilem.net/ngeo/scaleselector/scaledropdown.html.
=> Add a scale selector example

src/services/popup.js
This is to handle the cases where the popup content is trusted with `$sce.trustAsHtml`.
=> Change param type for ngeo.Popup#setContent

examples/layertree.js, exports/services/popup.js, src/services/popup.js
This PR makes a number of changes to the ngeo popup service:
* Use an isolate scope
* Replace the `show` method by `setOpen` (making it possible to hide the popup using `setOpen(false)`)
* Add a `getOpen` method to know whether the popup is currently open
Please review.
=> Changes to the popup service

Makefile, examples/layerorder.html, examples/layerorder.js, src/directives/sortable.js
This PR changes the `ngeo-sortable` directive to rely on Closure's `goog.fx.DragListGroup` rather than jQuery UI's sortable plugin.
This removes the dependency on jQuery UI and it will make the `ngeo-sortable` directive work on touch devices when https://github.com/google/closure-library/pull/405 is fixed.
Please review.
=> Base the sortable directive on Closure

src/ol-ext/interactions/measure.js
The default value for ol.Overlay autoPan is now  false. So there's no need to set autoPan to false for the measure tooltips.
=> ol.Overlay autoPan now false by default

src/directives/scaleselector.js
This PR follows the guidelines to use `goog.bind` instead of `angular.bind` in the ngeo code.
=> Use goog.bind instead of angular.bind

examples/measure.js, src/ol-ext/interaction/measurearea.js, src/ol-ext/interaction/measurelength.js
This pull request's goal is to get more realistic values for length and area measurements by converting coordinates to wsg84 and using geodesic measurements.
I don't think it needs to be optional since it will work in all cases no matter what the map projection is.
Please review.
=> Compute length and area using a wsg84 sphere (geodesic)

examples/profile.html, examples/profile.js, externs/ngeox.js, src/d3-ext/profile.js, src/directives/profile.js
An `ngeox.profile.ProfileOptions` typedef has been introduced and must be passed to the `ngeo.profile` factory. Additionally, the profile now depends on an `ngeo.ProfileExtractor`  to support any tabular data.
The directive has been updated to require the options attribute.
Basic support for updating the profile was added.
=> Introduce an ngeox.profile.ProfileOptions

examples/measure.html, examples/measure.js, externs/ngeox.js, src/ol-ext/interaction/measure.js, src/ol-ext/interaction/measurearea.js, src/ol-ext/interaction/measureazimut.js, src/ol-ext/interaction/measurelength.js
This PR makes it possible to use Angular (angular-gettext) to translate measure tooltips. The `measure` example shows how it works.
Please review.
=> Make the measure tooltips translatable

src/ol-ext/interaction/measure.js
This PR removes the `goog.provides('ngeo.interaction')` statement from `interaction/measure.js`. It also adds `goog.provides('ngeo.MeasureEventType')` to that file.
=> Fix goog.provides in measure.js

examples/profile.html, examples/profile.js, externs/d3.js, externs/ngeox.js, src/d3-ext/profile.js, src/directives/profile.js
This PR allows displaying POIs along the elevation curve.
There is now two extractors: one for elevation, and one for the POIs.
The `showPois` method on the profile can be used to update the POIs, allowing modification of the POIs without redrawing the curves: this operation may be common when editing POIs.
=> Optionnaly display POIs in profile

.travis.yml, Makefile
This commit makes Travis publish the standalone examples to https://camptocamp.github.io/ngeo/master/. This is done by running the gh-pages-from-travis Makefile target, only for the master branch, and when the build is not the run as a result of a pull request.
The secure variable in .travis.yml is created using this command:
```
$ travis encrypt -r camptocamp/ngeo 'GH_TOKEN=<token>'
```
where `<token>` is a "GitHub Personal access token" created on https://github.com/settings/applications.
=> Make Travis publish examples to github.io

Makefile
http://camptocamp.github.io/ngeo/master/ doesn't hav the `index.html` page. This PR fixes that.
=> Add examples index page to camptocamp.github.io/ngeo/master

externs/ngeox.js, src/d3-ext/profile.js
For example, prevent displaying negative values with `yLowerBound = 0`.
=> Profile y lower bound

src/d3-ext/profile.js
The value '15' is empirical and roughly represent the height in pixels
between two ticks. '10' is the  default number of ticks of d3.
=> Avoid overlapping y ticks in profile

src/directives/sortable.js
Make the `sortable` directive use the `getOptions` function. Calling that function is necessary to get the default handle class name when it's not specified by the user.
=> Make sortable directive use getOptions

Makefile, buildtools/example.json, buildtools/examples-all.json, buildtools/ngeo.json, examples/search.html, examples/search.js, externs/ngeox.js, package.json, src/directives/search.js, src/services/creategeojsonbloodhound.js
This PR adds an `ngeoSearch` directive, an `ngeoCreateGeoJSONBloodhound` service, and a `search` example.
The `ngeoSearch` directive is very generic/low-level. It just provides a directive for decorating an element with `typeahead`.
The `ngeoCreateGeoJSONBloodhound` service is a function returning a Bloodhound engine that expects GeoJSON responses from the remote service, and create `ol.Feature` objects as the suggestions.
The `search` example shows how to use the `ngeoSearch` directive and the `ngeoCreateGeoJSONBloodhound` service.
Please review.
=> Add an ngeoSearch directive

src/directives/partials/scaleselector.html, src/directives/scaleselector.js
With this commit scales are ordered by their zoom levels in the scale dropdown.
=> Fix scale order in scale selector

src/services/location.js
Useful when you want to change the path of the current location instead of just updating query parameters.
=> Add getPath and setPath methods to Location

exports/services/location.js, src/services/location.js, test/spec/services/location.spec.js
This PR adds the `ngeo.Location#getParamKeys` method. It also adds exports for the `hasParam`, `getPath` and `setPath` methods that were recently added.
=> Add ngeo.Location#getParamKeys

src/d3-ext/profile.js
I'm using `goog.object.extend` so that the user can configure only part of the `formatter`.
Please review.
=> Formatter can be configured partially

buildtools/example.json, buildtools/examples-all.json, examples/interactionbtngroup.js, examples/profile.js, src/ol-ext/interaction/measure.js, src/ol-ext/interaction/measureazimut.js
This PR fixes compile errors that we get because we now [use](https://github.com/openlayers/closure-util/pull/51) a more recent version of the compiler.
The new compiler is much more strict with respect to the presence/absence of `goog.provide` and `goog.require`.
And, unfortunately, I had to move `missingRequire` from `jscomp_error` to `jscomp_off` for the compilation of the examples. Otherwise we get compilation errors when `ngeox.js` is used as a source file rather than an externs file, which is what to do when compiling the application code. Indeed, `ngeox.js` cannot include `goog.provide`'s because it is used as an externs file for `ngeo.js`.
Please review.
=> Fix compile errors

Makefile, karma-conf.js, src/directives/scaleselector.js, test/spec/directives/scaleselector.spec.js
This PR changes the scale selector directive to use `$applyAsync` instead of `$apply` in the `change:resolution` listener. It is wrong to use `$apply` in a `change:resolution` listener, because it is not guaranteed that a `change:listener` will be executed outside Angular context.
The PR also adds tests for the scale selector directive. It also sets things up to be able to test directives with templates.
Please review.
=> Use $applyAsync in scale selector directive

src/d3-ext/profile.js, src/directives/profile.js
With this pull request the d3 component can receive `undefined` for data in which case the `svg` element is removed.
Please review.
=> Remove svg tag when there's no data

exports/services/location.js, src/services/location.js, test/spec/services/location.spec.js
This change implies to rename getUri() to getUriString() in the projects using ngeoLocation. Is there a changelog to advertise this?
=> Make the goog.Uri object available in ngeoLocation

buildtools/example.json, buildtools/examples-all.json, buildtools/ngeo.json, docs/guidelines.md, examples/animation.js, examples/backgroundlayer.js, examples/control.js, examples/geolocation.js, examples/interactionbtngroup.js, examples/interactiontoggle.js, examples/layeropacity.js, examples/layerorder.js, examples/layertree.js, examples/layervisibility.js, examples/measure.js, examples/permalink.js, examples/profile.js, examples/scaleselector.js, examples/search.js, examples/simple.js, src/directives/layertree.js, src/directives/layertreenode.js, src/directives/scaleselector.js
Use the new export_local_property_definitions compiler option. Using this option properties can be marked with `@export` in constructors. This means we can now use the following in controller constructors instead of using the square bracket notation:
```js
app.MyController = function() {
/**
* @type {Object}
* @export
*/
this.aProperty = {};
// …
};
```
=> Use export_local_property_definitions compile flag

externs/mapfish-print-v3.js
Add missing `requestEncoding` property to `MapFishPrintWmtsLayer` in the `mapfish-print-v3.js` externs file.
Please review.
=> Add requestEncoding to mapfish print externs

examples/mapfishprint.js, src/services/print.js, test/spec/services/print.spec.js
This commit does two things: (1) it allows passing `$http` options to `createReport` and `getStatus`, making it possible to pass a request canceler to `$http`, and (b) change the promise returned by `createReport` and `getStatus` to be an http promise instead of a regular promise, providing more flexibility and making it possible to be notified in case of HTTP errors.
=> Make it possible to pass $http options to print

src/d3-ext/profile.js
This PR fixes the shift when the y domain goes below the yLowerBound.
It also adds comments and better name for ratioXY.
=> Fix profile ydomain computation

examples/layertree.js
This commit fixes #227, reported by @fgravin. The bug is related to Angular's one-time binding (correctly) considering `null` values as defined values. The fix involves using `undefined` instead of `null` as the initial value for the `tree` data model.
Fixes #227.
=> Fix layertree example

src/ol-ext/interaction/measure.js, src/ol-ext/interaction/measurearea.js, src/ol-ext/interaction/measureazimut.js, src/ol-ext/interaction/measurelength.js
With this pull request, I make it so the measurement can be displayed even on touch devices.
Now the help tooltip is the only one to be shown on mousemove. The measurement tooltip displays and updates (content and position) as soon as the geometry is changed.
Please review.
=> Display measurements even on touch devices

examples/geolocation.js, examples/interactionbtngroup.js, examples/interactiontoggle.js, examples/measure.js, examples/profile.js, examples/search.js, package.json, src/ol-ext/interaction/measure.js, src/ol-ext/interaction/measurearea.js, src/ol-ext/interaction/measureazimut.js, src/ol-ext/interaction/measurelength.js
This PR removes the use of `ol.FeatureOverlay`. Feature overlays are replaced by "unmanaged" vector layers, that is vector layers that are always on top.
Fixes #236.
=> Remove ol.FeatureOverlay

examples/mapfishprint.js
This changes the mapfishprint example to use the new geomapfish server as the previous one is not in service anymore.
But there still is a problem. The WMS layer works but print requests fail because of the CORS issue. This is the error I get in the console:
```
XMLHttpRequest cannot load http://geomapfish-demo.camptocamp.net/1.6/wsgi/printproxy/report.pdf. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.
```
@sbrunner, I think we need your help for this.
=> Use new geomapfish server

src/services/print.js, test/spec/services/print.spec.js
- Use encodeImageWmsLayer to encode layer of type Tile and of source TileWMS
- Add a function to get the correct URL if the source is TileWMS and not
ImageWMS
- Add a custom parameter in the object to get images with transparency
=> Allow tiles from a TileWMS to be printed

src/services/print.js
This PR adds missing `goog.require`'s. I'll merge it when Travis is green.
cc @Jenselme.
=> Add missing goog.requires

src/services/print.js
Lines imported from KML have a filled style which makes them look as polygon once printed. This PR solves this problem.
However, as for #239, it may be a bug in openlayer. @elemoine any opinion?
=> Prevent LineStrings to be filled

src/services/print.js
This follows up on #247. We immediately `continue` the loop when we find a feature with no geometry.
@Jenselme, does this look ok to you?
=> Refactor code in the print service

src/ol-ext/interaction/measure.js
This fixes a bug where the user cannot add a point under the measure tooltip.
=> Set stopEvent to true in measure tooltip overlay

exports/services/print.js, src/services/print.js
This commit makes `ngeo.Print#encodeLayer` public. This, for example, makes it possible to applications to print "unmanaged" vector layers.
=> Make ngeo.Print#encodeLayer public

externs/closure-compiler.js
With https://github.com/google/closure-compiler/pull/1030 and https://github.com/google/closure-compiler/pull/1031 now closed we can remove these extern definitions.
=> Remove Angular externs from closure-compiler.js

src/directives/resizemap.js
When we listen on $animate events, callbacks may be called even for children of the element we listen to. This pull request prevents this by ensuring that the target of the event is actually the element itself.
Please review.
=> Strictly listen on container, not children

src/services/printutils.js
This commit makes `getOptimalScale` return `-1` if no optimal scale can be found.  This occurs when the optimal scale is lower than or equal to the smallest value of the `printMapScales` array. When this happens the user can take the action of her choice (e.g. use the smallest print scale).
=> Make getOptimalScale return -1 if no optimal scale

src/services/print.js, test/spec/services/print.spec.js
With this commint the vector style type used in the print spec is selected based on the geometry type, instead of being selected based on the properties found in the `ol.style.Style` object. Relying on the properties found in the `ol.style.Style` object is fragile, as a style object may be used for drawing different types of geometries.
=> Select print style type based on geometry type

externs/twbootstrap.js, externs/typeahead.js
`angular.JQLite` was de-typedef'ed in closure-compiler. See https://github.com/google/closure-compiler/commit/d785704f64e95e8764db5a9fb02809aaabf42c7e. Because of that we need to add externs definitions to `angular.JQLite`.
=> Add externs definitions on angular.JQLite

externs/twbootstrap.js
This one was not caught by the ngeo build because this extern definition is not used in the ngeo code or in one of the examples.
=> Fix typo in twbootstrap externs file

.travis.yml
This is an attempt to use `language: python` in the Travis config. Not sure it works and makes sense really.
=> Use language:python in .travis.yml

examples/gmf-simple.html, examples/gmf-simple.js, src/directives/gmf-map.js
Port of https://github.com/camptocamp/c2cgeoportal/pull/1471
To be discussed:
* ~~the new ngeo.gmf directive/controller are in a dedicated ``directives/gmf/`` to make GMF directives apart (clearer?).~~
* ~~on the other hand the ``gmf-simple.html`` example is at the root of ``examples/``. If files are placed in a ``gmf/`` dir, the page complains that ``Main script not in manager paths: ...``. I also suspect troubles with the hosted examples deployment.~~
* ~~the map expands on the whole viewport, the explanation test being pushed ouside of the window, despite the "#map" style provided in the example page. Any idea?~~
=> Add ngeo.gmf.mapDirective

externs/mapfish-print-v3.js, src/services/print.js, test/spec/services/print.spec.js
Currently, the opacity of WMTS and Vector layers are not set in the print specs sent to MapFish Print. This PR fixes that.
Please review.
=> Send layer opacity to MapFish Print

src/d3-ext/profile.js
When the profile div is not perfectly aligned, the `distance` may be greater than the maximum distance from the data. In this case, `i` is out of range and `point` would be `undefined`.
This commit adds a test.
=> Check for undefined point in profile highlight

contribs/gmf/examples/simple.html, contribs/gmf/src/directives/map.js
This removes the binding used for the gmf-map directive's "map" property. With this change the directive user no longer needs to use a one-time binding expression to prevent Angular from creating an unnecessary watcher.
=> Remove binding in gmf-map directive

Makefile
12558b9 introduced a regression where `$(GIT_BRANCH)` is used instead of `master` in the `gh-pages-from-travis` target.
=> Fix gh-pages-from-travis Makefile target

buildtools/gmf.json
The gmf simple example currently does not work on github.io. See http://camptocamp.github.io/ngeo/master/contribs/gmf/simple.html. This is because the `gmf.js` build does not include the `gmfMap` directive because of a mis-configuration in `gmf.json`. This PR fixes it.
=> Fix the gmf.js build

examples/search.html, examples/search.js, externs/typeahead.js, package.json, src/services/creategeojsonbloodhound.js
This change is not backward compatible
Fixes #282.
=> Update typeahead  to v0.11.1

src/services/featureoverlay.js
This PR sets `useSpatialIndex` to `false` and `updateWhileAnimating` and `updateWhileInteracting` to `true` on feature overlays. See the commit messages for more details.
Please review.
=> Feature overlay configuration

contribs/gmf/examples/search.js, contribs/gmf/src/directives/search.js, exports/services/featureoverlay.js
This PR makes a few changes related to the GMF search directive.
The exports for `ngeoFeatureOverlayMgr` and `ngeoFeatureOverlay` are necessary for non-compiled applications (our examples on github.io for example).
@ger-benjamin, could you please review this?
=> Changes for the gmf search directive

contribs/gmf/src/directives/map.js, contribs/gmf/src/directives/search.js, src/directives/btngroup.js, src/directives/scaleselector.js
Recent versions of the compiler require a goog.provide for every type defined as constructor.
=> Add goog.provide's for constructors

Makefile
With this PR `make dist` displays the build size after compilation:
```shell
$ make dist
mkdir -p dist/
node buildtools/build.js buildtools/ngeo.json dist/ngeo.js
info ol Parsing dependencies
info ol Compiling 396 sources
uncompressed: 516667 bytes
compressed: 156518 bytes
mkdir -p dist/
node buildtools/build.js buildtools/ngeo-debug.json dist/ngeo-debug.js
info ol Parsing dependencies
info ol No compile options found.  Concatenating 389 sources
uncompressed: 3936783 bytes
compressed: 741998 bytes
mkdir -p dist/
node buildtools/build.js buildtools/gmf.json dist/gmf.js
info ol Parsing dependencies
info ol Compiling 399 sources
uncompressed: 519074 bytes
compressed: 157238 bytes
```
=> Display build sizes

examples/permalink.html, examples/permalink.js, exports/ol-ext/format/featurehash.js, externs/ngeox.js, src/ol-ext/format/featurehash.js, test/spec/ol-ext/format/featurehash.spec.js
This PR adds an OpenLayers format for encoding and decoding features in permalinks. The code is based on sbrunner's OpenLayers 2 URLCompressed plugin.
TODOs:
=> Add ngeo.format.FeatureHash

examples/interactionbtngroup.js, exports/services/featureoverlay.js, src/services/featureoverlay.js, test/spec/services/featureoverlay.spec.js
This PR adds the possibility to configure an ngeo feature overlay with a feature collection (`ol.Collection.<ol.Feature>`).
This makes it possible to bind a drawing tool to an feature overlay:
```js
var features = new ol.Collection();
var overlay = ngeoFeatureOverlayMgr.getFeatureOverlay();
overlay.setStyle(myStyle);
overlay.setFeatures(features);
var draw = new ol.interaction.Draw({
type: 'point',
features: features
});
```
With this features drawn with the draw interaction are added to the ngeo feature overlay.
=> Add a setFeatures method to feature overlays

test/spec/services/print.spec.js
With https://github.com/marcjansen/ol3/commit/80995159b1e71cc5c48b634fadc9d52f02830efb text styles now have a default color. This broke the ngeo print tests. This commits fixes the problem by adding a fill style to the text styles used in the tests.
=> Fix the print tests

externs/ngeox.js, src/ol-ext/format/featurehash.js, test/spec/ol-ext/format/featurehash.spec.js
This commit adds an optional "properties" option to the ngeo.format.FeatureHash constructor. Using this new option the user can provide a function that returns serializable properties for a feature. This can be used to filter out feature properties. This can also be used to add properties that are not set in the feature.
=> Add a "properties" option to ngeo.format.FeatureHash

Makefile
Right now only ngeo.js is available on camptocamp.github.io. This adds ngeo-debug.js.
=> Copy ngeo-debug.js to examples/lib on github.io

externs/ngeox.js, src/ol-ext/format/featurehash.js
This PR adds an `encodeStyles` option to `ngeo.format.FeatureHash`. When set to `false` the format does not encode styles.
Please review.
=> Add an encodeStyles option to ngeo.format.FeatureHash

Makefile
We get a compile error with the latest jquery-1.9.js externs file:
```
ERR! compile .build/externs/jquery-1.9.js:94: ERROR - accessing name jQuery in externs has no effect. Perhaps you forgot to add a var keyword?
ERR! compile var $ = jQuery;
ERR! compile         ^
ERR! compile
ERR! compile
ERR! compile 1 error(s), 0 warning(s)
ERR! compile
ERR! Process exited with non-zero status, see log for more detail: 1
```
This commit fixes the problem by fetching the jquery-1.9.js file from a specific commit.
This is a temporary fix, until we (or someone) really fix the actual problem.
=> Latest jquery-1.9.js externs file is broken

Makefile, buildtools/example.json, buildtools/examples-all.json, buildtools/gmf.json, buildtools/ngeo.json, externs/closure-compiler.js
OpenLayers now uses version 20150920 of Closure Compiler. This PR updates ngeo to
* use the `master` version of the jquery-1.9.js externs again
* remove the `checkStructDictInheritance` option which does no longer exist
* remove the definition of `Navigator.prototype.languages`
=> Use version 20150920 of Closure Compiler

buildtools/check-example.js
Currently exceptions thrown when checking the examples with the `check-example.js` PhantomJS script are not detected. This leads to PRs whose builds pass Travis but whose examples don't actually work on github.io. This PR aims to fix that by making `check-example` exit 1 when errors are detected on the console.
=> Make check-example exit 1 on console errors

contribs/gmf/src/proj/epsg21781projection.js
To avoid to copy / paste this file in (almost) all client project.
=> Create EPSG21781 projection definition

contribs/gmf/examples/mobileapp.html
The Travis build generated an index page for the examples. The index page generation script currently fails because the `mobileapp` gmf example does not have a description. This PR adds a description to the example.
=> Add description to mobileapp example

src/ol-ext/interaction/measure.js
This fixes a typo in the docs of `ngeo.MeasureEventType.MEASUREEND`.
=> Fix measureend @event annotation

exports/services/printutils.js, src/services/printutils.js, test/spec/services/printutils.spec.js
This PR adds a `getOptimalResolution` function to `ngeo.PrintUtils`. This function returns the optimal map resolution for a given print scale. The optimal map resolution is such that the print rectangle fits into the map view.
This is WIP at the moment.
TODOs:
=> Add an ngeo.PrintUtils#getOptimalResolution function

contribs/gmf/src/directives/locationchooser.js, contribs/gmf/src/directives/map.js, contribs/gmf/src/directives/search.js, src/directives/btngroup.js, src/directives/control.js, src/directives/layertree.js, src/directives/map.js, src/directives/modal.js, src/directives/popup.js, src/directives/profile.js, src/directives/resizemap.js, src/directives/scaleselector.js, src/directives/search.js, src/directives/sortable.js
The primary consumer of annotations is the Closure Compiler. Directive factories are not constructors. And I don't think we should make the Closure Compiler believe they are constructors.
I know this is going to cause problems on the apidoc side, but I think we should address that problem in a different way.
=> Directive factories are not @constructor's

examples/modal.html, src/directives/modal.js
This changes the `ngeo-modal` directive to use `ngModelController`. With this `ngeo-modal` will be used together with `ng-model`. For example:
```html
<ngeo-modal ng-model="ctrl.modalShownHidden" ng-model-options="{getterSetter: true}">
</ngeo-modal>
```
This makes the directive more flexible. For example it can be used with a getter/setter as the assignable expression (as shown in the example above).
Please review.
=> Change ngeo-modal to use ngModelController

Makefile, buildtools/templatecache.mako.js
`templatecache.mako.js` currently removes spaces and line breaks between HTML elements. This is not correct, and it may break the user's HTML code. This commit fixes the problem by using the `htmlmin` tool instead of minifying the HTML ourselves.
This is WIP in progress at the moment (being tested in https://github.com/Geoportail-Luxembourg/geoportailv3/pull/929).
=> Use htmlmin in templatecache.mako.js

contribs/gmf/externs/gmfx.js, contribs/gmf/src/services/exportfeatures.js
The `gmfExportFeatures` service is a function to be used for exporting a GPX or KML document. The service relies on GeoMapFish's `exportgpxkml` web service.
Providing an example would be good, but the `exportgpxkml` is not yet available on the GeoMapFish demo instance.
=> Add a gmfExportFeatures service

exports/ol-ext/interactions/measure.js, src/ol-ext/interaction/measure.js, src/ol-ext/interaction/measurearea.js, src/ol-ext/interaction/measureazimut.js, src/ol-ext/interaction/measurelength.js
This PR refactors the measure interaction code to add `getFormattedArea` and `getFormattedLength` static function and make them public for use from outside.
Ready for review.
=> Add public getFormattedArea and getFormattedLength functions

examples/importfeatures.html, examples/importfeatures.js, src/directives/filereader.js, test/spec/directives/filereader.spec.js
This PR adds an `ngeoFilereader`  directive and an example showing how to use that directive to import features from a KML document read from the user's file system.
The directive is based on the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) object, itself being part of the [File API](https://w3c.github.io/FileAPI/#FileReader-interface).
Works in Chrome, Firefox, Safari and IE > 9.
=> Add an ngeoFilereader directive

src/d3-ext/profile.js, src/directives/map.js, src/directives/modal.js, src/directives/search.js, src/services/backgroundlayermgr.js, src/services/featureoverlay.js, src/services/location.js, src/services/popup.js, src/services/print.js, src/services/syncarrays.js
"The @example tag is not intended to be used to generate 'inline' examples"
From: https://code.google.com/p/jsdoc-toolkit/wiki/TagExample
=> Don't use the example jsdoc tag but indent the code

src/services/creategeojsonbloodhound.js
Wait 50ms instead of the default 300ms on each request (~speedup the search).
https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#remote
=> Set search's rateLimitWait to 50ms

contribs/gmf/exports/source/swisstoposource.js, contribs/gmf/externs/gmfx.js, contribs/gmf/src/source/swisstoposource.js
=> Add new gmf.source.Swisstopo

Makefile, contribs/gmf/examples/asitvd.html, contribs/gmf/examples/locationchooser.html, contribs/gmf/examples/locationchooser.js, contribs/gmf/examples/search.html, contribs/gmf/examples/simple.html, contribs/gmf/src/directives/locationchooser.js, contribs/gmf/src/directives/search.js, contribs/gmf/src/gmf.js, package.json
This is a WIP, open for discussions.
1. First, I had to add the ``gettext`` provider. Else, It throws an error because it doesn't find a provider for the ``translate`` keyword.
~~2. For the **locationchooser**, I had to change how I create the dropdown. ng-options doesn't work with "on-the-flight translation". So I've used a ``ng-repeat`` instead the ``ng-options``. The consequence is that I can't use an object in the "value" of the options. So now, I must use the extent as a String.~~
3. I've tried my changes in a GeoMapFish. For the **search**, I've saw that the project doesn't add the translation in the "pot" file. I had to add the same string as in the placeholder in a hidden markup in the html file.
=> Translate dropdown and placeholder

examples/locationchooser.html, examples/locationchooser.js, src/directives/recenter.js
From a user perspective, using the location chooser directive could be something like:
```html
<select ngeo-locationchooser ngeo-locationchooser-map="ctrl.map">
<option extent="[-1898084, 4676723, 3972279, 8590299]" translate>Europa</option>
<option extent="[727681, 5784754, 1094579, 6029353]" translate>Switzerland</option>
</select>
```
Or (with `ng-options`):
```html
<select ngeo-locationchooser ngeo-locationchooser-map="ctrl.map"
ng-options="location.label for location in mainCtrl.locations"></select>
```
handle `ng-change` events at `ngeo-locationchooser` level
Or (with simple links):
```html
<div ngeo-locationchooser ngeo-locationchooser-map="ctrl.map">
<a href="#" extent="[-1898084, 4676723, 3972279, 8590299]" translate>Europa</a>
<a href="#" extent="[727681, 5784754, 1094579, …
```
=> location chooser refactoring

contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile/js/mobile.js, contribs/gmf/less/map.less, examples/mobilegeolocation.html, examples/mobilegeolocation.js, externs/ngeox.js, src/directives/mobilegeolocation.js
This PR introduces the GMF mobile geolocation directive.  When clicked, if inactive, the inner geolocation gets activated.  A point feature is added on the map for the location and an other regular polygon feature is added for the precision.  If clicked again, if the position is at the center of the map, then the tracking is deactivated.  Otherwise, a new tracking position is obtained.
It also introduces an example in which it is featured.
It is possible to define 3 options:
* `accuracyFeatureStyle`
* `positionFeatureStyle`
* `zoom`
=> Gmf geolocation mobile

Makefile, jsdoc/get-angularjs-doc-ref.js, jsdoc/template/publish.js
Example: http://ger-benjamin.github.io/ngeo/master/apidoc/gmf.MapController.html
(link to the ``angular.Scope`` is not really clean. But it's like an exception...)
=> Add link to AngularJS documentation on AngularJS objects

contribs/gmf/src/services/themesservice.js
This PR adds a new gmf service `gmfThemes` that will handle the c2cgeoportal server side themes service.
The service is not completed, but this PR is required to provide the service and the interface to be used by other gmf components.
In a next PR we will need to 
The code is taken from https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/themesservice.js
Thanks to @adube for moving it to gmf.
=> Add a gmf service to handle the c2cgeoportal themes service

contribs/gmf/apps/mobile/js/mobile.js, contribs/gmf/src/controllers/abstractmobile.js
This PR suggests an architecture to override main controllers.
For maintenance purpose, we don't want to have customization in the `mainController` file itself.
This PR moves all shared code of the `MobileController` to an `AbstractMobileController`.
The `AbstractMobileController` class contains all the generic code of all gmf instances main controller.
It's moved to the `gmf` folder, and will be part of the library.
The new `MobileController` is just now an empty Controller, inheriting from `AbstractMobileController`.
This one is called from the template, and will be copied in all gmf instances.
It could be customised for each instance to override the main controller.
Same work will be done for destkop controllers.
=> [WIP] - Add a directive to extend the main controller

Makefile, contribs/gmf/apps/mobile/index.html
This reverts commit 3777d51e2fe89f956168d88a661d812077a5fcf0.
Last week i had to make this change to make the mobile apps works in local mode, and now i have to revert it. Don't understand why, maybe i fixed it last week upon an old version.
=> Revert "Fix loading of mobile.js in local mode"

contribs/gmf/src/services/themesservice.js, contribs/gmf/test/spec/beforeeach.js, contribs/gmf/test/spec/services/themesservice.spec.js
I prefer to have a `module.value` to manage the url to the themes service, and that this url is directly available in the angular `themesservice`.
I renamed the angular value to `gmfTreeUrl` and updated tests.
=> Remove the init method in themesService

src/directives/desktopgeolocation.js, src/directives/mobilegeolocation.js
To reproduce the issue:
- http://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html
- Click the geolocation button
- The geolocation point is display at [0, 0]
=> Don't display the geolocation point at an invalid position

contribs/gmf/examples/data/themes.json
This simple PR makes the theme json in the GMF example human readable.  In addition, it allows modifications to be more easily merged.  I got conflicts while rebasing and it took a short while to understand what was different.  Having the file like this would have avoided the conflict.
=> Fix GMF theme json example - human readable

Makefile, karma-conf.js, package.json
As stated by @tsauerwein:
> Because ngeo does not use a specifc version of ol3, it gets the current master of ol3. A PR related to .bind was merged 3 days ago. PhantomJS does not support .bind, you will have to use a shim, see:
https://github.com/openlayers/ol3/blob/db3ad70a3d7598254cbf11b7a6540b9fba3773ab/config/examples/example.html#L14
=> Use polyfill to shim ES5 'bind' (not supported by PhantomJS)

contribs/gmf/src/controllers/abstractmobile.js
- disable the rotation feature for mobile
- temporary solution for https://github.com/camptocamp/c2cgeoportal/issues/1861
- example: https://marionb.github.io/ngeo/map-rotation/examples/contribs/gmf/apps/mobile
=> Disable map rotation behaviour

contribs/gmf/src/directives/partials/search.html, contribs/gmf/src/directives/search.js
From the design proposal:
- when an item is selected it:
- hide the results div
- highlight the geometry
- recenter to the geometry
- the input value is set to the selected item's title
- a cross button is displayed in the input
- FIXME: un-focus the input to hide the keyboard?
- if the cross button is pressed it:
- clear the input text
- remove the highlighted geometry
- hide the cross button
linked to: https://github.com/camptocamp/c2cgeoportal/issues/1656
=> [Full-text search] We should be able to hide the geometries

contribs/gmf/examples/data/metadata.html, contribs/gmf/examples/layertree.html, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/partials/layertree.html
Exemple :  http://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/layertree.html . **try it on theme `Edit`, layer `point`, the one with a `metadataUrl`** (mode 'popup' only but I have added an option to open link in a new window).
Relative to c2c issue: camptocamp/c2cgeoportal#1707
=> Add a button to display metadata in gmf-layertree

contribs/gmf/apps/mobile/build.json, contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile/js/mobile.js, contribs/gmf/apps/mobile/less/mobile.less, contribs/gmf/examples/layertree.html, contribs/gmf/less/layertree.less, contribs/gmf/src/controllers/abstractmobile.js, contribs/gmf/src/directives/partials/layertree.html
Ref to https://github.com/camptocamp/c2cgeoportal/issues/1707
Exemple: http://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html
Theme "Cadastre" looks really bad but I don't know what to do with a 15+-letters-without-space string.
Checkbox icons aren't definitive.
=> Add gmf-layertree in mobile app

contribs/gmf/less/base.less, contribs/gmf/less/mobile-nav.less
* Make sure the map container is fully visible (e.g. the scalebar is not hidden)
* Avoid that the sidebars are visible when they are not active and the map container is dragged.
Related to https://github.com/camptocamp/ngeo/issues/399
=> Improve mobile application for iOS

contribs/gmf/less/mobile-nav.less
Also closes side navigation when swiping the map.
=> Mobile prevent scroll

Makefile, contribs/gmf/examples/https.js
related to https://github.com/camptocamp/c2cgeoportal/issues/1667
=> Redirect gmf example to https

externs/twbootstrap.js
Fixes issue with 'container: body' not taken into account when built
=> More options for tooltips externs

.travis.yml
Use node language instead of python.
Switch to a [trusty env](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-%28or-io.js-v3%29-compiler-requirements) since newer versions of node require a C++11 compiler.
=> Travis: test both 0.10 and 4.0

externs/ngeox.js, src/d3-ext/profile.js
We used to provide two options: yLowerBound and ratioXYRule to allow
applications to change the Y domain of the profile. This allowed enforcing
rules like: min y value > 0 or a specific aspect ratio.
It was not working so well though since the ratioXYRule signature was too
restricted (only taking a xDomainMax) which could lead to ugly results.
In this commit, these options are replaced by a more powerful option.
=> Profile: allow changing scales from application code

contribs/gmf/examples/themeselector.html, contribs/gmf/src/directives/themeselector.js
=> Make the default theme configurable

contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/mobile/js/controller.js, contribs/gmf/examples/https.js, contribs/gmf/externs/gmfx.js, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/controllers/abstractmobile.js
=> Be able to change everything what we needs in the application

contribs/gmf/apps/mobile/less/main.less, contribs/gmf/less/fullscreenpopup.less
Ref to camptocamp/c2cgeoportal#1707
Example: https://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html
(watch it in theme `edit`, layer `point` (button metadata (`i`)))
Css for classic popups. Used to display metadata url popup from layertree (But not used in this the app mobile layertree because current demo uses an option to open links in a new page).
=> Add css for gmf mobile fullscreen popups

contribs/gmf/apps/mobile/index.html
Remove as much levels in the left menu as possible.
https://github.com/camptocamp/c2cgeoportal/issues/1980
Demo:
https://pgiraud.github.io/ngeo/mobile_left_menu_itms/examples/contribs/gmf/apps/mobile/index.html
To be compared to:
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html
=> mobile app - reorganize the left menu

contribs/gmf/apps/desktop/index.html
Fixes #618 
After upgrading less to 2.6.0, the javascript compiler of less seem to hide the body when no less file is found.
We don't need to compile less in the browser so we don't need the less javascript file anymore.
=> Don't load less js, not required anymore

examples/toolActivate.html, examples/toolActivate.js, exports/services/toolActivateMgr.js, src/services/toolActivateMgr.js, test/spec/services/toolActivateMgr.spec.js
This PR aims to simplify the usage of the `ngeo.ToolActivateMgr`. Now, the active state of a tool can be directly bound to the active property of an interaction (or any other object).
Example:
this.drawPoint = new ol.interaction.Draw(...);
ngeoDecorateInteraction(this.drawPoint);
var drawPointTool = new ngeo.ToolActivate(this.drawPoint, 'active');
ngeoToolActivateMgr.registerTool('mapTools', drawPointTool);
Closes https://github.com/camptocamp/ngeo/issues/577
=> Use `watch` in toolActivateMgr

contribs/gmf/less/desktop.less, contribs/gmf/less/vars.less
Here's a quick change to make the desktop look more coherent and with less "agressive", more neutral colors.
Mobile also takes advantage of the modifications.
Some work may still need to be done, but it's a good start with only a bit of CSS.
=> Desktop styling

contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile/js/controller.js, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/controllers/abstractmobile.js, src/services/query.js
This PR adds the mobile query directive inside the GMF mobile application.
When any click is made inside the application, one or more request occurs.  At this stage, there's nowhere the result is put, yet.
The ToolActiveManager of ngeo is also added in there as well, with only the query tool being bound to it.  The query tool is also the "default" tool that has to remain active if no other tool is active.
Please, review.
=> Add query to gmf mobile app

Makefile
Fixes issue with webfont files being removed when stopping (Ctrl-C) `make serve`.
```
^Cmake: *** [serve] Error 130
make: *** Deleting intermediate file `node_modules/font-awesome/fonts/fontawesome-webfont.woff'
make: *** Deleting intermediate file `node_modules/font-awesome/fonts/fontawesome-webfont.woff2'
make: *** Deleting intermediate file `node_modules/font-awesome/fonts/fontawesome-webfont.eot'
make: *** Deleting intermediate file `node_modules/font-awesome/fonts/fontawesome-webfont.ttf'
```
To be tested.
=> Don't touch the webfonts in fontawesome node module

contribs/gmf/src/directives/mobilenav.js
In a sidebar, when clicking on a link in the main menu (e.g. "Background"), the title bar turned white during the animation on Safari.
The problem is that the newly inserted element did not have the right position after insertion. The "fix" forces Safari to calculate the position.
Closes https://github.com/camptocamp/c2cgeoportal/issues/1987
=> Fix menu animation on Safari (mobile application)

contribs/gmf/less/mobile.less
Closes https://github.com/camptocamp/c2cgeoportal/issues/1989
=> Hide native "clear X" in Edge (mobile search)

contribs/gmf/examples/permalink.html, contribs/gmf/examples/permalink.js, contribs/gmf/src/directives/map.js, contribs/gmf/src/directives/mobilebackgroundlayerselector.js, contribs/gmf/src/services/permalink.js
This PR introduces the `gmf-permalink` service.  Here's the todo list.
Live demo:
* (map x, y, z only) - http://adube.github.io/ngeo/permalink/examples/contribs/gmf/permalink.html
* (background layer, map x, y, z) - https://adube.github.io/ngeo/permalink/examples/contribs/gmf/mobilebackgroundlayerselector.html?baselayer_ref=map
=> Add gmf-permalink

contribs/gmf/less/map.less
Zoom button (+ and -) will no more remain grey after being clicked.
Fixes https://github.com/camptocamp/c2cgeoportal/issues/1971
=> Zoom button behavior fixed

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/controllers/abstractmobile.js
From `gmf.AbstractMobileController` and `gmf.AbstractDesktopController`, the map was created after we call the parent constructor.
In the parent constructor we need the map, for example for the `ngeoFeatureOverlayMgr.init(this.map);`
This PR fix this and add a check in abstract controller.
=> Create map in apps controller before calling parent controller

Makefile
This prevents failing errors on OSX.
=> use -c option for touch instead of --no-create

Makefile
With this pull request I'm addressing compatibility issue that happen when running make targets on OSX due mainly to differences between the options available for `sed`, `touch`, and `stat` commands.
For the `sed` command, it took me a while and here's a very nice resource:
http://stackoverflow.com/questions/14846304/sed-command-error-on-macos-x
This hasn't been tested on linux yet since I am having issues with gflags python package not installing.
=> Makefile osx compatible

contribs/gmf/examples/permalink.html, contribs/gmf/examples/permalink.js, contribs/gmf/src/services/permalink.js
This PR simplifies the initial loading and reading of the X, Y and Z values from the permalink.  It now occurs when registering the map in the permalink, which is done in the GMF map directive.
Live demos:
* http://adube.github.io/ngeo/app-mobile-permalink/examples/contribs/gmf/permalink.html
* https://adube.github.io/ngeo/app-mobile-permalink/examples/contribs/gmf/apps/mobile/index.html
=> Load x,y,z when registering map in permalink

contribs/gmf/less/mobile.less
Mobile: Right / left / bottom borders removed so results take the whole space.
Tablet: Bottom and top extra border removed.
=> Mobile / Tablet: Border behaviour adjusted

contribs/gmf/less/mobile.less
[Tablet]
* The magnifier search icon has now same space to outer border than the cross icon.
* Search field width is now changed to prevent the text of being displayed below the cross icon.
Related to #614.
Supersedes #658 partially.
=> Search magnifier icon and width/spaces adjustements

contribs/gmf/less/mobile.less
For mobile with a wide screen or mobile in landscape mode: Search input field is aligned left and clear button (cross) is aligned right.
=> Mobile: Search field for wide screen or landscape adjusted

contribs/gmf/src/directives/layertree.js, src/services/layerHelper.js
To fix: https://github.com/camptocamp/ngeo/issues/673
Example: https://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html
That can (and should probably) be improved by implementing the same system in the ngeo background manager (cause it can only manage one background for now). But this can be done later.
=> Separate same type of layers by some groups

package.json, src/ol-ext/format/featurehash.js, src/services/print.js
To follow the OpenLayers master a couple of small changes were required because:
* a style function can now return a single style and not only an array of styles (see https://github.com/openlayers/ol3/pull/4401)
* and because a fill style can now take a canvas gradient or pattern (see https://github.com/openlayers/ol3/pull/4632).
=> Update OpenLayers to current master

jsdoc/plugin.js
[#539]
Before: http://camptocamp.github.io/ngeo/master/apidoc/gmf.mobileBackgroundLayerSelectorDirective.html
After: http://camptocamp.github.io/ngeo/html-attributes/apidoc/gmf.mobileBackgroundLayerSelectorDirective.html
=> Display the attributes in HTML attributes

contribs/gmf/less/mobiledisplayqueries.less, contribs/gmf/src/directives/partials/mobiledisplayqueries.html
Fix: #711 
- On tablette, the component is moved to some pixel on the left (in the aim not hidding the lefts buttons of the app).
- Width limite to 350px bigger screen that "@screen-sm-min" (handle width priorities)
- Fix visual glitches on swipe animation (fix colonnes min/max-width)
- Hide "next" and "previous" buttons when there is only 1 result.
- Use `ng-show` and not `ng-class`+css to show/hide the component.
- + some minors fixes.
Example: https://ger-benjamin.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html?lang=en
=> Improvements on displayqueries layout

contribs/gmf/src/directives/themeselector.js
The theme object instanciated by default was not complete.
So, all dependencies from this object were broken on page load (layertree).
Fix this.
#720
=> Fix load default theme

contribs/gmf/examples/layertree.html, contribs/gmf/less/layertree.less, contribs/gmf/less/vars.less, contribs/gmf/src/directives/partials/layertree.html
Fix: https://github.com/camptocamp/ngeo/issues/644
Example: https://ger-benjamin.github.io/ngeo/gmf_layertree_icons/examples/contribs/gmf/apps/mobile
If we want that this example matches exactly with the example in the design document, I must create a new, plain, "node group" icon. For now, I just play with color's brightness.
=> Update gmf layertree icons

contribs/gmf/apps/mobile/index.html, contribs/gmf/examples/mobilequery.html, contribs/gmf/examples/mobilequery.js, src/directives/mobilequery.js
This allows to avoid one empty span element because the ngeo-mobile-query directive can be set on the gmf-map element.
Closes https://github.com/camptocamp/ngeo/issues/645
=> Make scope of query directive non-isolated

contribs/gmf/src/directives/search.js
If the result is an action, properties['layer_name'] is undefined, not an empty string.
fixes #741
=> Fix filter for 'action' result

contribs/gmf/less/desktop.less, contribs/gmf/less/mobile.less, contribs/gmf/less/search.less, contribs/gmf/less/vars.less
Supersedes #729
Must:
* + Clean this old file
Example: https://ger-benjamin.github.io/ngeo/debug_and_clean_search/examples/contribs/gmf/apps/mobile/?lang=en
We probably can do somethings better with all these not justified "em" units... But I think that good enough for now.
I've moved the "search" part in another less file. But we should done the same thing on desktop later.
=> Clean and fix search issues

contribs/gmf/apps/mobile/index.html, contribs/gmf/less/mobile.less
Supersedes #735.
Fixes #684.
Demo https://pgiraud.github.io/ngeo/measure_options_layout/examples/contribs/gmf/apps/mobile/index.html
Icon size is wrong, see https://github.com/camptocamp/ngeo/issues/737
=> Use checkbox for measure buttons

contribs/gmf/less/mobile-nav.less, contribs/gmf/less/mobile.less
Fix: https://github.com/camptocamp/ngeo/issues/737
Example : https://ger-benjamin.github.io/ngeo/separate-sizes-for-icons-buttons/examples/contribs/gmf/apps/mobile/
=> Separate sizes for map layout symbols

contribs/gmf/less/mobiledisplayqueries.less, contribs/gmf/src/directives/partials/mobiledisplayqueries.html
Fix: https://github.com/camptocamp/ngeo/issues/754
Demo: https://ger-benjamin.github.io/ngeo/query-small-details/examples/contribs/gmf/apps/mobile/index.html?lang=en
For the second commit (quick fix for the demo), we need a better solution. See issue https://github.com/camptocamp/ngeo/issues/756
=> Query small details

contribs/gmf/apps/mobile/index.html
Fix: https://github.com/camptocamp/ngeo/issues/753
https://ger-benjamin.github.io/ngeo/fix_753/examples/contribs/gmf/apps/mobile/?lang=en
=> Use toolActivate without one-time binding in mobile apps

contribs/gmf/apps/desktop/index.html
Currently desktop app doesn't load correctly.
`angular-touch.js` needs to be loaded for desktop app since it's required by the `gmf` module.
Please review.
=> ngTouch is required for gmf thus for desktop as well

contribs/gmf/less/mobiledisplayqueries.less, contribs/gmf/less/vars.less
Rel to https://github.com/camptocamp/ngeo/issues/670
Bug: On (very) small screen (or small screen, horizontal mode), query a feature. Then open completely the query displayer: Square menus buttons are above. My PR correct that. 
Example: https://ger-benjamin.github.io/ngeo/query_display_always_above/examples/contribs/gmf/apps/mobile
=> Query displayer above menu icons (very small screens)

contribs/gmf/examples/permalink.html, contribs/gmf/examples/permalink.js, contribs/gmf/externs/gmfx.js, contribs/gmf/src/directives/map.js, contribs/gmf/src/services/permalink.js, externs/twbootstrap.js, src/ol-ext/popover.js
This PR introduces the support of the `map_crosshair` and `map_tooltip` parameters for the `gmf-permalink` service.
Tasks to do:
Live example:
* http://adube.github.io/ngeo/gmf-permalink-map-crosshair-tooltip/examples/contribs/gmf/permalink.html
=> gmf-permalink - support map_crosshair & map_tooltip

Makefile
move `contribs/gmf/build/%.closure.js` to `.build/%.js` (needed only during the build)
=> Don't removes anything at the end of the build

contribs/gmf/less/desktop.less, contribs/gmf/less/fullscreenpopup.less, contribs/gmf/less/layertree.less, contribs/gmf/less/map.less, contribs/gmf/less/mobile-nav.less, contribs/gmf/less/mobile.less, contribs/gmf/less/mobiledisplayqueries.less, contribs/gmf/less/search.less, contribs/gmf/less/vars.less
Fix: https://github.com/camptocamp/ngeo/issues/794
Example: 
- https://ger-benjamin.github.io/ngeo/cleanup_css/examples/contribs/gmf/apps/mobile
- https://ger-benjamin.github.io/ngeo/cleanup_css/examples/contribs/gmf/apps/desktop
To compare with:
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile
- https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop
I've taken some liberty to standardize all the stuff.
Please tell me what to change if you disagree. (the bigger change is the color of the menu links, we used strange shades of browngrey before. But you can set it easily by set the `@nav-links` value in the `contribs/gmf/less/vars.less` file)
=> CSS cleanup

contribs/gmf/apps/mobile/index.html, contribs/gmf/less/mobile-nav.less, contribs/gmf/less/search.less, contribs/gmf/less/vars.less, contribs/gmf/src/controllers/abstractmobile.js, contribs/gmf/src/directives/search.js
Replace #789 
When the search field is active, hide anything else (for small screens).
Demo: https://tsauerwein.github.io/ngeo/search-overlay/examples/contribs/gmf/apps/mobile/
Closes https://github.com/camptocamp/ngeo/issues/778
=> Whiteout when search is active for mobile

src/services/layerHelper.js
This PR fixes the ngeo LayerHelper `createBasicGroup` method, allowing it to actually use the already created groups and return them.  Inside a `forEach`, calling `return` didn't actually did the return of the `createBasicGroup` method, but rather the anonymous function used for the forEach.
=> Fix LayerHelper group creation

contribs/gmf/src/directives/partials/mobiledisplayqueries.html
Fixes #783 
Adds a label before the numbers in the mobile query result template.
=> Add result label in mobile query result

contribs/gmf/src/controllers/abstractdesktop.js
The default configuration for tooltip is "hover focus". With `focus`, the tooltip may stay displayed when clicking on a button until it looses focus.
This for example happen in the desktop application when clicking on a tool button on the right side bar.
=> Ensure tooltips are dismissed even after click

contribs/gmf/apps/desktop/index.html, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/controllers/abstractdesktop.js
This PR introduces the following behaviour: in the desktop and mobile applications, when the user successfully logs in, the panels are closed to show back the map.
Fix: #780
Tasks:
Live demos:
* (mobile) https://adube.github.io/ngeo/gmf-back2map-login/examples/contribs/gmf/apps/mobile/
* (desktop) https://adube.github.io/ngeo/gmf-back2map-login/examples/contribs/gmf/apps/desktop/index.html?lang=fr
=> Go back to map after successful login

contribs/gmf/examples/search.js
Don't allow to select theme search actions (add_theme, add_group or add_layer)
=> Set groupValues and groupActions in search example

contribs/gmf/less/layertree.less
2 CSS rules added in layertree.less  to avoid subgroups of layers to be styled like root groups.
- padding-left added for nested ul on .treenode
- Different CSS style added for .group which are root compared to subgroups (e.g Restaurants) 
As shown by the screenshot, Restaurants (subgroup of  layers) are not style as root group (e.g Couches) anymore.
=> issue #845:

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/examples/layertree.html, contribs/gmf/examples/layertree.js, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/partials/themeselector.html, contribs/gmf/src/directives/search.js, contribs/gmf/src/directives/themeselector.js, contribs/gmf/src/services/treemanager.js, contribs/gmf/test/spec/services/treemanager.spec.js
To add, replace or remove theme, group or group by layername.
Fix: https://github.com/camptocamp/ngeo/issues/779
Needed by: https://github.com/camptocamp/c2cgeoportal/issues/1710
Needed by: https://github.com/camptocamp/c2cgeoportal/issues/1657
Specs: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231710-Theme-selector-(add)
Example: http://ger-benjamin.github.io/ngeo/add_theme_example/examples/contribs/gmf/layertree.html
Desktop example (try to search a group, a theme or a layer) (add theme mode: flush): http://ger-benjamin.github.io/ngeo/add_theme_example/examples/contribs/gmf/apps/desktop
Todo:
* ~~Use treeManager (and "its tree") in each example with layertree (insteade of use directly the Theme as source)~~
* ~~The gmf search should use the tree services to add and remove …
=> Add a tree manager service to manage source of layertree

contribs/gmf/examples/layertree.js
This PR adds the missing require statements, which fixes the layer tree example in gmf.
=> fix gmf layertree example (add missing require)

contribs/gmf/examples/mobilequery.html, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/gmf.js, contribs/gmf/src/services/permalink.js, contribs/gmf/src/services/themesservice.js, src/services/layerHelper.js
This PR introduces the support of layers within the gmf permalink service.
Here's the things remaining to do (to my knowledge):
**What is not covered by this PR**
This PR won't introduce the support of the `tree_groups` param.  The layer tree requires to be able to add new layers on the fly and this is not yet the case.  It is out of scope of this PR to make this possible.
**Live demo**
The following link demonstrates the loading of the `cafe` and `hotel` within the `Layers` group.
* (currently broken) https://adube.github.io/ngeo/gmf-permalink-layers/examples/contribs/gmf/mobilequery.html?tree_group_layers_Layers=cafe%2Chotel&map_x=697900&map_y=218500&map_zoom=3
With new layertree example:
* https://adube.github.io/ngeo/gmf-permalink-layers/examples/contribs/gmf/layertree.html
=> (WIP) Gmf permalink - support layers

contribs/gmf/examples/themeselector.html, contribs/gmf/examples/themeselector.js, contribs/gmf/src/directives/themeselector.js
And remove a now useless directive attribute
Change usefull after this change: https://github.com/camptocamp/ngeo/commit/b5585de3a80e5c77bd00c501428b33a83ae72151#diff-9040305a49e3edd158509e27caa44d42R191 
Example: https://ger-benjamin.github.io/ngeo/fix_themeselector_example/examples/contribs/gmf/themeselector.html/
=> Fix the themeselector example

src/directives/scaleselector.js
The goal of this PR is to allow to the list of scales to be refreshed.
The use case in our app is that the list of available scales is theme dependent. When a user switches the current theme, then the number of scales could vary.
My first thought was to listen on the maxzoom and minzoom property of the view and to limit the scales using these values. But none of both are observable. Therefore I've chosen this solution but I'm not sure, I've chosen the best way to achieve this. Could you please review and give advices.
=> Allow the scales array to be refreshed

contribs/gmf/src/directives/partials/authentication.html
We had `Password forgotten?` and `Password Forgotten?`
=> Remove duplicated translate keys

contribs/gmf/less/layertree.less
=> changing the rule .treenode ul ul { padding-left:20px; } ==> .treenode ul { padding-left:20px; }

examples/colorpicker.html, examples/colorpicker.js, src/directives/colorpicker.js, src/directives/partials/colorpicker.html
Add a basic color picker.
Will be used in style form for example.
Example: http://fgravin.github.io/ngeo/colorpicker/examples/colorpicker.html
See https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231658-Measures-and-redlining
=> Add a color picker directive

buildtools/mako_build.json, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/themeselector.js, contribs/gmf/src/services/themesservice.js, src/services/layerHelper.js
=> Get rid of goog.array.* functions

contribs/gmf/less/layertree.less
fixes #967
Cherry-pick #953 into the 2.0 branch
=> changing the rule .treenode ul ul {} to .treenode ul {}

contribs/gmf/examples/featurestyle.html, contribs/gmf/examples/featurestyle.js, contribs/gmf/src/directives/featurestyle.js, contribs/gmf/src/directives/partials/featurestyle.html, src/ngeo.js, src/ol-ext/interaction/measure.js, src/services/featurehelper.js
This PR introduces a `gmf-featurestyle` directive and an example featuring it.  It also introduces a `gmf.FeatureHelper` service that is responsible of giving utility methods to create, get and set the style for a feature using its inner properties.  It also contains methods to calculate and return a measure string from a feature geometry.
Wiki: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231658-Measures-and-redlining
* http://adube.github.io/ngeo/edit-feature-style/examples/contribs/gmf/featurestyle.html?map_x=-8003263&map_y=6362007&map_zoom=6
=> Add gmf feature style directive

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/mobilebackgroundlayerselector.js, contribs/gmf/src/directives/themeselector.js, contribs/gmf/src/services/authenticationservice.js, contribs/gmf/test/spec/beforeeach.js, contribs/gmf/test/spec/services/authenticationservice.spec.js, karma-conf.js
The authentication service now emits `login`, `logout` and  `ready` events, which later will also make it easier to disable/enable tools or other functionality depending on the user's permissions.
Closes https://github.com/camptocamp/ngeo/issues/966
=> Reload themes on login/logout

contribs/gmf/examples/layertree.html, contribs/gmf/examples/layertree.js, contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/services/permalink.js, contribs/gmf/src/services/themesservice.js, contribs/gmf/src/services/treemanager.js
This PR introduces the support of layers that are not in the existing loaded theme inside the permalink. What the permalink does is this:
* when a layer is added, it gets added in the state manager / url as well
* upon loading the application, layers that are defined in the state manager are added using the gmf tree manager
To do:
Live example:
* http://adube.github.io/ngeo/gmf-permalink-added-layers/examples/contribs/gmf/layertree.html
=> Gmf permalink added layers

Makefile, contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/examples/asitvd.html, contribs/gmf/examples/authentication.html, contribs/gmf/examples/layertree.html, contribs/gmf/examples/mobilebackgroundlayerselector.html, contribs/gmf/examples/mobilemeasure.html, contribs/gmf/examples/mobilequery.html, contribs/gmf/examples/permalink.html, contribs/gmf/examples/search.html, contribs/gmf/examples/simple.html, contribs/gmf/examples/themeselector.html, contribs/gmf/src/directives/partials/mobiledisplayqueries.html, contribs/gmf/src/gmf.js, karma-conf.js, package.json
This PR proposes to use [angular-sanitize](https://docs.angularjs.org/api/ng/directive/ngBindHtml) to sanitize feature attributes so that HTML code is rendered as HTML.
Closes https://github.com/camptocamp/ngeo/issues/965
=> Support HTML in feature attributes (query popup)

contribs/gmf/less/desktop.less, contribs/gmf/less/desktoplayertree.less, contribs/gmf/less/layertree.less, contribs/gmf/less/mobile.less, contribs/gmf/less/mobilelayertree.less, contribs/gmf/src/directives/partials/layertree.html
Following the spec [#1708](https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231708-Layertree-desktop)
- Adding the desktop layertree design
- Splitting layertree.less in 3 files in order to have a different design for mobile/desktop with a common base style
- Refactoring selectors for the future needs (e.g for #819 )
=> Add standard design for layertree

contribs/gmf/src/services/permalink.js
This PR fixes a missing `goog.require` in the dependencies of the `gmf.Permalink` service.
=> Add missing require in gmf.Permalink

contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/apps/mobile/js/controller.js
Fix: https://github.com/camptocamp/ngeo/issues/973
Examples:
- https://ger-benjamin.github.io/ngeo/add_epsg2056/examples/contribs/gmf/apps/mobile
- https://ger-benjamin.github.io/ngeo/add_epsg2056/examples/contribs/gmf/apps/desktop (search "2600000 1200000" here)
- https://ger-benjamin.github.io/ngeo/add_epsg2056/examples/contribs/gmf/apps/desktop_alt
=> Require EPSG2056 in controllers

contribs/gmf/src/directives/featurestyle.js
This PR fixes the un-listening of events in the `gmf-featurestyle` directive that are bound to the feature.
=> Fix event unlistening in gmf-featurestyle

contribs/gmf/src/directives/layertree.js, contribs/gmf/test/spec/beforeeach.js, contribs/gmf/test/spec/directives/layertree.spec.js
Only show a layer when `isChecked` is `'true'` in the layer meta-data.
Closes https://github.com/camptocamp/ngeo/issues/972
=> Hide layers by default

contribs/gmf/apps/mobile/index.html
Listen on `theme.name` instead of `theme`. Because theme is an object that never changes, only its values change.
See https://github.com/camptocamp/ngeo/issues/594#issuecomment-197804863
Closes https://github.com/camptocamp/ngeo/issues/594 again
=> Fix going back after theme selection

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/src/services/treemanager.js
Not covered by this PR: 
* Showing a message when a group is already loaded
* Removing groups
Closes https://github.com/camptocamp/c2cgeoportal/issues/1710
=> Enable "theme/group-add-mode" in alt. desktop app

contribs/gmf/examples/drawfeature.html, contribs/gmf/examples/drawfeature.js, contribs/gmf/src/directives/drawfeature.js, contribs/gmf/src/directives/featurestyle.js, contribs/gmf/src/directives/partials/drawfeature.html, src/directives/drawfeature.js, src/ngeo.js, src/ol-ext/interaction/modify.js, src/services/featurehelper.js
This PR introduces the `gmf-drawfeature` directive, which allows the user to draw vector features on the map and change their style, geometry, etc.  There are still things to do to consider the tool completed.
* a new `gmf-drawfeature` directive that combines the `ngeo-drawfeature` and `gmf-featurestyle` directives
* an example
* you can select a feature from the list or from the map
* you can change the style
* you can modify the geometry
* delete one or more features
It also contains some bug fixes across the other components used by the directive.
* proper modification of circles
* proper modification of rectangles
* move feature
* export
* drop-down menu on feature "click"
* official CSS styling
* show vertexes on selection / feature modification
* export
* …
=> GMF draw feature directive

Makefile, docs/developer-guide.md, karma-conf.js
This PR suggests to add a target `test-debug` to the Makefile which starts the unit tests in Chrome, so that the debugger can be used.
closes https://github.com/camptocamp/ngeo/issues/450
=> Make running the unit tests less painful

contribs/gmf/less/layertree.less, contribs/gmf/src/directives/partials/layertree.html
Long layer names are truncated using `text-overflow: ellipsis`, the title attribute contains the full name.
Closes https://github.com/camptocamp/ngeo/issues/968
Note that this PR is made against master and not 2.0 as confirmed with @ybolognini.
=> Truncate long layer names

examples/modifycircle.html, examples/modifycircle.js, externs/ngeox.js, src/ol-ext/interaction/modifycircle.js
This commit adds the modify circle interaction, along with an example of how it works.
[The interaction was taken from the luxembourg app](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/draw/modifycircleinteraction.js).
A live example is available here: http://adube.github.io/ngeo/modify-circle/examples/modifycircle.html
=> Add the modify circle interaction.

contribs/gmf/examples/featurestyle.js, contribs/gmf/src/directives/drawfeature.js, contribs/gmf/src/directives/featurestyle.js, src/ol-ext/interaction/modify.js, src/services/featurehelper.js
This PR adds the support of drawing vertex in addition to the original style in the feature helper.  The `gmf-featurestyle` directive uses it, in addition to the `gmf-drawfeature` one.
Geometries that **have** the vertex drawn:
* LineString
* Polygon
* Rectangle
Geometries that **don't have** vertex drawn:
* Circle
* Point
* Text
An additional "halo" style is added to selected features.
As a bonus, this PR also includes the `ngeo.interaction.ModifyCircle` interaction.  Circles are now properly modified.
* http://adube.github.io/ngeo/gmf-drawfeature-vertex/examples/contribs/gmf/drawfeature.html
=> Set select style (vertex, halo) in feature helper, used in gmf-drawfeature

contribs/gmf/examples/drawfeature.html, contribs/gmf/examples/drawfeature.js, contribs/gmf/src/directives/drawfeature.js, externs/ngeox.js, package.json, src/ol-ext/interaction/translate.js, src/ol-ext/menu.js
This PR introduces the `ngeo.Menu` overlay, which consists in a contextual menu configurable with any number of actions. When an action is clicked, it dispatches an event.  It can be closed with a close button, or automatically closed when an action is clicked (optional).
This PR also implements a `ngeo.Menu` in the `gmf-drawfeature` directive that is shown when a feature is clicked with the following actions:
* Move (works, behaviour is the one from the spec)
* Rotate (does nothing for now)
* Delete (deletes the feature properly)
* http://adube.github.io/ngeo/gmf-drawfeature-menu/examples/contribs/gmf/drawfeature.html
=> Add contextual menu on feature click in gmf-drawfeature

examples/popover.html, examples/popover.js, src/directives/popover.js
PR for the new ngeo component popover. The first goal of this component is to display actions capabilities for groups of layers or individual layers into the layertree but there is no limitation for other use at the moment.
**Behavior of the component:**
- Clicking on the anchor tag **SHOULD** toogle the popover
- If multiple anchors exist, only **one** popover can be displayed at a time
- Each anchor is linked to its own popover, meaning it exists as much popovers as anchors
- Clicking into the popover **SHOULD NOT** dismiss it
- Clicking somewhere else **SHOULD** dismiss the popover
Check the example on my GH pages [here](http://oliviersemet.github.io/ngeo/adding-popover-component/examples/popover.html)
=> Add ngeo popover component

contribs/gmf/examples/drawfeature.html, contribs/gmf/examples/drawfeature.js, contribs/gmf/src/directives/drawfeature.js, contribs/gmf/src/directives/partials/drawfeature.html, src/directives/exportfeatures.js, src/services/featurehelper.js
This PR introduces the ability to `export` features that are drawn using the `gmf-drawfeature` directive.  
* The `ngeo.FeatureHelper` is responsible of executing the writing of features and download as well.
* A `ngeo-exportfeatures` directive is responsible of the UI aspect.  It will also be responsible to show a drop-down list if more than one format is defined.
* The `ngeoExportFeatureFormats` constant will be responsible of defining in what formats we want the exportation to be supported.  Defaults to `KML` only, if not defined.
We won't use template instead of jQuery to build menu items, because the menu has to be a sibling of the button. That can't work with pure Angular.
* http://adube.github.io/ngeo/gmf-drawfeature-export/examples/contribs/gmf/drawfeature.html
=> Add ngeo-exportfeatures directive, used in gmf-drawfeature

.gitignore, contribs/gmf/src/directives/partials/layertree.html
=> Remove Layer group block

contribs/gmf/src/directives/partials/layertree.html
We currently add the legend block even if no legend is to be displayed.
This pull request fixes this by using the same `ng-if` statement as for the legend icon button.
Please review.
=> Don't add legend block if not required

src/services/query.js
When running locally with `make serve`, the mobile-query example failed with:
> Error: [$injector:unpr] Unknown provider: ngeoLayerHelperProvider <- ngeoLayerHelper <- ngeoQuery <- ngeoMobileQueryDirective
[query.js](https://github.com/camptocamp/ngeo/blob/master/src/services/query.js) was missing a require to `ngeo.LayerHelper`. Unfortunately this is not detected by the tests because the examples are run in built-mode.
=> Fix mobile-query example

contribs/gmf/src/services/permalink.js, src/ol-ext/interaction/modify.js, src/services/featurehelper.js
This PR introduces the support of drawn vector features by the `gmf-drawfeature` directive inside the `gmf-permalink` service.
* http://adube.github.io/ngeo/gmf-drawfeature-permalink/examples/contribs/gmf/drawfeature.html
=> Support drawn features (gmf-drawfeature) in gmf-permalink

contribs/gmf/src/services/permalink.js
This PR fixes the `gmf-permalink` when one or more features gets deleted the url is updated.
=> Fix gmf-permalink features on feature delete

contribs/gmf/less/desktoplayertree.less
@pgiraud 
check live example [here](https://oliviersemet.github.io/ngeo/1052-tree-actions-buttons-only-displayed-on-hover/examples/contribs/gmf/apps/desktop/)
IMO we should add some extra UI to clarify which layer item is currently hovered
=> Display action icons on mouse hover #closes 1052

contribs/gmf/examples/featurestyle.js, src/ngeo.js
This PR renames `ngeo.FeatureProperties` values to use a single letter, allowing the permalink to use less characters.
=> Rename ngeo.FeatureProperties values to use a single letter

src/ol-ext/interaction/modifyrectangle.js
This PR is a small fix for the `ngeo.interaction.ModifyRectangle` interaction.  The corner features were put in the feature's own properties, which was causing issues with the permalink.
Now, the corners are stocked in a cache item instead.
* http://adube.github.io/ngeo/fix-ngeo-modify-rectangle-corners/examples/contribs/gmf/drawfeature.html?rl_features=Fa(edkt_ccb5!nwknB..5x59*mwknB.~isRectangle*true%27name*Rectangle%25201%27color*%2523DB4436%27angle*0%27opacity*0.2%27showMeasure*false%27size*10%27stroke*1)&map_x=0&map_y=380882&map_zoom=3
=> ModifyRectangle - Set corner features in cache item

examples/modifyrectangle.js, src/ol-ext/interaction/modifyrectangle.js
This commit fixes a glitch with the modify rectangle that only occurs on the built version, and it also fixes a the styling issue in the gmf draw feature example where selecting the rectangle causes the style to be added twice.
This was occurring by a combination of the modify rectangle wanting to manage its own layer of polygons, which really wasn't necessary, and a bad management of added / removed features when creating / removing their corner handles.
The example now working well in the integrated draw feature example is available here: http://jlap.github.io/ngeo/modify-rectangle-style-bug/examples/contribs/gmf/drawfeature.html
The modify rectangle works exactly the same as it used to: http://jlap.github.io/ngeo/modify-rectangle-style-bug/examples/modifyrectangle.html
=> Fix styling issue with the modify rectangle.

examples/modifycircle.js, src/ol-ext/interaction/modifycircle.js
This fixes the bug where you couldn't resize a circle anymore.
This was caused by using the string 'isCircle' at some places, and a defined constant in other places, so when compiling some got minimized and some didn't. Now everything uses the constant, so the example here:
http://jlap.github.io/ngeo/fix-modify-circle/examples/contribs/gmf/drawfeature.html
and here:
http://jlap.github.io/ngeo/fix-modify-circle/examples/modifycircle.html
Are working again.
=> Fix the resizing of a circle in modify circle

examples/layerloading.html, examples/layerloading.js, src/services/decoratelayerloading.js
Expose a new `loading` property that is true when the source(s) is(are) loading and false otherwise.
Supports tiles and images layers.
=> Add new ngeo.DecorateLayerLoading service

contribs/gmf/src/services/permalink.js, externs/ngeox.js, src/ol-ext/format/featurehash.js, src/services/featurehelper.js
This PR adds the backward compatibility for `rl_features` in the permalink, i.e. for the features of the redlining tool from 1.6.
This PR was blocked by: #1069 
You can try them here: https://geomapfish-demo.camptocamp.net/2.0
Examples (removed prefix: https://geomapfish-demo.camptocamp.net/2.0/theme/Transport?map_x=542000&map_y=154000&map_zoom=2&):
* http://adube.github.io/ngeo/ngeo-featurehash-write-new-properties/examples/contribs/gmf/drawfeature.html?rl_features=Fp%28w8saFhdf3!~name*Un%2520titre~fillColor*%2523ff0000%27strokeColor*%2523ff0000%27pointRadius*6%27fontColor*%2523000000%29
*`rl_features=Fp%28w8saFhdf3!~name*Un%2520titre~fillColor*%2523ff0000%27strokeColor*%2523ff0000%27pointRadius*6%27fontColor*%2523000000%29`
* works fine
* `fontColor` is ignored
* `fillColor` and …
=> Backward compatibility for rl_features

contribs/gmf/examples/wfs-permalink.html, contribs/gmf/examples/wfs-permalink.js, contribs/gmf/src/services/permalink.js, contribs/gmf/test/spec/services/permalinkservice.spec.js, externs/ngeox.js, package.json, src/services/location.js, src/services/query.js, src/services/wfspermalink.js, test/spec/data/msGMLOutputFuel.js, test/spec/services/query.spec.js, test/spec/services/wfspermalink.spec.js
Adds a `ngeo.WfsPermalink` service which is used by `gmf.Permalink`. When calling the new example with e.g. `?wfs_layer=fuel&wfs_osm_id=1420918679`, a WFS GetFeature request is made and the features are shown with the `gmf-mobiledisplayqueries` directive.
For the yet to implement [WFS queries](https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231771-Querying-data-%28click-and-box%29), some functionality of `ngeo.WfsPermalink` might be refactored to avoid duplicated code.
Closes https://github.com/camptocamp/c2cgeoportal/issues/1670
=> Add WFS permalink service

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/examples/drawfeature.html, contribs/gmf/less/desktop.less, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/partials/drawfeature.html
This PR introduces the `gmf-drawfeature` directive within the **deskop** and **desktop_alt** apps.  The latter is the only one we can currently test, due to the issue described below.
* https://adube.github.io/ngeo/gmf-drawfeature-in-desktop-app/examples/contribs/gmf/apps/desktop_alt/?lang=fr&rl_features
=> Add gmf-drawfeature directive in desktop app

src/directives/popover.js
@fgravin or @fredj could you check?
- Using a transcluded directive for the popover content was not the good solution due to the scope.
- Attribut added to handle popover dismissing on scroll event on the parent container
=> popover behavior improvement

contribs/gmf/examples/drawfeature.html, contribs/gmf/src/directives/drawfeature.js, src/ol-ext/menu.js
This commit is for the issue #1088 
The example is live at: http://jlap.github.io/ngeo/menu-behavior/examples/contribs/gmf/drawfeature.html?map_x=576979&map_y=1613530&map_zoom=3
The example displays the new behaviors as described in #1088: 
* Action menu opens on right-click and long-press on mobile (so it won't open on geometry selection)
* Action menu should disappear when user clicks anywhere else or when an action is selected
* Remove "Action" title and cross to close the menu
This PR is ready for review!
=> Menu open/close behavior

contribs/gmf/src/directives/drawfeature.js, examples/rotate.html, examples/rotate.js, externs/ngeox.js, src/ol-ext/interaction/modifyrectangle.js, src/ol-ext/interaction/rotate.js
This commit adds a new Rotation interaction that allows the user to rotate features.
The integration with the draw feature example is included in this commit.
The modify rectangle had to be modified a bit as the calculation I used didn't work when the rectangle was on an angle.
The rotate interaction works similarly to the translate interaction:
- Activating the interaction adds an icon at the center of the polygon or line.
- Pressing the escape key deactivates the interaction.
- When you're done with your rotation (on mouse up), the interaction gets deactivated.
You can try it out in two places:
- Stand alone example: http://jlap.github.io/ngeo/rotation/examples/rotate.html
- Integrated with the draw feature: http://jlap.github.io/ngeo/rotation/examples/contribs/gmf/drawfeature.html …
=> Rotation interaction

contribs/gmf/src/directives/themeselector.js
demo: http://camptocamp.github.io/ngeo/template/examples/contribs/gmf/apps/desktop/index.html
=> Fix the templates path when the URL changed

contribs/gmf/less/desktoplayertree.less, contribs/gmf/less/layertree.less, contribs/gmf/less/popover.less, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/partials/layertree.html
- Legend UI following the specification (https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231708-Layertree-desktop#legend)
- Desktop live example :  [here](https://oliviersemet.github.io/ngeo/PR-layertree-legend-ui/examples/contribs/gmf/apps/desktop/index.html)
- Mobile live example : [here](https://oliviersemet.github.io/ngeo/PR-layertree-legend-ui/examples/contribs/gmf/apps/mobile/index.html)
ping @pgiraud @fredj for review. thanks
=> Layertree UI for  the node legend

contribs/gmf/less/base.less
Fix: #1140
Example: https://ger-benjamin.github.io/ngeo/shaking_loading_icon/examples/contribs/gmf/apps/desktop
(No board effect found)
=> Counter loading icon shaking

contribs/gmf/apps/desktop/default.js, contribs/gmf/apps/desktop_alt/default.js, contribs/gmf/apps/mobile/default.js, contribs/gmf/src/directives/themeselector.js
=> Use absolutes URL for the partiales

contribs/gmf/less/desktoplayertree.less, contribs/gmf/less/layertree.less, contribs/gmf/less/mobilelayertree.less, contribs/gmf/src/directives/partials/layertree.html
Here is my proposal to get a larger grab zone for reorder (check todo tasks #1147) without changing the layertree design.
The idea is to display a zone (div) in absolute position with a larger width than the handler icon. Therefore the handler icon is only display for the design purpose. The real "handling zone"  is the div itself (so we can change easily its size).
- desktop demo: [here](https://oliviersemet.github.io/ngeo/increase-size-of-drag-and-drop-handle/examples/contribs/gmf/apps/desktop/)
-mobile demo: [here](https://oliviersemet.github.io/ngeo/increase-size-of-drag-and-drop-handle/examples/contribs/gmf/apps/mobile/)
ping @fredj @pgiraud @sbrunner  if the solution looks good for you.
=>  Larger grab zone for reorder

contribs/gmf/src/services/permalink.js, contribs/gmf/test/spec/services/permalinkservice.spec.js
The moment the group layer for mixed layers is registered with the permalink service, the group does not have any layers yet. They are only added later when the directive in the layer tree is compiled (?).
By setting up a listener on the layer collection of each group layer, all layers can be registered.
Closes https://github.com/camptocamp/ngeo/issues/1163
=> Properly register group layers in permalink service

contribs/gmf/src/directives/partials/layertree.html, src/directives/popover.js
Fix the issue #1147  "When we click on « show legend » the popover should be hidden"
demo: https://oliviersemet.github.io/ngeo/PR-dissmiss-popover-on-show-hide-legend/examples/contribs/gmf/apps/desktop/index.html
@pgiraud @sbrunner @fredj
=> Adding dismissPopover() function to ngeoPopoverController

contribs/gmf/less/input-range.less
The colors are manually set but should instead use the colors defined in `vars.less` otherwise we'll loose coherence if the integrators want to customize the colors.
=> Use the primary & secondary colors for range inputs

contribs/gmf/src/directives/layertree.js
Close #1086
@ger-benjamin @sbrunner  those little changes do the work?
For now there is no node in the layertree with the metadata attribut legendImage for testing.
=> Use node.metadata.legendImage by default

contribs/gmf/less/desktoplayertree.less, contribs/gmf/less/layertree.less
Following @pgiraud advices on issue: #1115
- "hide legend" link a is bit smaller,
- Use "@link-color" for the "hide legend" link
- pointer cursor only on the "hide legend" link
demo: https://oliviersemet.github.io/ngeo/pr-layertree-ui-improvement/examples/contribs/gmf/apps/desktop/index.html
@pgiraud @ybolognini @sbrunner
=> UI layertree legend

Makefile
See: https://camptocamp.github.io/ngeo/add-desktop-alt/examples/contribs/gmf/
=> Add the alternate desktop application to the examples list

examples/notification.html, examples/notification.js, externs/ngeox.js, src/services/notification.js
This PR introduces the `ngeo.Notification` service. With it, one can display:
* http://adube.github.io/ngeo/ngeo-notification/examples/notification.html
=> Add ngeo.Notification service (with example)

src/services/notification.js
This PR removes the angular.$q service from the ngeo notification service since it's not used at all.
=> Remove angular.$q service from ngeo.Notification

examples/mobilegeolocation.html, examples/mobilegeolocation.js, src/directives/mobilegeolocation.js, src/services/notification.js
This PR introduces the usability of the `ngeo.Notification` service within the `ngeo.MobileGeolocation` directive. Instead of listening to the event and manage the errors at the application level, those are now managed directly in the geolocation service.
After clicking the "Toggle tracking" button, when the browser asks to share your location, choose "Block".  You'll see the error message being displayed.
* https://adube.github.io/ngeo/notification-on-geolocation-failure/examples/mobilegeolocation.html
=> Use notification service in mobile geolocation

examples/desktopgeolocation.html, examples/desktopgeolocation.js, src/directives/desktopgeolocation.js
This PR introduces the usability of the `ngeo.Notification` service within the `ngeo.DesktopGeolocation` directive. Instead of listening to the event and manage the errors at the application level, those are now managed directly in the geolocation service.
After clicking the "Toggle" button, when the browser asks to share your location, choose "Block".  You'll see the error message being displayed.
* https://adube.github.io/ngeo/notification-on-geolocation-failure-desktop/examples/desktopgeolocation.html
=> Use notification service in desktop geolocation

contribs/gmf/src/directives/authenticationdirective.js, contribs/gmf/src/directives/partials/authentication.html
This PR introduces the usability of the `ngeo.Notification` service within the `gmf.Authentication` directive.  The message are displayed where they used to be.
Try:
* login with bad credentials
* change password with bad credentials
in this example:
* https://adube.github.io/ngeo/notification-on-authentication-failure/examples/contribs/gmf/authentication.html
=> Use notification service in gmf authentication directive

src/services/featurehelper.js
This PR makes sure that the point coordinates that are drawn with the draw tools are shown above the point instead of directly on it.
* http://adube.github.io/ngeo/feature-helper-point-coordinates-above/examples/contribs/gmf/drawfeature.html?rl_features
=> Show coordinates above the point instead of directly on

contribs/gmf/src/directives/authenticationdirective.js, contribs/gmf/src/directives/partials/authentication.html
This PR makes sure that all errors messages within the gmf authentication service are shown using the notification service.
* https://adube.github.io/ngeo/gmf-auth-fix-login-err/examples/contribs/gmf/authentication.html
=> Fix #977 - Use notification in all gmf authentication err

contribs/gmf/src/directives/layertree.js, contribs/gmf/src/services/querymanager.js
Fix #1017 
@sbrunner @fredj  please review both and carefully.
live example: https://oliviersemet.github.io/ngeo/fix-no-request-when-layer-name-differente-from-node-name/examples/contribs/gmf/apps/desktop/index.html
I think, there is some extra work to have cleaner code (check the getNodeSate function from layertree directive) but I suggest to go step by step. This PR should fix the issue #1017 
Also we should test a node with multiple layers to have a concret case for node.layers = "layer_1, layer_2 ..."
=> Using node.layers property instead of node.name fix #1017

contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/services/treemanager.js, contribs/gmf/test/spec/directives/layertree.spec.js
=> Change isChecked type from string to boolean

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html
With this pull request I remove an unnecessary level of nesting of "row" & "col-span-12" elements in the tools content panel.
Please review.
=> Remove unecessary twbs row/col nesting

contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/services/querymanager.js, contribs/gmf/test/spec/data/themes.js, contribs/gmf/test/spec/services/querymanager.spec.js, contribs/gmf/test/spec/services/themesservice.spec.js
Closes https://github.com/camptocamp/ngeo/issues/962
Please review. I am not sure if this PR is complete, it seems that the format for `themes.js` has changed. E.g. the `themes.js` file used in the tests uses this format:
```js
{
"layers": "hotel",
"name": "hotel",
"queryable": 1,
"childLayers": [],
...
```
... while the [server](https://geomapfish-demo.camptocamp.net/2.0/wsgi/themes?version=2&background=background) returns this format:
```js
{
"layers": "hotel",
"name": "hotel",
"childLayers": [
{
"name": "hotel",
"queryable": false
}
],
...
}
```
Should both be supported?
=> Only include queryable child layers

examples/popup-service.html, examples/popup-service.js, externs/ngeox.js, src/services/popup.js
This PR introduces new methods in the `ngeo.Popup`:
* `setUrl`: set the content as iframe using an url
* `setWidth`, `setHeight` and `setSize`: forces the popup to use the defined size
* `addClass`: add an extra CSS class name to allow more customization of popups
* `setAutoDestroy`: when set, the popup gets automatically destroyed when closed, which is useful to do some automatic cleanup.
* `open`: a single method from which one can quickly and easily open a new popup with properties set in an object of options.  It is an alternative to calling each other methods separately.
It also introduces an example to show what's possible to do with the popup factory.
* http://adube.github.io/ngeo/window-with-iframe/examples/popup-service.html
=> Enhance ngeo.Popup, add example

contribs/gmf/externs/gmfx.js, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/authenticationdirective.js, contribs/gmf/src/services/authenticationservice.js
=> Use externe file for gmf User

contribs/gmf/src/directives/authenticationdirective.js, examples/disclaimer.html, examples/disclaimer.js, examples/notification.js, src/services/disclaimer.js, src/services/message.js, src/services/notification.js
This PR introduces the `ngeo.Disclaimer` service. Since it would have had some method in common with the `ngeo.Notification` service, both extend the same class to avoid copy/pasting code that would be the same.
This PR is the first step towards supporting disclaimers inside the map for layers.  It doesn't do that yet.  This PR is only the section for NGEO.  The layers will be managed in the next PR, for GMF.
* http://adube.github.io/ngeo/disclaimer/examples/disclaimer.html
=> Add ngeo-disclaimer service and example

contribs/gmf/src/directives/search.js, contribs/gmf/src/services/treemanager.js
Fix: https://github.com/camptocamp/c2cgeoportal/issues/1710
(Fix the last point `missing: Showing a message when a group is already loaded`)
Example: https://ger-benjamin.github.io/ngeo/groupAlreadyLoaded/examples/contribs/gmf/apps/desktop_alt
=> Add a notification on adding a group that is already in the tree

contribs/gmf/src/directives/partials/layertree.html
Fix #1217 
demo: https://oliviersemet.github.io/ngeo/fix-1217-opacity-slider-not-revelant-for-nodes-in-non-mixed-group/examples/contribs/gmf/apps/desktop/index.html
@pgiraud
=> Opacity slider must no be displayed for non-mixed nodes

src/directives/popover.js
Here is the issue. The dragListGroup component (from closure and used by the ngeo sortable directive) listen on a 'mousdown' event. When the event occurs, the component clone the node (in our case a gmf-Layertree node). So the DOM element dragged is a clone.
Definition of a click event:
> The click event is fired when a pointing device button (usually a mouse button) is pressed and released on a single element. 
Therefore when the device button is released, the element behind the pointer is not the same as when the mousdown event occurred. So neither the original element nor the cloned one won't trigger a click event.
That's why the click event do not occur and will never occur. 
We can't use a clic event.
@pgiraud @fredj Let me know if you think I missed something
Demo: …
=> Dismiss popover if a drag and drop event occurs

contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/apps/mobile/js/controller.js, src/services/featurehelper.js
Revival of #1262 
Fix https://github.com/camptocamp/c2cgeoportal/issues/2256
Example: http://ger-benjamin.github.io/ngeo/redliningcoodinates/examples/contribs/gmf/apps/desktop/index.html
=> Use filter to format coordinates in draw component

.gitignore, contribs/gmf/src/directives/layertree.js
Fix: https://github.com/camptocamp/c2cgeoportal/issues/2219 (Fix 2.0: must be merged on the 2.0 only., nothing to do in 2.1 (already works))
Example: https://ger-benjamin.github.io/ngeo/admin_value_2.0/examples/contribs/gmf/apps/mobile/theme/OSM?lang=en&baselayer_ref=map
(For example, hotel is not checked, some layer in the same group are checked and so on. You can compare with the admin interface of the demo 2.0 (ui_metadatas): https://geomapfish-demo.camptocamp.net/2.0/wsgi/admin/
=> Admin value isChecked is now taken in account in all cases

contribs/gmf/src/directives/drawfeature.js, contribs/gmf/src/directives/partials/drawfeature.html, src/services/featurehelper.js
This PR introduces the following behavior: in the draw tools (`gmf-drawfeature` directive), when a feature is selected from the list, if it's not currently visible on the map, recenter the map to the center of the feature.  The map zoom level never changes due to this behavior.  Clicking on the feature from the map to select it will not trigger that behavior either.
Click on the list item to see the behavior in action.
* http://adube.github.io/ngeo/1178-ensure-feature-visible/examples/contribs/gmf/drawfeature.html?rl_features=Fa(65ca*q37d-v6yGa1x8!bpgc!ya6Cya6Cbpgc!~n*Polygon%25201%27c*%2523DB4436%27a*0%27o*0.2%27m*false%27s*10%27k*1)&map_x=7983695&map_y=-1271912&map_zoom=3
=> gmf-drawfeature: Recenter map to selected feature from list

examples/disclaimer.html, examples/disclaimer.js, src/services/disclaimer.js
This PR fixes the closing of a disclaimer message in the `ngeo-disclaimer` service when done "programmatically", i.e. when using code to close the message instead of the X button.
It also demonstrates it in the example with the addition of a new button: "Close all".
* http://adube.github.io/ngeo/fix-disclaimer-close/examples/disclaimer.html
=> Fix disclaimer closing from application

contribs/gmf/examples/elevation.html, contribs/gmf/examples/elevation.js, contribs/gmf/src/directives/elevation.js, contribs/gmf/src/services/altitude.js
Part of: https://github.com/camptocamp/c2cgeoportal/issues/1668
Example: https://ger-benjamin.github.io/ngeo/elevation/examples/contribs/gmf/elevation.html
Example apidoc: https://ger-benjamin.github.io/ngeo/elevation/apidoc/gmf.elevationDirective.html
I've tried to exclude the dropdown of the directive. I think that's not a part of it. So we can display an elevation on any `<element>` and we don't need a partial. But that add two attributes in the html declaration of the directive (`gmf-elevation-elevation` and `gmf-elavation-layer`) and a watch (the layer)
=> Add elevation components

contribs/gmf/apps/mobile/index.html, contribs/gmf/less/desktop.less, contribs/gmf/less/desktoplayertree.less, contribs/gmf/less/layertree.less, contribs/gmf/less/mobile-nav.less, contribs/gmf/less/mobile.less, contribs/gmf/less/mobilelayertree.less, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/partials/layertree.html
With this pull request, a lot of work is done on the layer tree CSS to harmonize the different sizes.
Font size gets a bit larger without loosing space.
Also the different nodes in the tree now use the flexbox display so that elements are better aligned and distributed. The computed width of labels for example is a lot less hackish and takes the really available space.
Flexbox has an other advantage: no blank space is automatically added between elements. So this fixes #1134.
I also reduced the nesting when possible.
Legend icons size (actually ratio) is taken into account correctly. The layout actually adapts to it. Icons are not cropped to squeezed. Only max limits for width and height are fixed. Fixes #1302.
After / Before
On mobile, the font size is also bigger which makes it easier …
=> Layout harmonization

contribs/gmf/less/mobile-nav.less, contribs/gmf/less/mobile.less, contribs/gmf/less/vars.less
#1338 should be merged first.
The idea is to use as much space as possible for navigation panels on small devices on portrait mode.
This unfortunately breaks background and theme selectors layout since they use fixed sizes.
=> Use 90% of the viewport width on small mobile devices

contribs/gmf/examples/layertree.html, contribs/gmf/examples/layertree.js, contribs/gmf/src/directives/disclaimer.js, contribs/gmf/src/directives/layertree.js, src/services/eventhelper.js
This PR introduces the `gmf-disclaimer` directive, which is added to the layer tree example to demonstrate how it works.
It also introduces a `ngeo.EventHelper` that can be used to register and unregister events from OpenLayers or the Closure Library.  This may seem simple, but sometimes it's a little bit more complex.  For example, let's say you want to listen events from a collection.  If one of the items in the collection is also a collection, you want to listen to it as well.  This sort of complexity becomes hard to manage (the unlistening is what matters).  That's where the event helper comes in handy.  By giving it a uid, you can manage them more easily.
* https://adube.github.io/ngeo/gmf-disclaimer/examples/contribs/gmf/layertree.html
=> Add gmf-disclaimer directive

contribs/gmf/examples/layertree.html, contribs/gmf/examples/layertree.js, contribs/gmf/src/directives/disclaimer.js, externs/ngeox.js, src/directives/partials/popup.html, src/services/disclaimer.js, src/services/popup.js
This PR adds the possibility to display disclaimer messages as modals instead of alerts in the disclaimer service (ngeo).  The `gmf.disclaimer` directive now has an option that allows to turn this feature on (defaults to off).
The gmf layer tree example has been modified to be able to show this in action using a url parameter.
Note: this PR currently includes the content of #1341, since it hasn't been merged yet.
* (use modals) https://adube.github.io/ngeo/gmf-modal-disclaimer/examples/contribs/gmf/layertree.html?modal=true
* (use alerts, default behavior) https://adube.github.io/ngeo/gmf-modal-disclaimer/examples/contribs/gmf/layertree.html?modal=false
=> Support modal disclaimers

contribs/gmf/less/layertree.less
Fixed in a very simple way. This breaks alignments though.
@ybolognini please review.
=> Keep size ratio for legend icon

contribs/gmf/less/mobiledisplayqueries.less
Prevents errors with detailed query panel truncated on large tablets in portrait mode.
Fixes #1393.
=> Change max-height target

contribs/gmf/src/directives/partials/featurestyle.html
Removes the "name" label in the drawing style editor and replaces it by a placeholder.
=> Replace label by placeholder in feature style form

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/less/desktop.less, contribs/gmf/less/mobile.less, contribs/gmf/less/mobiledisplayqueries.less, contribs/gmf/less/vars.less
Removed all remaining rounded corners.
Demo: https://pgiraud.github.io/ngeo/radius/examples/contribs/gmf/apps/desktop
Actually the radius is configurable. Set to 0 by default.
=> Harmonize radius

contribs/gmf/src/directives/layertree.js
Close #1386 
Demo: https://oliviersemet.github.io/ngeo/fix-1386-getlegendgraphic/examples/contribs/gmf/apps/desktop/index.html
Go to OSM time to see the difference. The first and the last node have now an icon and a legend 
@sbrunner could you check please?
=> fix getLegendGraphic

contribs/gmf/less/mobile.less
- place the measures tool-tip on the level of the content (fixes issue #1350)
- [example](https://marionb.github.io/ngeo/mobile-measures-tooltip/examples/contribs/gmf/apps/mobile/?lang=en)
=> Define z-index for mobile measures tooltip

Makefile
See https://github.com/camptocamp/ngeo/commit/7d4c2ace43172bea4f994e05c074f3396638adab#commitcomment-17929803
=> Do not use pager for git attributes check

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/examples/elevation.html, contribs/gmf/less/desktop.less, contribs/gmf/src/directives/elevation.js, contribs/gmf/src/directives/mouseposition.js, contribs/gmf/src/directives/partials/mouseposition.html, src/directives/partials/scaleselector.html
With this pull request I improved the look&feel of the info bar.
The not exhaustive list of improvements is:
- alignments are more consistent,
- icons where removed because they take a lot of space and are not self explanatory,
- more space is added around component, this is more airy,
- info bar don't break layout if screen width is small,
- background selector position depends on whether the info bar is displayed or not.
Please also notice that I changed the behavior of the elevation directive. Now we call the service with only one layer at a time. And the elevation is displayed only when the mouse cursor is not moving. No elevation is displayed when the mouse is out of the map.
Démos:
https://pgiraud.github.io/ngeo/infobar_layout/examples/contribs/gmf/apps/desktop …
=> Infobar layout

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/examples/search.html, contribs/gmf/examples/search.js, contribs/gmf/less/desktop.less, contribs/gmf/less/search.less, contribs/gmf/src/controllers/abstractmobile.js, contribs/gmf/src/directives/partials/search.html, contribs/gmf/src/directives/search.js, contribs/gmf/src/gmf.js
replace #951 
https://github.com/camptocamp/c2cgeoportal/wiki/Specs-%23869---Color-of-search-result
without the color chooser:
* https://fredj.github.io/ngeo/style_search_overlay/examples/contribs/gmf/apps/desktop_alt/
with the color chooser:
* https://fredj.github.io/ngeo/style_search_overlay/examples/contribs/gmf/apps/desktop/
todo:
=> Manage search feature style

contribs/gmf/apps/mobile/index.html, contribs/gmf/src/directives/mobilenav.js
And use it to close the gmf-themeselector on mobile.
Fixes #1344
=> Add gmf-mobile-nav-back-on-click directive

contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/examples/timeslider.html, contribs/gmf/examples/timeslider.js, contribs/gmf/externs/gmf-themes.js, contribs/gmf/externs/gmfx.js, contribs/gmf/less/desktop.less, contribs/gmf/less/input-range.less, contribs/gmf/less/timeslider.less, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/datepicker.js, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/partials/layertree.html, contribs/gmf/src/directives/partials/timeslider.html, contribs/gmf/src/directives/timeslider.js, contribs/gmf/src/services/wmstime.js, contribs/gmf/test/spec/controllers/gmflayertreecontroller.spec.js, contribs/gmf/test/spec/services/wmstime.spec.js
This is a complete PR for the WMStime feature.
- This PR override #1353 
- Closes #1390 #1241 
- The datepicker has already been merged to master but the version was note completely operational. Consider this new version as a mature version 
examples:
- Desktop app: https://oliviersemet.github.io/ngeo/WMSTime-feature/examples/contribs/gmf/apps/desktop/
- Desktop alt app: https://oliviersemet.github.io/ngeo/WMSTime-feature/examples/contribs/gmf/apps/desktop_alt/
- Time slider component: https://oliviersemet.github.io/ngeo/WMSTime-feature/examples/contribs/gmf/timeslider.html
- Datepicker component: https://oliviersemet.github.io/ngeo/WMSTime-feature/examples/contribs/gmf/datepicker.html
Please read issue #1421 before comment 
Node: the time slider for the node named 'Temps OSM curseur …
=> WMSTime feature

contribs/gmf/src/directives/layertree.js
The mobile application is currently broken:
Error: [$injector:unpr] Unknown provider: gmfWMSTimeProvider <- gmfWMSTime <- GmfLayertreeController
This PR adds a missing `goog.require('gmf.WMSTime')` for the layer-tree.
=> Add missing require for `gmf.WMSTime`

examples/attributes.html, examples/attributes.js, src/directives/attributes.js, src/directives/partials/attributes.html
This PR introduces the `ngeo-attributes` directive, which produces a form to edit the properties of a feature.
This PR doesn't include a date picker. It should come in the next PR.
* http://adube.github.io/ngeo/ngeo-attributes/examples/attributes.html
=> Add ngeo-attributes directive

contribs/gmf/less/layertree.less, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/partials/layertree.html
ie. for when the WMTS capabilities are loading
Supersedes #1359
Fixes #1114
Fixes #1057 
After discussion with @ybolognini, we decided to fix this issue by simply not showing anything to the user when the capabilities are loading. The capabilities request doesn't last long enough to require a loader to be displayed.
Managing this in a more elegant way is a nice to have but requires more work.
Please review.
=> Remove specific style for no-source

contribs/gmf/apps/desktop_alt/less/main.less, contribs/gmf/examples/backgroundlayerselector.html, contribs/gmf/examples/themeselector.html, contribs/gmf/less/desktop.less, contribs/gmf/less/map.less, contribs/gmf/src/directives/partials/backgroundlayerselector.html, contribs/gmf/src/directives/partials/themeselector.html
Title says it all.
Démo: http://pgiraud.github.io/ngeo/selectors_layout/examples/contribs/gmf/apps/desktop/
=> Better layout for bg and theme selectors using flex

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/less/base.less, contribs/gmf/less/desktop.less, contribs/gmf/less/layertree.less, contribs/gmf/less/mobilelayertree.less, contribs/gmf/src/directives/partials/drawfeature.html, contribs/gmf/src/directives/partials/elevationwidget.html, contribs/gmf/src/directives/partials/featurestyle.html, contribs/gmf/src/directives/partials/mouseposition.html, contribs/gmf/src/directives/partials/print.html, src/directives/partials/scaleselector.html
With this pull request, font size gets uniformized. A smaller font is used everywhere.
Class names prefixed with "-sm" should be avoided as much as possible from now on.
Demo: https://pgiraud.github.io/ngeo/font-size-harmonization/examples/contribs/gmf/apps/desktop
=> Uniformize font size

contribs/gmf/examples/xsdattributes.html, contribs/gmf/examples/xsdattributes.js, contribs/gmf/src/services/xsdattributes.js
This PR introduces the `gmf.XSDAttributes` service, which is responsible of communicating with a GeoMapFish server to get the attributes of a layer in XSD format, convert them to an array of `ngeox.Attribute` objects.
It only sends the request for a single layer once using a promise.
That's the 3rd PR which completes the work of the "XSD Parser" task.  It currently includes the other 2 as well because none of them have been merged yet.  Let's wait for them to be merged before reviewing.
* https://adube.github.io/ngeo/gmf-xsdattributes-service/examples/contribs/gmf/xsdattributes.html
=> Add gmf.XSDAttributes service

examples/createfeature.html, examples/createfeature.js, src/directives/createfeature.js
This PR introduces the `ngeo-createfeature` directive, which allows the creation of vector features (point, line, polygon) using draw or measure interaction from a map.  Drawn features are added to a collection of features.
It is similar to the `ngeo-drawfeature` directive, but has the following things different:
* it only support drawing one type of geometry at a time (`ngeo-drawfeature` allows 6 types: point, line, polygon, text, circle, rectangle)
* it doesn't set any style to the feature
* it will be used for the purpose of editing features from real layers, while the `ngeo-drawfeature` only draw "sketchs" that are not saved
* http://adube.github.io/ngeo/ngeo-createfeature/examples/createfeature.html
=> Add ngeo-createfeature directive

contribs/gmf/examples/editfeature.html, contribs/gmf/examples/editfeature.js, contribs/gmf/src/services/editfeature.js
This PR introduces the `gmf.EditFeature` service along with a simple example that demonstrates what you can do with it. The example should be replaced in the incoming days with one that uses the "coming soon" directives that allows the user to actually select an editable layer first.
When trying to insert, update or delete, we get errors:
> XMLHttpRequest cannot load https://geomapfish-demo.camptocamp.net/2.1/wsgi/layers/113. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.
* ~~Fix the "Same origin" issues~~, moved to: https://github.com/camptocamp/c2cgeoportal/issues/2368
* https://adube.github.io/ngeo/gmf-editfeature-service/examples/contribs/gmf/editfeature …
=> Add gmf.EditFeature service with example

contribs/gmf/less/desktop.less
Here's a pull request to prevent the conflict between the info bar collapse/expand button and the features window.
Before
After
=> Put info bar expand in the center

contribs/gmf/less/mobile.less, contribs/gmf/less/search.less, contribs/gmf/less/searchmobile.less
fixes #1295.
Examples
- desktop: https://marionb.github.io/ngeo/split_search_styling/examples/contribs/gmf/apps/desktop/
- mobile: https://marionb.github.io/ngeo/split_search_styling/examples/contribs/gmf/apps/mobile/
=> Split mobile search and overwrite search style for narrow desktop browsers.

contribs/gmf/src/services/editfeature.js
This PR fixes the gmf.EditFeature service to use the correct header in the POST, PUT and DELETE requests it sends.
* https://adube.github.io/ngeo/fix-gmf-editfeature-service/examples/contribs/gmf/editfeature.html
=> Fix gmf EditFeature service header

contribs/gmf/src/directives/layertree.js
FIX #1424 
Related PR on server side: https://github.com/camptocamp/c2cgeoportal/pull/2328
As soon as a node with type set to "WMTS" get a property layer for its layer name, I'll provide an example.
@sbrunner  can you review please?
=> Fixing WMTS node not selected/unselected when clicking on a group

contribs/gmf/apps/mobile/index.html, contribs/gmf/src/directives/authenticationdirective.js, contribs/gmf/src/directives/mobilenav.js
Those changes allow to nav back to main menu in right navigation when the user is successfully logged in.
Fixes #1450.
I first reverted 079cd0cd5634e0c9ab6a1227f87da6d2ad9f832d to reintroduce `mobileNavBackDirective` but changed it so that it takes a boolean expression.
I also had to change the scope for the authentication directive. I'm not super happy with this change but couldn't find any better way.
Please review.
=> Mobile login nav

contribs/gmf/src/directives/partials/layertree.html
Related to c2cgeoportal issue [#2364](https://github.com/camptocamp/c2cgeoportal/issues/2364)
Demo: https://oliviersemet.github.io/ngeo/opacity-on-mixed-groups-must-not-be-possible/examples/contribs/gmf/apps/desktop/
**Select OSM theme:**
@sbrunner @pgiraud
=> Hiding opacity slider on mixed groups

contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/themeselector.js, contribs/gmf/src/services/permalink.js, contribs/gmf/src/services/treemanager.js, src/services/statemanager.js
Related to https://github.com/camptocamp/c2cgeoportal/issues/1657, this PR fixes some permalink bugs and complete the missing parameters 'tree_groups', 'tree_group_opacity' and 'tree_opacity'
**Empty your local storage before testing**
Demo:
- desktop : https://oliviersemet.github.io/ngeo/permalink-final-cut/examples/contribs/gmf/apps/desktop/
- desktop alt: https://oliviersemet.github.io/ngeo/permalink-final-cut/examples/contribs/gmf/apps/desktop_alt/
You must be able to retrieve the same state (except for group collapsing) of the application if:
- You copy the permalink to another tab
- Open the default url (without any url query parameter) in a tab
@fredj @pgiraud @sbrunner @ger-benjamin
=> Permalink final cut

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/examples/displayquerywindow.html, contribs/gmf/examples/displayquerywindow.js, contribs/gmf/examples/wfs-permalink.html, contribs/gmf/examples/wfs-permalink.js, contribs/gmf/less/desktop.less, contribs/gmf/less/displayquerywindow.less, contribs/gmf/less/mobile.less, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/controllers/abstractmobile.js, contribs/gmf/src/directives/displayquerywindow.js, contribs/gmf/src/directives/partials/displayquerywindow.html, contribs/gmf/test/spec/directives/displayqueries.spec.js
Fix #1534 
Example: http://ger-benjamin.github.io/ngeo/displayquerynames/examples/contribs/gmf/
Apidoc: http://ger-benjamin.github.io/ngeo/displayquerynames/apidoc
=> Rename 'displayqueries' to 'displayquerywindow'

contribs/gmf/src/directives/themeselector.js, contribs/gmf/src/services/treemanager.js, src/services/statemanager.js
Close #1026 
**Flush you localStorage before test**
Demo: https://oliviersemet.github.io/ngeo/store-theme-in-localstorage/examples/contribs/gmf/apps/desktop/
1. Load the [app](https://oliviersemet.github.io/ngeo/store-theme-in-localstorage/examples/contribs/gmf/apps/desktop/) with the default theme
2. Select any theme but not the default one (OSM)
3. Open the [app](https://oliviersemet.github.io/ngeo/store-theme-in-localstorage/examples/contribs/gmf/apps/desktop/) into an other tab
@fredj @pgiraud @sbrunner
=> Store the name of the selected theme in localStorage

examples/locationchooser.html, src/directives/recenter.js
Otherwise this code doesn't work:
```
<button ngeo-extent="[-1898084, 4676723, 3972279, 8590299]" translate>Move to Europe</button>
```
=> Fix click event listener in ngeo-recenter

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/examples/profile.html, contribs/gmf/examples/profile.js, contribs/gmf/less/desktop.less, contribs/gmf/less/profile.less, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/drawProfileLine.js, contribs/gmf/src/directives/drawprofileline.js, contribs/gmf/src/directives/partials/profile.html, contribs/gmf/src/directives/profile.js, externs/ngeox.js, src/d3-ext/profile.js
Fix: camptocamp/c2cgeoportal#1661
Specs: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231661-Profiles
Example: 
- 1 elevation raster: https://ger-benjamin.github.io/ngeo/profile21/examples/contribs/gmf/apps/desktop_alt
- Multiple elevations rasters: https://ger-benjamin.github.io/ngeo/profile21/examples/contribs/gmf/apps/desktop
(See just the last commit for the intergration and the new tool)
@pgiraud I need some specifications for the "Draw profile tool", the activation, the placement and some differences that come from the profile with more than 1 line. Can you take a look please ?
Edit: Integrated. Thanks
---
**Issue to create and resolve later** :
- Reload the profile on screen size change.
- It exists any tests for ngeo and gmf profile.
=> Profile Integration and dedicated tool to draw profile's line

contribs/gmf/apps/mobile/index.html, contribs/gmf/src/directives/displayquerywindow.js
fixes issue #781.
(Example: https://marionb.github.io/ngeo/default_open_query/examples/contribs/gmf/apps/mobile/index.html)
=> Add configuration variable to decide if the query result window is open or closed.

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/examples/share.html, contribs/gmf/examples/share.js, contribs/gmf/externs/gmfx.js, contribs/gmf/less/desktop.less, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/partials/share.html, contribs/gmf/src/directives/share.js, contribs/gmf/src/services/share.js, contribs/gmf/test/spec/beforeeach.js, contribs/gmf/test/spec/services/share.spec.js, src/directives/modal.js
Related to https://github.com/camptocamp/c2cgeoportal/issues/2071
**Demo:** 
- Desktop: https://oliviersemet.github.io/ngeo/share-permalink-feature/examples/contribs/gmf/apps/desktop/
- Desktop alt: https://oliviersemet.github.io/ngeo/share-permalink-feature/examples/contribs/gmf/apps/desktop_alt/
**Important**
- Currently the call to the Shortener API does not work (HTTP Bad request) because of a security reason. Indeed, the server check if the URL sended to be shortened is part of the domain  `geomapfish-demo.camptocamp.net` . Therefore it cannot work on my gh pages. @sbrunner will work on it.
- The _Desktop_ app use the Shortener API whereas the _Desktop Alt_ app does not (Testing the case when no Shortener API is available for the customer).
- In case of error, I display the following …
=> Share permalink feature

contribs/gmf/examples/search.html, contribs/gmf/examples/search.js, contribs/gmf/src/directives/search.js
To be able to customize the Typeahead configuration in a project.
=> Add new gmf-search-options attribute to gmf-search

contribs/gmf/src/directives/mobilenav.js
Otherwise the following doesn't work:
```
<a href data-toggle="slide-in" translate>foo</a>
```
The `translate` directive adds and extra `span` and it's this span that respond
to the click event.
=> Use the current target in slide-in click handler

contribs/gmf/examples/xsdattributes.html, contribs/gmf/examples/xsdattributes.js, externs/ngeox.js, src/directives/partials/attributes.html, src/ol-ext/format/xsdattribute.js
This PR introduces the support of geometry attributes in the XSDAttribute format.  They used to be completely ignored.  Now, they are added alongside other attributes.
The `ngeo.Attributes` directive is now the one that ignores the geometry attributes.
The example featuring the `gmf.XSDAttributes` directive demonstrate that one can detect the type of geometry used by a layer using the XSDAttribute format.
* https://adube.github.io/ngeo/xsd-attribute-support-geom/examples/contribs/gmf/xsdattributes.html
=> Support geometry attribute in XSDAttribute format

contribs/gmf/src/directives/layertree.js
FIX #1424
demo:
https://oliviersemet.github.io/ngeo/fix-regex-layersnames-same-prefix/examples/contribs/gmf/apps/desktop/?baselayer_ref=map&lang=fr&map_x=612600&map_y=148750&map_zoom=2&tree_group_layers_OSM%20functions=osm_time%2Cosm_time2%2Cosm_scale%2Cosm_open%2Cbank%2Crestaurant%2Ccafe%2Chalf_query%2Csrtm%2Caster&tree_groups=OSM%20functions
=> fix select/unselect node when layers have the same prefix

externs/ngeox.js, src/services/featurehelper.js
With this pull request I tried to simplify the helper to create a text style.
Currently this method can take 7 arguments (5 are optional).
This drives us to some code looking like this:
https://github.com/camptocamp/ngeo/blob/master/src/services/featurehelper.js#L211-L219
This is ugly in my opinion.
I propose instead to use only on object argument.
Please review.
=> Simplify createTextStyle by shortening the list of args

contribs/gmf/examples/editfeatureselector.html, contribs/gmf/examples/editfeatureselector.js, contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/editfeatureselector.js, contribs/gmf/src/directives/partials/editfeature.html, contribs/gmf/src/directives/partials/editfeatureselector.html, src/directives/createfeature.js
This is PR introduces the `gmf-editfeature` and `gmf-editfeatureselector` directives. There are still components and features that are missing from the SPECs, but I'm creating this early PR to be able to have the work in progress reviewed.
* https://adube.github.io/ngeo/gmf-editfeature-directive/examples/contribs/gmf/editfeatureselector.html
This PR doesn't include the following features.  They will come in separate tickets:
* refresh the WMS layer after a save has been made
* measure while drawing
* save button should be "gray" until modifications are maded
* geometry modifications
* validate required fields
* have an option for the pixel buffer
* confirm before delete
Also, there's currently a CORS error when deleting.
=> Add gmf-editfeature and gmf-editfeatureselector directives

contribs/gmf/src/directives/partials/featurestyle.html, src/directives/drawfeature.js, src/directives/measureazimut.js, src/ngeo.js, src/ol-ext/interaction/measureazimut.js, src/services/featurehelper.js
Supersedes #1573
I reworked @jlap 's pull request to make it simpler (well I hope).
Instead of storing the radius line geometry, only the azimut is kept as a property of the feature.
Also, the placement of the azimut value on the map is computed using the point which is on the circle instead of a complex computation with an offset from the center.
Also the radius value and the position of the azimut update correctly if the circle is modified.
Finally, the radius length displays along the line (ie. oriented).
Demo:
http://pgiraud.github.io/ngeo/azimuth/examples/contribs/gmf/drawfeature.html
https://pgiraud.github.io/ngeo/azimuth/examples/contribs/gmf/apps/desktop
Still missing: update of the azimut value when modifying the circle.
=> Display azimuth of circles in the redlining tools

contribs/gmf/src/services/permalink.js
**Demo**:
https://oliviersemet.github.io/ngeo/fixing-feature-wrong-area-value-after-reload/examples/contribs/gmf/apps/desktop_alt/?baselayer_ref=map&lang=fr&map_x=583100&map_y=130100&map_zoom=0&tree_groups&rl_features=Fa(qf83-57uF.rmt-1e3_..smt-~r*true%27n*Rectangle%25201%27c*%2523DB4436%27a*0%27o*0.2%27m*true%27s*10%27k*1)a(ye93-d5aD.z4f_wav_..15f_~r*true%27n*Rectangle%25202%27c*%2523DB4436%27a*0%27o*0.2%27m*true%27s*10%27k*1)
Close #1576 
@pgiraud @sbrunner PR ready for review.
=> Displaying features label after the locale has been loaded successfully

contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/partials/editfeature.html
This PR is a follow-up of #1585.  It features the addition of a confirmation message before deleting a feature. The "Delete" button is also only shown when an existing feature is selected, i.e. it's not shown when a feature is being created.
* https://adube.github.io/ngeo/gmf-editfeature-confirm-delete/examples/contribs/gmf/editfeatureselector.html
=> Add confirmation before deleting a feature in gmf-editfeature

contribs/gmf/examples/editfeatureselector.html, src/directives/createfeature.js
This PR is a follow-up of #1585.  It adds the measurements of lines and polygons while drawing
* https://adube.github.io/ngeo/gmf-editfeature-measure-while-drawing/examples/contribs/gmf/editfeatureselector.html
=> Support measure while drawing in gmf-editfeature

contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/editfeatureselector.js, contribs/gmf/src/directives/partials/editfeatureselector.html
This PR is a follow-up of #1585.  It adds the `pixelBuffer` option to both `gmf-editfeature` and `gmf-editfeatureselector` directives.
* https://adube.github.io/ngeo/gmf-editfeature-pixelbuffer/examples/contribs/gmf/editfeatureselector.html
=> Add pixelBuffer for gmf-editfeature directive

contribs/gmf/examples/editfeatureselector.js, contribs/gmf/src/directives/editfeature.js, src/ol-ext/style/style.js
This PR is a follow-up of #1585.  It introduces the support of geometry modification in the `gmf-editfeature` directive.
* https://adube.github.io/ngeo/gmf-editfeature-geometry/examples/contribs/gmf/editfeatureselector.html
=> Support geometry modification in gmf-editfeature

contribs/gmf/src/directives/drawfeature.js
Close #1580
**demo:**
[Here](https://oliviersemet.github.io/ngeo/display-interaction-cursor-on-top-of-features/examples/contribs/gmf/apps/desktop_alt/?baselayer_ref=map&lang=fr&map_x=521000&map_y=120250&map_zoom=0&rl_features=Fa(dhz2-9b9Fj_dn-rCym-rHwk-pMfj-eRfg-xV1e-807b-84-w7-v7-94-6b-90zd-yVeg-fRej-qMvk-sHxm-sCcn-k_en-j_xm-rCvk-rHej-pMeg-eRzd-xV6b-80v7-84-84-v7-806b-xVzd-eReg-pMej-rHvk-rCxm-j_cn-k_en-sCxm-sHvk-qMej-fReg-yVzd-906b-94-v7-w7-84-7b-801e-xVfg-eRfj-pMwk-rHym-rCfn-j_dn-k_ym-sCwk-sHfj-qMfg-fR1e-yV7b-90w7-94-94-w7-907b-yV1e-fRfg-qMfj-sHwk-sCym-~l*true%27n*Circle%25201%27c*%2523DB4436%27a*0%27o*0.2%27m*false%27s*10%27k*1)a(k6z3-18cEg!u7_cF77_8Mu5_vSu3_cZ51_e5-ww-ab-1t-mg-kn-jn-ng-zs-bb-vw-f5-41_dZt3_wSt5_9M67_dFt7_h!v7_g!67_cFt5_8Mt3_vS41_cZvw-e5-zs-ab-jn-mg-mg-jn-ab-zs-e5-vw-cZ4 …
=> Displaying interaction overlay on top of all features drawn (redlining)

contribs/gmf/examples/drawfeature.html, contribs/gmf/examples/drawfeature.js, contribs/gmf/src/directives/drawfeature.js
Supersedes #1603.
Fixes #1471 & #1579.
It looks like the filtering using "layer" in `forEachFeatureAtPixel` is not really required since we already ensure that the feature is the from the correct collection.
This means that we don't need to give the `drawFeature` directive a layer. The `ngeoFeature` service is already doing the job.
In summary, we were doing too much. Code has been simplified and it continues to work.
Demo
https://pgiraud.github.io/ngeo/fix_feature_selection/examples/contribs/gmf/apps/desktop
https://pgiraud.github.io/ngeo/fix_feature_selection/examples/contribs/gmf/drawfeature.html
=> Fix feature selection

contribs/gmf/src/directives/drawfeature.js, src/ol-ext/interaction/modifycircle.js
With this pull request I cleaned the modify circle by removing some code that looks not necessary to me. I actually figured out that the number of features managed by the modify circle interaction was increasing where there should be only the currently selected feature.
But the main goal is to allow modification of the azimut when modifying the circle.
Demo:
https://pgiraud.github.io/ngeo/azimut_modify/examples/contribs/gmf/apps/desktop
https://pgiraud.github.io/ngeo/azimut_modify/examples/contribs/gmf/drawfeature.html
(Draw a circle, check the "Show radius and azimut", then modify the circle)
=> Azimut modify

contribs/gmf/examples/editfeatureselector.js, contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/editfeatureselector.js, contribs/gmf/src/directives/partials/editfeatureselector.html, src/services/eventhelper.js, src/services/layerHelper.js
This PR is a follow-up of #1585.  It features the refreshing of the WMS layer after a save action occurs in the `gmf-editfeature` directive.
* https://adube.github.io/ngeo/gmf-editfeature-refresh-wms/examples/contribs/gmf/editfeatureselector.html
=> Refresh WMS layer after save in gmf-editfeature

contribs/gmf/examples/editfeatureselector.html, contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/partials/editfeature.html, examples/attributes.html, examples/attributes.js, src/directives/attributes.js, src/directives/partials/attributes.html
This PR is a follow-up of #1585.  It introduces `dirty` and `pending` properties in the `gmf-editfeature` directive :
* the directive is marked `dirty` when a feature is modified, i.e. its geometry or its properties. Only when dirty does the "Save" button is enabled
* the directive is marked `pending` while a save request or a get request is in progress. While so, the form and buttons are prevented from being used.
* https://adube.github.io/ngeo/gmf-editfeature-dirty-management/examples/contribs/gmf/editfeatureselector.html
=> Manage dirty and pending in gmf-editfeature

contribs/gmf/examples/editfeatureselector.html, src/directives/attributes.js, src/directives/datepicker.js, src/directives/partials/attributes.html
This PR introduces the use of the `ui-date` directive in the `ngeo-attributes` directive for both `date` and `datetime` attribute types. Note that we should definitively use something else for `datetime`, but this should come in an other PR.
* https://adube.github.io/ngeo/xsd-datetime/examples/contribs/gmf/editfeatureselector.html
=> Add ui-date in ngeo-attributes

contribs/gmf/src/directives/print.js
Fixes #1133.
With this pull request I address two different things:
- the race condition which in certain circumstances the print mask was displayed even if the print panel was already closed. See #1133.
- the fact that the capabilities promise is recreated each time the print panel is open. I gave it a new try and it's now taking into account the roleId change.
https://github.com/camptocamp/ngeo/commit/a7e53c966f6294eaa328370feaeb928b5047505d
https://github.com/camptocamp/ngeo/commit/92a284a1cce57efbc52a7cb0de08127dddae151a
Please review.
Démo https://pgiraud.github.io/ngeo/print_mask_race_condition/examples/contribs/gmf/apps/desktop_alt
=> Print mask race condition

contribs/gmf/src/directives/editfeature.js
This PR fixes an issue in the `gmf-editfeature` directive.
When clicking on a feature that has a date set, the value is read by the `ui-date` directive. Upon initialization, it converts it from a string to a `Date` object.  This is set in the feature, which triggers a change, which sets the dirty state to true.  Long story short: when clicking on a feature that has a date set, the save button is enabled, because the dirty is set.
This fix is simple: set a timeout to set the dirty state to `false` upon setting a new feature.  This leaves enough time for the feature to be set with a date upon initialization.
* https://adube.github.io/ngeo/gmf-fix-date-dirty/examples/contribs/gmf/editfeatureselector.html
=> Fix dirty state in gmf-editfeature

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/examples/editfeatureselector.js, contribs/gmf/less/desktop.less, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/partials/editfeatureselector.html, src/services/featurehelper.js
This PR introduces the `gmf-editfeature` directive in the **dektop** and **desktop_alt** applications.
You need to be logged in to see the editing tools.  Also, you need to have the "Editing" theme in order to have layers in the drop down list.
* (Desktop Alternate) https://adube.github.io/ngeo/gmf-editfeature-app/examples/contribs/gmf/apps/desktop_alt/index.html?baselayer_ref=map&lang=fr&map_x=537500&map_y=152851&map_zoom=3&tree_groups=Edit&tree_group_layers_Edit=line%2Cpolygon%2Cpoint
* (Desktop) https://adube.github.io/ngeo/gmf-editfeature-app/examples/contribs/gmf/apps/desktop/
=> Add gmf-editfeature in desktop and desktop_alt apps

contribs/gmf/src/directives/partials/editfeatureselector.html
Adds the `form-control` to the select element of the `gmf-editfeatureselector` directive.
* https://adube.github.io/ngeo/gmf-editfeature-select-form-control/examples/contribs/gmf/editfeatureselector.html
=> Add form-control to the layer <select> element

contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/partials/layertree.html
This PR introduces the following feature: show a small pencil icon in the layer tree while the `gmf-editfeature` directive is enabled.
There is no way of testing this without both a layer tree and the edit tools at the same time.  Instead of creating a new example or making either the layer tree or edit feature example more complex, I used the applications as test ground.
* https://adube.github.io/ngeo/gmf-editfeature-layertree-icon/examples/contribs/gmf/apps/desktop_alt/index.html?baselayer_ref=map&lang=fr&map_x=537500&map_y=152851&map_zoom=3&tree_groups=Edit&tree_group_layers_Edit=line%2Cpolygon%2Cpoint
=> Show pencil icon in layer tree while editing

contribs/gmf/src/directives/editfeature.js
This simple PR simplifies some code in the `gmf-editfeature` directive toggle method.
=> Simplify togging on/off of gmf-editfeature directive

contribs/gmf/src/directives/editfeatureselector.js
This PR makes sure that if a layer gets removed while it's active in the `gmf-editfeatureselector`, the selected layer gets reseted.
It's easier to see this in action with the application.
* https://adube.github.io/ngeo/gmf-editfeature-layer-remove-reset/examples/contribs/gmf/apps/desktop_alt/index.html?baselayer_ref=map&lang=fr&map_x=537500&map_y=152851&map_zoom=3&tree_groups=Edit&tree_group_layers_Edit=line%2Cpolygon%2Cpoint
=> Manage layer removal while active in gmf-editfeatureselector

contribs/gmf/src/directives/editfeature.js
This PR introduces the "rotation" and "move" action when right-clicking on a vector feature in the `gmf-editfeature` directive.  In order to work, you need to left-click first, which does a query to get the vector features.  Then, you can right-click on the vector feature to open the contextual menu.
* https://adube.github.io/ngeo/gmf-editfeature-rotate-move/examples/contribs/gmf/editfeatureselector.html
=> Support rotate and move in gmf-editfeature

src/services/printutils.js
Fixes #1533
Please review
Demo:
https://pgiraud.github.io/ngeo/print_mask_retina/examples/contribs/gmf/print.html?baselayer_ref=map&lang=en&map_x=552200&map_y=193800&map_zoom=0&tree_enable_osm_open=false&tree_enable_osm_scale=true&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions
(to be compared with https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/print.html?baselayer_ref=map&lang=en&map_x=552200&map_y=193800&map_zoom=0&tree_enable_osm_open=false&tree_enable_osm_scale=true&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions)
=> Take device pixel ratio when displaying print mask

contribs/gmf/src/directives/editfeature.js
This PR fixes #1652.  The dirty state is not reseted for newly created features.
* https://adube.github.io/ngeo/gmf-editfeature-fix-insert/examples/contribs/gmf/editfeatureselector.html
=> Fix #1652 - Fix gmf-editfeature dirty state with new features

contribs/gmf/examples/editfeatureselector.js, contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/directives/editfeatureselector.js, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/services/themesservice.js
This PR uses the `editable` theme node property as configuration for the `gmf-editfeatureselector` directive to determine which layers are editable. Adjust the other examples as well.
In order to see it in action, we need the layer tree.  This requires #1636 to be merged first.
* https://adube.github.io/ngeo/gmf-editfeature-editable/examples/contribs/gmf/apps/desktop_alt/index.html?baselayer_ref=map&lang=fr&map_x=537500&map_y=152851&map_zoom=3&tree_groups=Edit&tree_group_layers_Edit=line%2Cpolygon%2Cpoint
=> Use 'editable' theme node property as configuration

contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/search.js, contribs/gmf/src/services/themesservice.js, contribs/gmf/src/services/treemanager.js, src/services/layerHelper.js
Fixes #1220 
Note: In  [themesservice.js](https://github.com/marionb/ngeo/blob/d677bebe1a8b2d2e29b2cf1163dddf14d8077533/contribs/gmf/src/services/themesservice.js#L128) I changed the use of `layer.layers` to `layer.name` to be able to also use this for WMTS layers. Is there a particular reason that we should continue using `layer.layers`?
=> Enable search layer

.gitignore, Makefile, examples/https.js
Fixes #1626 
With this pull request we ensure that hosted examples are redirected to https when run on github.
To make it so, the `https.js` file is loaded in each example in their hosted version. There's only one `https.js` file throughout the application. It is copied adequately to be used both in ngeo, gmf or gmf-apps.
I also changed the `gh-pages` target so that it depends on `examples-hosted`.
Please review.
=> Examples https

src/services/featurehelper.js
This PR fixes the gmf-editfeatureselector example because of a missing comment block.
* https://adube.github.io/ngeo/gmf-editfeature-fix-example/examples/contribs/gmf/editfeatureselector.html
=> Fix error in gmf-editfeatureselector example

src/ol-ext/format/xsdattribute.js
Fixes #1633.
* https://adube.github.io/ngeo/fix-xsdattributes-ff/examples/attributes.html
=> Fix xsd attributes in Firefox

contribs/gmf/src/directives/partials/editfeature.html, src/directives/partials/attributes.html
Work in progress.
This PR implements "on-the-fly" validation in the attributes directive.
* https://adube.github.io/ngeo/gmf-editfeature-live-validation/examples/contribs/gmf/editfeatureselector.html
=> Add on-the-fly validation in attributes directive

Makefile
When re-installing the node modules while "make serve" is running, the system might freeze and you are forced to do a hard reboot. Now you get a warning if a node process is running.
=> Warn for potential system freeze

contribs/gmf/src/directives/layertree.js
The purpose of this pull request is to fix an issue related to node corresponding to several LAYERS params (ie. several mapfile layers).
Currently in the "OSM Functions" group, there's a node called "two_layers" which actually displays "sustenance" and "entertainment" features on the map.
Steps to reproduce bug:
- Clic on URL below
- Expand the OSM Function group,
- Deactivate the group -> the node "two_layers" is not deactivated.
Current:
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/?baselayer_ref=map&lang=en&map_x=601000&map_y=207500&map_zoom=4&rl_features&tree_groups=OSM%20functions&tree_group_layers_OSM%20functions=sustenance%2Centertainment%2Cosm_time%2Cosm_time2%2Cosm_scale%2Cosm_open%2Cbank%2Csustenance%2Centertainment%2Chalf_query%2Csrtm%2Caster …
=> Fix node with several layer names not correctly removed or added

contribs/gmf/src/services/querymanager.js
This pull request fixes the case where queries were issued even for not queryable layers.
This is a partial fix for #1659.
In the "OSM Functions", the nodes "srtm" & "aster" are generating requests even if they're not queryable.
Please review.
Ping @adube 
You can compare the results in the following examples. In the current version, you'll see that aster and srtm are available in the filter.
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop/?baselayer_ref=map&lang=en&map_x=610038&map_y=190238&map_zoom=3&rl_features&tree_group_layers_OSM%20functions=osm_time&tree_groups=OSM%20functions
https://pgiraud.github.io/ngeo/fix_query_two_layers/examples/contribs/gmf/apps/desktop/?baselayer_ref=map&lang=en&map_x=610038&map_y=190238&map_zoom=3&rl_features&tree_group_layers_ …
=> Don't query if no childLayer is queryable

src/services/location.js, test/spec/services/location.spec.js
Adds support for fragment parameters (`...#key1=val1&key2=val2`) to the `ngeo.Location` service.
=> Add support for url fragment parameters

contribs/gmf/src/services/themesservice.js, src/services/backgroundlayermgr.js
The group will appear in the background selector.
Selecting the group will activate child layers.
All children of a group are assumed to be plain layers.
Supported dimensions are read from the group.
In addition, trigger a source refresh on dimension change.
=> Handle one level of background groups

src/ol-ext/format/featurehash.js
In an application where we include ngeo alongside other libraries and in which we compile them all together using Compiler Compiler, we get errors like this one:
ERR! compile ngeo/ol-ext/format/featurehash.js:590:
ERROR - Property pointRadius never defined on Object<string,(boolean|number|string)>
ERR! compile   pointRadius = properties.pointRadius;
I checked if the minimized JavaScript file produced by the build script within ngeo and these properties stay as is, i.e. the compiler don't rename them.  In our app, it would.  This patch fixes this.
=> Fix properties not defined on Object

contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/print.js, contribs/gmf/src/services/permalink.js, src/services/layerHelper.js
Fix: #1436 
Example: https://ger-benjamin.github.io/ngeo/layerNodeName/examples/contribs/gmf/apps/desktop
=> Set layer property 'layerName' to 'layerNodeName'

contribs/gmf/src/directives/layertree.js, contribs/gmf/src/services/treemanager.js, contribs/gmf/test/spec/directives/layertree.spec.js
Fix: #1570
Demo: https://ger-benjamin.github.io/ngeo/gmfLayerOrder/examples/contribs/gmf/apps/desktop
Please, try around functions of the layertree (search layers, queries) as well.
I've:
- Removed redounded call of the "prepareLayer_" function (line 372 was redound with 395)
- "insertAt 0" inseatead of "push" of the wms/wmts layers (mixed groups). (line 394)
- Simplified the toggle function (part "not mixed groups", lines 653~681).
- Reorder wms LAYERS names in not mixed groups (every times read in order, must be added to the map in reverse order. (others changes)
Second commit is for the add layer action (order was wrong with wms layers).
(Create a function that update wms, keep server order AND works in all cases was a headache. I've gave up.)
=> Fix layer order in layertree

contribs/gmf/src/directives/layertree.js, contribs/gmf/src/services/themesservice.js, contribs/gmf/src/services/treemanager.js
Fix: #1614
Demo: https://ger-benjamin.github.io/ngeo/1614/examples/contribs/gmf/apps/desktop/
I hope it's correct, I don't really know how I can test in the current demo. But now, this method search the group in all `children`.
=> FindGroupByLayerName search now in sub groups

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/src/controllers/abstract.js, src/directives/bboxquery.js, src/directives/mapquery.js
Fix: #1527 
Demo: https://ger-benjamin.github.io/ngeo/printandqueries/examples/contribs/gmf/apps/desktop/
(No query tools in the desktop_alt)
I (already) don't remember, the query window should be effectively always visible ?
=> Deactivate query on print but keep query infos

contribs/gmf/src/controllers/abstractdesktop.js, src/services/layerHelper.js
see #1544 
Notes:
- The Infinity preloading applies to all WMTS layers, not only to the background layers.
- All the tiles are loaded while animating and interacting (but only form the desktop interface)
=> OpenLayers optimizations

contribs/gmf/src/directives/editfeature.js
This PR is a fix that allows vertice to be deleted on click on the selected vector feature in the `gmf-editfeature` directive.
The trick is to check if a vector feature was clicked before launching a new query. In that case, do nothing, which allows the default behavior of the `ol.interaction.Modify` to occur in case of a vertex click to delete it.
* https://adube.github.io/ngeo/1721-delete-vertex-fix//examples/contribs/gmf/editfeatureselector.html
=> Fix #1721 - Allow vertex deletion in gmf-editfeature

src/ol-ext/format/featurehash.js, src/ol-ext/format/xsdattribute.js, src/ol-ext/interaction/measure.js, src/ol-ext/interaction/measurearea.js, src/ol-ext/interaction/measureazimut.js, src/ol-ext/interaction/measurelength.js, src/ol-ext/interaction/measurelengthmobile.js, src/ol-ext/interaction/measurepointmobile.js, src/ol-ext/interaction/mobiledraw.js, src/ol-ext/interaction/modify.js, src/ol-ext/interaction/modifycircle.js, src/ol-ext/interaction/modifyrectangle.js, src/ol-ext/interaction/rotate.js, src/ol-ext/interaction/translate.js, src/ol-ext/menu.js, src/ol-ext/popover.js
This PR removes the `goog.base` methods from the files that are in `src/ol-ext`, i.e. from files that inherits from OpenLayers classes.
This allow those classes to be built with Closure-Util in which the `useOfGoogBase` configuration is not used.
=> Remove goog.base from ol-ext files

contribs/gmf/src/services/querymanager.js, externs/ngeox.js, src/services/query.js
Fixes #1659 
With this pull request nodes with layer names (for example "sustenance,entertainment") are correctly checked (ie. compared with the OL3 layer source LAYERS param) before the query request are sent.
Démo:
https://pgiraud.github.io/ngeo/too_much_queries/examples/contribs/gmf/apps/desktop_alt/?baselayer_ref=map&lang=fr&map_x=554380&map_y=145380&map_zoom=3&rl_features=Fa(57v1-3bcEgC8w*9t!hH90s6*~n*Polygon%25201%27c*%2523DB4436%27a*0%27o*0.2%27m*false%27s*10%27k*1)&tree_groups=OSM%20functions&tree_group_layers_OSM%20functions=osm_time
To be compared with:
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/?baselayer_ref=map&lang=fr&map_x=554380&map_y=145380&map_zoom=3&rl_features=Fa(57v1-3bcEgC8w*9t!hH90s6*~n*Polygon%25201%27c*%2523DB4436%27a*0%27o*0.2% …
=> Allow query on nodes that have several layer names

contribs/gmf/src/directives/displayquerygrid.js, src/services/csvdownload.js
This PR adds options in the `csvdownload` service:
* ngeoCsvEncoding
* ngeoCsvExtension
* ngeoCsvIncludeHeader
* ngeoCsvQuote
* ngeoCsvSeparator
See specs for description: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231672-Querying-results-CSV-export-plugin#configuration
The `csvExportLikeCurrentGrid` as not beed added. It's already possible to export only a sub-section of selected rows and in the proper order.
=> Add options in csvdownload service

contribs/gmf/less/desktop.less, contribs/gmf/src/directives/partials/editfeature.html, contribs/gmf/src/directives/partials/editfeatureselector.html, src/directives/partials/attributes.html
Fixes #1724 
- Removed the ":" after the label. The spaces before and after are not the same in the different languages. Also, it's not really required. So I removed them for simplicity.
- Changed the "chosen" editing layer title look and feel to make it a bit more clear.
- Added a more clear separation between the chosen editing layer title and the editing attributes section.
- Used primary color for the "save" button.
- Added a cross (close) button to deselect the current feature. It has the same behavior as the cancel button actually.
Please review.
After / Before
Demo:
https://pgiraud.github.io/ngeo/editing_ui/examples/contribs/gmf/apps/desktop?baselayer_ref=map&lang=fr&map_x=561294&map_y=204601&map_zoom=7&rl_features=Fa(57v1-3bcEgC8w*9t!hH90s6*~n*Polygon%25201%27c*%2523DB4436%27a*0%27 …
=> Rework of UI for editing panel

contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/partials/editfeature.html
This pull request adds support for showing a modal when there are unsaved modifications.
Supersedes #1727 by using promises instead of storing the coordinates of the clicked point.
It currently doesn't take into account the "stop editing" nor the deactivation of the editing panel.
Demo: https://pgiraud.github.io/ngeo/unsaved_modifications/examples/contribs/gmf/apps/desktop_alt/?baselayer_ref=asitvd.fond_couleur&lang=fr&map_x=539650&map_y=145250&map_zoom=2&rl_features=Fa(57v1-3bcEgC8w*9t!hH90s6*~n*Polygon%25201%27c*%2523DB4436%27a*0%27o*0.2%27m*false%27s*10%27k*1)&tree_groups=Edit&tree_group_layers_Edit=point%2Cpolygon%2Cline
=> Unsaved modifications

contribs/gmf/src/directives/layertree.js, contribs/gmf/src/services/treemanager.js
Fix #1722 
Example: https://ger-benjamin.github.io/ngeo/layerGroupOrder/examples/contribs/gmf/apps/desktop_alt
The problem was far more complex than expected. Please read and understand before to comment.
To summarize (it's hard), try to understand this example:
- If I add theme OSM, I add 4 first level groups at once.
- The layer at the top of the layer tree will be added first in the map
- then the second, etc.
- Then I add the "edit" theme. So one another first level layer group.
- I should add it at the top of the layertree but angular doesn't add all OSM theme again so it will be added alone.
The problem is that I can't just add layer in the map by a `insertAt(0, layer)` or a `push(layer)`.
- With `insertAt(0, layer)`, the OSM layer will be ordered correctly on the map but the edit …
=> Order group layers in tree and map.

contribs/gmf/less/map.less, src/services/disclaimer.js
Fix https://github.com/camptocamp/ngeo/issues/1692
Example: https://ger-benjamin.github.io/ngeo/fixclose/examples/contribs/gmf/apps/mobile
Close disclaimer is easier on litlle device and no more cut (a in my opinion, the cross is (more) coherent now).
=> Fix too small disclaimer close button

contribs/gmf/src/services/themesservice.js, src/ol-ext/interaction/measureazimut.js
This is necessary to avoid bad access farther in OpenLayers 3 code.
=> Skip undefined layers

contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/backgroundlayerselector.js, contribs/gmf/src/services/querymanager.js, contribs/gmf/src/services/themesservice.js, contribs/gmf/test/spec/services/themesservice.spec.js, src/ol-ext/interaction/measureazimut.js, src/services/backgroundlayermgr.js, src/services/layerHelper.js
Properly initialize background layers dimensions by passing the abstract
controller dimensions object.
Allow provisionning default dimensions with Angular gmfDefaultDimensions.
The dimensions should now be passed to the background selector.
Handle WMS layers in addition to WMTS layers.
=> Handle WMS background layers dimensions + fixes

contribs/gmf/apps/desktop_alt/js/controller.js
Closes https://github.com/camptocamp/ngeo/issues/1765
Note that this string is no extracted together with the GMF translation strings, like all other i18n strings in `contribs/gmf/apps`.
=> Mark merged layer label as translatable

contribs/gmf/less/desktop.less
This makes the tool panel in the right panel scrollable. At first I tried to keep the panel title fixed, and only make the panel content area scrollable. But this caused several layouting issues, which would require more profound changes. Considering that *usually* the vertical space is sufficient, I would propose to go with this simple but effective solution. If wanted we can still improve it later.
Closes https://github.com/camptocamp/ngeo/issues/1738
=> Make tool panel scrollable in sidebar

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/examples/search.html, contribs/gmf/less/desktop.less, contribs/gmf/less/mobile-nav.less, contribs/gmf/less/search.less, contribs/gmf/less/searchmobile.less, contribs/gmf/src/directives/partials/search.html, contribs/gmf/src/directives/search.js, examples/search.js
This PR fixes the CSS class name for the search tool.  Changes are made in the examples, directives, templates and applications.  See #1680.  Note that this is one among many PR that will come to fix #1680.
* https://adube.github.io/ngeo/1680-css-fix-search/examples/contribs/gmf/search.html
* https://adube.github.io/ngeo/1680-css-fix-search/examples/contribs/gmf/apps/desktop/
* https://adube.github.io/ngeo/1680-css-fix-search/examples/contribs/gmf/apps/desktop_alt/
* https://adube.github.io/ngeo/1680-css-fix-search/examples/contribs/gmf/apps/mobile/
=> #1680 - Fix CSS names of search tool

contribs/gmf/examples/datepicker.html, contribs/gmf/less/datepicker.less, contribs/gmf/src/services/wmstime.js, examples/datepicker.html, src/directives/partials/datepicker.html
This PR fixes the CSS class name for the ngeo datepicker directive.  Changes are made in the examples, directives, templates and applications.  See #1680.  Note that this is one among many PR that will come to fix #1680.
* (ngeo example) https://adube.github.io/ngeo/1680-css-fix-datepicker/examples/datepicker.html
* (gmf example) https://adube.github.io/ngeo/1680-css-fix-datepicker/examples/contribs/gmf/datepicker.html
=> #1680 - Fix CSS names of datepicker

contribs/gmf/examples/drawfeature.html, contribs/gmf/examples/featurestyle.html, contribs/gmf/examples/search.html, contribs/gmf/less/desktop.less, examples/colorpicker.html, src/directives/partials/colorpicker.html
This PR fixes the CSS class name for the ngeo colorpicker directive.  Changes are made in the examples, directives, templates and applications.  See #1680.  Note that this is one among many PR that will come to fix #1680.
*  https://adube.github.io/ngeo/1680-css-fix-colorpicker/examples/colorpicker.html
*  https://adube.github.io/ngeo/1680-css-fix-colorpicker/examples/contribs/gmf/drawfeature.html
=> #1680 - Fix CSS names of ngeo colorpicker

contribs/gmf/less/desktoplayertree.less, contribs/gmf/less/mobilelayertree.less, contribs/gmf/src/directives/partials/layertree.html, src/directives/sortable.js
This PR fixes the CSS class name for the ngeo sortable directive.  Changes are made in the examples, directives, templates and applications.  See #1680.  Note that this is one among many PR that will come to fix #1680.
* https://adube.github.io/ngeo/1680-css-fix-sortable/examples/contribs/gmf/apps/desktop_alt/index.html
=> #1680 - Fix CSS names of ngeo sortable

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/src/directives/search.js
Fix: #1764 
Example: https://ger-benjamin.github.io/ngeo/i18naddlayers/examples/contribs/gmf/apps/desktop_alt
Is that okay with this solution ?
I think it's good enough. We don't add new actions all day. If that become problematic with further dev, we can adapt the server part to add actions directly in english.
=> I18n search actions

contribs/gmf/examples/editfeatureselector.html
This PR fixes the edit feature selector example.  The list of layers was empty due to the changes of theme loading using the event.
Also, after logging in, we would normally need to reload the themes, but that's out of scope of this example (in my opinion) and would bring more complexity to it. A simple note about reloading the page after logging in is enough (again, in my opinion).
=> Fix editfeature selector example

contribs/gmf/examples/displayquerygrid.html, contribs/gmf/less/displayquerygrid.less, examples/grid.html, src/directives/grid.js, src/directives/partials/grid.html
This PR fixes the CSS class name for the ngeo grid directive.  Changes are made in the examples, directives, templates and applications.  See #1680.  Note that this is one among many PR that will come to fix #1680.
* https://adube.github.io/ngeo/1680-css-fix-grid/examples/grid.html
=> #1680 - Fix CSS names of ngeo grid

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/examples/backgroundlayerselector.html, contribs/gmf/examples/backgroundlayerselector.js, contribs/gmf/src/directives/backgroundlayerselector.js
Fixes #1791.  The `gmf-backgroundlayerselector` directive must use the `dimensions` options.  This PR fixes this in all 3 applications and in the example.
* (example) https://adube.github.io/ngeo/1791-fix-apps-bls/examples/contribs/gmf/backgroundlayerselector.html
* (app) https://adube.github.io/ngeo/1791-fix-apps-bls/examples/contribs/gmf/apps/desktop_alt/index.html
=> Fix #1791 - Background layer selector directive must use dimensions

contribs/gmf/apps/mobile/index.html, contribs/gmf/less/mobile-nav.less, contribs/gmf/less/mobilelayertree.less, contribs/gmf/src/controllers/abstractmobile.js, contribs/gmf/src/directives/mobilenav.js, contribs/gmf/src/directives/themeselector.js
This PR fixes the CSS class name for the gmf mobilenav directive and the navigation in general in the mobile application.  See #1680.
Just to clarify, here's the list of class names that are changed in this PR.
```
go-back              -->  gmf-mobile-nav-go-back
active               -->  gmf-mobile-nav-active
slide                -->  gmf-mobile-nav-slide
slide-out            -->  gmf-mobile-nav-slide-out
back                 -->  gmf-mobile-nav-back
nav-left             -->  gmf-mobile-nav-left
nav-right            -->  gmf-mobile-nav-right
nav-left-is-visible  -->  gmf-mobile-nav-left-is-visible
nav-right-is-visible -->  gmf-mobile-nav-right-is-visible
nav-trigger          -->  gmf-mobile-nav-trigger
nav-left-trigger     -->  gmf-mobile-nav-left-trigger
nav-right-trigger    --> …
```
=> #1680 - Fix CSS names of gmf mobile nav

contribs/gmf/src/directives/drawfeature.js, contribs/gmf/src/directives/editfeature.js
Fixes #1725.
With this pull request a right-click (or long press) on a feature when using the drawing or editing tools the propagation of the event is stopped. This helps preventing the contextual menu (with coordinates, elevation, etc...) to show up when a feature is right clicked.
In order to do that I had to use a different target for the event listener because it's not possible to stop propagation on the same element easily. Using `stopImmediatePropagation` is not possible here since we cannot make sure of the order in which the listeners are added.
Please review.
=> Make draw/edit context menu take precedence over contextual data

contribs/gmf/examples/editfeatureselector.html, contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/editfeatureselector.js, contribs/gmf/src/directives/partials/editfeatureselector.html
Fixes https://github.com/camptocamp/ngeo/issues/1740
In the `gmf-editfeatureselector` directive, when the "stop editing" button is click, if there are unsaved modifications then the `gmf-editfeature` directive takes care of showing the confirm modal.
* https://adube.github.io/ngeo/1740-unsaved-modifications-stop-editing/examples/contribs/gmf/editfeatureselector.html
=> Manage 'stop editing' with unsaved changes in gmf-editfeature

contribs/gmf/src/directives/partials/layertree.html, src/directives/partials/layertree.html
This PR makes the layer tree html templates easier to read by breaking very long lines into one per attribute within a node, if there's more than one.  Some space are also added above child nodes if the parent node has many children, again to improve readability.
Having more lines makes the files heavier, but that shouldn't matter since the templates get compiled in the end, on production.
=> Enhance readability of layertree html templates

contribs/gmf/examples/displayquerygrid.html, contribs/gmf/examples/displayquerywindow.html, contribs/gmf/examples/layertree.html, contribs/gmf/examples/print.html, contribs/gmf/less/desktoplayertree.less, contribs/gmf/less/layertree.less, contribs/gmf/src/directives/partials/layertree.html
This PR fixes the CSS class names for the gmf layertree directive.  Changes are made in every examples and applications figuring it and the html template itself.  **Important**: no changes were made to the JavaScript, i.e. to the controller itself because the layer tree is currently being refactored, as told by @ger-benjamin.  The other modifications were fine.
See #1680.  Note that this is one among many PR that will come to fix #1680.
Here's the list of class names that were **not changed** due to the fact that they are defined in the controller (i.e. in the .js file):
* `on`
* `off`
* `out-of-resolution`
* `indeterminate`
Those are all related to the 'state' of a node, which is controlled in the controller.  These can be changed **after** the refactoring is completed.  See #1814.
* …
=> #1680 - Fix CSS in gmf layertree

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html
Fixes #1781.  This PR adds the required configuration of the wfs permalink service to work properly in the gmf applications.
* https://adube.github.io/ngeo/1781-fix-apps-wfs-permalink/examples/contribs/gmf/apps/desktop_alt/index.html?wfs_layer=fuel&wfs_osm_id=1420918679&map_x=545278&map_y=148729&map_zoom=11&lang=fr&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions%2CExternal&baselayer_ref=map
=> Fix #1781 - Configure WFS permalink in gmf apps

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/less/displayquerygrid.less, contribs/gmf/less/profile.less
This PR fixes the CSS class name used in the `<body>` element of the desktop applications.  See #1680.  Note that this is one among many PR that will come to fix #1680.
No live updated required.
=> #1680 - Fix CSS class names in apps <body>

contribs/gmf/examples/contextualdata.html, contribs/gmf/less/contextualdata.less, contribs/gmf/src/directives/contextualdata.js
This PR fixes the CSS class name for the gmf contextualdata directive.  Changes are made in the example and and desktop application.  See #1680.  Note that this is one among many PR that will come to fix #1680.
* (example) https://adube.github.io/ngeo/1680-css-fix-contextualdata/examples/contribs/gmf/contextualdata.html
* (desktop app) https://adube.github.io/ngeo/1680-css-fix-contextualdata/examples/contribs/gmf/apps/desktop/index.html
=> #1680 - Fix CSS class name in gmf-contextualdata directive

contribs/gmf/examples/mouseposition.html, contribs/gmf/less/desktop.less, contribs/gmf/src/directives/mouseposition.js, contribs/gmf/src/directives/partials/mouseposition.html
This PR fixes the CSS class name for the gmf mouseposition directive.  Changes are made in the example and and desktop application.  See #1680.  Note that this is one among many PR that will come to fix #1680.
The use of an `id` within the directive is not a good practice.  If one wanted to have 2 maps with each their own mouse positions directive, then it wouldn't work because the directive appends the created control using the id of the element defined within the template.  That's not an issue for now, but this could be changed.
Instead of using the id in the CSS, the class name of the control itself is used.
* (example) https://adube.github.io/ngeo/1680-css-fix-mouseposition/examples/contribs/gmf/mouseposition.html
* (desktop app) …
=> #1680 - Fix CSS class name in gmf-mouseposition directive

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/less/desktop.less, contribs/gmf/src/directives/partials/elevationwidget.html
This PR fixes the CSS class name for the gmf elevation widget directive.  Changes are made in the desktop application and template of the directive.  See #1680.  Note that this is one among many PR that will come to fix #1680.
* (desktop app) https://adube.github.io/ngeo/1680-css-fix-elevation/examples/contribs/gmf/apps/desktop_alt/index.html
=> #1680 - Fix CSS in gmf elevation widget

contribs/gmf/src/directives/partials/share.html
This PR fixes the CSS class name for the gmf share directive.  See #1680.
The only class name unique to gmf is not actually used anywhere (no specific CSS definition in the example and apps).
=> #1680 - Fix CSS class names in gmf share

contribs/gmf/examples/drawfeature.html, contribs/gmf/examples/editfeatureselector.html, contribs/gmf/examples/mobilemeasure.html, contribs/gmf/examples/profile.html, contribs/gmf/less/desktop.less, contribs/gmf/less/mobile.less, contribs/gmf/src/directives/profile.js, examples/createfeature.html, examples/drawfeature.html, examples/measure.html, src/ol-ext/interaction/measure.js
This PR fixes the CSS class name for the ngeo measure interaction, more precisely the `tooltip` class names.  Changes are made in the example, applications and the interaction.  See #1680.  Note that this is one among many PR that will come to fix #1680.
* (ngeo example, draw a line)
* https://adube.github.io/ngeo/1680-css-fix-tooltip/examples/measure.html
* (gmf example, draw a line)
* https://adube.github.io/ngeo/1680-css-fix-tooltip/examples/contribs/gmf/drawfeature.html
* (gmf desktop_alt app, draw a line with the draw tools)
* https://adube.github.io/ngeo/1680-css-fix-tooltip/examples/contribs/gmf/apps/desktop_alt/index.html
=> #1680 - Fix CSS class names in ngeo measure interaction

contribs/gmf/examples/displayquerygrid.html, contribs/gmf/less/desktop.less, contribs/gmf/less/displayquerygrid.less, contribs/gmf/src/directives/partials/displayquerygrid.html
This PR fixes the CSS class name for the gmf displayquerygrid directive.  Changes are made in the example, desktop application and template.  See #1680.  Note that this is one among many PR that will come to fix #1680.
I also made trivial changes to the template to make it more easilly readable.
* (example) https://adube.github.io/ngeo/1680-css-fix-displayquerygrid/examples/contribs/gmf/displayquerygrid.html
* (desktop_alt app) https://adube.github.io/ngeo/1680-css-fix-displayquerygrid/examples/contribs/gmf/apps/desktop_alt/index.html
=> #1680 - Fix CSS class names in gmf displayquerygrid

contribs/gmf/examples/profile.html, contribs/gmf/less/profile.less, contribs/gmf/src/directives/partials/profile.html
This PR fixes the CSS class name for the gmf profile directive.  Changes are made in the example, applications and template.  See #1680.  Note that this is one among many PR that will come to fix #1680.
I also made trivial changes to the template to make it more easilly readable.
* (example) https://adube.github.io/ngeo/1680-css-fix-profile/examples/contribs/gmf/profile.html
* (desktop_alt app) https://adube.github.io/ngeo/1680-css-fix-profile/examples/contribs/gmf/apps/desktop_alt/index.html
=> #1680 - Fix CSS class names in gmf profile

contribs/gmf/less/timeslider.less, contribs/gmf/src/directives/partials/timeslider.html
This PR fixes the CSS class name for the gmf time-slider directive.  Changes are made in the applications and template of the directive.  See #1680.  Note that this is one among many PR that will come to fix #1680.
=> #1680 - Fix CSS class names in gmf time-slider

contribs/gmf/src/directives/partials/print.html, contribs/gmf/src/directives/print.js
This PR improves the readability of the gmf print directive html template.  The class name is also changed, but it's currently not used anywhere.  Finally, this PR also includes a missing `goog.require` for a missing dependency, which prevented the example from working in a dev environment.
=> Improve readability of print directive template

contribs/gmf/examples/displayquerywindow.html, contribs/gmf/examples/wfs-permalink.html, contribs/gmf/less/desktop.less, contribs/gmf/less/displayquerywindow.less, contribs/gmf/src/directives/partials/displayquerywindow.html
This PR fixes the CSS class name for the gmf displayquerywindow directive.  Changes are made in the example, desktop application and template.  See #1680.  Note that this is one among many PR that will come to fix #1680.
I also made trivial changes to the template to make it more easilly readable.
* ~~The demo server of GMF is currently returning errors when using the desktop app.  This needs to be investigated first.~~
* (example) https://adube.github.io/ngeo/1680-css-fix-displayquerywindow/examples/contribs/gmf/displayquerywindow.html
* (desktop app) https://adube.github.io/ngeo/1680-css-fix-displayquerywindow/examples/contribs/gmf/apps/desktop/index.html
=> #1680 - Fix CSS class names in gmf displayquerywindow

contribs/gmf/examples/backgroundlayerselector.html, contribs/gmf/less/map.less, contribs/gmf/src/directives/partials/backgroundlayerselector.html
This PR fixes the a CSS class name from the gmf backgroundlayerselector directive that had been forgotten in a previous one, i.e. the `active` one.  Changes are made in the example, desktop application and template.  See #1680.
* (example) https://adube.github.io/ngeo/1680-css-fix-bglayersel-active/examples/contribs/gmf/backgroundlayerselector.html
* (desktop app) https://adube.github.io/ngeo/1680-css-fix-bglayersel-active/examples/contribs/gmf/apps/desktop_alt/index.html
=> #1680 - Additionnal fix for CSS class names in gmf bglyr sel.

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/less/desktop.less, contribs/gmf/less/mobile.less
This PR fixes the a CSS class names defined in the 3 GMF applications.  See #1680.
The only class name I was unable to change is `overlay` in the mobile app.  I haven't found it in bootstrap and I'm not sure where it's coming from, but changing it to something else, i.e. `gmf-overlay` breaks the application.  I left it as is.
* (desktop app) https://adube.github.io/ngeo/1680-css-fix-gmf-apps/examples/contribs/gmf/apps/desktop/index.html
* (desktop_alt app) https://adube.github.io/ngeo/1680-css-fix-gmf-apps/examples/contribs/gmf/apps/desktop_alt/index.html
* (mobile app) https://adube.github.io/ngeo/1680-css-fix-gmf-apps/examples/contribs/gmf/apps/mobile/index.html
=> #1680 - Fix CSS class names in gmf applications

contribs/gmf/examples/themeselector.html, contribs/gmf/src/directives/partials/themeselector.html
This PR fixes the `active` CSS name defined in the `gmf-themeselector` directive.  It's not used in the applications and was not used in the example either, but since it's still somewhat a "feature" I added it in the example.
=> #1680 - Fix active CSS class name in gmf themeselector

contribs/gmf/less/displayquerygrid.less, examples/grid.html, src/directives/partials/grid.html
This PR fixes the `active` CSS class name in the `grid` directive, in ngeo.  See #1680.
* (example) https://adube.github.io/ngeo/1680-css-fix-grid-active/examples/grid.html
* (desktop app) https://adube.github.io/ngeo/1680-css-fix-grid-active/examples/contribs/gmf/apps/desktop_alt/index.html
=> #1680 - Fix active CSS class name in ngeo grid

contribs/gmf/src/directives/mouseposition.js, contribs/gmf/src/directives/partials/mouseposition.html
This PR fixes the mouse position directive in gmf to no longer use an `id` of the element where to render the mouse position control.  Instead, a CSS class name is used with the angular `$element` service.
* https://adube.github.io/ngeo/1841-mouseposition-id/examples/contribs/gmf/mouseposition.html
=> #1841 - Use class instead of id in MousePosition

contribs/gmf/less/displayquerywindow.less, contribs/gmf/src/directives/displayquerywindow.js
Fixes #1694.
Demo: https://pgiraud.github.io/ngeo/query_window_animation_flickr/examples/contribs/gmf/apps/mobile
=> Avoid text flickering in display query window

contribs/gmf/less/displayquerywindow.less, contribs/gmf/src/directives/partials/displayquerywindow.html
There were a regression introduced with this change https://github.com/camptocamp/ngeo/commit/867bf981ae3d7728e3697e5c369504c85c4b6b55#diff-df063e76ea0d193b20ec188cb6b50b55R68
The previous arrow never got inactive anymore.
With the current pull request, I simplify the way we handle inactivation of the arrows by using already existing bootstrap's classes. The benefit is also that the button is really disabled (not only visually).
Demo: https://pgiraud.github.io/ngeo/query_window_arrows/examples/contribs/gmf/apps/mobile/?baselayer_ref=asitvd.fond_gris&lang=fr&map_x=558817&map_y=156629&map_zoom=2&tree_groups=Layers
=> Fix prev/next inactive state

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/examples/themeselector.html, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/themeselector.js
=> Use the default_theme value from the login

contribs/gmf/src/controllers/abstract.js
Fixes #1780.  Before this fix, the abstract controller of the gmf applications was calling the loading of the background layer twice: first time upon initialization (with the reading of permalink), and a second (unwanted) time when the themes service triggers an event.  We do want to reload the bg layer on LOGIN or LOGOUT, but not on READY, which was the 2nd unwanted call that was overriding the first call that managed the permalink.
This PR doesn't currently have a live example yet due to #1807.
* https://adube.github.io/ngeo/1780-fix-permalink-bgmap/examples/contribs/gmf/apps/desktop_alt/index.html?baselayer_ref=asitvd.fond_couleur&lang=fr
=> Fix #1780 - Do not change bg layer on login READY

contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/editfeatureselector.js, contribs/gmf/src/directives/partials/editfeatureselector.html
This PR renames lots of inner properties inside the `gmf-editfeature` and `gmf-editfeatureselector` directives to prepare the ground for the introduction of the snapping.  There's not actual change to the logic here, only renaming.
=> Rename properties in editfeature selector direct. for incoming snapping

contribs/gmf/src/gmf.js, contribs/gmf/src/services/permalink.js, contribs/gmf/src/services/treemanager.js
This PR fixes the `gmf.TreeManager` service.
1. It was missing a require of the `ngeo.StateManager`
2. It is using the `gmf.PermalinkParam.TREE_GROUPS` constant but was not requiring the permalink service.  In the end, we can't do that because the permalink service already requires the tree manager as well and we would end up with a circular dependency.  To fix that, the constant `gmf.PermalinkParam` was moved to `gmf.js`.
I found this out while trying to view the theme selector example, which didn't work on dev.
* https://adube.github.io/ngeo/fix-treemanager/examples/contribs/gmf/themeselector.html
=> Fix treemanager missing require

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/src/controllers/abstract.js
Currently the editing button shows up on the interface and then disappears if user doesn't have any layer to edit.
Demo: https://pgiraud.github.io/ngeo/editing_startup/examples/contribs/gmf/apps/desktop
Please review.
=> Prevent editing button to briefly show up at startup

buildtools/cleanup-ghpages.py
When pushing branches to github pages, the `gh-pages` Makefile target also cleans up local repo by removing branches that are not in the remote repo (for example when they've been deleted).
Unfortunately we rely on a request on the github api which returns only a fragment of the branches list because of pagination. This results in branches not being sent to gh-pages because the list is truncated.
With this pull request I make sure that at least 100 branches are supported.
Please review.
=> Handle more branches in gh-pages branches cleanup

src/services/query.js
This PR fixes the query service. When no queryable source is found, it doesn't launch new queries, which prevents the spinner to be shown indefinitively.
Fixes part 1 of #1786.
* https://adube.github.io/ngeo/1786-fix-query/examples/contribs/gmf/apps/desktop_alt/index.html?lang=en&map_x=560193&map_y=141696&map_zoom=7&tree_groups=OSM%20functions%20mixed&baselayer_ref=asitvd.fond_gris&tree_enable_osm_time_r_dp=false&tree_enable_osm_time_v_dp=false&tree_enable_osm_time_v_s=false&tree_enable_osm_time_r_s=false&tree_enable_osm_scale=true
=> #1786 - Prevent query to do request if no queryable source

contribs/gmf/src/services/treemanager.js
This PR adds a method to the treemanager to return the Layertree controllers kept as reference. The goal of this is to make possible to watch the array for newly added or removed elements.
=> Add public getTreeCtrlReferences method

contribs/gmf/examples/editfeatureselector.html, contribs/gmf/examples/editfeatureselector.js, contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/editfeatureselector.js, contribs/gmf/src/directives/partials/editfeatureselector.html
This PR fixes the editing tools, i.e. the `gmf-editfeature` and `gmf-editfeatureselector`.
Requires #1874 and #1870.
=> Fix editfeature and selector directives for LayerTree refactoring

contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/services/syncLayertreeMap.js, contribs/gmf/test/spec/services/syncLayertreeMap.spec.js
This PR fixes how the OpenLayers layer is obtained in the `gmf-editfeature` directive.  It used to only check the parent treeCtrl, but the layer may be in a higher level group (i.e. if we have groups inside groups).
To fix this, a new static method has been added to the gmf layertree controller.  It can be used to find a layer object from a ngeo treeCtrl that has a leaf as node (because I think it only makes sense to work from leaves when you want to know the associated layer, you don't really care about the ol.layer.Group).
=> Fix editfeature dir. layer getting

src/directives/resizemap.js
In https://github.com/Geoportail-Luxembourg/geoportailv3/pull/1444 it was reported that the resize of the map doesn't work on some computers.
The following patch ensures that the map is correctly resized at least at the end of the animation.
Please review.
=> Make sure map is resized at the end of animation

.npmignore
This is required for projects that re-use the jsdoc tools of ngeo. Currently, the folder `jsdoc` is excluded in `.npmignore`, so it is not available when installing ngeo as normal npm package.
I would propose to remove `jsdoc` from  `.npmignore` so that the scripts can be re-used.
=> Include jsdoc folder in npm package

contribs/gmf/apps/desktop/index.html, contribs/gmf/src/directives/authenticationdirective.js, src/directives/createfeature.js, src/directives/measurearea.js
With this pull request, we add missing translations in the Login, Edit (& drawing), Profile tools.
This is partial fix for #1801. Still need work for the search field.
Please review.
=> Missing translations

contribs/gmf/less/displayquerywindow.less
Fixes #1855.
Please review.
Demo:
https://pgiraud.github.io/ngeo/query_window/examples/contribs/gmf/apps/mobile/?baselayer_ref=asitvd.fond_gris&lang=fr&map_x=552517&map_y=152879&map_zoom=2&rl_features=Fa(57v1-3bcEgC8w*9t!hH90s6*~n*Polygon%25201%27c*%2523DB4436%27a*0%27o*0.2%27m*false%27s*10%27k*1)&tree_groups=Layers&tree_group_layers_Layers=hospitals%2Csustenance%2Centertainment%2Cosm_time%2Cpost_office%2Cpolice%2Ccinema
=> Typo in css class name

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/externs/gmfx.js, contribs/gmf/src/services/permalink.js
Add a new options to gmfx.PermalinkOptions to deactivate to storage into the local storage.
The desktop_alt now uses this option.
=> Add an option to bypass the local storage

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/services/themesservice.js
`layer.name` was used but was never defined.
The layer param passed to the promise is an array of ol.layer.Base not GmfLayer
=> Use the label property to match the layer name

contribs/gmf/src/services/authenticationservice.js
fixes #1937 
set all the fields from the authentication service but only dispatch a `gmf.AuthenticationEventType.LOGIN` event if the username is defined.
=> Always set the gmfUser response

contribs/gmf/src/directives/search.js
Fix: #1941 
Example: https://ger-benjamin.github.io/ngeo/translateSearchPlaceholder/examples/contribs/gmf/apps/desktop_alt
=> Translate search placeholder

contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/editfeatureselector.js, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/themeselector.js, contribs/gmf/src/services/permalink.js, contribs/gmf/src/services/querymanager.js, contribs/gmf/src/services/share.js, contribs/gmf/src/services/snapping.js, contribs/gmf/src/services/syncLayertreeMap.js, contribs/gmf/src/services/thememanager.js, contribs/gmf/src/services/themesservice.js, contribs/gmf/src/services/treemanager.js
Fix:  #1931 
Example: https://ger-benjamin.github.io/ngeo/prefix_gmfthemes/apidoc/
That's a little strange that almost all gmfThemes.* are _class_ and not _type_ . I've should leave theme defined as _class_ because _type_ doesn't support the `@extend` tag / function (see apidoc and commit 2 to understand)
=> Prefix gmfthemes

src/services/print.js
Closes https://github.com/camptocamp/ngeo/issues/1966
With https://github.com/mapfish/mapfish-print/pull/468 this change is no longer required, but this avoids having to update MFP/GMF.
=> Fix printing rotated labels

contribs/gmf/apps/desktop_alt/index.html
Fix: #1967 
Example: https://ger-benjamin.github.io/ngeo/modal_disclaimer_for_desktop_alt/examples/contribs/gmf/apps/desktop_alt
(open theme osm, look at the disclaimer in a popup)
=> Display disclaimers in a modal in desktop_alt

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/themeselector.js, contribs/gmf/src/services/thememanager.js
Fix #1988 
Example: https://ger-benjamin.github.io/ngeo/already_loaded_theme/examples/contribs/gmf/apps/desktop_alt
=> Don't display 'already loaded' message for themes on startup

contribs/gmf/less/mobile.less
`position: initial` is not supported by Internet Explorer.
=> Don't use 'initial' for CSS position

contribs/gmf/examples/objectediting-hub.html, contribs/gmf/examples/objectediting-hub.js, contribs/gmf/src/services/objecteditingmanager.js, contribs/gmf/src/services/themesservice.js
This PR features a "Hub" example that will be the point of entry to open examples and applications that use the ObjectEditing tools.
**Note** For now, the example opens the authentication example.  This will be changed when we have an example featuring the ObjectEditing tools.
* https://adube.github.io/ngeo/oe-2600-hub-example/examples/contribs/gmf/objectediting-hub.html
=> #2600 - Add ObjectEditing Hub example

contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/partials/layertree.html, src/directives/sortable.js
Replace: #1948 
Fix: #1744 
Example: https://ger-benjamin.github.io/ngeo/layertree_order_delete/examples/contribs/gmf/apps/desktop_alt
(More explanation in the PR of pgiraud)
- The order is now done on the same object that the ng-repeat build the layertree (Group node of the root treeCtrl)
- There is now a callback function that is called after the move end of the sortable directive
- Via that, after move end, the gmf layertree update the treeCtrls order and layers from the map
Also, there is a problem with the permalink but it's not bound with this issue I think.
=> Layertree order delete

src/services/location.js, src/string.js, test/spec/services/location.spec.js
When using values like `6+,7a+` as fragment parameters, the values have to be url encoded/decoded.
=> Encode values for fragment parameters

contribs/gmf/src/services/querymanager.js, externs/ngeox.js, src/services/query.js
Fix: #1977
Example: https://ger-benjamin.github.io/ngeo/query_mapserver_groups/examples/contribs/gmf/apps/desktop/
(Before it takes only the first childlayer and tests if it's on the map. Now it does this check on the layer)
(2000th PR :tada:  )
=> Can query map server groups

.eslintrc, buildtools/mako_build.json, contribs/gmf/examples/objectediting.html, contribs/gmf/examples/objectediting.js, contribs/gmf/examples/objecteditinghub.js, contribs/gmf/src/directives/objectediting.js, contribs/gmf/src/directives/objecteditinggetwmsfeature.js, contribs/gmf/src/directives/objecteditingtools.js, contribs/gmf/src/directives/partials/objectediting.html, contribs/gmf/src/directives/partials/objecteditingtools.html, contribs/gmf/src/services/objecteditingmanager.js, contribs/gmf/src/services/objecteditingquery.js, contribs/gmf/src/services/permalink.js, externs/jsts.js, externs/ngeox.js, package.json, src/directives/createfeature.js, src/directives/createregularpolygonfromclick.js, src/ngeo.js, src/ol-ext/interaction/drawregularpolygonfromclick.js, src/services/featurehelper.js
This PR adds the `gmf-objectediting` and `gmf-objecteditingtools` directives, which includes all possible actions to do:
* action: save
* action: undo
* action: delete
* tool: draw/add
* tool: draw/delete
* tool: triangle
* tool: copy from
* tool: delete from
Additionnal features of this PR:
* show a confirmation message before closing the page if there are unsaved modifications.
* refresh the WMS layer after save or delete
* addition of the JSTS library
* support of Multi geometries in the feature helper
* addition of `ngeo.interaction.DrawRegularPolygonFromClick` interaction and `ngeo-drawregularpolygonfromclick` directive
The following features are not included in this PR.  They will come in separate PRs.
* Proper CSS styling of the tools
* Make the radius of the triangles configurable …
=> WIP ObjectEditing 2594 Tools

contribs/gmf/examples/objectediting.html, contribs/gmf/src/directives/objectediting.js
This PR introduces the 'undoing' of all modifications when deactivating the ObjectEditing directive.
=> ObjectEditing - Undo all changes on deactivation

contribs/gmf/src/directives/objectediting.js, contribs/gmf/src/directives/objecteditingtools.js, contribs/gmf/src/directives/partials/objectediting.html
This PR ensures that the list of querable layers is only visible when a tool that requires it is activated.
=> ObjectEditing - show list of queryable layers only when needed

contribs/gmf/src/directives/objectediting.js, externs/jsts.js
This PR adds the following validation in the ObjectEditing tools that use the 'DELETE' process type:
Before applying the `difference` operator using JSTS, check if the geometries intersect first.  If they don't, no need to apply the `difference`.  This avoids pushing changes of geometries that have no actual changes when deleting.
=> ObjectEditing - Check intersects b4 deleting

contribs/gmf/examples/objectediting.html, contribs/gmf/externs/gmfx.js, contribs/gmf/src/directives/objecteditingtools.js
This PR allows to configure the radius of the shapes created by the "draw regular polygon from click" directive within the `gmf-objecteditingtools` directive.
=> Add configurable options for oe-tools draw reg.poly.

Makefile, buildtools/templatecache.mako.js, requirements.txt
Python 2.7 glob does not support '**' which is used in the template cache mako file.
Switching to glob2 makes it work automagically.
=> Switch to glob2

contribs/gmf/examples/objecteditinghub.js, contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/services/objecteditingquery.js
This PR make use of the `metadata` available in the layer node (in the themes), to:
* create a list of only the editable layers in the object editing hub example, i.e. those that have the `identifierAttributeField` metadata.
* narrow down the list of queryable layers to only those that have the `copyable` metadata
=> ObjectEditing - use metadata for copyable and editable layers

contribs/gmf/apps/oeedit/index.html, contribs/gmf/apps/oeedit/js/controller.js, contribs/gmf/examples/objecteditinghub.js
This PR is a follow-up of #2037.  It adds the `gmf-objectediting` directive to the OEEdit applicaition.  The hub example is also updated to be able to load the app from there.
=> Add gmf-objectediting to OE application

contribs/gmf/src/directives/partials/print.html
This avoids the print service to be killed by users clicking several times in a row on the print buttons
Fixes #2055.
=> Disable print button while printing

src/ol-ext/format/featurehash.js
This PR fixes the `ngeo.format.FeatureHash` when used with features that have `null` or `undefined` property values.
My use-case is this: I'm using the `ol.format.GPX`, which does the following:
feature.set('extensionsNode_', undefined);
So, when attempting to use the featurehash format with features written by the gpx format, it fails because of this undefined property.
=> Do not write null & undefined values in FeatureHash format

src/services/popup.js
Add a new optional param to ` ngeo.Popup#setContent` to 'trust' the content passed to the function.
=> Optionally trust the content passed to the popup

examples/backgroundlayer.js, examples/backgroundlayerdropdown.js, examples/layerloading.js, examples/layerorder.js, examples/layervisibility.js
Related to: #2073
This reverts commit 72dbe4a097e666491b2b46bebd817ec239df96e1.
Seems that the servers was just down (sorry, I was in a hurry, and I'm too suspicious about http url now...)
But do we really want http url in our examples ? Someone know example served with https ?
=> Revert "use https for boundless and opengeo"

contribs/gmf/src/directives/objectediting.js, src/ol-ext/jstsexports.js
JSTS requires some symbols and properties from OpenLayers to work, i.e. the library uses objects and methods from the `ol.geom` namespace.  Nothing gets exported in the ngeo or gmf builds from ol.
This PR introduces a list of symbols and properties that are exported within a file, which gets included where JSTS is used.
Fixes #2066.
=> Export symbols and properties from ol required by JSTS

contribs/gmf/examples/objecteditinghub.html, contribs/gmf/examples/objecteditinghub.js
The ObjectEditing 'hub' example allows one to open either the example or the applications that feature the ObjectEditing tools.  When working on a dev environment, the path to the applications is `../apps`, but when hosted the path is `apps`.
This PR allows the hub example to work in both environments: hosted and dev.
=> ObjectEditing - Add all urls in hub example

src/ol-ext/jstsexports.js
This PR adds the messing properties required to be exported for JSTS to work properly.
=> Add missing OL deps for JSTS

externs/angular-gettext.js
Add missing optional scope parameter.
See https://angular-gettext.rocketeer.be/dev-guide/api/angular-gettext/
=> Fix signature for gettext#Catalog#getString

contribs/gmf/examples/displayquerygrid.js, contribs/gmf/examples/displayquerywindow.js, examples/backgroundlayer.js, examples/backgroundlayerdropdown.js, examples/bboxquery.js, examples/colorpicker.js, examples/layertree.js, examples/mapquery.js, examples/measure.js, examples/permalink.js, examples/scaleselector.js, examples/search.js
Simplify the examples by using:
```
controller: 'fooController as ctrl'
```
Instead of:
```
controller: 'fooController',
controllerAs: 'ctrl'
```
=> Don't use controllerAs in examples

externs/angular-gettext.js
Fix inconsistencies:
- getCurrentLanguage was missing in @typedef
- getString had 2 conflicting definitions
Amendment of #2088
=> Remove duplication in angular-gettext externs

contribs/gmf/src/directives/objectediting.js
This PR fixes the ObjectEditing directive when it attemps to insert a feature.  The geometry has to be MULTI.
=> ObjectEditing - Ensure multi-geometry on INSERT

contribs/gmf/src/directives/objectediting.js, contribs/gmf/src/directives/objecteditingtools.js, contribs/gmf/src/directives/partials/objectediting.html, contribs/gmf/src/directives/partials/objecteditingtools.html
This PR fixes the label of the ObjectEditing 'Delete From' tool, a.k.a 'Cut From'.  The label `Copy from` was previously shown by both 'Copy From' and 'Delete From' tools.
=> ObjectEditing - Show 'Cut from' label when tool is active

contribs/gmf/src/directives/partials/editfeature.html, src/directives/createfeature.js
This fixes #2084.
The idea is to ensure that the drawn geometry is multi if the geometry type (as defined in the .xsd) is multi as well.
=> Add support for multi geometries

contribs/gmf/src/services/syncLayertreeMap.js
When the first child is checked and there exist another child which
is not checked, the parent was incorrectly checked instead of being
indeterminate.
To avoid this, the parent state is always refreshed.
The root cause is that state management is done too early, when the
layertree controller hierarchy is instanciated.
A more involved fix would be to:
- stop initializing layertrees in their constructors;
- have layertrees register a ready listener on the root layertree;
- have the root layertree triggers an onReady event in its postLink
function.
=> Fix layertree parent state

contribs/gmf/src/services/objecteditingquery.js
This PR fixes the list of copyables layers in the ObjectEditing tools that have 'undefined' values when using minimized code.
* https://adube.github.io/ngeo/oe-layers-list-undefined/examples/contribs/gmf/objecteditinghub.html
=> ObjectEditing - Fix list of copyable layers with undefined values

contribs/gmf/src/directives/objectediting.js, src/directives/createfeature.js, src/utils.js
Fixes #2125
Instead of fixing the closure compile issues due to the fact that `getCoordinates` is not available for `ol.geom.SimpleGeometry` in the code I recently added, I decided to use the utility used in the object editing functionality after moving into ngeo core code.
Please review.
=> Add an utility method to convert geom to multi

buildtools/mako_build.json, examples/locationsearch.html, examples/locationsearch.js, examples/search.js, externs/geo-admin-api.js, options/ngeox.js, src/modules/search/creategeojsonbloodhound.js, src/modules/search/createlocationsearchbloodhound.js, src/modules/search/searchmodule.js, test/spec/beforeeach.js, test/spec/data/geoAdminLocationSearch.js, test/spec/modules/search/createlocationsearchbloodhound.spec.js
This PR proposes to add a service for the [GeoAdmin location search](http://api3.geo.admin.ch/services/sdiservices.html#search) which creates a Bloodhound object that parses the response from the location service and creates features (similar to the `createGeoJSONBloodhound` service).
=> Add Bloodhound service for GeoAdmin location search

contribs/gmf/src/directives/objectediting.js
After inserting a new feature in the ObjectEditing tool, the id returned in the JSON was not stored in the existing feature.  Therefore, further actions were not working because they require the id.
This fixes this issue.
=> ObjectEditing - Fix save requests after insert

contribs/gmf/examples/print.html, contribs/gmf/examples/print.js, contribs/gmf/src/directives/print.js
Fix #2141 + example of the attribute `gmf-print-fieldvalues` (in the example page)
Example: https://ger-benjamin.github.io/ngeo/print_values/examples/contribs/gmf/apps/desktop_alt/
=> Better management of print field values

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/services/treemanager.js
Fix: https://github.com/camptocamp/ngeo/issues/2111
Example: https://ger-benjamin.github.io/ngeo/layertree_login/examples/contribs/gmf/apps/desktop_alt
We lost the opacity information for now (a `fixme` is in the code). That's more complicated to handle (because the info is, and should be set, in the layer and not in the layertree or the node's metadata).
We can do that on demand in a second time.
=> Refresh layertree on login

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html
See #2082 
Improve touch support in desktop and desktop_alt
demo: https://camptocamp.github.io/ngeo/desktop_viewport/examples/contribs/gmf/apps/desktop
=> Add viewport meta in desktop and desktop_alt

src/directives/colorpicker.js
The `colorPicker` directive didn't take the input colors array.
=> Fix colorpicker colors array input binding.

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/oeedit/index.html, contribs/gmf/apps/oeview/index.html, contribs/gmf/examples/profile.html, contribs/gmf/examples/profile.js, contribs/gmf/src/directives/profile.js, contribs/gmf/test/spec/directives/profile.spec.js, src/services/download.js, src/utils.js
There are several issues with the file download on Safari, see https://github.com/eligrey/FileSaver.js/issues/12. The latest Safari Tech Preview fixes these issues, but as long as no official release is available, it would be good to have a work-around.
The first commit addresses the problem that Safari is not able to start a download for files with a mime-type other than `text/plain`. So, when using Safari, the mime-type is set to `text/plain` (instead of the mime-type for csv/kml/gpx). This will open the file in a new tab and the user can download with `File -> Save as`. Not optimal, but as least the user can get the data.
The second commit deals with the problem that on Safari a download can only be started within 1000ms in the event handler of a *trusted event* (an event generated by …
=> Work-around for download on Safari

src/services/statemanager.js
Fix: #2173
Get item from local storage like before (https://github.com/camptocamp/ngeo/commit/af0891365becb9ae73a7cb2450f75901c490b358#diff-bfba152385d92f4e01dc75880a5122f5L58)
(https://docs.angularjs.org/api/ng/function/angular.fromJson)
=> Remove quote in url

src/modules/import/importlocal.js, src/modules/import/importonline.js, src/modules/import/partials/import-local.html, src/modules/import/partials/import-online.html
This PR replace uses of `gettextCatalog` by `gettext` to fix the translation and also remove use of tranlsate filter when it's unneeded.
=> Fix translations

contribs/gmf/examples/filterselector.html, contribs/gmf/examples/filterselector.js, contribs/gmf/src/directives/filterselector.js, contribs/gmf/src/directives/partials/filterselector.html, contribs/gmf/src/services/datasourcesmanager.js, options/ngeox.js, src/datasource.js, src/directives/layertree.js, src/services/datasources.js
This PR introduces the `ngeo.DataSource` object, which will be used as base for anything that wants to get information about specific data sources, such as: which ones are queryable, how can they be queried, etc.
This PR introduces the `gmf.DataSourcesManager` service, which is hooked to the theme and treeManager services in order to create and add the `ngeo.DataSource` objects from the themes.  The treeManager is used to synchronize the `visible` property, i.e. when the treeCtrl state becomes "on", the visibility of the data source is set.
Finally, this PR introduces an example in which the manager is injected for the data sources to be created.  It also includes the `gmf.FilterSelector` directive, which doesn't currently do anything.  It will do something in further pull requests.
=> Filter - Add ngeo.DataSource & gmf.FilterSelector example and directive

contribs/gmf/less/fullscreenpopup.less, contribs/gmf/options/gmfx.js, contribs/gmf/src/controllers/abstract.js
Fix: #2195 
Example: https://testgmf.sig.cloud.camptocamp.net/bge (theme OSM .> layer OSM open -> select a dot -> click on the "Open" link -> the popup open (with some css errors (out of ngeo project)))
Add static functions `gmf.OpenTextPopup` and `gmf.OpenIframePopup`
\+ add some imporvement in the (unused) css for fullscreenpopup
=> Add static function to open popup

contribs/gmf/examples/filterselector.js, contribs/gmf/src/services/datasourcesmanager.js, options/ngeox.js, src/datasource.js, src/directives/map.js, src/services/datasources.js, src/services/syncDataSourcesMap.js
This PR introduces the `ìnRange` dynamic property within the `ngeo.DataSource` object.
It is a dynamic property, i.e. its value can change and be watched.
The value is calculated every time the map view resolution changes and uses the `maxResolution` and `minResolution` properties.  This is not directly managed within the `ngeo.DataSource` object, but inside a `ngeo.SyncDataSourcesMap` service in order to listen only once for each change of resolution.  That service is injected in the `ngeo.Map` directive.
=> Filter - Add and synchronize ngeo.DataSource inRange property

contribs/gmf/examples/displayquerygrid.js, contribs/gmf/examples/displayquerywindow.html, contribs/gmf/examples/displayquerywindow.js, contribs/gmf/examples/filterselector.html, contribs/gmf/examples/filterselector.js, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/displayquerygrid.js, contribs/gmf/src/directives/displayquerywindow.js, contribs/gmf/src/services/objecteditingquery.js, examples/bboxquery.js, examples/mapquery.js, options/ngeox.js, src/datasource.js, src/directives/bboxquery.js, src/directives/mapquery.js, src/services/datasourceshelper.js, src/services/mapquerent.js, src/services/querent.js, src/services/query.js, src/services/wfspermalink.js
**Work in progress**
This PR introduces replacement for the `ngeo.Query` service.  Their replacements are:
* `ngeo.Querent` - a service that issues WMS GetFeatureInfo and/or WFS GetFeature queries through promises. It doesn't store the result.  It uses a list of `ngeo.DataSource` as point of entry to do its requests.  It supports combining requests when data sources use the same url.
* `ngeo.MapQuerent` - the direct equivalent of the `ngeo.Query` service, but it uses the `ngeo.Querent` to issue queries.
All directives, services, examples and app controllers are updated in this PR to use these new components instead of the `ngeo.Query`.
The structure of the `ngeo.QueryResult` is the same as before.  It is defined in the `ngeo.MapQuerent` service. The only difference is that the sources are …
=> Replace the 'query' service for the 'querent' and 'mapquerent'

contribs/gmf/examples/displayquerygrid.html, contribs/gmf/examples/displayquerygrid.js, options/ngeox.js, src/services/mapquerent.js, src/services/querent.js
This PR introduces the concept of doing "count" requests before WFS GetFeature requests, as supported in the current query service.
The `ngeo.Querent` is responsible of doing the requests.  The `ngeo.MapQuerent` reads what's returned and use it in the result.
=> Filter query count first

contribs/gmf/src/services/datasourcesmanager.js, options/ngeox.js, src/datasource.js, src/services/querent.js
**Work in progress**
This PR adds the `dimensions` to the data sources and use them in the `ngeo.Querent`.
There's nothing responsible of updating the `activeDimensions` (yet).
=> Support dimensions in data sources and querent service

contribs/gmf/src/directives/filterselector.js, contribs/gmf/src/directives/partials/filterselector.html
This PR introduces a dropdown list of "filtrable" data sources within the `ngeo.FilterSelector` directive (component).
Important note: the GMF server is not yet ready and doesn't have any information about the filtrable layers yet.  For now, the queryable data sources are used instead.  I can't go much further for now...
=> Filter - Add list of filtrable data sources to filterselector directive

contribs/gmf/examples/filterselector.html, contribs/gmf/examples/filterselector.js, contribs/gmf/options/gmfx.js, contribs/gmf/src/directives/filterselector.js
This PR is the follow-up of #2283.  It ensures that the data sources that are filtrables are added in the `gmf.FilterSelector` directive (component).  For that, the `gmf.User` service is used, from where the `filtrable_layers` are obtained in the `functionnalities`.  In other words, you need to be logged in to use the filter tool.
Once the tool is activated AND the list of filtrable layers are available, that's where the data sources are registered and added to the list.
=> Use gmfUser to populate filtrable data sources in gmf.FilterSelector

contribs/gmf/src/directives/filterselector.js
This PR allows the list of filtrable data sources to be filled upon loading the page and if we are not connected.  The 'anonymous' user can contain functionnalities, therefore can contain filtrable layers.
**Note**: This works, but only when loading the page.  If you log in with a user, then log out you're not as the 'anonymous' user thereafter and no filtrable layers are there.  If this is an issue, this should be addressed in an other PR as this is out of scope of the Filter project.
=> Filter - Allow anonymous filtering

src/ol-ext/wfsdescribefeaturetype.js
ping @adube 
The structure returned by a `read` is something like:
```json
{
"element": [{
"name": "foo",
"type": "fooType",
"substitutionGroup": "gml:AbstractFeature"
}, {
"name": "bar",
"type": "barType",
"substitutionGroup": "gml:AbstractFeature"
}],
"complexType": [{
"name": "fooType",
"complexContent": [{
"name": "THE_GEOM",
"type": "gml:PointPropertyType",
"minOccurs": "0",
"maxOccurs": "1"
}, {
"name": "display_name",
"minOccurs": "0",
"type": "string"
}]
}, {
"name": "barType",
"complexContent": [{
"name": "ref_id",
"minOccurs": "0",
"type": "long"
}]
}]
}
```
=> [wip] Add ol.format.WFSDescribeFeatureType

contribs/gmf/examples/filterselector.html, contribs/gmf/examples/filterselector.js, contribs/gmf/externs/gmf-themes.js, contribs/gmf/options/gmfx.js, contribs/gmf/src/datasource.js, contribs/gmf/src/directives/filterselector.js, contribs/gmf/src/directives/partials/filterselector.html, contribs/gmf/src/services/datasourcehelper.js, contribs/gmf/src/services/datasourcesmanager.js, contribs/gmf/src/services/enumerateattribute.js, options/ngeox.js, src/attribute.js, src/datasource.js, src/ngeo.js, src/ol-ext/format/wfsattribute.js, src/ol-ext/format/xsdattribute.js, src/ol-ext/wfsdescribefeaturetype.js, src/services/datasourceshelper.js, src/services/querent.js
This PR ensures that a data source is ready for filtering when being selected in the `gmf.FilterSelector` directive.
It features:
* the addition of the `gmf.DataSource` to allow the gmfThemes.Layer to be referenced in the data source and access some meta data
* the addition of a `gmf.DataSourcesHelper` service to be able to asynchronously fetch:
* the attributes (using the ngeo.Querent service and a WFS DescribeFeatureType request)
* the values of an attribute listed in the `EnumeratedAttribute` metadata
Once ready, the data source is set in a `readyDataSource` property in the `gmf.FilterSelector`.  The next step will be to sync that data source with the upcoming `ngeo.Filter` directive.
=> Filter - Prepare data source for filtering

contribs/gmf/examples/filterselector.html, contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/directives/filterselector.js, contribs/gmf/src/directives/partials/filterselector.html, options/ngeox.js, src/datasource.js, src/directives/filter.js, src/directives/partials/filter.html, src/ngeo.js, src/rule/rule.js, src/rule/select.js, src/rule/text.js, src/services/rulehelper.js
This PR introduces:
* the `ngeo-filter` directive (component), which is responsible of listing the rules to apply to a data source in order to do filtering on it.
* the `ngeo.rule.*` classes, which are the objects that define a filter rule
Here are the things that won't be managed in the PR:
* geometry rules
* `ngeo-rule` directive (component) --> that's the next PR I'll be working on.
=> Add ngeo-filter component and rule classes

contribs/gmf/examples/filterselector.html, contribs/gmf/examples/filterselector.js, contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/directives/filterselector.js, contribs/gmf/src/directives/partials/filterselector.html, contribs/gmf/src/services/datasourcehelper.js, src/directives/filter.js, src/directives/partials/filter.html, src/directives/partials/rule.html, src/directives/rule.js, src/rule/rule.js, src/services/datasourceshelper.js, src/services/rulehelper.js
This PR introduces the `ngeo-rule` component, which is used to set the value of a rule.  It is used by the `ngeo-filter` directive.
This PR includes:
* support of `text` rule type
* support of `select` rule type
* rename metadata `EnumeratedAttributes` to `enumeratedAttributes`
* rename metadata `DirectedFilterAttributes` to `directedFilterAttributes`
* support of removing custom rules
This PR doesn't include:
* support of `date` rule type (will come in the next PR)
* support of `geometry` rule type
Please note that I decided to go with always using "apply" and "cancel" buttons  and prevent the closing of the drop-down menu with click outs.  I did this to allow the `active` property of the `ngeo-rule` component to be toggled on while the drop-down menu is shown, which is also linked to a …
=> Filter - Create rule component, support 'text' and 'select' types

contribs/gmf/src/controllers/abstractmobile.js, src/directives/mobilegeolocation.js
If no zoom level is provided in th configuration, use the accuracy circle.
fixes #2388
=> Use the accuracy circle to recenter the view

src/attribute.js
This PR allows the support of GML 3.2 geometry types, such as `Surface` and `Curve`.
=> Support GML 3.2 geometry types in attributes definition

contribs/gmf/examples/filterselector.html, src/directives/partials/rule.html, src/directives/rule.js
This PR adds the support of filter rules using a date.  For that purpose, the `ngeo-date-picker` directive is used.
The datepicker can't have its values set other by itself.  That's contrary to the other types of rules, i.e. a text rule can have its value input to something, then the user clicks 'cancel' and the menu is closed and value reverted.  That can't happen with the date picker.  However, it's possible to create a date picker giving it initial values.  For that reason, the date picker directive is created every time the menu of a rule is opened and destroyed on close.  This allow the control of the value to set.
Also, please note the following important things:
* when using a date range, the "upperValue" is equal to "today" by default.
* when using a date rante, the "lowerValue" …
=> Filter - Support date rule

contribs/gmf/examples/filterselector.html, contribs/gmf/src/directives/filterselector.js, contribs/gmf/src/directives/partials/filterselector.html, options/ngeox.js, src/directives/drawfeature.js, src/directives/filter.js, src/directives/partials/filter.html, src/directives/partials/rule.html, src/directives/rule.js, src/rule/geometry.js, src/rule/rule.js, src/rule/select.js, src/rule/text.js, src/services/featurehelper.js, src/services/rulehelper.js
This PR adds the support of spatial rules to the `ngeo-rule` directive.
It also changes the way a rule is activated. Now, an `active` property exists within the `ngeo.rule.Rule` class to manage the activation. This allows the parent directive, `ngeo-filter`, to deactivate a rule before removing it.
Upon activating a geometry rule, an operator is immediately selected and the draw tools are shown.  The user can change the operator using the list and the draw tools are updated accordingly.
When a draw tool is clicked, the operator list is deactivated.  The user can then draw on the map. When the drawing is completed, the tool is deactivated and the geometry can be immediately modified.
Even when deactivated, the feature stays on the map.
Also, the `ngeo.rule.Geometry` object has been …
=> Filter - Support spatial rule

contribs/gmf/src/services/permalink.js
Fix https://github.com/camptocamp/ngeo/issues/2381
=> Return null if x,y or z in NaN

contribs/gmf/less/displayquerywindow.less
=> Remove white space when no identifier attribute

contribs/gmf/src/services/permalink.js
Fix: #2386
In my change, I take the groups from the url, not from the local storage.
So if you use an url without groups, we don't load groups defined in the local storage.
=> Don't use local storage if theme has changed and no groups in permalink

contribs/gmf/examples/filterselector.html, contribs/gmf/src/directives/filterselector.js, contribs/gmf/src/directives/partials/filterselector.html, contribs/gmf/src/services/savedfilters.js, options/ngeox.js, src/directives/filter.js, src/directives/partials/filter.html, src/directives/partials/rule.html, src/directives/rule.js, src/rule/geometry.js, src/services/rulehelper.js
This PR introduces the saving of filters in the local storage.
The `gmf.SavedFilters` is a new service responsible of:
* storing a list of saved filter items locally
* storing a list of saved filters for a particular 'active' data source, i.e. it's built using the above list items that have an id equal to the current active data source.
* saving the items in the local storage
The service is injected in the `gmf-filterselector` component to be able to have the list of items bound to a single data source.  The component has 2 new items added: a drop-down list of the items and a save button.
When saving, we check if there's an item that has the same name for the given active data source first.  If that's the case, an confirmation to overwrite the previous one is prompted.  Otherwise, the …
=> Filter - Support saved filters

contribs/gmf/src/services/querymanager.js, contribs/gmf/test/spec/services/querymanager.spec.js, examples/bboxquery.js, examples/mapquery.js, options/ngeox.js, src/services/query.js, test/spec/services/query.spec.js
=> Query the layer only on when he is visible

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/less/desktop.less, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/filterselector.js, contribs/gmf/src/directives/partials/filterselector.html, src/directives/filter.js, src/directives/partials/filter.html, src/directives/partials/rule.html, src/directives/rule.js
Add the filter tool in the `desktop` and `desktop_all` applications.
Fixes are made to adjust the CSS styling accordingly as well.
* https://adube.github.io/ngeo/filter-add-in-apps/examples/contribs/gmf/apps/desktop_alt/
How to test the live example:
1. Use the "Clear all" button to remove all layers
1. Add the "Filters" theme
1. Open the filter tool on the right
1. Select a layer
From there on, you can test the UI accordingly.  The only thing that currently does nothing is the "apply" button.
=> Add Filter in desktop apps

contribs/gmf/src/directives/filterselector.js
This PR fixes the FilterSelector component.  When deactivated, the selected data source is set back to `null`.
=> Filter fix activate

contribs/gmf/src/directives/filterselector.js, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/partials/filterselector.html, contribs/gmf/src/directives/partials/layertree.html, contribs/gmf/src/services/datasourcebeingfiltered.js, options/ngeox.js, src/datasource.js
This PR introduces the possibility to activate the filter tool from the layer tree, from a particular layer.
It also introduces the `filtrable` property of the `ngeo.DataSource` object, which is calculated by the `gmf.FilterSelector` directive once, then re-used "as-is" thereafter when trying to determine if a data source if filtrable or not.
That same `filtrable` property is from now on watched by the layer tree as well to add the `Filter` link in the dropdown menu.
A `gmf.DataSourceBeingFiltered` angular value service has been created to hold the data source currently being filtrered.
* https://adube.github.io/ngeo/filter-from-layertree/examples/contribs/gmf/apps/desktop_alt/
=> Filter - Activate from layer tree

contribs/gmf/less/desktoplayertree.less
To avoid the flickering effect when collapsing layer tree items.
=> Remove padding from collapsed items

contribs/gmf/src/services/editfeature.js
This fixes a regression introduced in the [Don't use goog.uri anymore](https://github.com/camptocamp/ngeo/commit/f41d24686ce7ea7a6d880544ed73a994a47a6c9c#diff-884a73f388e9658f99da80f09af55ff5L51) task.  The use of parameters was replaced by `/`, but that's invalid.
=> Fix gmf.EditFeature#getFeaturesInExtent, use ol.uri.appendParams

.eslintrc.yaml, buildtools/mako_build.json, contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/less/desktop.less, contribs/gmf/src/controllers/abstractdesktop.js, examples/googlestreetview.html, examples/googlestreetview.js, externs/google_maps_api_v3_27.js, src/directives/googlestreetview.js, src/directives/partials/googlestreetview.html
This PR introduces the `ngeo-googlestreetview` component.  It features:
* a new ngeo example with the component in it
* the addition of the component to the **desktop** and **desktop_alt** GMF applications.
Please note that this introduces a requirement to both these apps: Google Maps API.
* https://adube.github.io/ngeo/google-street-view/examples/googlestreetview.html
=> Add Google Street View component

contribs/gmf/less/displayquerywindow.less
it prevents the font-size to be changed with:
```css
.gmf-displayquerywindow-container {
font-size: 12px;
}
```
=> Remove unneeded font-size on query window

contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/objecteditingtools.js, examples/createfeature.js, src/directives/createfeature.js
In the [Upgrades for Angular 1.6](784c025fe04c956c5d1df5c0571f5060013fd3bb) task, a bunch of changes were made, such as switching from directives to components.  For one of them, the `ngeo-createfeature`, the change was incompatible.  A component only support being declared as the element level, i.e. `<ngeo-createfeature>`, i.e. it doesn't support being declared using the attribute of an existing element`<div ngeo-createfeature>`.
The tool was made so that it supported being declared using attributes, making it not compatible with components.  The change that was made broke the tool.
This PR reverts that specific change for that tool only.
=> Fix CreateFeature - revert to being a directive

Makefile, Makefile_windows, github_versions
This reverts commit eeb36fe25d121cc4a0751153ef45fef832b048b3.
fixes #2526
=> Revert "Use the master version of angular externs"

options/ngeox.js, src/directives/partials/attributes.html, src/ngeo.js, src/ol-ext/format/xsdattribute.js
Fixes #2527 
This PR introduces:
* a new type of `ngeox.Attribute`: `boolean`
* a new property for the `ngeox.Attribute`: `numType`, which distincts how to render a number attribute.  The two current values are: `integer` and `float`.
* a new property for the `ngeox.Attribute`: `maxLength`
These changes are used in the `ngeo.Attributes` component, i.e. in the html template.  Only the text attribute support the "maxLength".  The boolean is rendered as a checkbox.  The "numType" is used to distinguish integers from floats accordingly, and are also both renderered as number input field.
**Note** This PR only changes the attributes that are used in the editing tools.  The ones used in the filter tools remain unchanged as they use WFS DescribeFeatureType requests to get the attributes.
=> Support more attribute types in editing
