camptocamp/ngeo

contribs/gmf/src/directives/displayquerywindow.js
And remove annoying acronym.
FIX #2567
We use `desktopIn` in js and `desktop` in partial => bug
I've remove the "In". (And what does it means ?  Integration ? Input ? Integer ? We have a compilation system to reduce our code, why using acronym ?)
=> Can use desktop displayQueryWindow

contribs/gmf/src/directives/objectediting.js
This patch fixes the regression introduced in https://github.com/camptocamp/ngeo/pull/2387/commits/114e05d2dba44bbfe8d7c957085f76cdf0cac1a9
The array `this.geometryChanges_` can have null values.  A null value occurs when the feature has no geometry, i.e. when a feature has no geometry yet in the ObjectEditing project.
=> ObjectEditing - Geometry changes can contain null values

src/ol-ext/format/featurehash.js, test/spec/ol-ext/format/featurehash.spec.js
FIX #2573 
Use accuracy of 0.1m instead of 1m. Like in cgxp: https://github.com/camptocamp/cgxp/blob/95ee7b5dbe9a49119d141e302047850787e623ae/core/src/script/CGXP/widgets/RedLiningPanel.js#L75
=> FeatureHash - Use same accuracy as in cgxp

src/services/rulehelper.js
Fixes #2574.
Instead of `NOT (A AND B)`, we now have `NOT (A OR B)`.
=> Filter - 'Not' condition should include an OR, not an AND

contribs/gmf/less/desktop.less
Fixes #2570.
Variable height for StreetView in desktop and desktop_alt applications.
=> StreetView - make 100% height in gmf desktop apps

src/directives/googlestreetview.js
Fixes #2571.
With this fix, changing the position of the panorama using the controls within it do will not attempt to re-calculate the nearest location thereafter.
=> StreetView - do not reposition if change comes from SV navigation

contribs/gmf/src/services/syncLayertreeMap.js, contribs/gmf/src/services/themesservice.js
The value is set but never read.
The editable nodes are now collected here:
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/editfeatureselector.js#L138-L141
=> Remove unused editableIds property

options/ngeox.js, src/datasource.js, src/rule/rule.js, src/services/querent.js
Referencing ngeo symbols adds a hard dependency on the referenced symbol, forcing applications using the library to pass extra js code to their invocation of the closure compiler.
=> Stop referencing ngeo symbols in ngeox.js

contribs/gmf/src/directives/authenticationdirective.js, src/directives/grid.js, src/directives/layertree.js, src/modules/import/importdnd.js, src/modules/import/importlocal.js, src/modules/import/importonline.js, src/modules/import/wmsgetcap.js, src/modules/import/wmsgetcapitem.js
They used boolean instead of string.
See [this comment](https://github.com/camptocamp/ngeo/pull/2543#discussion_r114507611) in #2543 for the original report.
=> Correct return type of some get template URL functions

contribs/gmf/apps/oeedit/index.html, contribs/gmf/apps/oeedit/less/main.less
- Removed panel when in query mode, because there is no content to display in there and it uses up valuable space.
- Closing edit mode panel switches state to the only other option, query mode.
- Query details window didn't handle long content well. Now it allows horizontal scrolling and is 50% wider, since there is more space available because the query mode doesn't have a panel any more.
=> UI adjustments to gmf oeedit app based on user feedback

contribs/gmf/less/mobile.less
Initially firefox mobile is using default border-radius for button when no value is provided.
This add a border-radius: 0 to all button uniformally to display the same result on all mobile browsers in the mobile homepage.
=> Mobile border-radius fix (add it to all buttons uniformally)

contribs/gmf/src/directives/objectediting.js, src/coordinate.js, src/geom.js
In the ObjectEditing tool, when using the 'copy' tool, WMS GetFeatureInfo requests are made to fetch the geometry of the features to copy.  The geometry read may contains "XYZ" coordinates.  When those are used to INSERT features using GMF, it fails.  GMF doesn't seem to like having "XYZ" coordinates.
This only occurs on INSERT for features that are copied, because otherwise there would only be "XY" coordinates.
This patch makes sure to convert any "XYZ" coordinates to "XY" just before we save.
=> ObjectEditing - Ensure 2D geometry

contribs/gmf/src/directives/search.js
Was using the gmf-search-maxzoom config and noticed that the value still always is 16.
=> FIX: Don't overwrite gmf-search-maxzoom if set

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/importhelper.js, options/ngeox.js, src/modules/import/file.js, src/modules/import/importmodule.js, src/modules/import/partials/wmts-get-cap-item.html, src/modules/import/partials/wmts-get-cap.html, src/modules/import/style/import.less, src/modules/import/style/owsgetcap.less, src/modules/import/style/owsgetcapitem.less, src/modules/import/wmtsgetcap.js, src/modules/import/wmtsgetcapitem.js
I have a working solution that looks good to me. However, I have an error I don't know how to correctly fix when I run `make check`:
```
node buildtools/build.js .build/examples/interactionbtngroup.json .build/examples/interactionbtngroup.js
info ol Parsing dependencies
ERR! Unsatisfied dependency "ol.source.WMTS.optionsFromCapabilities" in script: /home/jenselme/Work/forks/ngeo/src/modules/import/wmtsgetcap.js 
Makefile:346: recipe for target '.build/examples/interactionbtngroup.js' failed
make: *** [.build/examples/interactionbtngroup.js] Error 1
```
I require `ol.source.WMTS.optionsFromCapabilities` in [wmtsgetcap.js](https://github.com/Jenselme/ngeo/blob/wmts-import/src/modules/import/wmtsgetcap.js#L5) because I use it [here](https://github.com/Jenselme/ngeo/blob/wmts-import/src/module …
=> Add directive to import layers from a WMTS server

npm.mk
In Windows, `convert` is a system command. Moreover, in Windows, all ImageMagick commands are prefixed by `magick` in order not to be interpreted as a system command.
The current PR relies on a suggestion made by @sbrunner.
Please merge (if I manage to make Travis happy for once...)
=> Use magick convert if in Windows or Cygwin

src/modules/import/wmtsgetcap.js
If ngeo-wmts-get-cap-url is not present, capabilitiesUrl is undefined in the configuration of the layer.
Close #2622
=> Add an attribute to ngeo-wmts-get-cap to save capabilities URL

src/services/statemanager.js
=> Ignore the no_redirect patameter

.tx/config.mako, Makefile
GeoMapfish uses .tx/config.mako as is for the project it generates and those
projects must support more than de and fr.
Now, the languages are passed as a variable to the MAKO file.
=> Make translation targets configurable

contribs/gmf/src/directives/print.js
=> Switch to WMS layer in print

contribs/gmf/src/directives/objectediting.js, contribs/gmf/src/directives/partials/objectediting.html, src/geom.js
This PR fixes an issue that occured in the ObjectEditing tools.  When a user manually deletes the geometry of an existing feature, whether by using the "minus" or "scisors" buttons, clicking on "save" caused the server to fail because it was attempting to save with an empty geometry.
To prevent this, we add an additionnal condition to the save button.  It gets disabled automatically if the feature has no geometry at any point.  The user can still use the delete button to remove the feature, which doesn't use the empty geometry if the user had deleted it manually, and the request to delete it works.
=> ObjectEditing - Disable save button when feature has no geom

src/modules/import/wmtsgetcap.js
See https://github.com/camptocamp/ngeo/issues/2673
=> ServiceProvider is optional in WMTS GetCapabilities

options/ngeox.js, src/directives/rule.js, src/rule/date.js, src/rule/rule.js, src/services/rulehelper.js
Fixes #2679 
When using WFS, date filters need to use the proper type of operator.  The standard ones wont work, i.e. those with `property equals to`, `between`, etc. do not work.  We need to use temporal ones instead.
MapServer currently supports `During` only, so that's the one we'll use.
The fix is applied to the filter tool, when we're dealing with a date attribute.  We removed the `>`, `<` and `not` operators as they are not required / make less sense than just using `=`, `>=`, `<=`.
Since During always have a beginning and an end, we need to calculate their value when dealing with an operator other than "between".  For min value, we use `1970-01-01`.  For the max value, we add **30 years**.
https://adube.github.io/ngeo/2679-fix-date-filters/examples/contribs/gmf/filterselector.html?t …
=> #2679 - Fix date filters

contribs/gmf/apps/mobile/index.html
Currently we have a meta balise supporting chrome for android: 
`<meta name="mobile-web-app-capable" content="yes">`
I added the iOS supported meta balise to allow this feature on iOS:
`<meta name="apple-mobile-web-app-capable" content="yes">`
This allow to save the page on desk screen and open it in full-screen mode without the browser UI (navbar, etc.)
=> Enable fullscreen opening for iOS

contribs/gmf/src/services/datasourcesmanager.js, src/services/backgroundlayermgr.js
Fixes #2712.
In 2.2, the `ngeo.Query` service was changed to the `ngeo.Querent`:
* `ngeo.Query` - used to loop in the current map layers to find those that are queryable and issue requests from there
* `ngeo.Querent` - uses the `ngeo.DataSource` as way to fetch the queryable information and issue requests.
To be queryable, a data source:
* must be in the `ngeo.DataSources` collection
* must be visible
* must be queryable (property)
The data sources from the "overlay" layers are managed with the layer tree manager.  The background layer were **not** managed at all.
To fix this, the ngeo background layer manager was added to the data sources manager service.  On change, we get the current background layer, get its `querySourceIds` property (which happens to be the list of ids of the data …
=> Fix #2712 - Support background layers in query (regression fix)

contribs/gmf/src/directives/search.js
Fix the initialization of the `inputValue` and and `placeholder` properties in the `gmf.Search` directive.  Those must happen in the `$onInit` method.
=> Fix initialization of gmf.Search directive

contribs/gmf/src/controllers/abstract.js
Avoid error with AbstractController.updateHasEditableLayers_
that is called inside an event before it is created.
=> Create ctrl.updateHasEditableLayers_ before registering events.

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/oeedit/index.html, contribs/gmf/apps/oeview/index.html, contribs/gmf/examples/objecteditinghub.js, contribs/gmf/examples/themeselector.html, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/partials/themeselector.html, contribs/gmf/src/directives/themeselector.js, contribs/gmf/src/services/permalink.js, contribs/gmf/src/services/thememanager.js, contribs/gmf/test/spec/services/thememanager.spec.js
FIX #2714 
DEMO: https://testgmf.sig.cloud.camptocamp.net/bge_permalink
Be able to:
- Set a theme linked to a backgound layer (here theme cadastre is linked to background layer "Blank")
- Set the background layer again (like OSM)
- Refresh the page using the permalink and get the Theme with the second background (here theme "cadastre" with background layer "OSM")
Please, try to find a bug (I've changed some things in the theme manager).
Only the "mode flush" (theme manager) should be different that before.
=> Fix permalink background

Makefile, options/ngeox.js, src/services/rulehelper.js
Depending on actual types in ngeox.js is bad since it forces users of
ngeo to depend on the js files providing these types, even if they are
not used in their project.
To avoid this, use ngeox.rule.Rule instead of ngeo.rule.Rule and
ngeox.DataSource instead of ngeo.DataSource.
See c6d6e8fd9cef1e308073fd3c65441163ddb6e0b4.
=> Enforce ngeo.rule.Rule and ngeo.DataSource are not used in ngeox.js

contribs/gmf/src/services/authenticationservice.js
fixes https://github.com/camptocamp/c2cgeoportal/issues/2991
=> Remove trailing slash from authenticationBaseUrl

contribs/gmf/src/controllers/abstractdesktop.js
Fix #2756 
The current display will be 0 decimals (set in abstract controller) as default value. Then it can be overridden in project html or js files. I added the precision value as well as it wasn't set previously. Preview:
=> Set default decimals and precision values for drawing

contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/services/datasourcesmanager.js, options/ngeox.js, src/datasource.js, src/services/querent.js
This is an alternative to #2718, i.e. a fix for the use of the `dimensions` property within the querent service.
The dimensions are globally defined in the GMF abstract controller.  From there, the `gmf.DataSourcesManager` is injected and given the global dimensions, allowing it to give them to the created data sources.
Within a data source, we have:
* `globalDimensions`: property, is a reference to the global dimensions that come from 
* `innerDimensions`: property, the static dimensions that are unique for the data source
* `activeDimensions`: method, returns the "current" dimensions to use with the data source.  If a inner dimensions is defined with a `null` value, then the global dimensions is used.
Two data sources can be **combined** for a WMS or WFS query if they both have the …
=> Use 'dimensions' properly in querent service

contribs/gmf/src/directives/displayquerygrid.js
Fixes #2778
I added the extension to the startDownload function (on third parameter, for the filename) for displayquerygrid directive, as it is actually done with the same function used in the profile directive for csv export : https://github.com/camptocamp/ngeo/blob/868618f9ebdf2b1a0d68d07b23d6f3223be2ff1b/contribs/gmf/src/directives/profile.js#L704.
=> Add missing .csv extension for displayquerygrid csv export

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/search.js, contribs/gmf/src/services/fulltextsearch.js
Introduces two new parameters:
- **search**: (string) recenters map on first result of fulltext search
- **search-select-index**: (number) use nth result from search instead
If a feature is found, it gets added to the search input field. Clicking the X-button there deletes the feature from the feature-overlay.
`[APP-URL]/desktop/?search=Lausanne`
In the gmf demo app, this would center the map on "District de Lausanne" (district layer)
`[APP-URL]/desktop/?search=Lausanne&search-select-index=4`
In the gmf demo app, this would center the map on "Lausanne" (osm layer), the fourth result in the response of the fulltextsearch call.
- [technical] Is the search directive the right place to put this?
- ~[usability] Different name/behaviour for _search-offset_?~ Changed to **search-select-index**
- …
=> Search-parameter

contribs/gmf/less/desktop.less
Fixes #2786 
This fix add a CSS transition on width changes used by street-view panel. The transition is then listened by the resizeMap directive that will run the resize actions at the 'transitionend' event: https://github.com/camptocamp/ngeo/blob/f6c897e3ada535f9f483ba18f290b056d9387703/src/directives/resizemap.js#L62-L65
The current duration used is 0.01s because we don't want a animation to start and be visible, we just want to run the transition to make the resizeMap directive do his job on width changes.
=> resizeMap when switching from opened panels to street-view panel and vice-versa

.travis.yml
=> Use the latest version of node

contribs/gmf/src/directives/displayquerywindow.js, contribs/gmf/src/directives/partials/displayquerywindow.html, contribs/gmf/src/directives/swipe.js
https://jira.camptocamp.com/browse/GSGMF-12
=> Provide vertical swipe

contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/filterselector.js
This PR introduces the support of the two following GMF user "functionalities":
`"open_layer_filter_panel": ["true"]` - when defined, the filter panel is open upon loading a desktop application.
`"preset_layer_filter": ["inventaire_equipements"]` - when defined, the name of the layer (data source) automatically: 1) open the filter panel, 2) select the data source in the filter selector tool.
=> Support user functionalities to toggle the filter tool on upon init

contribs/gmf/less/base.less, contribs/gmf/less/desktop.less, contribs/gmf/less/displayquerywindow.less, contribs/gmf/src/directives/displayquerywindow.js, contribs/gmf/test/spec/directives/displayquerywindow.spec.js, src/directives/modal.js
- Fix issue with "share map" modal that was not resizeable
- Make query results window draggable and resizable
- Adapt styling of modals in gmf
See https://jira.camptocamp.com/browse/GSGMF-8
=> Fix move/resize issues and improve styling

contribs/gmf/src/services/permalink.js, contribs/gmf/test/spec/beforeeach.js, src/ngeo.js
Required by c2cgeoportal build on Docker
=> Adds some missing requires for annotations 

src/source/swisstopo.js
Cross origin is required for [forEachLayerAtPixel](https://openlayers.org/en/latest/apidoc/ol.Map.html#forEachLayerAtPixel) method, for example. Without that option user gets an error:
```
intermediatecanvas.js:140 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
at ol.renderer.canvas.TileLayer.ol.renderer.canvas.IntermediateCanvas.forEachLayerAtCoordinate (http://localhost:8180/build/ol/renderer/canvas/intermediatecanvas.js:140:44)
at ol.renderer.canvas.Map.forEachLayerAtPixel (http://localhost:8180/build/ol/renderer/canvas/map.js:207:30)
at ol.Map.forEachLayerAtPixel (http://localhost:8180/build/ol/map.js:627:25)
at ol.Map.hoverUnlistenKey_.map.on (http://localhost:8180/common/map/click.js:159:11)
at …
```
=> Add support for crossOrigin option

src/services/location.js
`replaceState` fails on some browser if the domain in the state is not the same as `location.origin`.
Ignore these errors
=> Ignore history.replaceState errors

contribs/gmf/src/directives/layertree.js
Apply global dimensions only if layer config value is null.
To be consitent with ngeo.datasource.
Replace #2819
=> Fix layertree dimensions precedence

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/oeedit/index.html, contribs/gmf/apps/oeview/index.html, contribs/gmf/src/directives/themeselector.js
When gmfThemeManager is not in flushMode, themeName remains equal to null.
So when not in flush mode replace "Theme:Loading..." by "Themes".
=> Fix theme selector title when not in flush mode.

jsdoc/template/tmpl/params.tmpl
Fix: #2848
The documentation is already better with that (type is now defined in directive and components).
But I still don't have links on documentation on the types.
To do that, I need to copy all the related content of "helper.registerLink" (like https://github.com/camptocamp/ngeo/blob/master/jsdoc/template/publish.js#L450-L461) in the "plugin" file.
It isn't a better way to do that ? Can't I have a "common" file ? Do you have any clue @sbrunner @gberaudo  ?
=> Type for directives and components

contribs/gmf/src/services/thememanager.js
Commit 1: needed by the layertree title (otherwise, it doesn't exist in the HTML so the value is always false)
Questions:
- It is useful in the mobile app ? https://github.com/camptocamp/ngeo/blob/2.2/contribs/gmf/apps/mobile/index.html#L177
- This line was switched, is there a reason for that ? (that make one change more in the ngeo.diff during an upgrade: https://github.com/camptocamp/ngeo/blob/2.2/contribs/gmf/apps/desktop/index.html#L303 (was at line 299)
=> Export modeFlush for layertree title

package.json
Using the git-protocol explicitly there has caused issues on multiple instances. This configuration change allows an automatic fall-back to https.
=> Switch to protocol-agnostic GitHub shortcut url

contribs/gmf/src/services/themesservice.js
The previous code rewrote the theme dimension rules at init time.
This was wrong since dynamic dimensions should be updated during the life of the application.
=> Do not freeze background dimensions on init

package.json
Using the git-protocol explicitly there has caused issues on multiple instances. This configuration change allows an automatic fall-back to https.
Same issue as #2875
=> Switch to protocol-agnostic GitHub shortcut url [2.2]

contribs/gmf/less/mobile-nav.less, contribs/gmf/less/mobile.less, contribs/gmf/less/search.less, contribs/gmf/less/searchmobile.less
=> searchtext icon overlaps placeholder on ipad

contribs/gmf/src/controllers/abstract.js
It looks like I made a mistake while rebasing this [pull request](https://github.com/camptocamp/ngeo/pull/2719).
There shouldn't be any changes to contribs/gmf/src/controllers/abstract.js
Can someone else verify if the search-param works as intended now?
=> Remove duplicate param handling

contribs/gmf/src/services/datasourcesmanager.js, src/services/datasources.js
Patch for 2.2.  Replaces #2882.
In GMF, OpenLayers layer objects can be created with the combinaison of multiple data sources.
In GMF, only one data source may be filtered at a time.
The issue was: when playing with the visibility of the data sources, i.e. using the layer tree when toggling on/off the layer source params LAYERS, if the change occured on an other data source that's within the layer, then the synchronization between the WMS parameter FILTER and LAYERS becomes broken.
This patch fixes this.
=> Fix Manage FILTER param in WMS request issue

src/directives/filter.js
Fixes #2927.
In the ngeo filter component, when using `getData`, only get data from the data source that is currently being filtered, not all currently visible data sources.
=> GetData on filtered data source only (2.2)

src/services/filters.js
The additional parameters are strings and have to be in quotes. Otherwise they are undefined and lead to unintended behaviour.
=> Examples of ngeoUnitPrefix filter do not work, missing quotes

src/directives/drawfeature.js
Was looking for usages of $compile to have an example. $compile gets injected but not used here.
I checked the history of the file, $compile was never used. Probably a leftover from development.
=> Remove unused import of $compile

contribs/gmf/src/directives/search.js, examples/search.js, src/modules/search/creategeojsonbloodhound.js, src/modules/search/createlocationsearchbloodhound.js
All definitions should be local to the provided symbol.
As such, a symbol ngeo.search.toto cannot define Toto in ngeo.search.
=> Fix definitions leaking outside of the provide

src/services/print.js, test/spec/services/print.spec.js
Default values in OpenLayers are 'center' and 'middle'.
fixes #2963
=> Set correct print labelAlign

contribs/gmf/less/layertree.less, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/directives/partials/layertree.html
FIX: #2950
Demo: (try with theme: Demo, layergroup "OSM function", layer "two_layers"): https://testgmf.sig.cloud.camptocamp.net/bge/theme/Demo?lang=en&tree_group_layers_Transport=fuel&baselayer_ref=OSM%20map&theme=Demo&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions%2CExternal%2CFilters%20mixed%2CFilters&tree_group_opacity_Group=0.65&tree_enable_osm_scale&tree_enable_osm_time_r_s&tree_enable_osm_time_v_s&tree_enable_osm_time_v_dp&tree_enable_osm_time_r_dp&tree_enable_osm_time_r_year_mounth&tree_enable_osm_time_d_year_mounth&tree_enable_osm_time_r_mounth_year&tree_enable_osm_time_v_mounth_year&tree_group_layers_Layers&tree_group_layers_OSM%20functions
With multiple layers on one ol layer:
QGISServer: GetLegendGraphic with `LAYER=layer1,layer2,...` (non-standard but …
=> Be able to get legend for multiple layers

externs/mapfish-print-v3.js
see:
https://mapfish.github.io/mapfish-print-doc/attributes.html#!datasource
=> Adding missing datasource attribute to mapfish-print externs

src/directives/scaleselector.js
Otherwise `$applyAsync` is called on every frame change (~60 / second)
=> Only update the scale value at the end of the zoom animation

src/services/print.js
The stroke and fill colors can also be strings.
=> Fix goog.asserts in ngeo.Print

src/services/filters.js
To avoid renaming by the closure-compiler
=> Add quotes arround $stateful property

contribs/gmf/less/desktoplayertree.less
Fixes #2978 
This was already in use with the mobile interface, as this interface had no style for this element. 
In most case no changes are visible as the layer names are usually shorter than the panel width. 
In the longest label length, the text will now wrap to the next line and the icon will still be at the right end of the label. This will allow this icon to be displayed regardless of the label.
=> Multi-line layer name in layer-tree, allow icons to diplay regardless of label length

contribs/gmf/apps/mobile_alt/index.html
Add the missing dependency in `mobile_alt` application to make it work again.
=> Add missing gmfLayersUrl in mobile_alt app

contribs/gmf/less/mobile.less
Make sure that the rotate button, on mobile devices, is white (not grey).
=> Fix rotate button on mobile devices

contribs/gmf/src/directives/displayquerygrid.js
=> Doc displayquerygrid ngClass in body element

contribs/gmf/apps/mobile/js/controller.js
Disable 'autorotate' on mobile app.  Keep it enabled on mobile_alt app.
Wait for #2995 to be merged first.
=> Disable autorotate on mobile app.

contribs/gmf/src/directives/search.js
Fitting the map used to ignore the map_zoom parameter. This is annoying when dealing with small features as results. Those will set the map to an unreasonable high zoom level.
This change uses map_zoom as maximum zoom level when fitting the map to the search result.
To test the feature:
`make build-gmf-apps examples-hosted-apps serve`
Then visit:
http://localhost:3000/.build/examples-hosted/contribs/gmf/apps/desktop_alt/?search=bettingen (defaults to map_zoom == 5 because of the feature size)
http://localhost:3000/.build/examples-hosted/contribs/gmf/apps/desktop_alt/?search=bettingen&map_zoom=3
The example data doesn't have very small features to search for, but this should show the functionality.
=> Preserve map_zoom setting when using search parameter

contribs/gmf/less/base.less, contribs/gmf/src/directives/displayquerywindow.js
Fix the min size the display query window.  Also, make sure to show the proper pointer cursor when hovered to tell that it can be dragged and show an other cursor while being dragged.
=> Fix display query window minimum size

src/directives/modal.js
This PR adds the `ngeo-modal-resizable` option to the modal directive. Default value is: `false`.
This changes the default behaviour of the modals, which could all be resized before.  However, it makes little sense to do so, as most of the times modals are used to show content from an "controlled" interface, i.e. content from other directives / components.  The content container of the modal (bootstrap) already manages to be bigger in height if it has lots of content, and show a scroll bar if necessary.
Making the modal resizable doesn't help anyway, as the whole container of the modal is resized, unnaffecting the header, footer and content. This results in having more "blank" space and nothing more.
=> Add resizable option to ngeo.Modal

contribs/gmf/src/directives/search.js
Addresses @fredj [feedback](https://github.com/camptocamp/ngeo/pull/3001#discussion_r145355559).
=> search parameter/map_zoom: Test for null to allow 0 as value

contribs/gmf/src/directives/print.js
The attribute did not match the name anymore:
`'hiddenAttributeNames': '=gmfPrintHiddenattributes',`
The [full example](https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/examples/print.html#L199) is correct.
=> Make example match actual attribute name

contribs/gmf/less/desktop.less
Fixes #3012 for pt.1 filter panel.
Just apply the same color for the separator in the panel, was already used with the heading separator.
=> Fix filter panel separators color

contribs/gmf/less/desktop.less, contribs/gmf/src/directives/partials/drawfeature.html
Fixes #3012 pt. 2 for draw and measure panel
I added a hr element that is shown if there is something drawn (aka there is actual information for the drawn feature shown in the partial list). This fix uniformize with the separator display in filter panel.
=> Show draw&measure separator only when a geometry is drawn on the map

contribs/gmf/less/popover.less
So we need to set a min width rule to force it.
fix  https://jira.camptocamp.com/browse/GEO-609
=> IE11 doesnt consistently size the popover box.

contribs/gmf/src/directives/print.js, contribs/gmf/src/services/themesservice.js
Fix #2980 
You can temporarily try here : https://testgmf.sig.cloud.camptocamp.net/bge/s/ocFN (with the theme "demo", group "OSM functions mixed" activate layers "osm open" and, or "Cant. routes for exceptional loads"). Then print with the legend. You should get the same legend image in the print than in the layertree (both layers have have static-image).
Problem: I got a red square instead of my image. But (now) the url looks good in the print report request.
=> Print - Able to get the legend in metadata

contribs/gmf/less/displayquerywindow.less
This PR makes the height content of the DisplayQueryWindow relative to its parent, i.e. the height is calculated instead of being fixed.
This allow the size to be dynamic.  For example, when resizing the window, the content height follows.
Note: the width is already working properly.
=> Fix displayquerywindow content height

contribs/gmf/less/importdatasource.less
Fixes the position (CSS) of the description in the ImportDataSource tool.
=> Fix ImportDataSource description position (CSS, flex)

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js
This PR removes the legacy 'Import Layer' tool from the `desktop_alt` app.
Note that its components are not removed by this PR, as the new ImportDataSource tool replacing it doesn't currently support the "typeahead" feature, and code might still be borrowed from the legacy version.
Once the "typeahead" features is supported in the new tool, then we'll be able to do the last "cleanup" of the files that were used by the legacy tool.
=> Remove legacy ImportLayer from desktop_alt

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile_alt/index.html, contribs/gmf/less/desktop.less, contribs/gmf/less/displaywindow.less, contribs/gmf/less/mobile.less, contribs/gmf/less/mobiledisplaywindow.less, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/displaywindow.js, contribs/gmf/src/directives/partials/displaywindow.html
This PR includes a new component that can be used as replacement of the `ngeo.Popup`, but with the possibility to make it resizable/draggable.
It is used in all 4 apps, instead of the `ngeo.Popup`:
* desktop
* desktop_alt
* mobile
* mobile_alt
* ~~The dragging of the window doesn't work in the `desktop_alt` version.  I have no clue why...  Following these recommendations, everything seems to be OK, with my doubts being that something must mess with the event jQuery is supposed to listen.  Resizable works fine.  See: https://stackoverflow.com/questions/7159118/jquery-ui-draggable-not-working~~ Unrelated to this PR. Issue created: #3056
=> gmf-displaywindow Component

contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/examples/displayquerygrid.html, contribs/gmf/examples/displayquerywindow.html, contribs/gmf/examples/displayquerywindow.js, contribs/gmf/examples/partials/queryresult.html, contribs/gmf/options/gmfx.js, contribs/gmf/src/directives/displayquerygrid.js, contribs/gmf/src/directives/displayquerywindow.js, contribs/gmf/src/directives/partials/displayquerygrid.html, contribs/gmf/src/directives/print.js, contribs/gmf/src/services/permalink.js, contribs/gmf/test/spec/directives/displayquerygrid.spec.js, examples/partials/queryresult.html, examples/profile.js, options/ngeox.js, package.json, src/ol-ext/interaction/modify.js, src/ol-ext/interaction/modifycircle.js, src/ol-ext/interaction/translate.js, src/ol-ext/menu.js, src/ol-ext/popover.js, src/services/featurehelper.js, src/services/mapquerent.js, src/services/querent.js, src/services/rulehelper.js, src/source/asitvd.js, src/source/swisstopo.js
Fix: #2604 (query groups)
Fix: #2672 (ngeo query examples broken)
Fix: #2844 (fix examples broken by permalink)
Also for GEO-471
And update ol3 (to a tag)
Example: https://testgmf.sig.cloud.camptocamp.net/bge
also (for grid): https://camptocamp.github.io/ngeo/query_set_type_feature/examples/contribs/gmf/apps/desktop_alt/index.html?debug&lang=en&baselayer_ref=OSM%20map%20WMS&tree_groups=Layers%2CGroup&tree_group_layers_Transport=fuel&map_x=615823&map_y=177798&map_zoom=4&tree_group_opacity_Group=0.65&tree_group_layers_Group=osm&tree_group_layers_Layers
or other changes like debug examples: https://camptocamp.github.io/ngeo/query_set_type_feature/examples/bboxquery.html
...
=> Query set type feature

contribs/gmf/src/directives/disclaimer.js
Fix #2912
From where come the issue:
- The node is detected as a not-mixed-group
- So an ol3 layer is created and added to the map
- A add_layer event is launched by ol3
- the disclaimer directive read immediately the layer and display the disclaimer information from the layer
- The js process continue and THEN the ol3 layer is filled with the name of the layers inside. (that correspond to add string inside the layer. Like when we check/un-check a layer. There is no special event to detect for that)
So, I've added a timeout to wait until the layer is completely fulfilled.
=> Wait on layer construction before displaying disclaimer

contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/partials/editfeature.html
Will log the error message from  PostgreSQL when editing or updating a feature in GMF.
See https://github.com/camptocamp/c2cgeoportal/issues/3233
=> Display edit feature postgres error

contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/examples/importdatasource.html, contribs/gmf/examples/importdatasource.js, contribs/gmf/less/importdatasource.less, contribs/gmf/less/search.less, contribs/gmf/less/typeahead.less, contribs/gmf/src/datasource/externaldatasourcesmanager.js, contribs/gmf/src/directives/importdatasource.js, contribs/gmf/src/directives/partials/importdatasource.html, externs/typeahead.js
This PR introduces Twitter's typeahead in the ImportDataSource component.
The url is displayed in the suggestions, and used in the search.  This could be enhanced in the future (i.e. we could use the name instead / too).
=> ImportDataSource - Add twitter typeahead to list servers

Makefile
Previously only the files newer than the timestamp were passed to the linter.
Changing the linter config or version did not trigger a lint of all the files.
With this commit, all files are linted on changes.
=> Make lint target reliable

src/directives/attributes.js, src/directives/createfeature.js, src/services/eventhelper.js
Since the goog.event-part wasn't even used throughout the project, it seems to be safe to remove.
=> Remove goog.events from eventhelper

contribs/gmf/options/gmfx.js, contribs/gmf/src/services/permalink.js, src/ol-ext/popover.js
And use ngeo.EventHelper in gmf.Permalink
=> Use 'one' function from jQuery to close the ngeo-popover

buildtools/check-example.js, src/directives/drawfeature.js, src/services/featurehelper.js
For #3065 (but don't fix it)
I set the default stroke to 2, that's more visible than 1. (And 3 is too much in the MapFishPrint report, see my comment in the issue: https://github.com/camptocamp/ngeo/issues/3065#issuecomment-344189374)
I add the stroke value to the createTextStyle_ function. Before, it was always using the default value (stroke size was 3)
=> Better size for text stroke

contribs/gmf/src/directives/layertree.js, contribs/gmf/src/services/themesservice.js
Fix: #3070
Before, we are only looking in the max/minResolutionHint of the node (so what's specified in the mapfile (or eq.)). Now, I also look in the metadata of the node.
=> Allow to zoom with resolutions in metadata

Makefile, options/ngeox.js, src/services/rulehelper.js
Related to https://github.com/camptocamp/ngeo/issues/2855
It seems there are no unit tests for the ``RuleHelper`` service and I see no other test that could be related.
Documentation of the ``ol.format.filter.like`` function, whose arguments are edited in this PR to explicitly add ``matchCase=false`` (default value is undefined => this attribute didn't appear previously in the WFS request):
http://openlayers.org/en/latest/apidoc/ol.format.filter.html#.like
Posted WFS ``GetFeature`` request formerly contained:
```
<PropertyIsLike wildCard="*" singleChar="." escapeChar="!"><PropertyName>name</PropertyName><Literal>linde</Literal></PropertyIsLike>
```
Now is:
```
<PropertyIsLike wildCard="*" singleChar="." escapeChar="!" matchCase="false"><PropertyName>name</PropertyName><Literal>linde</Liter …
```
=> Make sure string filtering is case insensitive for WFS requests

src/directives/profile.js
Gets rid of this warning:
```
node buildtools/build.js .build/app-desktop.json .build/desktop.js
info ol Parsing dependencies
info ol Compiling 555 sources
ERR! compile /home/mkuenzli/dev/ngeo/src/directives/profile.js:39: WARNING - dangerous use of this in static method ngeo.profileDirective
ERR! compile ngeo.profileDirective = function(ngeoDebounce) {
ERR! compile                                                ^
ERR! compile 
ERR! compile 
ERR! compile 0 error(s), 1 warning(s), 96.9% typed
ERR! compile 
```
=> Fix compiler warning

contribs/gmf/less/displayquerywindow.less, contribs/gmf/src/directives/displayquerywindow.js
Allow text in the gmf-displayquerywindow directive to be selectable.
The jQuery UI draggable widget was preventing text to be selected using a drag of the mouse.  Instead, it dragged the window.  To fix this, we use the `cancel` option of the widget, see: http://api.jqueryui.com/draggable/#option-cancel.  This prevents the dragging to occur for any defined selector.
Since the gmf-displayquerywindow always shows its content in a table, the `tr` is the chosen selector to prevent the selection. The rest of the selector are the default values that I thought made sense to keep.
While mouse hovering a `tr`, the CSS cursor changes to `text`.
=> Allow text in gmf-displayquerywindow to be selectable

src/services/print.js
The URL constructor does not support protocol-relative URLs.
=> Prepend protocol to WMS url

contribs/gmf/less/desktoplayertree.less, contribs/gmf/src/directives/partials/layertree.html
This PR changes how the external layers are added in the layer tree:
* they are shown first (were last)
* they are shown "as-if" they were part of the other layers, i.e. the gap between the 2 has been removed *
* Important note: the `height: 100%;` was removed to allow this. It was introduced in #1375.  I played with drag-dropping items and it didn't seem to affect the UI.  Please, make sure this PR didn't break #1375.
=> Show imported layers first in layertree, remove 100% height on ul

contribs/gmf/src/directives/importdatasource.js, contribs/gmf/src/directives/partials/importdatasource.html
This PR fixes the following issue: in the DataSourceBrowser component, the "connect" button was sometimes disabled after the selection of an item.
This was due to the fact that the field itself is of `url` type and there's an angular rule applied on the connect button that automatically disables it if the form is invalid.  The selection using the drop-down list uses typeahead. Now, I don't know exactly why, but the selected value was not always properly copied in the model, i.e. it was pasted in the input field, but not the model.
This fix ensures that, after the selection of an item among the typeahead selections, the value is properly copied.  At the same time, I do a "focus" on the connect button.
This solution keeps the `url` type on the field, because I think it's very useful to …
=> Fix typeahead selection in ImportDataSource component

contribs/gmf/less/base.less
This PR fixes an issue that occurs in the `gmf-displaywindow` component when its content is an iframe (url) and while resizing it.
When the mouse cursor moves over the iframe, then the jQuery UI draggable widget no longer works because the event isn't fired, i.e. we're no longer in the main frame.
To fix this, while resizing, we hide the iframe using CSS, which prevents the issue from occuring.
=> Fix displaywindow resizing with iframe

contribs/gmf/less/base.less
Similar to #3128: when using the jQuery UI draggable widget, when the cursor of the mouse hovers an iframe, the dragging stops because we're no longer in the same frame.
While dragging, hide any iframe to prevent this issue.
=> Hide iframe content while dragging

contribs/gmf/src/directives/search.js
But only the children of the current search node
https://jira.camptocamp.com/browse/GSGMF-158
=> Don't change all the twitter-typeahead element in the page

contribs/gmf/src/directives/displayquerygrid.js
Enable the admin to pick a default name for the query-result csv file
=> gmf csv filename can now be configurated

contribs/gmf/src/directives/partials/layertree.html
Fixes #3152
This PR allows the popup for filterable layers to be opened with only filters available (when no legend or opacity metadata is active).
=> Allow popover menu to be opened with filters

contribs/gmf/src/controllers/abstract.js
fixes #3113 
Without it, no theme change event is dispatched and the background layers are not re-computed correctly.
=> Dispatch a theme change on user change

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/examples/print.html, contribs/gmf/examples/print.js, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/partials/print.html, contribs/gmf/src/directives/print.js, contribs/gmf/test/spec/controllers/gmfprintcontroller.spec.js
For GSGMF-155
Work well on example, and apps
=> GMF Print: Move from directive to component

contribs/gmf/src/directives/displayquerygrid.js, contribs/gmf/src/directives/drawfeature.js, contribs/gmf/src/directives/partials/drawfeature.html, src/directives/drawfeature.js
Adds a showMeasure variable that can be configurated in the template to check by default the display measurement check box.
`                  gmf-drawfeature-showmeasure="true"
`
=> Enable to configurate the default display of measurements

examples/animation.js, examples/backgroundlayer.js, examples/backgroundlayerdropdown.js, examples/bboxquery.js, examples/colorpicker.js, examples/layertree.js, examples/locationsearch.js, examples/mapquery.js, examples/measure.html, examples/measure.js, examples/search.js
https://jira.camptocamp.com/browse/GSGMF-151
=> Directive to component for examples

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/displayquerywindow.js, contribs/gmf/src/directives/displaywindow.js
This PR adds:
* the `draggable-containment` option to the `gmf-displaywindow` component
* the `gmf-displayquerywindow-draggable-containment` option to the `gmf-displayquerywindow` directive
I chose `draggable` as first word for the option, because it's the name of the jQuery UI widget.
I chose `containment` as last word for the option, because it's the name of the option of the jQuery UI draggable widget.
There is an issue with the desktop version.  We're able to drag slighly more to the left, i.e. outside of the containment.  I don't know why that happens.  On the desktop_alt site, it works properly.
Please, let me know if this is a blocker.
=> Add draggable containment opt 2 gmf display-[query-]window

examples/simple3d.html, examples/simple3d.js, package.json, src/modules/olcs/Manager.js, src/modules/olcs/Service.js, src/modules/olcs/controls3d.js
- simplify service and make it optional;
- simplify example.
=> Rework olcs Manager

src/directives/mobilegeolocation.js
Use native javascript to fetch gyroscope data from mobile devices instead of ol.DeviceOrientation
TODO:
=> Fix autorotate

src/services/rulehelper.js
Fixes #3186
This PR allow the 'contains' filter to fetch result with pattern that are not only starting a attribute value, but also be in the middle of a word, or string, or at the end.
Example:
"med" will not give us only with result "medbase" but now the following results are valid as well:
"Bergrestaurant Jatzmeder", "Dr. med. dent. V. Nielsen", etc
Escaping works partially. Character '.' are working while the characters '!', '*' is not giving us the wanted result, but the issue is probably from MapServer does interpret it anyways as part of the expression.
=> Text constraint filter expression

contribs/gmf/src/directives/displayquerywindow.js, contribs/gmf/src/directives/displaywindow.js
When the `gmf-displaywindow` was made smaller using the jQueryUI resizable widget, the parent div was keeping the original size.  That parent div had the jQueryUI draggable widget on it, which allows the window to be dragged even when seemed to be dragging outside the window.
To fix this, both widgets now interact with the same div: the first div within the widget (at the root).
=> gmf-displaywindow - drag/resize on same div

contribs/gmf/src/directives/disclaimer.js
An issue has been raised about the disclaimer messages in the `desktop_alt` application.  It's now showing an empty message.  It seems to be a combinaison of multiple things.  Here goes.
First, when the update to Angular 1.6 was made, changes were made in several directives to change them as components without them being tested.  The `gmf-disclaimer` was one of them.  Look at the first commit of this PR. The component was created before its controller.  From this point moment on, the component stop from working under the 'development' environment.  When compiled, it worked because I suppose the compiler was smart enough to understand to define the controller before and then use it, I don't know...
Introduced in https://github.com/camptocamp/ngeo/pull/2142
Fixed in the "first step" commit. …
=> WIP - Fix empty disclaimer

examples/recenter.html, examples/recenter.js, src/map/module.js, src/map/recenter.js
For GSGMF https://jira.camptocamp.com/browse/GSGMF-174
=> Modularize recenter

Makefile, TODO.md, github_versions
Only the first 4 commits of #3137, hopefully all trivial things that don't cause any build issues.
- Remove unused compiler-latest rules from Makefile
- Remove unused closure-library rule/version from Makefile/github_versions
- Remove outdated TODO file
- Reduce duplication in Makefile
=> Makefile cleanup

buildtools/build.js
Document we are going to keep the old buildtools scripts for projects that depended on it. This may be temporary though, and these files finally cleaned out.
=> Document usage of old buildtools scripts

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/src/directives/authenticationdirective.js, contribs/gmf/src/directives/partials/authentication.html
Whether to show the password forgotten link. Default to true.
fixes #3202
=> Add new gmf-authentication-allow-password-reset option to gmf-authentication

contribs/gmf/src/directives/partials/editfeature.html, contribs/gmf/src/directives/partials/objectediting.html
Fixes a small issue I caught in EPFL: some of the tooltips were incorrectly set as the " | translate" was visibile in the interface.
I grepped on " | translate' " to make sure there were no file left wrapping the pipe and following anymore.
=> Fix title value to be correctly set in object editing pages

contribs/gmf/src/datasource/datasourcesmanager.js, contribs/gmf/src/services/wfsaliases.js, options/ngeox.js, src/datasource/ogc.js, src/format/wfsattribute.js, src/format/xsdattribute.js, src/services/mapquerent.js
Some WFS backends such as QGIS Server may provide ``alias`` attributes for results of WFS requests. They are made available through a WFS DescribeFeatureType request. For instance:
```
...
<element alias="Vitesse" type="integer" name="Speed"/>
...
```
This PR aims to display those aliases if any in the query results window. See  https://jira.camptocamp.com/browse/GEORD-21
Still to do:
* ~~support layers added using the WMS browser~~
* ~~make sure WMS GFI are supported~~
=> Support of WFS attributes aliases

src/ol-ext/interaction/measure.js
Fixes the unlistener to be correctly executed at end of drawing interaction.
I extracted the unlisteners to have a similar behavior for the mobile measure tool, which were already used in drawing features on desktop apps.
=> Extract unlistener for mobile measure tool

contribs/gmf/src/directives/featurestyle.js, contribs/gmf/src/directives/partials/featurestyle.html, contribs/gmf/src/services/permalink.js, src/directives/drawfeature.js, src/format/featurehash.js, src/ngeo.js, src/services/featurehelper.js
Enable the user to display the feature label. 
As it is done for the measurement label.
cf
=> Display label drawing

contribs/gmf/src/directives/featurestyle.js, contribs/gmf/src/directives/partials/featurestyle.html, contribs/gmf/src/services/permalink.js, src/directives/drawfeature.js, src/ngeo.js, src/ol-ext/format/featurehash.js, src/services/featurehelper.js
=> 2.2 add labels drawing

Makefile, contribs/gmf/apps/ios-overlap-fix.js, contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile_alt/index.html, contribs/gmf/less/iphone.less, contribs/gmf/less/mobile.less, utils/ios-overlap-fix.js
Fixes #2695
This PR introduce a iOS less file that take specific classes. Then in the interface, the ios user-agent is checked to know if it is an iOS device and its version. If true and egal to iOS 10, it applies the classes to the HTML elements.
TODO:
Known issues:
- Overlap on the botton of the screen (it is possible to get the screen scrolled with a focus on the search field and drag at the bottom)
- ~Code is not minified/transpiled in the build (so may break on IE ?)~
Demo:
https://camptocamp.github.io/ngeo/ios-overlap-fix/examples/contribs/gmf/apps/mobile/
=> Fix UI overlapping on iOS 10 (Safari)

contribs/gmf/src/directives/displayquerygrid.js, contribs/gmf/src/directives/mobilemeasurepoint.js
=> Some docs fix

Makefile_windows, buildtools/generate-info.js
This PR:
- Updates the Windows_makefile
- Proposes a fix in order to have jsdoc run on windows. Basically, the file names to be parsed by jsdoc are no longer passed to the windows command but injected into the jsdoc config file as windows does not support long command strings (...)
Known issue: [this file](https://github.com/camptocamp/ngeo/blob/master/buildtools/jsdoc/info/conf.json) will appear as modified in git after dist build.
@fredj: would you like to review and merge ?
=> fix windows issues

contribs/gmf/src/directives/displayquerygrid.js, contribs/gmf/src/directives/displayquerywindow.js
Fix #3252 
I make it similar as displayquerywindow.js
=> Fix highlight features in display query grid

src/directives/partials/attributes.html
Fix #3212
For now, a "false" value is considered as not set and is not valid (you cannot save)
The easier way to fix it.
What does it mean "required" on a boolean field ?
=> Edition - Checkbox with 'false' value are also valid

contribs/gmf/src/services/permalink.js
It was not working anymore (and a lot of examples use the permalink)
Note that this code will be removed when the permalink will be in a module.
=> Debug gmf permalink (push gmf.theme requirments)

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/src/directives/authenticationdirective.js
Fix: #3278 - Use of is_password_changed
Demo here: https://ger-benjamin.github.io/ngeo/is_password_change_func/examples/contribs/gmf/apps/desktop
You can try it with the user: demobern (please, don't change the password).
=> Force user to change its password

contribs/gmf/src/directives/mouseposition.js
Fixes #3344 
This fixes the translation issue with the mouse position OL control. Now we wait for gettextCatalog to fire an event that the language is loaded/changed to create the component with the correct language string.
=> Mouse position translation

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/src/directives/displayquerygrid.js, contribs/gmf/src/directives/partials/displayquerygrid.html
Fixes #3273.
With this fix, we escape the IDs (generated from the value in ctrl.mergeTabs for merged tabs or OL datasource). If an invalid value would result in an invalid ID selector (css), then the value is stripped from unauthorized characters. Other change is the use of the datasource IDs for the HTML ids instead of the label value that contained spaces, etc.
Ideally ids defined in the ctrl.mergeTabs should have no spaces, or any specific characters such as parentheses, brackets, etc. This fix allow all project to work without changing ids manually, but if possible having a correct value is just best practice...
In that context I changed the value in our desktop example, while the fix was tested on the previous value, 'OSM time merged'.
=> Escape sourceLabel ids when invalid characters are present

contribs/gmf/src/services/permalink.js, examples/simple3d.html, package.json, src/modules/olcs/Service.js, src/modules/olcs/constants.js, src/modules/olcs/olcsmodule.js
Manage 3d permalink if cesium is active.
Here the params used 
```
3d_enabled=true
3d_lon=23.49043
3d_lat=-40.49055
3d_elevation=993992
3d_heading=360.000
3d_pitch=-42.408
```
=> Lux 3dpermalink

contribs/gmf/src/services/enumerateattribute.js
Fix: #3365
Now we query each attributes to get their "description" and so, we can filter on multiple enumerated attributes (tested locally).
Note that for that, we need:
- (mapfile) That the column is given by the sql request and "exported" via the gml_include_items.
- (vars file) That each attribute is listed in the layers->enum-><layer>->attributes section
- (admin) That the layer has a enumeratedAttributes metadata with the value "column1,column2,etc"
- (Column can't have alias ! )
=> Accepte multiple enumerate attributes (filters)

src/services/querent.js
Fixes https://jira.camptocamp.com/servicedesk/customer/portal/6/GEO-865
Currently the WFS requests are sent with header 'content-type': 'application/json', but we always send a xml payload to Mapserver. Issue is on one of baselstadt instance (integration), this behaviour did redirect the request for some reasons ... Setting the correct content-type header to 'text/xml'.
More generally, outside this use case, the content-type should have been 'text/xml' anyways.
=> Set content-type header for WFS requests

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile/js/controller.js, contribs/gmf/apps/mobile_alt/index.html, contribs/gmf/apps/mobile_alt/js/controller.js, contribs/gmf/examples/search.html, contribs/gmf/src/directives/search.js
This PR allow the rateLimitWait parameter, that is used with the Bloodhound engine for debouncing fulltext-search requests, to be set up. That allow as well to set different values for each interfaces. Like mobile could get a higher value in order to get less request / bandwidth used with the backend for fulltext-search.
If the value is not set from the directive html, or not existing in the interface controller, the search component is going to set it to the default value: 50 ms. This was the value we previously hard-coded. There should be no issue for project that have outdated html for the search component as the component is going to initialize the value correctly in any cases.
I updated every interface, only desktop_alt have a different value that the default one.
Fixed the gmf …
=> Allow bloodhound rateLimitWait params to be settable in gmf

.eslintrc.yaml, .gitignore, Makefile, buildtools/mako_build.json, contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile_alt/index.html, contribs/gmf/apps/oeedit/index.html, contribs/gmf/apps/oeview/index.html, contribs/gmf/less/base.less, contribs/gmf/src/directives/editfeature.js, externs/datetimepicker.js, externs/php-date-formatter.js, options/ngeox.js, package.json, src/directives/attributes.js, src/directives/datetimepicker.js, src/directives/partials/attributes.html, src/ngeo.js, src/ol-ext/format/xsdattribute.js
=> Fix the date field in the attribute editor

contribs/gmf/apps/mobile_alt/index.html, contribs/gmf/src/directives/mobilemeasurepoint.js, src/ol-ext/interaction/measurepointmobile.js
=>  Be able to configure the mobile measure format

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/services/permalink.js, contribs/gmf/src/services/thememanager.js
Correctly set the background layer at page load.
Change: at page load, the theme name is directly set to the url; it was not the case previously.
=> Set the background layer from the them at page load

src/services/print.js, test/spec/services/print.spec.js
This was the old behavior for 2.1 (icons were rotating with the map).
Adding parameter 'useNativeAngle' to 'false' fixes the issue in 2.2.
=> Allow print symbols rotation in gmf projects

contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/objectediting.js, src/ol-ext/interaction/modify.js, src/utils.js
Instead of alt + single click, see:
https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#olinteractionmodify-deletes-with-alt-key-only
fixes #3413
=> Allow vertex deletation on single click

src/services/featurehelper.js
=> Fix text place when the label and the coords are displayed

src/services/print.js
It seems that the ogcserver sent by IE11 and Edge is the following:
"ogcserver": "Main+PNG"
while the correct format sent by Chrome and Firefox is:
"ogcserver: "Main PNG"
The wrong format causes the plus sign to be encoded into %2B, and breaks the print request.
The condition I add is not doing anything in the cases when Chrome and Firefox are sending the right value.
=> Fix ogc server encoding for IE11/Edge

Makefile, contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/directives/print.js, contribs/gmf/src/services/syncLayertreeMap.js
I set the parameter this way in a project controller via metadata 'printNativeAngle' in the admin interface applied to the layer group I want.
printNativeAngle value was not sent to the ngeo print component because gmf did not retrieve the original layerGroup but create a new one just before sending it to ngeo.
Desktop_alt updated to test this use case.
=> Add printNativeAngle parameter to the gmf-created print LayerGroup

contribs/gmf/src/directives/print.js
Was working with a single group in the layer tree with 'false' as value. 
If only one of many groups in the layer tree is set to use the printNativeAngle, the variable would be set back to 'true' because the next group iterated would have the value 'true', thus no icons orientation would works even if the value needed was 'false'...
=> Fix gmf printNativeAngle when more than one group in the layer tree

src/source/swisstopo.js
Change URL to hosts wmts{20-24}.geo.admin.ch, which is what the current
documentation recommends:
http://api3.geo.admin.ch/services/sdiservices.html#other-projections
=> Update swisstopo WMTS URL for EPSG:2056

contribs/gmf/examples/authentication.html, contribs/gmf/src/directives/authenticationdirective.js, contribs/gmf/src/directives/partials/authentication.html
First commit fix a $compile:multiling Linking Element Multiple Times angular error.
Second commit fix: https://github.com/camptocamp/ngeo/issues/3278
~~The problem is that the READY event was not emitted on login (but I need it, and it looks not problematic to emit it at the same time as the LOGIN event.) Then, the problem is that the "soft" reload of the page remove the notification, I've used a timeout to avoid this problem. If you know a better method...~~
=> Debug login errors and force-password-change message

contribs/gmf/src/directives/displayquerygrid.js, contribs/gmf/test/spec/directives/displayquerygrid.spec.js
see: GEO-977
Tested with desktop_alt. Changes to the bound object during runtime will be reflected in a new search.
This should not break existing code as long the feature is used like in the desktop_alt.
=> Change type of binding to allow changes to mergetabs during runtime

package.json
work in progress
As npm scripts but this can moved into the Makefile is needed.
webpack-dev-server is not developed anymore
=> Add new npm script to serve the examples and apps

contribs/gmf/src/controllers/AbstractDesktopController.js
Used in desktop but was missing.
(Not used in mobile)
=> Fix resize map (missing ngeo-map-resizemap)

src/olcs/controls3d.js
The const is necessary to attach the comment block.
=> Fix controls3d

src/services/layerHelper.js
Improve performance.
(See: https://jira.camptocamp.com/projects/GEO/queues/custom/52/GEO-891)
=> Can set preload value of Tiles (default to 0)

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/services/authenticationservice.js
=> Prevent reload of user object during logout for specific user role.

contribs/gmf/test/spec/controllers/gmfprintcontroller.spec.js, contribs/gmf/test/spec/directives/displayquerygrid.spec.js, contribs/gmf/test/spec/directives/displayquerywindow.spec.js, contribs/gmf/test/spec/directives/profile.spec.js, contribs/gmf/test/spec/services/permalinkservice.spec.js, contribs/gmf/test/spec/services/share.spec.js, contribs/gmf/test/spec/services/thememanager.spec.js, contribs/gmf/test/spec/services/themesservice.spec.js, contribs/gmf/test/spec/services/treemanager.spec.js, test/spec/directives/filereader.spec.js, test/spec/directives/grid.spec.js, test/spec/directives/layertree.spec.js, test/spec/directives/scaleselector.spec.js, test/spec/search/createlocationsearchbloodhound.spec.js, test/spec/services/autoprojection.spec.js, test/spec/services/backgroundlayermgr.spec.js, test/spec/services/csvdownload.spec.js, test/spec/services/debounce.spec.js, test/spec/services/featureoverlay.spec.js, test/spec/services/filters.spec.js, test/spec/services/getbrowserlanguage.spec.js, test/spec/services/layerHelper.spec.js, test/spec/services/location.spec.js, test/spec/services/toolActivateMgr.spec.js, test/spec/services/wmstime.spec.js
For: https://jira.camptocamp.com/browse/GSGMF-261
The last unused vars (except 2 projections in test, but that will be done later)
(All file was already loaded)
=> Remove unused import in tests

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile_alt/index.html, src/services/layerHelper.js
=> Preload for Tiles is configurable now

contribs/gmf/src/directives/partials/displayquerygrid.html
Fixes https://github.com/camptocamp/ngeo/issues/3462
The track by property from ngRepeat is breaking if we used the id, but works when using the label (as it was previously to my last PR fixing the component: https://github.com/camptocamp/ngeo/pull/3351).
The bug was related to layers using two wms sources displayed together (layer "Two layers" under the "OSM function mixed" group in "demo" theme).
=> Fix ngRepeat track by displayquerygird

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile_alt/index.html, contribs/gmf/examples/backgroundlayerselector.html, contribs/gmf/examples/backgroundlayerselector.js, contribs/gmf/less/map.less, contribs/gmf/src/directives/backgroundlayerselector.js, contribs/gmf/src/directives/partials/backgroundlayerselector.html, contribs/gmf/src/gmf.js, src/services/backgroundlayermgr.js, test/spec/services/backgroundlayermgr.spec.js
Add a way to get a static background layer linked to an opacity slider, via a parameter to include in the interface. I.E:
```
/**
* @type {string}
* @export
*/
this.bgOpacityOptions = 'Test aus Olten';
```
The string is the layer label (WMS name from admin interface).
The component is defined as follow in the html:
```
<gmf-backgroundlayerselector
gmf-backgroundlayerselector-map="::mainCtrl.map"
gmf-backgroundlayer-opacity-options="::mainCtrl.bgOpacityOptions"
class="dropdown-menu">
</gmf-backgroundlayerselector> 
```
`gmf-backgroundlayer-opacity-options` is facultative and if ignored, the application will just set as it was without the feature.
First commit is remove correctly the dimension used in the past but not done completly.
The app now use a group containing the active layer and …
=> Backgroundlayerselector opacityslider

contribs/gmf/less/popover.less
Fixes https://github.com/camptocamp/ngeo/issues/3494
Maybe with 2.3 using movable elements, some adjustements will nee to be done.
Tested that the popover is on top of the contextual menu.
=> Add z-index to popover

package.json
To be able to use ngeo 2.2 again.
Problem was: 
````
ngeo/node_modules/@camptocamp/closure-util/lib/manager.js:186
throw new Error('Unsatisfied dependency "' + require + '" ' +
^
Error: Unsatisfied dependency "ol.ext.pixelworks.Processor" in script: ngeo/node_modules/openlayers/src/ol/source/raster.js
````
=> Add rollup to fix missing ol.ext dependencies

contribs/gmf/src/directives/displayquerygrid.js, contribs/gmf/src/directives/partials/displayquerygrid.html
FIX: GEO-1022
The id in the querysources is not always unique (not in case of multiple server layers in one ol layer). And the querygrid already use label as ID to be able to merge the layers and because that make no sens to have multiple tabs with the same name, so to be based on id is a bad idea. Having a mix of id/label is also a bad idea.
Now all is based on labels. Note that we must escape the label to be able to use and select it as class or id (and avoid to fall again in this issue: https://github.com/camptocamp/ngeo/issues/3273)
=> Use escaped label as id for querygrid, because id are not unique

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/oeview/index.html, contribs/gmf/examples/authentication.html, contribs/gmf/examples/authentication.js, contribs/gmf/options/gmfx.js, contribs/gmf/src/authentication/Service.js, contribs/gmf/src/authentication/component.html, contribs/gmf/src/authentication/component.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/controllers/AbstractMobileController.js, src/message/modalcomponent.js
For https://jira.camptocamp.com/projects/GEO/queues/custom/52/GEO-712
(/!\ New dev, no webpack / es6 thing)
IT:
- Force user to change it's password via a modal (that we can't dismiss).
- Add a possibility to use a function to validate that the password fulfill some requirements
- Add possibility to  keep modal open.
Added in desktop and mobile.
(What a headheach :unamused: But work well now)
=> Force password change

buildtools/templatecache.mako.js
Otherwise it breaks the fontawesome placement.
the doc for the `remove_all_empty_space` option says: This is almost guaranteed to break your HTML :-)
=> Don't remove the spaces in template HTML

src/services/backgroundlayermgr.js, src/services/layerHelper.js, test/spec/services/backgroundlayermgr.spec.js
Fix ZIndex on the first level children on a ol.layer.Group. It is used when a group is given as active or overlay background layer.
Tests are updated. ngeo.layerHelper is updated to provide this utility function.
=> Fix ZIndex on first children layers on ol.layer.Group for backgroundselector-opacityslider

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/search.js
Fixes #3551
Add a new permalink parameter "search-maxzoom" that takes a integer. It does the same behavior as using the gmf-search-maxzoom from the directive, but for permalink. Also remove conflicts with the directive in abstract.js.
=> Add maxzoom for permalink search

contribs/gmf/src/directives/print.js
Fix: GEO-1051
Summary: 
If the scale 1:1000 is never the "best calculated scale" for the print, the scale will be automatically adapted. Than means, we will never be able print in 1:1000. This PR correct that.
@jwkaltz can you test if that's the expected behaviors ? I've taken the same client-scale/print-scale than your, as explained in your comment, in the ticket.
@fredj can you valid the code ?
Demo here: https://gmf-test.sig.cloud.camptocamp.net/bge
=> Print - Selected scale must not be auto. adapted

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile_alt/index.html, contribs/gmf/examples/backgroundlayerselector.html, contribs/gmf/examples/backgroundlayerselector.js, contribs/gmf/less/contextualdata.less, contribs/gmf/less/map.less, contribs/gmf/less/popover.less, contribs/gmf/src/authentication/Service.js, contribs/gmf/src/backgroundlayerselector/component.html, contribs/gmf/src/backgroundlayerselector/component.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/gmf.js, contribs/gmf/src/query/gridComponent.html, contribs/gmf/src/query/gridComponent.js, contribs/gmf/src/search/component.js, src/map/Backgroundlayermgr.js, src/map/LayerHelper.js, test/spec/services/backgroundlayermgr.spec.js
We are going to move BackgroundLayerMgr in gmf in a new PR after this merge. 
For now the CI is not happy with the gmf dependency in ngeo, so the temporary solution is just to hardcode it until I open a new PR with the file moved to the right place in gmf (+ unit tests).
=> Merge 2.2 into master

contribs/gmf/src/gmf.js, src/map/Backgroundlayermgr.js
This PR remove the hardcoded group name introduce temporery in the #3651 merge
Instead of moving the component in gmf as discussed for #3651, use a inner file variable for the background group name. 
This allows Luxembourg to not break...
https://github.com/camptocamp/luxembourg_geoportailv3/blob/3d/geoportailv3/static/js/backgroundlayer/backgroundlayerdirective.js#L23
=> Background group name use a variable

src/directives/filter.js, src/directives/partials/filter.html
For GEO-1053
Example (tmp): https://gmf-test.sig.cloud.camptocamp.net/bge
- Open theme "filters"
- (keep only one group, otherwise, it's hard to know which layer is currently active)
- Open panel filters, choose one layer.
Then, new with this PR:
Buttons "Apply filter" and "Get Data" are enable only on the following condition: "at least one rule exist" and "the layer is activated". Otherwise there are, and look, disable.
=> Improve filter buttons activation

contribs/gmf/src/directives/print.js
For GEO-1051  (fix the fix) 
If the scale was already adapted, the map was not updated and so, the mask neither.
=> Update print mask manually on scale selection

src/services/backgroundlayermgr.js
Missing @export  ....
Well, technically, I wasn't able to check that from source-code or github.io ... (desktop_alt)
:-(
=> Add missing @export to backgroundlayermgr

src/services/print.js
As the map is ordered by z-index with OL, the print need to replicate this otherwise layers are unsorted and given to mapfish in that state...
=> Order print layers by z-index

src/services/wfspermalink.js
Fixes https://jira.camptocamp.com/servicedesk/customer/portal/6/GEO-1030
Add missing headers for wfs permalink requests.
=> Add headers to wfs permalink request

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/src/directives/search.js
Side PR of https://github.com/camptocamp/c2cgeoportal/pull/3565
For GEO-908
=> Doc for gmf FTSearch's similarity

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/desktop/less/main.less
Fixes GSGMF-386
Was only present in desktop_alt, but it is a standard feature, so I added it to desktop.
=> Add the import datasource module to desktop interface

contribs/gmf/apps/desktop_alt/js/controller.js
Fix GSGMF-382
Put back the WFS permalink to the desktop_alt app
=> Re-enable WFS permalink for desktop_alt

contribs/gmf/apps/desktop/index.html, src/message/modalcomponent.js
Now the default value when nothing is provided will always allow to close a modal from the "close button" or clicking outside the modal.
=> Fix closable attribute in modalcomponent

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html
Fix GSGMF-402 and GSGMF-404
If a tag is self-closing and is not part of the HTML5 standard, IE11 seems to not know how to handle it (especially as it is custom tags used with directive components). This fixes the issue and allow the DOM to be generated correctly.
=> Fix IE11 wrongly generated DOM

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/less/desktop.less, contribs/gmf/less/routing.less, contribs/gmf/src/controllers/AbstractDesktopController.js, examples/routing.html, examples/routing.js, externs/typeahead.js, options/ngeox.js, src/misc/filters.js, src/routing/NominatimInputComponent.js, src/routing/NominatimService.js, src/routing/RoutingComponent.js, src/routing/RoutingFeatureComponent.js, src/routing/RoutingService.js, src/routing/module.js, src/routing/nominatiminput.html, src/routing/routing.html, src/routing/routingfeature.html
work in progress, replaces #2669
=> Add routing service and directive

requirements.txt
Better Transifex version filter
=> Just ignore the 0.13 versions

buildtools/webpack.prod.js, package.json
Fixes the two issues with webpack build we have on EPFL project.
Dependency update from url-loader 1.0.0 to 1.0.1 fixes an issue with urls being processed as [Object object] instead of the wanted base64 inlined data strings.
Use of file-loader instead of url-loader allow the production css file to have static relative urls instead of base64 inlined strings for the png, svg, eot, woff and woff2 files format. This change allowed in EPFL to reduce css from 2 Megabytes to 250 Kilobytes.
I'm not sure if we should do it for .cur files, probably it is not a huge gain as there is only 2 files and probably not many added in projects...
=> Update url-loader to 1.0.1 and adapt webpack build config

contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/filters/filterselectorcomponent.js, contribs/gmf/src/map/mousepositionComponent.js, contribs/gmf/src/print/component.js, contribs/gmf/src/profile/component.js, contribs/gmf/src/query/gridComponent.js, contribs/gmf/src/query/windowComponent.js, contribs/gmf/src/raster/component.js, contribs/gmf/src/theme/selectorComponent.js
Not sure if it is added to the right file, but it is missing when building the app with webpack (consequence is EPFL theme selector is not visible when clicking the theme button).
=> Add missing webpack import for dropdown

examples/displaywindow.css, examples/displaywindow.html, examples/displaywindow.js, src/message/displaywindowComponent.js
Allows angularjs templates inside the popups of ngeo-displaywindow.
Example in action: https://geomapfish-demo.camptocamp.com/mkuenzli/displaywindow.html
=>  Add support for angularjs templates to ngeo-displaywindow

examples/displaywindow.css, src/message/displaywindowComponent.html, src/message/displaywindowComponent.js
- [minor change] Add draggable to webpack imports (like resizable)
- **Restrict dragging to header handle.**
If the whole window is the handle, the user cannot interact with certain elements of the window. For example, it is not possible to select text there. ~~A potential issue introduced with this change is, that there is no visual indicator, that the header is the dragging-handle. I'm open for suggestions.~~
Edit: The only visual indicator currently is the cursor, which changes if the window is draggable and the user is hovering over the header. This should be enough for the example, right?
=> Restrict dragging to header handle of displaywindow component (+ imports)

contribs/gmf/examples/mobilemeasure.html, contribs/gmf/examples/mobilemeasure.js, contribs/gmf/examples/profile.js, contribs/gmf/src/disclaimer/component.js, contribs/gmf/src/drawing/featureStyleComponent.js, contribs/gmf/src/mobile/measure/lengthComponent.js, contribs/gmf/src/mobile/measure/pointComponent.js, contribs/gmf/src/objectediting/component.js, src/filter/RuleHelper.js, src/interaction/Modify.js, src/interaction/ModifyCircle.js, src/interaction/Rotate.js, src/interaction/Translate.js, src/map/FeatureOverlayMgr.js, src/rule/Geometry.js
Fix several gmf examples:
- drawfeature
- profile
- mobilemeasure
Fix ngeo example:
- modifycircle
Also various fixes for gmf apps.
=> Fix gmf examples

buildtools/webpack.commons.js, contribs/gmf/src/editing/editFeatureComponent.js, karma-conf.js, src/misc/datetimepickerComponent.js, src/misc/php-date-formatter.js
Stéphane converted the php-date-formatter lib into a webpack custom supported version we can use find in the src/misc directory. Other changes are minor syntax errors in webpack configs and import of css.
=> Fix editfeatureselector example

contribs/gmf/apps/desktop/Controller.js, contribs/gmf/apps/oeedit/Controller.js, contribs/gmf/apps/oeview/Controller.js
I could not test: there were 500 errors with dynamic.js.
Same as what we did in EPFL project.
=> Override contextual data in gmf apps

examples/offline.html, examples/offline.js, src/offline/component.html, src/offline/component.js
GSLUX-78
- Manage mask
- Manage extent (polygon on overlay, and recenter on)
(color and quality are bad only in the gif)
Works well with map in meters. I'm not sure if all are well with another unit.
=> Offline - Manage extent

examples/offline.less, src/offline/component.html, src/offline/component.js
GSLUX-79 and finish GSLUX-65
Result (there is also a new "Are-you-sur-you-want-aboart-download" modal menu):
Note:
- The symbol is not the same because in GA, the symbol is from  the pro version of FontAwesome.
- The loading screen is not the same because it have a very special look in GA. So I've just done somethings easier / more "passe partout".
=> Add the loader (0=>100%) and the offline menu icon

contribs/gmf/src/layertree/common.less
To have the same behavior as version 2.2
=> Fix text-decoration style in layertree

examples/offline.html, examples/offline.js, examples/offline.less, examples/simple3d.js, src/offline/NetworkStatus.js, src/offline/module.js
Add a service that keeps network status up to date.
See comment:
```
* This service watches the status of network connection.
*
* Currently it watches every $http and $.ajax requests errors, if an error
* occurs we wait 2 sec then we make an http request on the checker file.
* If the checker responds that means we are online, otherwise we make a
* 2nd request 2 sec later, if the 2nd requests failed that means we
* are offline.
*
* A timeout of 1 sec is set for the checker file, so if we have a bad
* connection, we consider we are offline.
*
* During offline mode we test every 2 sec if we are back online.
```
I wonder why that have chosen to use ` $.ajax` instead of `$http`.
Some code is useless if we have no action while request are currently loading and not yet responded (ga use it for …
=> Add NetworkStatus service for offline detection

contribs/gmf/src/editing/editFeatureSelectorComponent.js
To reproduce the issue:
* go to edit component and start drawing a polygon
* switch to the print component
To draw interaction is still active
=>  Stop edit mode when leaving edit component

contribs/gmf/src/less/vars.less, contribs/gmf/src/search/search.less
In some cases, overriding won't work if the variable is defined in the very file it is used.
By moving the variable to the vars.less file, it is trivial for the app to control the order of the overrides.
=> Extract @search-size to allow overriding in apps

src/offline/NetworkStatus.js
Part of GSLUX-89
I'm not sure how it's compiled now, but it looks like that the "offline" property doesn't exist for the html. So perhaps this fix the problem.
(there is no problem on the demo with `?debug` params)
=> Fix offline detection

src/offline/component.js
See https://jira.camptocamp.com/browse/GSLUX-83
- fix mask size
If no `extentSize` is given to offline component, then the mask will not stick to an extent. 
The mask is then static, changing map resolution will change extent size, as on google map offline.
The size of the mask is a constant square, with a minimum margin defined by the user.
- zoom constraints
While the mask is open, the view zoom will be constraint with specified bounds.
=> Offline: add a mode for constant pixel size mask

src/offline/component.js
Issue cause bindings come from html, so already there in constructor.
Move logic to `$ngOnInit`
=> Fix offline mask bindings

docs/guidelines.md
=> Document $injector usage

src/offline/DefaultConfiguration.js
The default offline image was a blank image, it overlap other images so it must be transparent.
1x1 px transparent.
=> Fix offline default img to make it transparent

contribs/gmf/src/import/importdatasourceComponent.html
Fix for GSGMF-559
There is somewhere a conflict with the bootstrap class "input-group-sm". My opinion is to remove the class, then the field looks normal again and there is actually no need to minifying the looks/height of it for a 3 elements panel ... The interface is not cluttered by a bigger button here from the initial idea.
=> Fix local data import button

src/offline/Mode.js
Offline `hasdata` info should be dispatched in the mode service, which contains all info about the offline mode.
It must be extracted from component.
=> Offline has data in a service

src/offline/component.js
GSLUX-119
Relatively easy ;-)
Out of scope, but in same file:
In this file, we have references to a "debug" attribute that we don't use anymore. Should I remove it ?
=> Offline - Hide extent after downloading

src/offline/component.html, src/offline/component.js
Second commit to remove a now useless attribute.
**First commit for GSLUX-116.**
The condition I've added is never true in ngeo, but we can upgrade the "estimateLoadDataSize" in lux to answer `0` if no background and no layer is on the map.
=> No data no save

src/map/LayerHelper.js, src/print/Service.js
Fixes an print issue with opacity background layer when this is a group of layer instead of a single layer element.
When we generate the print layers, we flatten the gmf layers to remote the group, but we did loose the opacity in the process when this value was only on the group. This PR fixes and apply back the opacity to the layer once flatten.
=> Fix print layers when opacity background layer is a layer group

contribs/gmf/src/services/treemanager.js
This fixes the group name that are not translated when we add a theme twice and receive the notification that it cannot be added again. (desktop alt interface in the demo)
=> Fix group translation in notifications

contribs/gmf/src/datasource/ExternalDataSourcesManager.js, contribs/gmf/src/import/import.less, contribs/gmf/src/import/importdatasourceComponent.html, contribs/gmf/src/import/importdatasourceComponent.js
GSGMF-467
The error has the same look as for the "online" mode.
Do we need colors to make it more visible ?
=> Inform user if the imported file is not valid

contribs/gmf/src/datasource/ExternalDataSourcesManager.js
=> Import KML: Manage Empty geometry import error

contribs/gmf/src/theme/Themes.js, src/map/LayerHelper.js
See https://jira.camptocamp.com/browse/GSGMF-572.
=> Create layers using custom options metadata

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/oeedit/index.html.ejs, contribs/gmf/apps/oeview/index.html.ejs, contribs/gmf/src/authentication/component.html, contribs/gmf/src/controllers/desktop.scss, contribs/gmf/src/controllers/mobile-nav.scss, contribs/gmf/src/editing/editFeatureComponent.html, contribs/gmf/src/filters/filterselectorcomponent.html, contribs/gmf/src/layertree/timeslider.scss, contribs/gmf/src/lidarprofile/lidarprofile.scss, contribs/gmf/src/permalink/shareComponent.html, contribs/gmf/src/print/component.html, contribs/gmf/src/profile/profile.scss, contribs/gmf/src/query/grid.scss, contribs/gmf/src/query/window.scss, contribs/gmf/src/sass/base.scss, contribs/gmf/src/sass/fullscreenpopup.scss, contribs/gmf/src/sass/map.scss, contribs/gmf/src/sass/popover.scss, contribs/gmf/src/sass/vars_only.scss, contribs/gmf/src/search/search.scss, contribs/gmf/src/theme/selectorComponent.js, src/message/Disclaimer.js, src/message/Notification.js, src/routing/routing.html
GSGMF-418
See also: https://getbootstrap.com/docs/4.0/migration/
=> Scss bootsrap 4

package.json
Url-polyfill is (maybe) useless since: https://github.com/camptocamp/ngeo/pull/4086/commits/80ad2964db4d31383a4988fa3054c219743f4896
Can supersede #4112 If this PR works (I0ll test with gh-pages).
=> Remove url-polyfill

contribs/gmf/src/search/search.less
GSGMF-418
`calc(~"100vh -" 6 * @app-margin);` was too big.
And we can't know (via a variable) the header (logo) size in this file, so I prefers to keep this variable simple and use a simple `vh` unit
=> Fix search tt-menu max height.

contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs, contribs/gmf/src/controllers/desktop.scss, contribs/gmf/src/controllers/mobile.scss, contribs/gmf/src/layertree/common.scss, contribs/gmf/src/layertree/component.html, contribs/gmf/src/print/component.html, contribs/gmf/src/query/window.scss, contribs/gmf/src/query/windowComponent.html, contribs/gmf/src/sass/map.scss, contribs/gmf/src/search/mobile.scss, contribs/gmf/src/search/search.scss, src/sass/font.scss
GSGMF-418
Some icons needs to have specified `font-weight: 900` to be displayed
=> Fix Font Awesome icons

contribs/gmf/less/map.less
When a theme label (in the theme selector popup) is too long it is cropped with a "..." but without the width attribute the text move pushes the icon inside the container. This fixes the icon alignment inside the container while keeping current flex rules for the container styling.
This issue was visible on long labels, mainly long german labels.
=> [2.2] Fix theme selector layout when label is too long

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs
Fix https://jira.camptocamp.com/browse/GSGMF-621
IE11 need URL polyfill and this is not included in the default es6 parameter. This add the last polyfill from the polyfill.io library.
=> More polyfills for IE11 (and print)

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/src/controllers/desktop.scss, contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/import/importdatasourceComponent.html, src/routing/routing.html, src/routing/routing.scss
GSGMF-418
@sbrunner all buttons take 100% of the width in the right panels now (except for the print). Because:
- That was easier.
- Stack of button in the right corner was strange for "login / change password / reset password" and for routing buttons
=> Uniformize buttons in right panel

contribs/gmf/apps/desktop/Controller.js, contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/examples/elevation.html, contribs/gmf/src/raster/component.js, contribs/gmf/src/raster/widgetComponent.html
fix https://jira.camptocamp.com/browse/GSGMF-620
=> Add raster layers unit

contribs/gmf/src/directives/objectediting.js
FIX GEO-1043
Now if you close the tab / the page and have no modification, you'll be able to do it without any warning message on IE11 (was already working like that on other browsers.)
=> Prevent alert in ie11 if there is no changes

contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/controllers/AbstractDesktopController.js
Fixes GSGMF-610.
This fix makes it possible to draw features using the draw tool (a.k.a. red lining) from a desktop application, then copy the `rl_features=zzz` parameter from the url and then open a mobile application, paste the `rl_features` param in it and be able to see the features that were drawn, without the possibility to edit them.
It turned out to be a very simple fix.  Here's a complete explanation why.
Ngeo provides a `ngeoFeatures` angular value, which is an `ol.Collection`.  That value is injected in the GMF draw feature and it is where features are pushed when drawn.
GMF has a permalink module, which is responsible of reading params from the url.  It also injects `ngeoFeatures`, and any features present in the url are automatically pushed in the collection.
Finally, the …
=> Fix 610 - Render drawn features from draw tool in mobile apps

contribs/gmf/src/profile/component.js, src/profile/d3Elevation.js
camptocamp/c2cgeoportal#4121
https://jira.camptocamp.com/browse/GSGMF-629
=> Set nodata values to null and not 0

contribs/gmf/src/drawing/drawFeatureComponent.js
In the drawing tool, a.k.a. "redlining", when we right-click on a feature, make sure to close any existing menu.
=> Fix 645 - Draw feature, close menu

contribs/gmf/src/datasource/ExternalDataSourcesManager.js, examples/importfeatures.js
https://jira.camptocamp.com/browse/GSGMF-628
ExtractStyles options is true by default, if style is defined in the kml openlayers will use
a white border and fill => https://openlayers.org/en/v4.6.5/apidoc/ol.format.KML.html
By setting ExtractStyles to false, the default ol.Style will be used !
=> On kml import force the use of default style

contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/editing/editFeatureComponent.js, src/misc/FeatureHelper.js, src/utils.js
~~Requires #4244 to be merged first.~~
This patch changes the way vertice can be removed from a feature.
The original behaviour was: on left click, delete the vertex immediately.  This is the default behaviour in OpenLayers.
This behaviour has been changed to two ways:
1. on left click + ctrl (cmd on Mac), delete the vertex immediately.
1. on right click, show a menu with the `Delete vertex` item that, when clicked, deletes the vertex
**Approval required** The first behaviour was not originally specifically asked.  It is a suggestion on my end for avanced users that are used to clicking on the vertice directly to remove them.
* GMF drawing tool (a.k.a. redlining)
* GMF editing tool
The way the detection of a vertex work is this: upon hitting a feature with the `contextual` menu event, we …
=> Fix 613 - Delete feature vertex on right click with menu

src/filter/rulecomponent.html
Fixes the issue that occurs in the filter "rule component", i.e. when selecting an attribute in the filter tool, the dropdown menu was not opened.  Clicking on the drop-down list did show the menu, but in the background we had a broken state.
Cause: in Bootstrap 4, the class `show` has to be used on the element with the css class `dropdown-menu`, see (inspect the drop down menu when opened, you'll see the "show" css class name":
https://www.w3schools.com/bootstrap4/tryit.asp?filename=trybs_dropdown-menu&stacked=h
In Bootstrap 3, this was different.  The css class `open` had to be set on the element with the `dropdown` css class.
=> Fix 652 - Bootstrap 4 dropdown-menu use 'show' instead of 'open'

contribs/gmf/src/query/windowComponent.html, options/ngeox.js, src/grid/component.html, src/misc/filters.js
This patch introduces a new filter in ngeo that allows to return a value as trusted HTML in addition to automatically converting http(s) or email strings into anchor html strings.
`StringToHtmlReplacements` is an angular constant that defines expressions that can be converted and a template to use when a string matches.
`ngeoTrustHtmlAuto` is the new filter that does like `ngeoTrustHtml`, but will replace strings with html if a match is found.
Note: Instead of the regex provided in 607 for the email, I used the one from: https://www.regular-expressions.info/email.html, which is lighter when used in a case-insensitive regex and more robust.
=> Fix 607 - Format http(s) links and emails as <a> in query results

contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/controllers/AbstractDesktopController.js
This patch makes sure that the GMF drawing module is loaded in all apps, not only in the desktop ones.
Follow-up of #4243.
=> GMF - Load drawing module in all apps, not only in desktop

src/print/VectorEncoder.js
https://jira.camptocamp.com/browse/GSGMF-658
=> Missing layer param in style function call

contribs/gmf/apps/desktop/index.html.ejs
https://jira.camptocamp.com/browse/GSGMF-641
=> Remove GoogleStreetView from desktop app

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs, contribs/gmf/apps/oeedit/index.html.ejs, contribs/gmf/apps/oeview/index.html.ejs
https://jira.camptocamp.com/browse/GEO-1471
If not explicitly asked, this polyfill is missing from the default provided...
@ger-benjamin I guess that oeview was missing because it was old and we didn't notice ?
=> Add includes polyfill for IE11

contribs/gmf/apps/oeedit/index.html, contribs/gmf/options/gmfx.js, contribs/gmf/src/services/permalink.js
see GEO-1465
Test link: http://localhost:3000/contribs/gmf/apps/oeedit/?&objectediting_geomtype=MultiPoint&objectediting_id=Le%20Mol%C3%A9son&objectediting_layer=113&objectediting_theme=ObjectEditing&objectediting_property=name
(You need to be logged into the demo 2.2 backend)
You can create new links here:
http://localhost:3000/contribs/gmf/examples/objecteditinghub.html
=> Add max-zoom setting for point geometries for oedit permalinks

contribs/gmf/apps/oeedit/Controller.js, contribs/gmf/options/gmfx.js, contribs/gmf/src/permalink/Permalink.js
same as #4279 but for 2.3
Test:
1. Make sure you're logged in here: https://geomapfish-demo.camptocamp.com/2.3
2. `make serve-gmf-apps-oeedit`
3. Open: http://localhost:3000/contribs/gmf/apps/oeedit.html?objectediting_geomtype=MultiPoint&objectediting_id=default_name&objectediting_layer=113&objectediting_theme=ObjectEditing&objectediting_property=name
=> should load on zoom level 10
=> Add max-zoom setting for point geometries for oedit permalinks [2.3]

src/misc/FeatureHelper.js
Fixes https://jira.camptocamp.com/browse/GSGMF-612
In the GMF Drawing tool, when selecting a feature from the list, if the feature would be too big for the current map view extent, then fit the view to the feature instead of just panning to it.
=> Fix 612 - GMF Drawing, zoom out if feature doesn't fit map view extent

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/controllers/desktop.scss
Work in progress
Fix 609 - https://jira.camptocamp.com/browse/GSGMF-609
This patch makes it possible to resize and collapse the left 'data-panel' that is in both GMF desktop apps.
We use the jQuery "resizable" widget to do so.
When the handle is clicked, the "collapse" takes effect, using the ngeo MapResize directive.
* ~change the style of the cursor while mouse hovering to have 2 arrows instead of one pointing right~ No need to do that.
=> [WIP] Fix 609 - Make desktop apps left data panel resizable and collapsible

contribs/gmf/src/drawing/drawFeatureComponent.js, src/misc/FeatureHelper.js
This patch introduces the missing behaviour that was explained in 612 for the GMF drawing tool: if a feature is visible but would not fit the extent of the map if we panned, then zoom out.
The NGEO featureHelper `panMapToFeature` has been renamed to `fitMapToFeature` and the `opt_zoom` option was removed.  It was getting too complex to keep that option, and not really wanted anyway.  Therefore, the goal of the method was no longer only to "pan", but to "pan", "zoom" or "fit" depending on the scenario.
=> 612 - GMF draw - Zoom out when required

buildtools/webpack.prod.js
Currently on my host:
Desktop size: 1954962
Mobile size: 1694458
Real time: 5.08 [min]
CPU time (user + sys): 10.93 [min]
With this pull request:
Desktop size: 1982910 (+6.7%)
Mobile size: 1715072 (+6.8%)
Real time: 3.7 [min] (-27%)
CPU time (user + sys): 5.9 [min] (-46%)
Just by no suppress unused code:
Desktop size: 1982910 (+1.4%)
Mobile size: 1715072 (+1.2%)
Real time: 4.5 [min] (-12%)
CPU time (user + sys): 8.8 [min] (-20%)
No mangle and no suppress unused code::
Desktop size: 3184860 (+63%)
Mobile size: 2805945 (+66%)
Real time: 3.9 [min] (-23%)
CPU time (user + sys): 8.3 [min] (-24%)
Details: [ngeo-build-time.zip](https://github.com/camptocamp/ngeo/files/2505623/ngeo-build-time.zip)
=> Speedup build

examples/backgroundlayer.css, examples/backgroundlayer.js, examples/backgroundlayerdropdown.js, examples/bboxquery.js, examples/measure.js, examples/partials/backgroundlayer.html, examples/partials/backgroundlayerdropdown.html
I saw that this was the preferred solution since you migrated to webpack.
Alternatively, you could use `html-loader` and do something like:
```js
import templateString from './template.html';
exports.myComponent = {
template: templateString
};
```
=> Fix root examples

contribs/gmf/src/directives/partials/layertree.html
cf https://github.com/camptocamp/ngeo/commit/b36783615ecb081d7558ba02b84684602a22dd0b)
backport for project gr_webmap
=> Backport of Update legend on (map resolution) change

contribs/gmf/examples/displayquerygrid.html, contribs/gmf/examples/displayquerywindow.html, contribs/gmf/examples/editfeatureselector.html, contribs/gmf/examples/gmf-hidden.inc.css, contribs/gmf/examples/hidelayertree.inc.css, contribs/gmf/examples/print.html, contribs/gmf/examples/search.css, contribs/gmf/examples/share.html, contribs/gmf/examples/wfspermalink.css, src/Popover.js
This patch includes fixes for the remaining issues with GMF examples (excluding the print one).
* permalink (well, not entirely the permalink, but more a fix to the popover which wasn't working anymore since the upgrade to Bootstrap 4)
* search (color chooser)
* share (emailing popup)
* wfspermalink (was missing FontAwesome css definition)
* missing css file to exclude the layer tree from some of the examples
=> 685 - Fix remaining issues with GMF examples

contribs/gmf/src/permalink/Permalink.js
Fix GSGMF-688: Emit the authenticationrequired event even when the function return prematurely in case layertree is empty.
Fix GSGMF-695: Avoid emitting authenticationrequired event for groups whith no check layers (avoid empty string in groupLayersArray).
=> Permalink authentication required fixes

contribs/gmf/examples/wfspermalink.js, options/ngeox.js, src/statemanager/WfsPermalink.js, test/spec/services/wfspermalink.spec.js
Take the `url` option out of ngeoWfsPermalinkOptions and define as ngeoPermalinkOgcserverUrl instead.
=> 636 - Take url out of ngeoWfsPermalinkOptions

contribs/gmf/src/layertree/component.html
#4230 was merged into master, but we need that in 2.3.
I tested that locally since I am now able to use a local NGEO distribution out of Docker (and this is a little revolution, thanks @sbrunner !!!)
See comments in https://jira.camptocamp.com/browse/GSGMF-625#add-comment for more info !
Please review
=> IE11 distored layer images - backport #4230

contribs/gmf/src/editing/editFeatureComponent.html
I don't know why `$parent` was there, it probably works some time.
But it does not works anymore and `efCtrl` is used directly everywhere in this file since 2 years.
=> Fix error message modal dialog in editFeatureComponent

options/ngeox.js, src/editing/attributescomponent.html, src/format/XSDAttribute.js
Fixes 615: https://jira.camptocamp.com/browse/GSGMF-615
This patch introduces the concept of read-only attributes in the GMF feature editing tool and the XSDAttributes.
Instead of binding a list of read-only attributes in the themes, i.e. using a metadata parameter containing the list of read-only attributes, we went for a definition in the XSD that describes the attributes instead since it was much closer to what the current implementation uses.
Here's an example of how the definition of a readonly attribute is made:
```
<xsd:element minOccurs="0" name="datetime" nillable="true" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<readonly value="true"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
```
The XSDAttribute format parses that property and sets a new `readonly` property in …
=> Fix 615 - Support readonly attributes in editing

api/src/Map.js
Fix https://jira.camptocamp.com/browse/GSGMF-726
As map is not rendered yet when overlay.setPosition is called, overlay is not really positionned.
See: https://github.com/openlayers/openlayers/blob/c6be2c7ff5f6d7b64ec0011e6fc43b6c8e6a1524/src/ol/Overlay.js#L502
So autoPan has bad side effect.
As far as I understand, as we manually set the view center, we do not want to use autoPan on popup when the position is set on overlay, but to see the marker in center of the view.
=> [API] Fix view center after selectObject

src/misc/sortableComponent.js
With this fix the sort features is working again.
I feel it is hard (and has been hard on <=2.2) to use on touch devices because the draggable area  is very small. It may be a good idea to make it larger.
=> Add missing import for jquery-ui touch support

contribs/gmf/src/contextualdata/component.js, contribs/gmf/src/controllers/AbstractAPIController.js, contribs/gmf/src/controllers/AbstractMobileController.js, contribs/gmf/src/datasource/Helper.js, contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/editing/editFeatureComponent.js, contribs/gmf/src/filters/filterselectorComponent.js, contribs/gmf/src/layertree/TreeManager.js, contribs/gmf/src/permalink/Permalink.js, contribs/gmf/src/print/component.js, contribs/gmf/src/profile/component.js, contribs/gmf/src/search/component.js, contribs/gmf/test/spec/services/permalinkservice.spec.js, src/filter/RuleHelper.js, src/filter/ruleComponent.js, src/format/FeatureHash.js, src/interaction/MeasureLengthMobile.js, src/interaction/MeasurePointMobile.js, src/misc/FeatureHelper.js, src/print/Service.js, src/profile/d3Elevation.js, src/profile/elevationComponent.js, src/query/MapQuerent.js, src/query/Querent.js, src/search/createGeoJSONBloodhound.js, src/search/createLocationSearchBloodhound.js
The `assign` function from ol is already a polyfill for `Object.assign` but we're
loading this polyfill from polyfill.io: https://polyfill.io/v2/docs/features/#default-sets
=> Stop using 'assign' function from ol

src/services/print.js
Fix https://github.com/camptocamp/aeroportdelyon_sig/issues/443.
`for (const element of URL.searchParams)` is not supported by IE11 even with url-polyfill.
=> Fix issue with print and IE 11.

contribs/gmf/apps/oeedit/index.html, contribs/gmf/src/directives/objectediting.js, contribs/gmf/src/directives/objecteditingtools.js
FIX https://jira.camptocamp.com/browse/GEO-1652
Now if  the objectediting tool is deactivated, it's not possible anymore to edit the feature.
(Easier to understand commit per commit).
(currently corners are style displayed, even if we can't move them anymore. It's not very nice, but it causes no problem)
=> Be able to disable oeedit

buildtools/webpack.commons.js, package.json
Unmaintained ans have some incompatibility issues with Dll plugin.
I get error like:
```
ERROR in chunk oeedit [entry]
oeedit.085aa7.js
/usr/lib/node_modules/babel-loader/lib/index.js??ref--13!/src/geoportal/demo_geoportal/static-ngeo/js/apps/Controlleroeedit.js
e4de6c920a5f4bbd861837c15c7a4eec
Unexpected token (1:95)
| /* harmony default export */ var __WEBPACK_MODULE_DEFAULT_EXPORT__ =
(undefinedfunction (o, i) {
|   return o.interfaces_ && o.interfaces_.indexOf(i) > -1;
| });
```
See also:
https://github.com/mzgoddard/hard-source-webpack-plugin/issues/443
=> Remove HardSourceWebpackPlugin

CHANGES.md, contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/iframe_api/index.html.ejs, contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs, contribs/gmf/apps/oeedit/index.html.ejs, contribs/gmf/apps/oeview/index.html.ejs, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/controllers/bootstrap.js
No inline script
No Javascript on server side
=> Get setting from JSON

options/ngeox.js, src/misc/FeatureHelper.js, src/query/Action.js, src/query/Keyboard.js, src/query/MapQuerent.js, src/query/bboxQueryComponent.js, src/query/mapQueryComponent.js
https://jira.camptocamp.com/browse/GSGMF-667
This patch introduces the concept of "actions" within the query tool (i.e. within the map and bbox querent components, the map querent and querent) using pressed keyboard keys.
- on click - the results are replaced
- on box query (ctrl) - the results are replaced
- on click while holding the "a" key - the results are added to the existing ones
- on bbox query while holding the "a" key (ctrl + a) - the results are added to the existing ones
- on click while holding the "x" key - the results are removed from the existing ones
- on bbox query while holding the "a" key (ctrl + x) - the results are removed from the existing ones
=> 667 - Multiple selection in Query

contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs, contribs/gmf/src/controllers/AbstractMobileController.js, src/datasource/DataSource.js, src/datasource/OGC.js, src/interaction/MeasureAreaMobile.js, src/rule/Rule.js
Remove getter/setter functions when a variable can be used instead.
=> Code simplifications

src/query/MapQuerent.js
Fix total when keep is true.
Without this, when removing from selection, after handleResult_, total is < 0 so selection is not shown.
=> Fix total in MapQuerent.clear when keep is true

contribs/gmf/src/query/window.less, src/message/displaywindowComponent.js
#4471 is not working, because, IHMO, we need to call the function and not just define it in the watcher.
I tested that in my project and it seems to work.
Could somebody please review that and eventually merge it, because I really need it inside 2.3...
Thanks a lot.
=> Fix #4471 - Call the function in watcher

contribs/gmf/src/directives/partials/layertree.html
This is #4230 for the 2.2 branch.
=> Fixes distored images in IE11 by wrapping img in div

contribs/gmf/src/controllers/abstract.js
If no theme is set, the setDefaultBackground_ method was not called.
Now it's called on each login action.
GEO-1722
=> Set bg layer on login

options/ngeox.js, src/services/mapquerent.js, src/services/querent.js
To be able to access the bbox of the queried zone in a MapFile.
GEO-1746
=> Add a option to send bbox as GET param of getfeature requests

contribs/gmf/src/controllers/AbstractAppController.js, options/ngeox.js, src/query/MapQuerent.js, src/query/Querent.js
The new one (supersede #4569 )
=> Merge 2.2 into 2.3

contribs/gmf/src/controllers/AbstractDesktopController.js, src/message/popoverComponent.js
The name was changed between version 3 and 4:
https://getbootstrap.com/docs/4.0/components/tooltips/#methods
https://getbootstrap.com/docs/4.0/components/popovers/#methods
=> Call dispose on tooltips and popovers

src/misc/WMSTime.js
Fix https://jira.camptocamp.com/browse/GSGMF-772
=> Add user friendly format for second resolution

contribs/gmf/src/layertree/component.js, contribs/gmf/src/layertree/timeSliderComponent.js, contribs/gmf/src/lidarprofile/Config.js, contribs/gmf/src/lidarprofile/Manager.js, contribs/gmf/src/lidarprofile/Measure.js, contribs/gmf/src/lidarprofile/Plot.js, contribs/gmf/src/lidarprofile/Utils.js, contribs/gmf/src/lidarprofile/panelComponent.js
=> More typecheck fixes for gmf

src/query/Keyboard.js, src/query/bboxQueryComponent.js, src/query/mapQueryComponent.js
This patch introduces a new way to deal with addition / removal of query results.  With this patch, while the user presses the "A" or "X" key, the map can either be clicked or have a box being drawn to either add or remove features to/from the query results.
In order to do that, the Keyboard class has been changed to a angular service to make its `action` getter watchable.  Then, in the bboxQuery directive, an extra section has been added to automatically add an OpenLayers DragBox interaction on top of all others to make it the active interaction while the user presses the "A" or "X" key.  The same handler is used to issue a request to the map querent, so nothing new needs to be done other than that.
=> 752 - Alternate way to deal with query ADD and REMOVE

contribs/gmf/src/datasource/Helper.js, contribs/gmf/src/datasource/OGC.js, contribs/gmf/src/datasource/WFSAliases.js, contribs/gmf/src/editing/Snapping.js, contribs/gmf/src/editing/editFeatureComponent.js, contribs/gmf/src/filters/SavedFilters.js, contribs/gmf/src/filters/filterselectorComponent.js, contribs/gmf/src/import/importdatasourceComponent.js, contribs/gmf/src/import/wmsCapabilityLayertreeComponent.js, contribs/gmf/src/import/wmtsCapabilityLayertreeComponent.js, contribs/gmf/src/layertree/SyncLayertreeMap.js, contribs/gmf/src/layertree/TreeManager.js, contribs/gmf/src/layertree/component.js, contribs/gmf/src/themes.js, contribs/gmf/test/spec/services/syncLayertreeMap.spec.js, src/datasource/Helper.js, src/datasource/OGC.js, tsconfig.json
As title says.
I noticed that the getter/setters `filterCondition` for ngeo/datasource/OGC have been removed.  Why?
=> Even more typecheck fixes for gmf

contribs/gmf/src/authentication/Service.js, contribs/gmf/src/controllers/AbstractAPIController.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/controllers/AbstractMobileController.js, contribs/gmf/src/controllers/bootstrap.js, contribs/gmf/src/datasource/ExternalDataSourcesManager.js, contribs/gmf/src/datasource/Helper.js, contribs/gmf/src/datasource/Manager.js, contribs/gmf/src/datasource/OGC.js, contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/drawing/featureStyleComponent.js, contribs/gmf/src/search/component.js, contribs/gmf/src/themes.js, package.json, src/filter/RuleHelper.js
This patch fixes the remaining type issues in GMF.
Following @fredj recommendation, I copied the properties from ("ngeo/datasource/OGC.js").OGCOptions to ("gmf/datasource/OGC.js").OGCOptions, because typescript doesn't currently support inheritence of objects for typing purpose.
There are also 2 remaining errors that I don't know what to do about.  They are about the use of DocumentTouch property, which seems to be deprecated.  I suspect this is something that needs to be addressed (and not just ignored using ts-ignore). Here they are:
```
contribs/gmf/src/controllers/bootstrap.js:24:65 - error TS2339: Property 'DocumentTouch' does not exist on type 'never'.
24       if (small_screen && (('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch)) { …
```
=> Fix remaining typechecks in gmf

contribs/gmf/src/controllers/bootstrap.js
Note: the `TOUCH` variable only checks for touch events support
=> Use ol.has.TOUCH to check if the device support touch events

contribs/gmf/examples/search.js, examples/disclaimer.js, examples/notification.js
=> Don't use angular.element for notify target element

src/message/popoverComponent.js
This patch changes the popover component to make it dismiss on body click instead of body mousedown.
It also fixes the unlistening (`off`) which given the wrong method (`on` was using an anonymous method returned by bind, `off` was using the original one).  Now they both use the same.
=> Dismiss popover on click instead of mousedown

contribs/gmf/src/directives/print.js
Bind values in `onInit` + the code to check if a legend exists in the layout is useless because there is always values for legend (so the initial state of the checkbox was always to true and not configurable)
=> Can set rotate maske and disable legend per default

contribs/gmf/src/sass/base.scss, src/message/modalComponent.js
=> Add new ngeo-draggable-handle option to modalComponent

contribs/gmf/src/authentication/Service.js, contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/print/component.html, contribs/gmf/src/print/component.js, contribs/gmf/src/print/print.scss, src/print/Service.js, src/print/mapfish-print-v3.js
This patch introduces sending a printed file using the GMF Print tool to an email.  The specs are described in this task: https://jira.camptocamp.com/browse/GSGMF-738
It is not yet completed, as there are things remaining to do:
=> GMF Print - support sending printed file to email

contribs/gmf/src/print/component.js
In the GMF Print component, when the user chooses to receive the file by email, then do not get the status of the report.  Instead, show a message telling him that he'll receive the file by email soon, and reset the state of the print component.
=> GMF Print - When sending by email, don't get status

contribs/gmf/src/contextualdata/component.js
With the option `gmfContextualdataOptions`:
```json
{
"rasterParams": {
"layers": "srtm"
}
}
```
Fix https://jira.camptocamp.com/browse/GSGMF-781
=> Be able to limit layers on raster service

buildtools/webpack.commons.js, contribs/gmf/src/print/component.js
Fix https://jira.camptocamp.com/browse/GSGMF-788
=> Fix QGIS legend in print

src/query/Querent.js
A logical regression was introduced in ngeo Querent while fixing types, which resulted in requests not working unless wfsCount was enabled.
This fix reverts this regression, making the code behave like before.
=> Fix regression in Querent

contribs/gmf/src/controllers/desktop.scss
Fixes:
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt.html
=> Don't wrap text in dropdown

contribs/gmf/src/editing/EditFeature.js, contribs/gmf/src/editing/editFeatureComponent.js
`application/geo+json` is the type returned by the service:
https://geomapfish-demo-dc.camptocamp.com/2.4/layers/112
No need to send the `Content-Type` for the `delete`.
=> Use application/geo+json instead of application/json

contribs/gmf/src/query/gridComponent.js
Fixes the GMF query grid to support addition of features.
Before, since it was not possible to add new features, checking the total number of features and look for `0` as a way to make the grid pending was a good way to hide it or make it work (pending).  Now, features can be kept in the results, and the total may be > 0, which broke the logic.
This fix proposes that while the results are pending, we treat the grid as if it had 0 result (i.e. pending).
=> Fix GMF query grid to support adding result

contribs/gmf/src/datasource/Manager.js
This patch fixes the filters component, more specifically when applying a filter.
The bug why it wasn't working anymore is simply because the OpenLayers getUid utils method used to return numbers.  Now, it returns strings.  There were a lot of places in ngeo/gmf that this value was used as number and was automatically changed as string, but that caused errors.  Some of them were reverted like what they were before: numbers.
However, this caused a simple logic issue with the filter while checking onto what data source to apply it.  Casting it to string then does the trick.
=> Fix apply filter

src/print/Service.js
The ngeo print service is responsible of creating the specs for the print request, which includes the layers to print in a specific order: by zIndex.  The issue was that the layers were not ordered properly.
After investigating, it turns out that the method responsible for ordering by zIndex was not working properly due to undefined values returned some of the layers z indexes.  Marking those as `0` made the method worked properly and the order correctly set from there on.
=> Fix print layer order

contribs/gmf/src/editing/editFeatureComponent.js
In the GMF feature editing tool, while trying to stop editing when there a feature is selected and dirty, a modal opens asking for confirmation.  In the process of applying the cancel, the modal gets hidden with an animation for a short period of time.  If we cancel right away, the modal gets destroyed while animating and the result is we have the modal backdrop still there.
This patch lets the modal do its animation then apply the cancel.
=> 793 - Fix GMF edit feature stop editing while dirty

contribs/gmf/src/controllers/abstract.js
Currently, the updateCurrentTheme_ call happens before the  loadThemes call. This is problematic if you log in as an user who has a default theme that is non-public. At the time updateCurrentTheme_ gets called, this non-public theme is not available. It will be, after the loadThemes call has finished. That's why updateCurrentTheme_ should happen after loadThemes.
=> [2.2] Update current theme after loadThemes call is done

contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/editing/editFeatureComponent.js, examples/googlestreetview.js, examples/rotate.js, src/filter/ruleComponent.js, src/routing/RoutingFeatureComponent.js, test/spec/services/print.spec.js
Use `Font Awesome 5 Free` instead of `FontAwesome` and weight `900` instead of `normal` (alias to `400`)
=> Fix font name used in OpenLayers text style

contribs/gmf/src/controllers/mobile.scss
The container of the messages in the mobile apps were partially rendered on top of the measure tools, which resulted in some of the buttons not working.  To fix this, the container is moved up in this patch.
I've noticed an other issue while working on that.  There was an extra message being shown, a link saying that "you're in the mobile version, go in the desktop version" which was hidden using opacity to 0.  That means that you were able to click on the link even if you couldn't see it and end up in an other page.  I think this could be considered as a bug.  Also, it left a big empty gap as well.
Instead of the opacity, I made it invisible using display:none only if it should be hidden.
=> Fix app map messages on mobile

src/message/displaywindowComponent.html
For version 2.3
An issue happened with ngeo displaywindow components in desktop apps.  A title was being shown with `mainCtrl.displaywindowTitle` as content when mouse hovering any of its content (close button, header, container, etc.)
```
gmfx.openIframePopup('page.html', 'My page', 500, 400);
```
This happens because the one of the component's options is `title`, which is a reserved attribute in HTML:
```
<ngeo-displaywindow
content="mainCtrl.displaywindowContent"
desktop="true"
draggable-containment="mainCtrl.displaywindowDraggableContainment"
height="mainCtrl.displaywindowHeight"
open="mainCtrl.displaywindowOpen"
title="mainCtrl.displaywindowTitle" <------
url="mainCtrl.displaywindowUrl"
width="mainCtrl.displaywindowWidth"
></ngeo-displaywindow>
```
To bypass this issue, setting …
=> Fix unwanted title in ngeo displaywindow component

contribs/gmf/src/search/component.js, src/search/searchDirective.js
In the GMF search component, when there are no results found after a query, an item "No result found" is added.  When clearing the query to an empty text, then clickout the search tool and then go back in, the message is still there.
This patch fixes this issue by listening the the typeahead `change` event and do an extra check there in case the query string is empty.
=> Fix search to remove 'No result' on change and empty query

buildtools/webpack.commons.js
When the only changes are HTML or CSS the hash was not updated.
This commit should fix the issue.
=> Fix CSS caching issue

contribs/gmf/src/query/gridComponent.js, contribs/gmf/src/query/windowComponent.js
I need this to be able to extend a controller in a project.
=> Export query window and grid controllers, to be able to extend them

contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/theme/Manager.js
To keep things simple, I simply reload current theme when in flush mode and no default_theme for the user.
This have no impact on "not flush" mode.
=> In flush mode load current theme private groups on login

contribs/gmf/src/print/component.js, contribs/gmf/src/themes.js
911
Fix: https://jira.camptocamp.com/browse/GSGMF-911
=> Fix image URL with QGIS server, allows to have hi DPI

contribs/gmf/src/query/windowComponent.js
Bugfix from #4852
> I wanted to show a different cursor if there is a pending map query. But query/windowComponent (formerly displayquerywindow) keeps clearing ngeoQueryResult right after MapQuerent.issue() gets called. This clearing is not distinguishable from a unsuccessful query.
=> Don't overwrite possibly pending ngeoMapQuerent state [2.3]

contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/layertree/TreeManager.js, contribs/gmf/src/theme/Manager.js, src/statemanager/Service.js
Fix https://jira.camptocamp.com/browse/GSGMF-962
=> Removes unneeded already loaded layer

api/src/Themes.js
```js
const map = new Map();
console.log('item' in map);
map.set('item', 'yes !')
console.log('item' in map);
```
prints:
```js
false
false
```
:cry:
=> Don't use 'in' operator with Map

contribs/gmf/src/datasource/ExternalDataSourcesManager.js, contribs/gmf/src/datasource/Manager.js, contribs/gmf/src/datasource/OGC.js, contribs/gmf/src/datasource/WFSAliases.js, contribs/gmf/src/filters/filterselectorComponent.js, contribs/gmf/src/permalink/Permalink.js, examples/bboxquery.js, examples/mapquery.js, src/datasource/Helper.js, src/datasource/OGC.js, src/datasource/WMSGroup.js, src/map/LayerHelper.js, src/query/Querent.js
Fix: https://jira.camptocamp.com/browse/GSGMF-995
=> Fix query on a WMS layer group

README.md
Old HTTP links don't get a response anymore.
=> Example links only work with HTTPS now

buildtools/svg-viewbox-loader.js, buildtools/webpack.dev.js, buildtools/webpack.prod.js, contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/apps/desktop_alt/image/crosshair.svg, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/src/drawing/drawFeatureComponent.html, contribs/gmf/src/editing/editFeatureComponent.html, contribs/gmf/src/import/wmsCapabilityLayertreeComponent.html, contribs/gmf/src/layertree/component.html, contribs/gmf/src/layertree/datasourceGroupTreeComponent.html, contribs/gmf/src/permalink/Permalink.js, examples/font.svg, examples/inline.svg, examples/svg.css, examples/svg.html, examples/svg.js, package.json
To test:
https://camptocamp.github.io/ngeo/svg-more-flexible/examples/contribs/gmf/apps/desktop.html?map_crosshair=true
https://camptocamp.github.io/ngeo/svg-more-flexible/examples/contribs/gmf/apps/desktop_alt.html?map_crosshair=true
https://camptocamp.github.io/ngeo/svg-more-flexible/examples/svg.html
=> Try to be more flexible and less magic by default

contribs/gmf/apps/appmodule.js, contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/src/floor/floorselectorComponent.js
See also:
https://github.com/camptocamp/c2cgeoportal/pull/5137
=> Fix and simplify floors injections

contribs/gmf/src/backgroundlayerselector/component.js
The value can be a string or undefined, not null.
=> Fix val type in getSetBgLayerOpacity function

contribs/gmf/src/import/import.scss, contribs/gmf/src/import/importdatasourceComponent.html, contribs/gmf/src/import/importdatasourceComponent.js, contribs/gmf/src/map/mousepositionComponent.html
By using the custom-file-input from Bootstrap:
https://getbootstrap.com/docs/4.3/components/input-group/#custom-file-input
=> Simplify file input in import datasource component

src/editing/createregularpolygonfromclickComponent.js, src/interaction/DrawRegularPolygonFromClick.js
See also: https://jira.camptocamp.com/browse/GSTBA-46
Test: https://camptocamp.github.io/ngeo/fix-triangle/examples/contribs/gmf/apps/oeedit.html?objectediting_geomtype=MultiPolygon&objectediting_id=Test&objectediting_layer=112&objectediting_theme=ObjectEditing&objectediting_property=name&tree_groups=ObjectEditing
=> Fix triangle in object editing

src/interaction/DrawAzimut.js
=> Fix geometry validity test in DrawAzimut

api/src/Map.js
Fix https://jira.camptocamp.com/browse/GSGMF-1085
=> GSGMF-1085: api query fix

contribs/gmf/src/editing/Snapping.js, contribs/gmf/src/layertree/component.html, contribs/gmf/src/layertree/component.js, contribs/gmf/src/theme/Themes.js, contribs/gmf/src/themes.js
https://jira.camptocamp.com/browse/GSGMF-1035
Test link : https://camptocamp.github.io/ngeo/gsgmf-1035-improve_snapping/examples/contribs/gmf/apps/desktop_alt.html?dim_FLOOR=*&lang=fr&tree_groups=Edit%2CSnapping%2CSnapping%20tollerance%2CSnapping%20no%20edge%2CSnapping%20no%20vertex&baselayer_ref=OSM%20map&baselayer_opacity=100&tree_group_layers_Snapping%20tollerance=Snapping%20tollerance%2Cpoint%20snap%20tolerance%2Cline%20snap%20tolerance%2Cpolygon%20snap%20tolerance
Activate or deactivate snapping on some layers and give a try to "Draw and measure".
=> Improve snapping

contribs/gmf/src/layertree/TreeManager.js, contribs/gmf/src/layertree/datasourceGroupTreeComponent.html, contribs/gmf/src/theme/Manager.js
Not really happy with this fix.
Initially I wanted to just set a boolean but refreshFirstLevelGroups_ function is called after and modify the firstLevelGroups variable that is used in the function addFirstLevelGroups called in the process of user change. That means that I don't get the full array of current groups to reload but just a set after the modification, and I was forced to save it at user change in a separate variable to keep its current state (in this.initialLevelFirstGroups_).
Fix: GSGMF-1086
=> Reorder private groups

buildtools/webpack.dev.js, contribs/gmf/src/backgroundlayerselector/component.js, src/map/BackgroundLayerMgr.js
see: https://github.com/camptocamp/ngeo/pull/5101
fix: https://jira.camptocamp.com/browse/GSGMF-1102
=> Fix the opacity slider, don't download unneeded tiles

buildtools/check-example.js
https://jira.camptocamp.com/browse/GSGMF-1090
=> In check-examples.js allow all requests to urls that match page hostname

docs/guidelines.md, utils/ios-overlap-fix.js
See also https://github.com/camptocamp/ngeo/pull/5117
=> Some spell fixies

examples/query.css, examples/query.html, examples/query.js, src/datasource/Helper.js, src/events.js, src/query/MapQuerent.js, src/query/Mode.js, src/query/ModeSelector.js, src/query/component.js, src/query/module.js
This patch is the first step towards implementing a new way to query the map by drawing polygons.
This patch introduces:
* a new `QueryModeSelector` service that:
* will replace the `QueryKeyboard` service
* stores the **mode** of the queries, i.e. "click", "draw_box", "draw_polygon"
* stores the **action** of the queries, i.e. "add", "remove", "replace"
* listens to the keyboard key pressed to temporarily change the mode or action
* a new `<ngeo-query>` component that:
* will replaces the `<ngeo-map-query>` and `<ngeo-bbox-query>` directives
* uses the new query mode selector
* uses a Draw interaction to draw the boxes (instead of DragBox in the original mapquery directive)
* a new ngeo "query" example that features the component, in which you can see it in action, with all the modes …
=> Introduce a new query component and example

examples/query.js
This patch fixes the ngeo query example to use projection 2056.
=> Fix query example projection - 2056

contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/editing/editFeatureComponent.js, src/draw/Controller.js, src/editing/createfeatureComponent.js, src/interaction/Measure.js
https://jira.camptocamp.com/browse/GSEPF-259
=> Press escape to desactivate drawing in edition

src/datasource/OGC.js, src/filter/RuleHelper.js, src/query/Querent.js, src/query/component.js, src/query/panelComponent.html
This patch is the last step towards implementing a new way to query the map by drawing polygons, as it is included in the patch.
The query component now includes a drawfeature interaction that uses polygon type. A button is also added in the query panel tool.
In the Querent service, the polygon is given as an option (like a coordinate or box could be given) and transformed into a Spatial Filter that is added to the WFS request sent.
In the filter/RuleHelper, a method is introduced to "join filters", i.e. given two filters (both of which can be null), wrap them in an AND filter, if necessary.
=> Introduce polygon query

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop/sass/desktop.scss, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/desktop_alt/sass/desktop_alt.scss, contribs/gmf/src/filters/filterselectorComponent.js, contribs/gmf/src/filters/filterselectorcomponent.html, src/filter/component.html, src/filter/component.js
https://jira.camptocamp.com/browse/GSGMF-1044
=> Filters stay active when panel closed/open

src/filter/ruleComponent.js
In the filter tool, drawing a feature on the map did nothing  The issue comes from the RuleComponent, which is not longer doing anything upon being activated.
The watcher on the "active" property of the rule has been wrongly changed to always return `false` instead of the intended value.  This regression was introduced in 6d38eed1c249a8d3624eeb8ab2a3248c5b508d16
This patch fixes the issue.
=> Fix spatial filter issue

contribs/gmf/src/sass/swipe.scss
This patch fix  styling issues; 
1) The vertical swiper is working on Windows Firefox.
2) The vertical bar is correctly positionned on the limit. 
3) The vertical bar touch the top of the map.
https://camptocamp.github.io/ngeo/T9224-1-mapswipe-firefox/examples/contribs/gmf/apps/desktop.html
=> Fix swiper styling issues.

contribs/gmf/src/index.js, contribs/gmf/src/layertree/SyncLayertreeMap.js, contribs/gmf/src/permalink/Permalink.js, contribs/gmf/src/theme/Themes.js, src/map/LayerHelper.js
This patch introduce 'mapswipe'  as a parameter for the permalink service.
=> Support MapSwipe in Permalink

.travis.yml, buildtools/check-example.js, examples/elevationProfile.js
* Don't cancel request when it's used in a checker.
* Better fileMock.
* Remove `process.exit(2);` in request finish.
* Use https for wms.geo.admin.ch.
* `request.abort('aborted');` => `request.abort('failed');` to have errors...
=> Fix request abort 

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop/sass/desktop.scss, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/desktop_alt/sass/desktop_alt.scss, contribs/gmf/src/controllers/AbstractDesktopController.js
In the "desktop" and "desktop_alt" applications, when there is an actual filter being set onto a layer in the filter tool, then change the icon of the filter in the toolbar.
This replaces the behaviour of having the background being changed instead.
Also, the icon is only changed while the filter is in action, where the background color was always there even if the filter was not active.
##Technical details
In order to do so, we look for the "gmfDataSourceBeingFiltered.dataSource" value, which is the data source being filtered and if it has filters, then its `filterRules` won't be null.
=> While filter is active, change toolbar icon

contribs/gmf/src/authentication/Service.js, contribs/gmf/src/authentication/component.html
Requires: https://github.com/camptocamp/c2cgeoportal/pull/5356
=> Support intranet users

contribs/gmf/src/layertree/SyncLayertreeMap.js, contribs/gmf/src/theme/Themes.js, src/map/LayerHelper.js
When creating WMTS layer, the min/max resolutions are set as min/max resolutions metadata. In the desktop_alt application, the 'Alpine convention' layer has a minResolution of 10 and a maxResolution of 100.
=> WMTS layers get metadata limits

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/src/sass/swipe.scss, src/map/swipe.html, src/map/swipe.js
This patch introduce the close button to the map swiper. By clicking on it, the swiper closes
=> Introduces close button to the swiper

src/datasource/OGC.js, src/format/ArcGISGeoJSON.js, src/query/Querent.js
This patch introduces the support of WMS GetFeatureInfo requests made on WMS layers served by ArcGIS.
A GeoJSON format is used as INFO_FORMAT, since it seems to be the only one supported by ArcGIS.  The format returns a `layerName` property for each feature, which identifies the layer it corresponds to.  In order to read that information, a custom `ngeo.format.ArcGISGeoJSON` format is created in this patch.
* run the desktop_all app
* clear all layers
* select the "Demo" theme
* remove all groups with the exception of "Externals"
* set visible the following layer: NPA localite noWFS
* zoom out / pan the map until you see the layer (yellow lines)
* click on features
* --> you should get results in the grid below
ArcGIS (at least with the layer used in the test above) does not return …
=> Support ArcGIS WMS GetFeatureInfo requests using GeoJSON format

src/array.js, src/datasource/OGC.js
~~This tiny patch fixes the duplicates that we had in the query results due to the fact that the WFS layers were not being pushed in the proper array.~~
~~So, if the wms and wfs layers were the same, they were duplicated.  In some cases, wms use a layer "group" as name, but wfs uses layer names, so this may explain why there were not duplicates sometimes.~~
**Update**: This patch now properly fixes the listing of wms layer names to be used for query result.
=> Fix duplicate WMS query results

contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/editing/editFeatureComponent.js, src/draw/Controller.js, src/editing/createfeatureComponent.js, src/interaction/Measure.js, src/interaction/Rotate.js, src/interaction/Translate.js, src/utils.js
When clicking escape while a mouse button is in the 'mousedown' state
the OpenLayers interactions can be messed up (polygons).
This commit avoids the described situation.
=> Workaround escape while clicking issue

contribs/gmf/src/layertree/component.js, src/map/swipe.js
While a layer is being swiped (in the map swipe tool), if it is turned off (visible: false) or removed from the map, then deactivate the map swipe tool.
=> Close map swipe when layer is turned off or removed

src/query/Querent.js
This patch disables the `wfsCount` setting of the query tool (Querent).
In other words, the query `queryCountFirst` is forced to false as part of this patch as a temporary mean to force WFS queries to be always made, even if they would exceed their "limit" set.
This change should be reverted the day we come up with a better solution to allow queries onto WFS layers that would exceed their limit.
=> Disable query wfsCount

contribs/gmf/src/controllers/desktop.scss, contribs/gmf/src/drawing/drawFeatureComponent.html, contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/drawing/drawFeatureOptionsComponent.html, contribs/gmf/src/drawing/drawFeatureOptionsComponent.js, contribs/gmf/src/drawing/module.js, src/draw/Controller.js, src/draw/component.js, src/draw/point.js, src/draw/rectangle.js, src/draw/text.js, src/measure/area.js, src/measure/azimut.js, src/measure/length.js
This patch introduces a new component in GMF to specify sizes (length, width, height, radius) while drawing features in the draw tool.
A new component is born: gmf-drawfeatureoptions
The parameters it must have are:
* the OpenLayers map
* a single interaction responsible to draw the feature (can be a measure interaction from ngeo, or an OpenLayers Draw interaction directly)
The behaves according to the type of interaction it was given.  The possible ones are:
* the ngeo length measure interaction
* the ngeo area measure interaction
* the ngeo azimut measure interaction
* a draw interaction (used to draw rectangles)
The Snap interaction of OpenLayers is used as main way to force the drawing tool to "snap" to an invisible grid while drawing and while sizes are set.
A single feature is …
=> Support defining size of features in GMF draw tool

contribs/gmf/src/layertree/component.html, contribs/gmf/src/layertree/component.js, contribs/gmf/src/themes.js
https://jira.camptocamp.com/browse/GSGMF-1161
This fix allows a node to be removed from layertree as well as its associated popup menu if existing.
I had to add a new ID to HTML element to easily find the attributes I needed to extract. Popup identifier is created randomly at each new opening and is not consistent when closing/opening the menu.
I added this popup identifer to a optional custom attribute in the GMF group and retrieve it when I want to target the existing popup.
I use UID over ID, as these last are duplicated when a single layer is in several groups loaded in the layertree. If I don't I'm not able to select the correct html element.
=> Close associated popup submenu at layertree removal

contribs/gmf/src/profile/component.js
This patch fixes the GMF profile tooltips, which were not working since a regression was introduced in 6d38eed1c249a8d3624eeb8ab2a3248c5b508d16.
The extra "if" makes no sense there, because the code that would create the elements is inside the if and therefore no tooltips were ever created.
=> Fix GMF profile tooltips

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs, contribs/gmf/src/authentication/component.html, contribs/gmf/src/authentication/component.js, contribs/gmf/src/icons/spinner.svg, contribs/gmf/src/import/importdatasourceComponent.html, contribs/gmf/src/import/importdatasourceComponent.js, contribs/gmf/src/layertree/component.html, contribs/gmf/src/permalink/shareComponent.html, contribs/gmf/src/permalink/shareComponent.js, contribs/gmf/src/print/component.html, contribs/gmf/src/profile/component.html, contribs/gmf/src/profile/component.js, contribs/gmf/src/profile/drawLineComponent.js, contribs/gmf/src/profile/profile.scss, contribs/gmf/src/query/grid.scss, contribs/gmf/src/query/gridComponent.html, contribs/gmf/src/query/gridComponent.js, contribs/gmf/src/raster/widgetComponent.html, contribs/gmf/src/sass/base.scss, contribs/gmf/src/search/search.scss, contribs/gmf/src/spinner/directive.js, contribs/gmf/src/spinner/loader.scss, contribs/gmf/src/spinner/module.js, src/search/searchDirective.js
List of changes and status:
Out of scope (find alternative implementation) in another PR:
=> Loading notifications

contribs/gmf/src/layertree/SyncLayertreeMap.js, contribs/gmf/src/permalink/Permalink.js, src/map/LayerHelper.js
The WMTS layers are created in a way that their properties get asynchronously set, i.e. after WMTS capabilities are obtained.
The setting of the layer's initial visibility can be done before that, which can result in an issue of overriding the visibility after the capabilities are read, i.e. the created layer while reading the capabilities has its visible property set to true, but the original one may have its visible property to false.
To fix this issue, an utility method was added in the LayerHelper of ngeo to be able to exclude the keys we know we don't want to copy.
=> Do not copy 'visible' property for WMTS layers

contribs/gmf/src/themes.js, src/datasource/Helper.js, src/datasource/OGC.js
The main goal of this patch is to introduce the support of filtering a WMS layer that uses a group as layer name.
To accomplish this, the following change was made.
The creation of attributes within an OGC data source object is made by first checking if there are attributes set for the layers used by the data source in the inner `ogcLayers_` property.  Then, they are combined together, i.e. only the attributes that are commonly shared in all layers are kept.
From there, the rest works as usual.
~~There is an issue with this approach.  To resume: it is currently not supported by MapServer to give the name of the group in the LAYERS parameter while giving only one filter in the FILTER property.  Therefore, this patch breaks the MapServer WMS layers in those cases.~~
~~More about this issue …
=> Support layer group filtering

contribs/gmf/src/datasource/Manager.js, contribs/gmf/src/themes.js, src/datasource/OGC.js
With the introduction of #5250 (Support layer group filtering), a WMS data source that use a "group" as WMS layer can have multiple inner WFS layers, each of which get filtered properly.
However, an issue occurs when we try to query such a data source: we get duplicate records.  More precisely, we have 1 set or records per WFS layer.  For example, in a group "hotel_filter", which groups 2 layers: "hotel" and "hotel_layer", we have 2 sets of results, one for "hotel" and one for "hotel_layer".
We should have only one.
~~It is assumed that a WMS data source that uses a group layer should only have ONE of its inner WFS layer to return data when queries are issued.~~ It's okay to have multiple inner layers within a group that can return data.
It is assumed that all WFS layer within a group can …
=> Read queryLayers metadata for WMS data source

contribs/gmf/apps/iframe_api/index.html.ejs
https://jira.camptocamp.com/browse/GSGMF-1192
I added the new loading notification for the missing iframe API interface.
@sbrunner Do you know if there is any other missing spinner ?
=> Change loading spinner for iframe api interface

Makefile
See: https://camptocamp.github.io/ngeo/api-link/examples/
=> Add link to api help page

src/statemanager/WfsPermalink.js
The following change was made automatically by 6d38eed1c249a8d3624eeb8ab2a3248c5b508d16:
```
-   if (size !== undefined) {
+   if (size !== undefined && this.pointRecenterZoom_ !== undefined) {
```
This change breaks the recentering on a feature in the WFS service due to the fact that `pointRecenterZoom_` becomes mandatory.  It should stay optionnal.
This patch reverts this change, fixing the issue.
=> Revert regression introduced in ngeo WfsPermalink service

api/dist/apihelp/apihelp.html, api/src/Themes.js, api/src/constants.js
Fix API help coordinates
Same background layer as in demo
=> Better message on error on a WMTS layer

contribs/gmf/src/drawing/drawFeatureOptionsComponent.js
Otherwise, the geometry is not updated when the vertices count is 2.
https://camptocamp.github.io/ngeo/GSNGM-1175/examples/contribs/gmf/apps/desktop.html
=> Initialize verticesCounter to NaN

src/message/displaywindowComponent.js
This patch fixes an other regression introduced by the automatic changes in: 6d38eed1c249a8d3624eeb8ab2a3248c5b508d16
This time it's the ngeo `displayWindowComponent`.
An angular component gets its its binding properties (i.e. those defined in the html) being set their values in the $onInit method.  In the constructor, their values are not yet set but we do need to type them:
```
/**
* @type {boolean}
*/
this.resizable;
```
The issue introduced by the auto-patch is that they got values assigned according to their type:
```
/**
* @type {boolean}
*/
this.resizable = false;
```
This breaks the setting of the value by Angular in $onInit.  Therefore, we should not do that.  It's okay to leave the type as `boolean`, because the property itself in `this` will be set to a boolean in $onInit.  The …
=> Revert regression introduced in ngeo displayWindow component

contribs/gmf/src/print/component.js
A regression was introduced in the gmf print component by the following "auto-replace" commit: 6d38eed1c249a8d3624eeb8ab2a3248c5b508d16
The code it replaced broke the logic of how the legend in the print component is included.  This patch reverts it to its original state, which restores the feature properly.
=> Revert regression in gmf print component

contribs/gmf/src/search/component.js
As discussed with @sbrunner we from Basel-Stadt are creating a pull request to get this additional gmf functionality within our project.
Our aim is to include tools to the search so a user can search for a tool and with a click on the search result the tool will be opened. The implementation in our project can be found here: https://github.com/camptocamp/baselstadt_mapbs/commit/a2d95c78976a8fa30d4ecb47c71699429ac3e18e
How do we have to proceed to get this to GMF 2.5 as base functionality for futher versions?
=> Additional search actions

contribs/gmf/src/query/window.scss, src/filter/rulecomponent.html, src/measure/azimut.js
Fix https://jira.camptocamp.com/browse/GSGMF-1200
=> Fix window query

src/filter/RuleHelper.js, src/format/filter.js
QGIS does not support "During" operator.
=> Use between as temporal operator with QGIS

src/query/ModeSelector.js, src/query/component.js
This patch introduces a `pending` property in the ngeo query ModeSelector to manage the changing of query mode while a request is already pending.
The idea is to keep the mode "active" while the request is pending to prevent the issue that was occuring while pressing the Ctrl key to draw a box, make the query tool issue a request and while it was still pending releasing the Ctrl key immediately changed the mode.
=> Introduce pending in query ModeSelector

contribs/gmf/src/search/component.js
demo: https://camptocamp.github.io/ngeo/GSGMF-1206/examples/contribs/gmf/apps/desktop_alt.html
=> Don't hide color picker when clearing the search input

src/interaction/Modify.js, src/interaction/Translate.js
Fix bug with Translate and Modify interactions in ngeo (regression introduced by: d207fc7788791bf9db5b4989ad9a04f1343fd0b3)
In the setState methods of these interactions, both the map and active properties are checked to unregister events.  An extra check was made for the map, and when falsy the method did nothing, while it had to (unregister events).  The cause was that upon selecting a feature in the draw tool, new events were incrementing and the clicked features was being "selected" 1 extra time everytime, cummulatively.
This fixes this issue.
Also, I don't understand how it can be possible the the interactions and listenerKeys properties can be `undefined` when the method is called since they are initialized in the constructor, but they can!  The extra "if" takes care of that very …
=> Fix Translate and Modify interactions

src/map/swipe.js
Rotating the map while the map swipe component is active doesn't work well.  This patch fixes this issue.
* when the map gets rotated, the map swipe tool gets deactivated
* when the map swipe tool gets activated, restore the rotation of the map
=> Manage map view rotation and map swipe

src/datasource/Helper.js
In ngeo, the list of attributes of a data source are no longer fetched using a WFS DescribeFeatureType request.  Instead, we use the attributes that are in the themes.
The attribute types in there are camel cased, like this: `dateTime`.  The Attribute format that was used to create the attributes from the describe response was used to create the attributes, and converted all types as lowercase.  So, the type in an attribute is "datetime", not "dateTime".
This patch fixes the issue when creating the attributes from the themes.
=> Fix datetime filter

contribs/gmf/src/layertree/component.html, contribs/gmf/src/layertree/component.js
https://jira.camptocamp.com/browse/GSGMF-1212
~~"Show" class was never applied... And I tried to put everything into the css files but that worked only using the inline "display: none" style, so I kept it that way...~~
Bootstrap 4 changes the "show"/"hide" classes to become:
```
The classes are named using the format:
- .d-{value} for xs
- .d-{breakpoint}-{value} for sm, md, lg, and xl.
Where value is one of:
- none
- inline
- inline-block
- block
- table
- table-cell
- table-row
- flex
- inline-flex
```
https://getbootstrap.com/docs/4.1/utilities/display/
=> Fix node menu in mobile layertree to open and close

contribs/gmf/src/layertree/component.html, contribs/gmf/src/layertree/component.js
Fixes the regression introduced in dd38023b8ad9a45370babc90e18a215c9f161d57 that caused the show/hide to no longer works for any legend in the layer tree. (@llienher Please, check what I restored and see if/why the change was made).
Then, this patch also fixes the issue with QGIS legends.  It was simply a matter of nothing being handled for them at all.
=> Fix legend show/collapse, and legend for QGIS

contribs/gmf/src/layertree/TreeManager.js, contribs/gmf/src/layertree/component.js
https://github.com/camptocamp/ngeo/pull/new/GSGMF-1215_submenu-on-theme-change
=> Remove layertree submenu when changing theme

contribs/gmf/src/layertree/datasourceGroupTreeComponent.html
This patch makes the node of a datasourceGroupTreeComponent opened by default.
This component is only used by the GMF import tool.  The behaviour of the regular "groups" that are defined in the themes and the other groups in the layer tree remain unchanged.  The metadata "isExpanded" still works as usual.
For the datasourceGroupTreeComponent, a "WMSGroup" data source is created, in which there's no metadata, i.e. no concept of "isExpanded".  Therefore, the change proposed here should be safe.
=> Expand group in tree for imported WMS layers

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/controllers/AbstractDesktopController.js
This patch introduces the following behaviour:  In the "desktop" applications, after the user successfully logs in, the "login" panel will stay open until:
* the login is successful (as before)
* and after the new themes have been loaded (this is new)
Also, after loging in, while the new themes are being loaded, a message is shown in the login panel along with a spinner.
=> Show loading screen after login while themes are loading

contribs/gmf/src/print/component.js, src/print/Service.js, src/print/VectorEncoder.js, src/print/mapfish-print-v3.js
With this pull request we would like to add the configuration of the MapFishPrint goodnessOfFit parameter to ngeo. The issue was already discussed here:
- https://github.com/mapfish/mapfish-print/issues/969
- https://github.com/mapfish/mapfish-print/issues/981
=> Allow to set goodness of fit parameter for labels

contribs/gmf/src/print/component.js, src/print/Service.js, src/print/VectorEncoder.js
Port 2.4 features in master branch
=> Port default print layout

contribs/gmf/src/permalink/Permalink.js, src/statemanager/WfsPermalink.js
Allow to set the zoom level with the parameter **map_zoom** in the URL for a WFS-Permalink.
=> Allow setting permalink zoom with map_zoom param

contribs/gmf/src/search/component.js
With this changes we make sure that the transparency of the default style is applied to new colors set by the colorpicker.
=> Apply transparency on search color

package.json
This reverts commit 3fe026839ca879be394a233fe740a602f17fa129.
Fix: https://jira.camptocamp.com/browse/GSGMF-1261
=> Revert "Bump jquery from 3.4.1 to 3.5.0"

api/src/Querent.js
For GMF layers with multiple child layers.
Backport of #5553
=> [Backport 2.5] Fix getFeaturesFromIds

buildtools/publish
When we do the 'git checkout gh-pages' the committed files will disappear...
=> Fix missing API help

src/datasource/OGC.js
When 2 OGC data sources don't have dimension filters set, they should be considered as having the same filters.
This patch makes it so.
=> Data sources without dimension filters are considered equal

contribs/gmf/src/layertree/common.scss, contribs/gmf/src/layertree/component.html, contribs/gmf/src/layertree/component.js
FIX GSGMF-1336
It's not easy to open a popup on the parent node with a link. I give up to achieve that for now.
I add the message `More options at the group level` for layers with parents having a "filter" possibility or a "set opacity" possibility.
Is the message understandable ?
I add this message as first option item in the mobile because the legend must be last.
UPDATE
Tests are failing, but It looks like it's not this PR fault. I've done a fix here: https://github.com/camptocamp/ngeo/pull/6013
And that could be good to have too: https://github.com/camptocamp/ngeo/pull/6002
=> Gui for swipe on layertree groups gsgmf 1336

buildtools/travis-npm-publish.sh
Try to reduce length of logs because travis fail with "The job exceeded the maximum log length, and has been terminated."
=> Fix travis 2 4

contribs/gmf/examples/displayquerygrid.html, contribs/gmf/examples/displayquerygrid.js, contribs/gmf/examples/displayquerywindow.html, contribs/gmf/examples/displayquerywindow.js, contribs/gmf/src/query/window.scss, contribs/gmf/src/query/windowComponent.html, contribs/gmf/src/query/windowComponent.js, contribs/gmf/test/spec/directives/displayquerywindow.spec.js
For GSGMF-1298
- Add export csv (layer per layer) in querywindow component.
- Add tests
- Adjust styles
- Correct GMF query examples.
Example: https://camptocamp.github.io/ngeo/export_csv_in_querywindow_gsgmf-1298/examples/contribs/gmf/apps/desktop.html
I've some doubts on the css:
- The popup menu is not aligned (as before, as for the filter popup), I wonder if we have to do better, it's not trvial
- I follow the mock-up and repeat "Export <layer>". That's not so nice, can't we have a header "Export CSV" then a list of layer ?
- The button is a little bit different on the mockup, I've prefered to follow the style of the filter button. It is okay ?
Also, this feature is desktop only, right ?
=> Export csv in querywindow

contribs/gmf/src/search/component.html, src/map/FeatureOverlay.js, src/map/FeatureOverlayMgr.js, test/spec/services/featureoverlay.spec.js
Fix https://github.com/camptocamp/ngeo/pull/6034 and https://jira.camptocamp.com/browse/GSGMF-1348
The isEmpty function was not working as expected.
I remove the features in the overlay. Features exist also in the featureOverlayManager and looks managed by this one. Within our code, the features_ variable in the FeatureOverlay looked absolutely useless.
=> Fts keep clear button when feature gsgmf 1348

contribs/gmf/src/datasource/ExternalDataSourcesManager.js, contribs/gmf/src/datasource/fileGroup.js, contribs/gmf/src/datasource/module.js, contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/editing/Snapping.js
This patch introduces the support of snapping to features from the Draw/Measure tool and from the imported vector files (Import Layer / Local).
Before detailing the changes of this patch, I would like to first describe what we had that handled the Snapping.
In GMF, we have a service called `Snapping` (in contrib/gmf/src/editing).  It hooks with the layer tree root node to get all the tree controlers that have node (i.e. layer node from theme) with the "snappingConfig" metadata.  The nodes that have it are WMS, and support WFS.  When snapping to those, WFS is used to fetch the features.
The features from the gmf Draw tool are added in the ngeoFeatures collection, which is also an "angular value" that can be injected from anywhere.  That part was the easy one, as we only needed to add a …
=> Support snapping on features from Draw and Import tools

src/datasource/FileGroup.js
GSGMF-1354
All external datasources are conserved in the background during the session. All of them are tried to be suppressed even if they aready are.
=> Do not unregister already unregistered file datasources

contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/apps/desktop_alt/index.html.ejs
After: GEO-3403
In upgrade of a GeoMapFish project, the line:
```
module.value('gmfLayertreeOptions', {'legendIcon': {'width': '30', 'height': '30'}});
```
becomes (with two slashes at the end):
```
module.value('gmfLayertreeOptions', {'legendIcon': {'width': '30', 'height': '30'\}\});
```
I try to correct that, but I think the real problem is not in ngeo.
Add an example in desktop_alt in https://github.com/camptocamp/ngeo/pull/5971
=> Corrections after release v2.4.2 geo 3403

src/query/component.js
Fix GSGMF-1353
Drawend was emitting a "click" event. Releasing the "ctrl" key too kick was enabling the "onClick" listener quickly enough to catch this "click" event. I disable this event emitting.
=> Do not emit click on drawend queries

src/print/Service.js, test/spec/services/print.spec.js
As for now STYLES param is passed in the print requests in the ``customParams`` object. This leads to having a duplicated STYLES parameter in the GetMap requests sent by the print tool.
It seems no problem with Mapserver but causes a "Can't parse XML request." error with ESRI.
=> Fix duplicated STYLES parameter in print requests

contribs/gmf/src/disclaimer/component.js, contribs/gmf/src/layertree/SyncLayertreeMap.js
Was done for GSGMF-1364
I can close it, or merge it as it only:
- Do some cleaning and correction
- Prepare groups to have a disclaimer and so, be able to be displayed by the disclaimer system. (The disclaimer directive must be updated to know when the disclaimer must be shown on a group)
But the last commit removes the second point. So **this PR only do some cleaning**.
=> Prepare (clean) groups to support disclaimer

contribs/gmf/src/layertree/component.html
For GSGMF-1402
Don't solve the problem, but another one with the `openLinksInNewWindow` (the html-angular syntax was not correct)
---
**For Chorme**
@sbrunner  in fact, **we can't login** properly anymore on localhost or gh-pages.
When we login in, we looks logged but **we don't have any cookie created.**
On request response header, on cookie, we have the message:
```
Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite 
attributeBecause a cookie's SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, 
which prevents the cookie from being set in a cross-site context. This behavior protects user data from 
accidentally leaking to third parties and cross-site request forgery.Resolve this issue by updating the 
attributes of …
```
=> Debug openLinksInNewWindow

contribs/gmf/apps/desktop_alt/Controller.js, src/grid/component.js, src/query/ModeSelector.js, src/utils.js
Fix point 3 of GSGMF-1405
I'll also provide a fix (at least for discussions) in ol. => https://github.com/openlayers/openlayers/pull/11693
`evt.ctrlKey` sometimes don't work on firefox (You can test on: https://codepen.io/ger-benjamin/pen/ZEOeyRb). I switch to use the W3C Modifier Keys Attributes value to detect ctrl key
=> Fix Firefox ctrl key

src/utils.js
Post #6397 and for point 3 of GSGMF-1405
My last workaround was a bad workaround.
I realized that the key string contains always only one key. That means, if you press ctrl and alt at the same time, there is still two events, one with key ctrl, one with key alt (**but not both !**). The first have only one flag to true, the second have both flag activated.
The best workaround I found is to continue to check the ctrlKey flag, but also check the key to minimize errors in Firefox.
This workaround looks strong enough, I can't reproduce a ctrlKey malfunction in the application.
Thus, the ctrlKey flag bug looks only append on Firefox for Ubuntu (and maybe only Ubuntu 18) (see: https://bugzilla.mozilla.org/show_bug.cgi?id=1673362)
For the same reasons, I give up to provide a fix in openlayers.
=> Better work around for ctrlKey events

contribs/gmf/src/datasource/Manager.js, contribs/gmf/src/datasource/OGC.js, contribs/gmf/src/themes.js, package.json, src/datasource/OGC.js, src/filter/RuleHelper.js, src/options.js, src/query/MapQuerent.js, src/query/Querent.js, test/spec/all.js, test/spec/services/querent.spec.js
For GSGMF-1294
I've named the `queryTouchMin` option to `toleranceTouch` to be coherant with the `tolerance` for desktop and `tolerance`for the edition (which is use basically for the the same behavior).
I've not seen any `queryToleranceTouch` to remove.
Done, PR here : https://github.com/openlayers/openlayers/pull/11740
**We have to wait on a new ol realease**
It looks already done: https://github.com/camptocamp/c2cgeoportal/pull/6512/files
There is no `tolerance` or `toleranceTouch` in ngeoQueryOptions from constants of CONST_vars.yaml . And none is needed. A default value exists in ngeo (the same default value as before).
I've take care of: https://github.com/camptocamp/ngeo/pull/4570 (still and always send the simple click with tolerance bbox as GET parameter. A custom bbox can be …
=> Click tolerence per layer

contribs/gmf/src/print/component.js
Here is a proposition to fill timezone in print.
This solution only fill timezone if attribute is present in layout.
I firstly think to add it directly in print service in ngeo part (easier), but this may raise errors in case attribute is not present in print config but throwErrorOnExtraParameters is activated.
May be discussed before merge.
=> Auto fill timezone attribute in print

contribs/gmf/src/datasource/Manager.js, contribs/gmf/src/editing/Snapping.js, contribs/gmf/src/themes.js, src/datasource/OGC.js
QGIS server does not completly support GML. When doing a getFeatureRequest asking for GML. 
QGIS returns coordinates in the wrong order.
The GMF Snapping tool uses the GML format
see
- http://lists.osgeo.org/pipermail/standards/2016-October/000994.html
- https://tools.ietf.org/html/rfc5165
- http://www.ogcnetwork.net/axisorder
This PR enables to invert X and Y in the ol coordinates array. When adding in the snapping config 
`invertXY : true`
I am not sure what is the way to update the documentation....
This affects ftth_tirol project that is using 31254
=> Enable to change the xy order on getFeature GML format

src/query/Querent.js
Fix GSGMF-1435 and https://github.com/camptocamp/ngeo/pull/6445
Oups... : If there is no queryIconPosition, use a simple array of names and a common geom.
We can query every queriable layer again now.
=> Retablish query without queryIconPosition

contribs/gmf/src/layertree/component.html
Hi, it seems that since PR #6009, the filter button which appears next to the layer (when clicking the gear icon) does not work for some layer, although they still appear in the drop down menu in the right panel. See for example in the demo the layer "OSM map" in the group "Filters mixed". Thanks to @RenataMuellerC2C we found out that the button re-appears by reverting one change of the commit b37759d78d048d173138a8fa6a294c49817741ae
=> Use getDataSource to check if layer is filtrable

contribs/gmf/src/print/component.js
Fix https://github.com/camptocamp/ngeo/pull/6456
I remove two line concerning the timezone. It makes no sens like that and throw an error on the desktop interface (includes on a not existing options.hiddenAttributes element => error and unable to print anymore).
I think you can still hide the timezone input by adding this `timezone` in the vars of <interface>->print->hiddenattributes.
=> Debug print timezone

contribs/gmf/src/layertree/SyncLayertreeMap.js, contribs/gmf/src/permalink/Permalink.js, contribs/gmf/src/print/LegendMapFishPrintV3.js, contribs/gmf/src/print/component.js, contribs/gmf/test/spec/all.js, contribs/gmf/test/spec/classes/legendmapfishprintv3.spec.js, src/map/LayerHelper.js, src/print/mapfish-print-v3.js
For GSGMF-1367
Spec:
- Provide to the print the layer group information from the client.
- Display only one name if layername is identical to the group name.
Done:
- I've moved the legend creation in a specific class in a specific file.
- I've cut the function into multiple smaller function.
- Legend classes are now embedded in other legend class to provide the hierarchical group representation of layers to the print.
- Group name are now sent to the print.
- Legend creation is now tested.
Without adaptation of the legend print template, the legend will looks not so good.
=> Group legend

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs
Same fix as for https://jira.camptocamp.com/browse/GEO-3866
Under the grid, a blank line can appear as the map-resize is disconnected to the queryGridActivate value.
Appear almost always with the filter tool (and interfaces with the grid). You can test the bug on the GMF demo 2-6
This fix correct that.
=> Fix blank line on grid (do resize map)

contribs/gmf/src/query/grid.scss, contribs/gmf/src/sass/vars_only.scss
(tested in GMF 2.5 but seems the same with GMF master)
When trying to customize GMF's gmf-displayquerygrid height, overridding ``$grid-height`` in the project's ``vars_desktop.scss`` as for the colors (eg. ``$brand-primary``) has no effect.
It seems because ``$grid-height`` is directly set in https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/query/grid.scss#L26 (right before using it in the grid styles) instead of being added to https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/sass/vars_only.scss 
This PR moves the var in the ``vars_only.scss`` and rename it.
Tested successfully in a GMF 2.5 project.
=> Make displayquerygrid height overridable

src/misc/FeatureHelper.js
With QGIS value can be
```
{
"_content_": undefined
"xsi:nil": "true"
}
```
Fix: GSGMF-1454
=> Handle QGIS nil value

src/offline/component.js
When disabling the offline mask, the view was "zoom" locked.
=> Fix offline mask

contribs/gmf/src/options.js, contribs/gmf/src/print/LegendMapFishPrintV3.js, contribs/gmf/test/spec/classes/legendmapfishprintv3.spec.js
GSGMF-1367.
We can't identify groups title in a MapFishPrint template.
That means we can't remove them if we don't want them.
This commit add a possibility to remove groups title by
setting the new GMF Print Legend option "showGroupsTitle".
I'll add a note in the Changelog of c2cgeoportal to speak about this new variable.
But I'll not set the variable in the default vars file as I'll adapt the legend.jrxml to indent groups
=> Add a "flat legend possibility" (no groups title)

contribs/gmf/src/print/LegendMapFishPrintV3.js, contribs/gmf/test/spec/classes/legendmapfishprintv3.spec.js
For GSGMF-1367
Look at https://github.com/camptocamp/c2cgeoportal/pull/7694 for the list of PR for this ticket.
- Fix layer order
- Remove first layerGroup (technical group) to have the real first level in bold and without indentation.
**Now you can test the indented legend in the example**
There is still one fix to come but in another PR
=> Reverse order print legend

Makefile, contribs/gmf/src/layertree/SyncLayertreeMap.js, contribs/gmf/src/print/LegendMapFishPrintV3.js, contribs/gmf/src/theme/Themes.js, contribs/gmf/test/spec/classes/legendmapfishprintv3.spec.js, src/map/LayerHelper.js
For GSGMF-1367
Look at camptocamp/c2cgeoportal#7694 for the list of PR for this ticket.
**Change in Makefile**: `make serve-debug` throw an error `unknow parameter: debug` with karma 6. I'm able to debug without this parameter so I've deleted it. (I've not found a replacement, and I've not seen any effect).
**For the legende**:
Take the case of the `layer with a very very very ... long name` in our demo. In the tree it's a:
`Fonction OSM Mixed` (-> layergroup)
`layer with a very very very ... long name` (wms layer in a mixed group)
**Not displayed**: `bank` (name of the wms layer)).
In 2.5, the legend shows:
`bank`
[legend-image]
In 2.6, previous to this PR, the legend shows:
`Fonction OSM Mixed` (-> layergroup)
`layer with a very very very ... long name` (wms layer in a mixed group) …
=> Wmslayer name print legend

contribs/gmf/src/controllers/desktop.scss
As noticed by @ger-benjamin for Mapilary, the ghost for left and right panel do not look the same. The reason is that the resizing of the right panel is not done on the panel itself, because it contains the app bar which should  not be stretched, but on its content. This PR proposes a solution to make them look more similar.
=> Set ghost style

src/datasource/Helper.js, src/format/WFSAttribute.js
For filtering only the default rules were available for numbers, because the attribute types were not changed to ngeoFormatAttributeTypes (double -> number).
=> Change attribute types to ngeoFormatAttributeTypes

contribs/gmf/src/drawing/featureStyleComponent.js, src/misc/FeatureHelper.js
Fix GSGMF-1463
Without this PR, move a line with arrows and arrows are left at the same place.
Now arrows move with the line.
@sbrunner I'm not sure what to do to solve the CI issue: Remove the "backport 2.6" tag or add a new branch/update the list:
```
Run check versions
:: versions: The backport labels do not have the right list of versions [2.4, 2.5, 2.6, master] != [2.4, 2.5, master]
Error:  versions: The backport labels do not have the right list of versions [2.4, 2.5, 2.6, master] != [2.4, 2.5, master]
```
=> Update arrow position (draw) on modify

contribs/gmf/src/authentication/component.js, contribs/gmf/src/backgroundlayerselector/component.js, contribs/gmf/src/backgroundlayerselector/status.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/search/component.js, contribs/gmf/src/theme/selectorComponent.js
Fix GSGMF-1249
We can't determine when app is fully loaded. So I've applied the invert logic: Specify when a user touch the background selection And from then, start to ignore the permalink.
I'll do more cleaning on 2.6
=> Ignore permalink on manual background selection

ci/config.yaml
It is the correct way to correct check version on 2.6 ?
And it is useful to have the 2.6 in the audit ?
=> Fix versions in CI, add 2.6

contribs/gmf/src/controllers/AbstractAppController.js
After GSGMF-1249
Cleaning on 2.6 only as it's a sensible point.
This method do the same (except thta it's missing to search the background layer in the theme functionalities) as the method `setDefaultBackground_` under:  https://github.com/camptocamp/ngeo/blob/26c7180f9079d78fdeb7faefac744c0e253471ec/contribs/gmf/src/controllers/AbstractAppController.js#L704
I don't call it here because it's already called multiple times during the process. Notably by the initial unavoidable "login".
=> Simplify background selection

Makefile, contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/oeedit/header.html, contribs/gmf/apps/oeedit/index.html.ejs, contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/header/component.html, contribs/gmf/src/header/component.js, contribs/gmf/src/header/module.js, contribs/gmf/src/mainmodule.js
Fix GSGMF-1469
The commit that break the permalink is surprisingly this innocent one: https://github.com/camptocamp/ngeo/pull/6375
It looks than using `ng-include` create problem with the `$location` service. Maybe it's related to this warning: https://github.com/camptocamp/ngeo/blob/779251e31115d77ffd2451deac5670336e9fa97f/src/statemanager/Location.js#L29-L33
I've not investigate more in depth. ng-include breaks our permalink.
To avoid using `ng-include`, I've create a directive for the header. It's fare more line of code (even without every comments), but it works and it's still possible to override the partial.
Another possibility would be to investigate into the permalink and the `$location` service to know why we have this issue but it could cost us a lot of time...
1. I've added the …
=> Fix permalink: avoid using ng-include

contribs/gmf/src/authentication/component.html, contribs/gmf/src/authentication/component.js
Fix GSGMF-1478
Authentication modal do not work on mobile, as the right menu use "position: fixed" (as the modal black screen), the childen elements can't appears above...
Solution: the modal is not really useful. I'll display the message in a simple alert, in the component.
From 2.6, I'll have another modal to move to a simple message (lost connection message).
=> Use alert instead of modal to show changed password (simple message)

src/filter/RuleHelper.js, src/filter/component.js, src/filter/ruleComponent.js, src/filter/rulecomponent.html, src/format/filter.js, src/rule/Date.js, src/rule/Geometry.js, src/rule/Rule.js, src/rule/Select.js, src/rule/Text.js
And change type from {number|string} to {number|string|string[]}.
To avoid using comma as separator in "select" rules.
=> Rename Rule.expression to Rule.literal

src/filter/rulecomponent.html
Because the button only adds a rule and does not apply it yet.
I have noticed several users confused because filters were not actually applied to the map when pressing the "Apply" button available in the form to add filters. Instead, one has to eventually press the global "Apply filter" button to have the set of filters applied.
I suggest to remove this confusion by simpling renaming the button to "Add". Eventually the users will press the "Apply filter" button when they are done setting rules.
=> Rename 'Apply' button in rule creating form

contribs/gmf/src/objectediting/coordinate.js
Fix GEO-4161
On oeedit save, we call this method to remove the third (or more) dimension to have a 2D coordinate.
But if the saved coordinate is already a 2D coordinate, the result is undefined as nothing is returned.
Now, the result is the 2D coordinate.
The process will still fail with a 1D coordinate or no coordinate, the function will still return undefined. But I think that in this case, the error is clear enough, no need to add an error log.
As it's oeedit, it will be hard to test, sorry...
But I was able to check the code in the project of the original issue.
=> Fix oeedit with 2d geom GEO-4161

src/print/VectorEncoder.js
Fix GSGMF-1479
If a feature have a style with a geometry, and this geometry has a style AND a text, we now push both symbolizers.
=> Fix print text on feature

contribs/gmf/src/search/component.html, contribs/gmf/src/search/component.js
Fix GSGMF-1482
The `clearButton` in search was and still must be to `true` per default.
See also: https://github.com/camptocamp/demo_geomapfish/pull/188
=> Retablish search clear button to true per default

contribs/gmf/src/search/component.js
Fix GSGMF-1504
Given coordinates are now `2056` , we have code that transforms it to a 2056 projection, with correct code `EPSG:2056`. I've change the code to use it (it's called but not used since ngeo 2.3...)
@sbrunner the search on desktop understand now only EPSG:2056. Should I adapt the manual tests booklet ? (Desktop alt understand 21781, 3857, 2056, precise desktop_alt and add `850000 5900000` to test EPSG:3857).
@sbrunner  Also, on 2.5, we don't support 3857 but 4326. I've added a PR here: https://github.com/camptocamp/demo_geomapfish/pull/209
Should I also set the const vars in c2cgeoportal to add this 4326 projection ?
=> Fix search coordinates

api/dist/apihelp/apihelp.html
Not in any issue yet, but I think that's not a bad idea to have (and propose) the same polyfill in api than in the apps.
What do you think ?
I found that because on Ipad, it says "unknow loop for of"... and refuse to read the maps, the loop looks coming from OpenLayers.
=> Add polyfill in api

contribs/gmf/test/spec/classes/legendmapfishprintv3.spec.js, src/map/LayerHelper.js
For GSGMF-1560
Somehow better now, but with scale bigger than 25'000, I still get wrong results. (until 25'000, it looks working).
Like this request: https://geomapfish-demo-2-6.camptocamp.com/mapserv_proxy?ogcserver=QGIS+server&cache_version=d8714cbf6e4c4b33841550cc2c25f2a5&FORMAT=image%2Fpng&TRANSPARENT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetLegendGraphic&LAYER=osm&DPI=254&BBOX=2530379.3079208867%2C1156552.5068461096%2C2540168.9108334263%2C1168458.7806586574&SRS=EPSG%3A2056&SRCWIDTH=1958&SRCHEIGHT=2381&ITEMFONTFAMILY=DejaVu%20Sans&ITEMFONTSIZE=8&LAYERFONTFAMILY=DejaVu%20Sans&LAYERFONTSIZE=10
Is at the nord of lausanne. There are not "pompier" feature in the area, and even not near. But it still appears in the legend...
=> Better printed legend for qgis

contribs/gmf/src/layertree/TreeManager.js
For GSGMF-1527
Step to reproduce the issue (From the ticket and without this PR as this PR fix it):
```
- Open https://geomapfish-demo-2-6.camptocamp.com/desktop_alt
- Click on the "clear all" link in the layertree, right under the themes selector
- Add the "Heritage" theme
- Uncheck the "Bank" layer
- Add the "Water management" theme
- Copy the URL in the address bar and paste it in a new tab => the "Bank" layer is on despite it was off in the initial tab
```
With this PR, we remove from the permalink **only** the elements that have been removed from the tree. Before, if we add on groups, he removed all the sub_groups by removing all the `tree_group_layers_<groupName>`.
As this debug is for one existing GMF 2.5 app, I backport it to GMF 2.5. (Sorry, I should have started to work directly …
=> Clean permalink only of removed groups

contribs/gmf/src/search/component.js
Not sure what is the best way to set the value correctly.
`this.option.highlight` is the value that the component will use in the end.
The initial value was set to `this.typeaheadOptions` object but not used so I re-added the Object.assign used in the 2.5 code. We could as well just set directly the `this.option` object with the correct highlight value.
=> Search result highlight

src/geolocation/component.js
Fix GSGMF-1610
When the zoom param is not set, null value should go in the "else" instead of "if".
=> If zoom is undefined or null condition

contribs/gmf/apps/appmodule.js, contribs/gmf/examples/editfeature.js, contribs/gmf/examples/editfeatureselector.js, contribs/gmf/src/authentication/Service.js, contribs/gmf/src/authentication/component.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/filters/filterselectorComponent.js, contribs/gmf/src/permalink/Permalink.js, contribs/gmf/test/spec/services/authenticationservice.spec.js, src/store/user.ts
A complete integration of the new User based on the rxjs store.
We can discuss on that Friday. There is other implementation possibility, I think this one is good.
Some interesting points:
- It was already working on the (small) first commit. But the original implementation is strange (because `gmfUser` was a constante).
- Simplify the code at some points: no more mix of OpenLayer and ngeo events, no injection... 
- My last commit set back the userState (logged in, logged out, ready...) to a simple string.  Reason in the commit message:
```
With two observable, if you subscribe to one, you have
no guarantee that the other is already up to date. Even
if they are updated at the same time !
```
- I've seen that the (old/gmf) auth component is initialized three times by AngularJs, but only …
=> RxJS User implementation

contribs/gmf/apps/desktop_alt/index.html.ejs, src/auth/component.ts, src/auth/panel.ts
PasswordValidator addition was straight-forward.
Final decision to drop onSuccessfulLogin, we can override it from the angular controller if needed.
Previously:
I have to assign the value of onSuccessfulLogin when the Angular controller is done initializing. Otherwise trying to do it outside the store getProperties().subscribe() get the value undefined and will not change later, as the Angular controller is not ready before the DOM of the web-component and there is no compatible watcher to lit-element.
On the matter of not using updated (https://lit.dev/docs/components/lifecycle/#reactive-update-cycle-completing):
The updated(changedProperties) works as watcher on attributes/properties in general, but not on @property({attribute: false}) as we need to bind the variable to a function and …
=> Bindings for passwordValidator

buildtools/codeshift-js2ts.js
Result:
`import('pkg/test.js').default`
=> imported as (fixed):
`pkgTest`
`import('pkg/Test.js').default`
=> imported as:
`PkgTest`
=> Fix imported cass

package.json
Title: [1004768] XSS in `*Text` options of the Datepicker widget in jquery-ui
Severity: moderate
CWE: CWE-79
Vulnarable versions: <1.13.0
Patched versions: >=1.13.0
Recommendation: Upgrade to version 1.13.0 or later
Version: 1.12.1
Path: jquery-ui
More info: https://github.com/advisories/GHSA-j7qv-pgf6-hvh4
Title: [1004769] XSS in the `of` option of the `.position()` util in jquery-ui
Severity: moderate
CWE: CWE-79
Vulnarable versions: <1.13.0
Patched versions: >=1.13.0
Recommendation: Upgrade to version 1.13.0 or later
Version: 1.12.1
Path: jquery-ui
More info: https://github.com/advisories/GHSA-gpqq-952q-5327
Title: [1004770] XSS in the `altField` option of the Datepicker widget in jquery-ui
Severity: moderate
CWE: CWE-79
Vulnarable versions: <1.13.0
Patched versions: >=1.13.0 …
=> Bump jquery-ui who has security issues

contribs/gmf/src/print/LegendMapFishPrintV3.js
Fix GSGMF-1702
The layer name was given instead of the node name. The node.metadata was not reachable in some cases. Like in layer OSM time (interval popup): https://geomapfish-demo-2-6.camptocamp.com/theme/Demo?lang=fr&baselayer_ref=OSM%20map&theme=Demo&tree_group_opacity_Group=0.65&tree_enable_osm_time_r_dp=true&tree_time_osm_time_r_dp=2006-01%2F2013-12&tree_group_layers_Layers=&tree_group_layers_Layers-exclusive=&tree_enable_osm_scale=false&tree_group_layers_Group=&tree_group_layers_OSM%20functions=&tree_enable_ch.swisstopo.dreiecksvermaschung=false&tree_enable_ch.swisstopo.geologie-gravimetrischer_atlas=false&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen=false&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung=false&tree_enable_NPA%20loc …
=> Fix printed legend image - use layer node name

contribs/gmf/apps/desktop_alt/index.html.ejs
We cannot fetch the translations from i18next outside of the web-components for now.
=> Remove use of i18next translation in desktop_alt

contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/permalink/Permalink.js, src/auth/FormElement.ts, src/auth/PanelElement.ts, src/auth/component.spec.ts, src/auth/component.stories.ts, srcapi/store/user.ts
Probably not the cleanest implementation possible, but do the job with the following requirements:
- Switch to another tool panel should reset the login message to empty state
- Close the panel or collapse it should reset the login message to empty state
- If login is required will both broadcast an event for desktop the AngularJS way and use the store to change the store Observable for desktop_alt
Missing:
- Translation of the message value
NB: I had to fix the promises adding some catch() and the gmfUser naming in the permalink.js so it is a bit of a mess for this file...
=> Display login message when authentication is required on private layers

contribs/gmf/src/controllers/AbstractDesktopController.js
As we checked that the panel was not null in abstract controller, we did not set the value to false when the panel was closed so the mask in the print wasn't synced anymore with the correct value.
=> Correctly toggle print mask

contribs/gmf/src/search/component.js
For instances using more than one search input, we need to support multiple configs in the vars like we do for the streetview component.
=> Add options name for search options

buildtools/webpack.api.js
Remove core-js, it shouldn't be needed because on 2.6 it wasn't present...
=> Fix the API help

contribs/gmf/test/spec/services/treemanager.spec.js
Was already backported in 2.6 in #7985 
I hope other test case doesn't do this strange error.
=> Clean more theme object in test to avoid strange error

src/lidar/Manager.ts, src/lidar/Plot.ts
The graph was updating only when it intercepted a "mouseMove" event but not the other types like "WheelEvent", so this fixes that.
=> Fix lidar graph not updating with Zoom event

contribs/gmf/src/editing/Snapping.js
Fix [GSGMF-1734](https://jira.camptocamp.com/browse/GSGMF-1734)
I don't know if we should better use console.info() for the message of this error when it is an aborted promise result...
=> Catch error on WFS query promise (in snapping)

src/disclaimer/component.js
Propertychange listener is not runned at the layer level but on the group activation, so using rootscope allows us to trigger the disclaimer code when a layer is enabled or disabled.
=> Display & hide disclaimers when a layers is visible/hidden

examples/mapillarystreetview.js
Fix missing example: [GSGMF-1812](https://jira.camptocamp.com/browse/GSGMF-1812)
PS: mapillary key seems wrong for the local example, I don't know if there is somewhere the right one (probably for the Azure demo but I don't have it)...
=> Add bufferSize parameter to mapillary options in example

contribs/gmf/apps/desktop_alt/index.html.ejs
Non interactive elements such as body or div don't takes the focus when we want to handle keyboard events on them ... So it seems like we need to add the element to the tab index as the keyboard events is not currently handled. Tab index lists the elements that support keyboard focus.
https://developer.mozilla.org/fr/docs/Web/HTML/Global_attributes/tabindex
=> Makes body element focusable for onKeyDown event

.github/workflows/main.yaml, cypress.json
Some things that were buggy when starting doing automation of testbook.
Cypress `integrationFolder` is not supporting multiple paths so we need to trick it with glob in the `testFiles` parameter...
=> Fix cypress config and ci workflow

src/layertree/mobile.scss
Fix  [GSGMF-1828](https://jira.camptocamp.com/browse/GSGMF-1828)
.off class is applied to the parent element when the layers state is inactive (so ">" selector).
=> Hide cog icons in mobile layertree on inactive layers

src/datasource/ExternalDataSourcesManager.js
https://jira.camptocamp.com/browse/GSGMF-1897
From WMS specification:
The OnlineResource element within the Service element may be used to refer to the web site of the service provider. There are other OnlineResource elements used for the URL prefix of each supported operation (see below).
=> Fix external datasource url

.github/workflows/main.yaml
See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Upgrade deprecated set-output commands

src/print/component.js, src/themes.js
The hiDPILegendImages setting is used only in the print component, fix the documentation for this setting accordingly.
=> Documentation: fix the hi DPI explanation

contribs/gmf/src/datasource/Manager.js
Fix for EPFL to allow WMS layer to be queryable with dimensions when in the background group.
https://jira.camptocamp.com/browse/GSEPF-635
=> Allow dimensions to be passed for WMS layers in background group

src/proj/utils.js
This is needed in order to parse WFS responses from GeoServer which may use another formatting for the attribute `srsName` than the one in the request (see https://sourceforge.net/p/geoserver/mailman/geoserver-users/?viewmonth=202308&viewday=11)
=> Add alias for SRS code

src/layertree/Controller.js, test/spec/directives/layertree.spec.js
Fix [GEO-6859](https://jira.camptocamp.com/browse/GEO-6859)
Currently:
The parent get a refreshState
=> getCalculateState on the parent
=> getCalculateState=>'' on the children becaude the children are not initialized (getState=>'off')
Then the child get a refreshState
=> getCalculateState on the child => 'off' because the children are initialised
=> no notification to the parent because the state didn't changed...
=> Fix child notification

api/dist/apihelp/apihelp.html, api/dist/apihelp/data.txt, api/index.js, buildtools/check-example.js, contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/iframe_api/index.html.ejs, contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs, contribs/gmf/apps/oeedit/index.html.ejs, contribs/gmf/examples/options.js, contribs/gmf/test/spec/classes/legendmapfishprintv3.spec.js, contribs/gmf/test/spec/data/themes.js, contribs/gmf/test/spec/services/syncLayertreeMap.spec.js, cypress.config.ts, examples/options.js, examples/url.js, src/auth/component.spec.ts, test/spec/data/msGMLOutputBusStopWfs.js, test/spec/data/msGMLOutputFuel.js, test/spec/data/msGMLOutputInformationHitsWfs.js, test/spec/data/msGMLOutputInformationWfs.js, test/spec/services/wfspermalink.spec.js
See JIRA issue: [DEMO-2](https://jira.camptocamp.com/browse/DEMO-2).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9407/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9407/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9407/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9407/merge/apidoc/)
=> Uses the demo 2.9

src/layertree/component.html
Load https://carto.grand-chatellerault.fr/theme/ads 20x faster.
There is 793 legend images / 930 requests at loading time => 2min
Legend images are put in queue before tiles, and WMS layers, portal is not usable before 2 min.
With this change it takes 6 sec: https://lamiseretest.grand-chatellerault.fr/theme/ads
I made the PR on 2.8, but IMHO it could be backported on all supported versions.
Note: This comes with the side effect that legend images start loading after expanding the group and appear while receiving images. Not sure we need an option for this.
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9393/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9393/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9393/merge/api/apihelp/api …
=> Lazy load legend images

src/auth/FormElement.ts, src/auth/component.stories.ts, srcapi/store/config.ts, srcapi/store/user.ts
See JIRA issue: [GSGGR-152](https://jira.camptocamp.com/browse/GSGGR-152).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9408/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9408/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9408/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9408/merge/apidoc/)
[GSGGR-152]: https://camptocamp.atlassian.net/browse/GSGGR-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Login for OIDC client

.npmignore, package.json, src/auth/component.spec.ts, src/e2e/desktop.spec.ts, src/e2e/mobile.spec.ts, tsconfig.json
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9472/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9472/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9472/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9472/merge/apidoc/)
=> Some fix to be able to integrate in c2cgeoportal

src/import/importdatasourceComponent.js, src/mobile/navigation/component.js
See:
https://github.com/camptocamp/ngeo/security/code-scanning/24 
https://github.com/camptocamp/ngeo/security/code-scanning/25 
https://github.com/camptocamp/ngeo/security/code-scanning/41
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9475/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9475/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9475/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9475/merge/apidoc/)
=> Fix DOM text reinterpreted as HTML

examples/search.js
This PR debugs the search that was broken.
Font-awesome work again with the latest nego changes - nothing to do.
See JIRA issue: [GSNGEO-18](https://jira.camptocamp.com/browse/GSNGEO-18).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9478/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9478/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9478/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9478/merge/apidoc/)
[GSNGEO-18]: https://camptocamp.atlassian.net/browse/GSNGEO-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix search example

src/proj/EPSG_2056.js, src/proj/EPSG_21781.js, src/proj/utils.js
@sbrunner We could also drop these projection and register function (except the multiple one) and use https://github.com/geoblocks
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9480/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9480/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9480/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9480/merge/apidoc/)
=> Better returns for proj registration

buildtools/check-example.js
Currently, some runs create a folder like
/tmp/puppeteer_dev_chrome_profile-nXlTSz
with 13Mo of data
See also:
https://github.com/puppeteer/puppeteer/issues/6414
Concretely:
- Better browser close
- Set `userDataDir` to `/dev/null`
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9483/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9483/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9483/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9483/merge/apidoc/)
=> Don't store the user data

contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/apps/desktop_alt/sass/desktop_alt.scss
- Remove missing calc warning in css
- Remove useless drawLidarprofilePanelActive property
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9484/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9484/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9484/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9484/merge/apidoc/)
=> Clean desktop alt lidar active property and css

src/controllers/bootstrap.js
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9507/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9507/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9507/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9507/merge/apidoc/)
=> Remove webpack5 workaround

Makefile, buildtools/webpack.commons.js
Currently, on https://geomapfish-demo-2-9.camptocamp.com/ we have the error:
`window.gmfapi is undefined`
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9508/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9508/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9508/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9508/merge/apidoc/)
=> Fix exposition of gmfapi

src/layertree/TreeManager.js
See:
- https://sonarcloud.io/project/issues?severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&types=BUG&id=camptocamp_ngeo&open=AZGiwaQ21t-asUFI6xuC
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9512/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9512/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9512/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9512/merge/apidoc/)
=> Use forEach instead of map

buildtools/check-example.js, package-lock.json, package.json
Change:
1. Ol moved to as peerDependencies. 
2. I don't see any usage of `color-rgba`, `color-space`. They were added to fix sub version, but everything looks working without them. I think we can get ride of them.
Open questions:
1.  We import all d3, we could be more selective. => Tried and was complicated, let see that in another PR
1. And do we want flexibility on more library ? Candidate:
1.   file-saver
1.   lit*
1.   moment
1.   ol mapbox
1.   ol layerswitcher only used for css !)
1.   qruri
1.   rxjs
1.   tinycolor
1.   Others ?
=> Can be moved to peerDepedencies **on demand** later.
See JIRA issue: [GSNGEO-19](https://jira.camptocamp.com/browse/GSNGEO-19).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9504/merge/examples/) …
=> Better peer-dependencies

CHANGES.md
Please, review mainly the 2.9 part. Should I go deeper in details ?
Maybe take a quick look at the other parts (notably, is there a mentioned point not concerning ngeo, but was for c2cgeoportal ?)
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9539/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9539/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9539/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9539/merge/apidoc/)
=> Document changes

src/controllers/AbstractAppController.js
For https://camptocamp.atlassian.net/browse/GSSCHWYZ-429
And https://github.com/camptocamp/GeoMapFish/issues/92
But will break (origin): https://camptocamp.atlassian.net/browse/GSGMF-2009
Who looks to be a issue on a particular GMF.
This workaround was making the map less blurry in case of map height with a not round number of pixels, but it cause the map zoom to "jump" if the view.contrainResolution is set to true.
My idea is to trash this function, and let the concerned GMF implement it on need.
Another possibility would be keep the function in the code but not active by default (let the user choose if he want to use it).
Or to add a options in the vars to activate it or not.
If we keep it we could also add a debounce to to not recenter too quickly. …
=> Remove force center after view animation.

src/options.js, src/streetview/MapillaryGraphQueryCreator.js, src/streetview/MapillaryService.js, src/streetview/component.js
I created a custom class `MapillaryGraphQueryCreator`.
Note that I cannot extend `Mapillary.GraphQueryCreator` as it is not available before defered import.
Also note that I didn't typed everything there.
See JIRA issue: [GSGMF-2048](https://jira.camptocamp.com/browse/GSGMF-2048).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9540/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9540/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9540/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9540/merge/apidoc/)
[GSGMF-2048]: https://camptocamp.atlassian.net/browse/GSGMF-2048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Filter Mapillary images by organzation_id

contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/examples/options.js, contribs/gmf/test/spec/classes/legendmapfishprintv3.spec.js, contribs/gmf/test/spec/data/themes.js, examples/layerorder.js, examples/options.js, examples/url.js, src/canvas/ToolButtonsImplElements.ts
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9551/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9551/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9551/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9551/merge/apidoc/)
=> Add missing selection tool 0894b56 

src/streetview/MapillaryService.js
See JIRA issue: [GSGEOC-406](https://jira.camptocamp.com/browse/GSGEOC-406).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9553/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9553/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9553/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9553/merge/apidoc/)
[GSGEOC-406]: https://camptocamp.atlassian.net/browse/GSGEOC-406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Use geometry field instead of computed_geometry in Mapillary

src/editing/Snapping.js
When features are loaded for snapping, some services returned 400 because of default Content-Type application/json. So change it to text/xml. 
See JIRA issue: [GSGGR-117](https://jira.camptocamp.com/browse/GSGGR-117).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9556/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9556/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9556/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9556/merge/apidoc/)
[GSGGR-117]: https://camptocamp.atlassian.net/browse/GSGGR-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow snapping for more wfs layers

src/editing/Snapping.js
Missed to add backport label when merging.
See JIRA issue: [GSGGR-117](https://jira.camptocamp.com/browse/GSGGR-117).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9571/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9571/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9571/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9571/merge/apidoc/)
[GSGGR-117]: https://camptocamp.atlassian.net/browse/GSGGR-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GSGGR-117 backport fix feature loading

src/auth/FormElement.ts
When the openIdConnectBaseUrl is modified, the openIdConnectUrl should also be updated.
See JIRA issue: [GSGMF-2114](https://jira.camptocamp.com/browse/GSGMF-2114).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9583/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9583/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9583/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9583/merge/apidoc/)
[GSGMF-2114]: https://camptocamp.atlassian.net/browse/GSGMF-2114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix OIDC login on mobile

src/editing/editFeatureComponent.js, srcapi/elements/BaseElement.ts
src/editing/editFeatureComponent.js AND src/misc/datepickerComponent.js import datepicker.
And we can see that there are two jquery on the debugger, at the "datepicker not found" error. The "other" jquery has it, I think removing this jquery could fix this issue.
We could have the same issue with the drag element or resize, or swipe. But I don't have any draggable/resizable element in the desktop alt. To keep in mind if we have such issue again (and if this fix really fix the issue).
See JIRA issue: [GSGMF-2118](https://jira.camptocamp.com/browse/GSGMF-2118).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9584/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9584/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9584/merge/api/apihelp/ …
=> Remove double import of jquery-datepicker

src/sass/popover.scss
Use more appropriate `z-index: 5` to have the date-picker popup (from a layer with time) above the left-panel-resize button.
See JIRA issue: [GSGMF-2135](https://jira.camptocamp.com/browse/GSGMF-2135).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9597/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9597/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9597/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9597/merge/apidoc/)
[GSGMF-2135]: https://camptocamp.atlassian.net/browse/GSGMF-2135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move date-picker popover above the resize-panel-left button

CHANGES.md, contribs/gmf/examples/common_dependencies.js, contribs/gmf/test/spec/beforeeach.js, src/controllers/AbstractAppController.js, src/layertree/timeSliderComponent.js, src/map/swipe.js, src/message/displaywindowComponent.js, src/message/modalComponent.js, src/misc/common-jquery-dependencies.js, src/misc/datepickerComponent.js, src/misc/datetimepickerComponent.js, src/misc/sortableComponent.js, src/query/windowComponent.js
To avoid double import of jquery, it's now the responsability of the app to load wanted jquery and jquery dependencies.
datepicker are still not working. I use here a more aggressive method, but I think that makes sens. That allows the user to have more choice on what he want to import.
See JIRA issue: [GSGMF-2118](https://jira.camptocamp.com/browse/GSGMF-2118).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9603/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9603/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9603/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9603/merge/apidoc/)
[GSGMF-2118]: https://camptocamp.atlassian.net/browse/GSGMF-2118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> Move jquery import out of component

src/query/MapQuerent.js, src/query/Querent.js, src/query/gridComponent.html.js, src/query/gridComponent.js, src/statemanager/WfsPermalink.js
See JIRA issue: [GSGMF-2137](https://jira.camptocamp.com/browse/GSGMF-2137).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9607/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9607/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9607/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9607/merge/apidoc/)
[GSGMF-2137]: https://camptocamp.atlassian.net/browse/GSGMF-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Query: Fix max results message 

contribs/gmf/examples/datepicker.html, contribs/gmf/examples/datepicker.js, contribs/gmf/examples/timeslider.html, contribs/gmf/examples/timeslider.js, src/controllers/AbstractAppController.js, src/filter/ruleComponent.js, src/filter/rulecomponent.html.js, src/layertree/component.html.js, src/layertree/component.js, src/misc/customEventDirective.ts, src/time-input/datepicker.ts, src/time-input/time-input.ts, src/time-input/timeslider.ts
Second PR for GSGMF-2138
Previously, I ran the callback into the time-input. Which is complicated with the anguarjs context. And it was also strange to command an angularjs digest loop from lit.
My aim (and initial) was to add a "ng-change" listener on the directive to avoid that, but that's not possible as ng-change only listen on some specific markup.
I've created here directive to listen to custom event. Now:
- Lit time-input only emits the time event and is cleaner
- My angular directive listen to events and run a callback with the changed value.
I think it's cleaner now.
See JIRA issue: [GSGMF-2138](https://jira.camptocamp.com/browse/GSGMF-2138).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9615/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9615/me …
=> GSGMF-2138-time-input: handle angular part in angular

src/datasource/Manager.js, src/editing/editFeatureComponent.js, src/layertree/SyncLayertreeMap.js, src/layertree/component.js, src/map/LayerHelper.js, src/objectediting/component.js, src/print/LegendMapFishPrintV3.js, src/print/Service.js, src/utils.js
For https://camptocamp.atlassian.net/browse/GSSCHWYZ-437
Waiting https://github.com/camptocamp/schwyz_geoportal/pull/463 to test the detection on partially supported WebGL.
Without WebGL or with partial support of WebGL, ol can crash and the portal works, but without some elements, or without the whole map (it depends on the device).
I detect support of WebGL (based on OL function) and provide `ol/layer/Tiles` instead of `ol/layer/WebGLTile` if WebGL is not supported. The properties of both classes are currently the same and differs only by the rendering. Therefore, I leave the typing on "WebGLTile" when possible (It's only a fallback for rare cases).
See JIRA issue: [GSSCHWYZ-437](https://jira.camptocamp.com/browse/GSSCHWYZ-437). …
=> Fallback tiles without WebGL

src/editing/attributescomponent.html.js, src/editing/editFeatureComponent.js, src/misc/FeatureHelper.js
This PR makes that, while editing an item, the geometries can not be modified, if the geometry attribute name is part of the metadata 'readonlyAttributes' of the layer.
If the geometry is not editable, the selected item is highlighted in grey without vertices.
See JIRA issue: [GSGGR-39](https://jira.camptocamp.com/browse/GSGGR-39).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9640/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9640/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9640/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9640/merge/apidoc/)
[GSGGR-39]: https://camptocamp.atlassian.net/browse/GSGGR-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> Disable modifying geometry if 'geom' is part of readonlyAttributes

buildtools/compile-catalog.js
error: too many arguments. Expected 0 arguments but got 2.
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9650/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9650/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9650/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9650/merge/apidoc/)
=> Add argument to fix c2cgeoportal CI

src/canvas/ToolButtonsImplElements.ts, src/controllers/AbstractDesktopController.js
Follow-up of PR #9909.
Changing the panel name in the tool button is a breaking change since it requires to change the slot name in the main HTML document, so change the panel name in the listener instead.
Additionnally, there still was a mismatch in the name of the AbstractDesktopController class field and the tool active property name (editFeatureActive)
See JIRA issue: [GSGRAUB-142](https://jira.camptocamp.com/browse/GSGRAUB-142).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9911/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9911/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9911/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9911/merge/apidoc/)
[GSGRAUB-142]: …
=> Really fix edit panel activation
