camptocamp/ngeo

contribs/gmf/externs/gmf-themes.js
Fix: #2870 
Ready for a review, please, say me if it's understandable (and correct spelling).
(look also: https://github.com/camptocamp/c2cgeoportal/issues/3085)
=> Better documentation for metadata

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/services/permalink.js
* Move gmfUser.functionalities.default_theme check in permalink service.
* Get the default theme by priority order from url, local storage, user
functionalities or defaultTheme constant.
=> Fix default theme resolution.

src/services/statemanager.js
=> Disable the localstorage by default

contribs/gmf/src/directives/partials/authentication.html
=> What's authCtrl.translate?

examples/scaleselector.html, examples/scaleselector.js, src/directives/partials/scaleselector.html, src/directives/scaleselector.js
=> Simplify and fix scaleselector example

src/ol-ext/interaction/measure.js
=> measure tools tooltip is moving when panning the map

contribs/gmf/src/directives/layertree.js
=> Enter digest cycle on node collapse

contribs/gmf/src/services/syncLayertreeMap.js
=> Correctly hide WMS layers that have not active children

contribs/gmf/apps/desktop/js/controller.js, contribs/gmf/apps/desktop_alt/js/controller.js, contribs/gmf/apps/oeedit/js/controller.js, contribs/gmf/apps/oeview/js/controller.js, contribs/gmf/examples/mouseposition.js
=> Fix EPSG:2056 label

contribs/gmf/src/directives/backgroundlayerselector.js, contribs/gmf/src/directives/partials/backgroundlayerselector.html
This fixed the display of the selected layer in the background layer selector.
=> Background map+login problem

src/directives/partials/grid.html
=> Use ng-bind-html for the grid header

contribs/gmf/less/displayquerygrid.less
=> Fix the element z-index in grid

contribs/gmf/src/directives/displayquerygrid.js
=> Remove the ol_uid also on build

contribs/gmf/less/base.less
=> Fix profile width

src/proj/epsg2154.js, src/proj/epsg27572.js, src/proj/epsg3947.js
* EPSG:2154: official national projection in FR
* EPSG27572: previous national projection (DEPRECATED) in FR
* EPSG:3947: local projection in the new official projection in FR
=> Add custom fr EPSG definition

contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/src/directives/authenticationdirective.js
=> Check allowPasswordChange value in an $onInit function

contribs/gmf/less/datepicker.less
=> Use the standard font in the datepicker widget

contribs/gmf/src/services/permalink.js
=> Debounce call to update permalink when feature is updated

examples/locationsearch.js
Try to fix ngeo 2.2 (without certitude....)
(looks also: https://github.com/camptocamp/ngeo/pull/2968#issuecomment-335799599)
=> Fix 2.2 (bloodhound type)

contribs/gmf/src/directives/layertree.js
=> Take admin dimensions into account in WMS Requests

src/directives/partials/scaleselector.html, src/services/filters.js
To reevaluate the value when the locale change
fixes #2983
=> Change ngeo.Scalify filter to be stateful

contribs/gmf/src/directives/contextualdata.js, contribs/gmf/src/directives/drawfeature.js, contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/directives/objecteditinggetwmsfeature.js, src/directives/profile.js, src/ol-ext/interaction/drawregularpolygonfromclick.js, src/ol-ext/interaction/measure.js, src/ol-ext/interaction/measureazimut.js, src/ol-ext/interaction/modifycircle.js, src/ol-ext/interaction/rotate.js, src/ol-ext/interaction/translate.js, src/ol-ext/menu.js, src/ol-ext/popover.js
=> Remove goog.events.*

examples/locationsearch.html, examples/locationsearch.js
Fix location search example (travis was still failling (allowed errors): https://travis-ci.org/camptocamp/ngeo/builds/286879391)
=> Fix 2.2 bloodhound

examples/locationsearch.js
Fix https://travis-ci.org/camptocamp/ngeo/builds/288467978
=> The good one - fix location search example

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/oeedit/index.html, contribs/gmf/apps/oeview/index.html, contribs/gmf/examples/displayquerygrid.html, contribs/gmf/examples/displayquerywindow.html, contribs/gmf/examples/print.html, contribs/gmf/src/directives/layertree.js
Fix #2970
Must be reported in branch 2.2 and master
=> Document gmflayertree openlinkinnewwindow attribute

.travis.yml
to solve this error https://travis-ci.org/camptocamp/ngeo/jobs/289535682
=> Be able to build from external repository

contribs/gmf/src/directives/partials/authentication.html, contribs/gmf/src/directives/partials/featurestyle.html, contribs/gmf/src/directives/partials/print.html, contribs/gmf/src/directives/partials/search.html, contribs/gmf/src/directives/partials/share.html
Aka debug ie11
Fix #3020
Coding standard to report into 2.2, master
=> Use ng-attr to bind interpolated attributes

contribs/gmf/src/directives/print.js
=> Fix gmf-print directive bindings

contribs/gmf/less/importdatasource.less, contribs/gmf/src/directives/partials/importdatasource.html, contribs/gmf/src/directives/partials/wmscapabilitylayertreenode.html, contribs/gmf/src/directives/partials/wmtscapabilitylayertree.html
Improves the UI of the ImportDataSource widget, more specifically the WMS/WMTS trees within, to look more like the original layer tree.
=> ImportDataSource -  Improve UI

contribs/gmf/src/services/permalink.js
Could we cherry-pick this commit into 2.2, please?
PR (merged into master): https://github.com/camptocamp/ngeo/pull/2835
=> Cherry-pick #2835 into 2.2

contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile_alt/index.html
=> Fix demo server URL

contribs/gmf/src/services/themesservice.js
=>  When adding a layer group, consider all levels not only the first one

src/directives/filter.js, src/directives/googlestreetview.js, src/directives/rule.js
Avoid renaming by the compiler
=> Add missing quotes in component bindings

contribs/gmf/apps/mobile/index.html, contribs/gmf/apps/mobile_alt/index.html
=> `Vous utilisez l'application mobile. Allez sur l'` + `application standard`
=> Be able to correctly translate in french

contribs/gmf/src/controllers/abstract.js
=> Reset the theme name on login/logout

src/modules/import/file.js
=>  Fix WMTS Capabilities file detection

contribs/gmf/src/directives/displayquerygrid.js, contribs/gmf/src/directives/displayquerywindow.js
=> [wip] Clear query results on window/grid clear

contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/contextualdata.js, contribs/gmf/src/directives/elevation.js, contribs/gmf/src/directives/layertree.js, contribs/gmf/src/services/snapping.js, contribs/gmf/src/services/themesservice.js
=> Remove provide gmf directives

contribs/gmf/src/controllers/abstractdesktop.js, examples/scaleselector.js, options/ngeox.js, src/directives/scaleselector.js
=> Move scale selector options to the options file

examples/popover.js, src/directives/popover.js
=> Remove multiple popover providers

contribs/gmf/examples/mobilemeasure.js, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/drawfeature.js, examples/createfeature.js, examples/interactionbtngroup.js, examples/measure.js, examples/toolActivate.js, src/directives/btngroup.js, src/directives/drawfeature.js
For GSGMF-141
btnDirective can be used alone.
btnGroupDirective can only be used with btnDirective
--> I provide only btnDirective
=> Remove useless provide of btnGroupDirective

contribs/gmf/src/controllers/abstract.js
=> Better background layer computation on user change

contribs/gmf/options/gmfx.js, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/datasource/datasourcesmanager.js, contribs/gmf/src/directives/backgroundlayerselector.js, contribs/gmf/src/directives/drawfeature.js, contribs/gmf/src/directives/editfeature.js, contribs/gmf/src/services/authenticationservice.js, contribs/gmf/src/services/permalink.js, contribs/gmf/test/spec/services/authenticationservice.spec.js, options/ngeox.js, src/customevent.js, src/directives/createfeature.js, src/directives/drawfeature.js, src/directives/measurearea.js, src/directives/measureazimut.js, src/directives/measurelength.js, src/directives/rule.js, src/ol-ext/interaction/measure.js, src/ol-ext/interaction/rotate.js, src/ol-ext/menu.js, src/services/backgroundlayermgr.js
=> Add ngeo.CustomEvent to rule them all

src/services/querent.js
4395d4307d was badly imported into master
fixes #3114
=> Fix bad 2.2 to master merge

contribs/gmf/src/directives/disclaimer.js, contribs/gmf/src/directives/filterselector.js, contribs/gmf/src/directives/objecteditinggetwmsfeature.js, contribs/gmf/src/directives/partials/filterselector.html, examples/animation.js, src/directives/createfeature.js, src/directives/createregularpolygonfromclick.js, src/directives/desktopgeolocation.js, src/directives/filter.js, src/directives/googlestreetview.js, src/directives/mobilegeolocation.js, src/directives/partials/filter.html, src/directives/partials/googlestreetview.html, src/directives/partials/rule.html, src/directives/rule.js
But use the default `$ctrl` variable in templates
=> Don't use controllerAs

contribs/gmf/examples/displayquerygrid.js, contribs/gmf/examples/displayquerywindow.js
https://jira.camptocamp.com/browse/GSGMF-156
=> Minor move to components

contribs/gmf/src/directives/displayquerygrid.js
=> fix indentation

contribs/gmf/examples/share.js, contribs/gmf/examples/themeselector.js, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/directives/partials/share.html, contribs/gmf/src/directives/partials/themeselector.html, contribs/gmf/src/directives/share.js, contribs/gmf/src/directives/themeselector.js
https://jira.camptocamp.com/browse/GSGMF-154
=> Change gmf.share and gmf.themeselector to components

contribs/gmf/apps/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile/index.html, contribs/gmf/examples/search.html, contribs/gmf/examples/search.js, contribs/gmf/options/gmfx.js, contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/directives/partials/search.html, contribs/gmf/src/directives/search.js, src/modules/README.md
For GSGMF-155
Work well on example, and apps
=> GMF Search: move from directive to component

contribs/gmf/src/controllers/abstract.js, contribs/gmf/src/services/permalink.js, contribs/gmf/src/services/thememanager.js
=> Rename gmf.ThemeManagerEventType to gmf.ThemeManager.EventType

contribs/gmf/src/directives/print.js, contribs/gmf/src/directives/search.js
Answer to comment in PR #3151 from @apastuhow 
Also for GSGMF-155
- Better bindings
- Use ES6 classes
- Clean
Interesting fact: With ES6 classes, a lot of undetected type errors is now detected.
=> Improve search and print

Makefile
=> Add missing gmfmodule items into the template cache

src/services/print.js
Fix #3065
Work well, also with a double
=> Fix printed halo size

src/services/csvdownload.js
=> Fix CSV mime-type

contribs/gmf/src/controllers/AbstractDesktopController.js, examples/animation.html, examples/animation.js, src/map/module.js, src/map/resizemap.js
For https://jira.camptocamp.com/browse/GSGMF-181
=> Move ngeo resizemap in the map module

Makefile
=> Fix default.js path in examples-hosted

Makefile, buildtools/check-no-goog.sh, contribs/gmf/apps/oeedit/js/controller.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/controllers/AbstractMobileController.js
=> Remove last drop of goog library

contribs/gmf/src/directives/partials/displayquerywindow.html
=> Allow html in displayquerywindow keys

src/directives/mapquery.js
=> Don't query the map on double click

contribs/gmf/src/directives/partials/featurestyle.html
=> move the measure label checkbox

contribs/gmf/src/directives/profile.js, examples/elevationProfile.html, examples/elevationProfile.js, src/profile/.eslintrc.yaml, src/profile/d3Elevation.js, src/profile/elevationComponent.js, src/profile/module.js
For: https://jira.camptocamp.com/browse/GSGMF-206
It's right what I've done with the d3Elevation function ? 
I've renamed it to profile.elevation because we will get a "lidar" profile in the future.
=> Create ngeo profile module

contribs/gmf/examples/drawfeature.js, contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/directives/drawfeature.js, contribs/gmf/src/services/permalink.js, examples/drawfeature.js, src/draw/.eslintrc.yaml, src/draw/Controller.js, src/draw/component.js, src/draw/features.js, src/draw/module.js, src/draw/point.js, src/draw/rectangle.js, src/draw/text.js, src/filter/rulecomponent.js, src/measure/area.js, src/measure/azimut.js, src/measure/length.js, src/services/features.js
For: https://jira.camptocamp.com/browse/GSGMF-211
=> Create ngeo draw module

Makefile
=> Fix Transifex call

src/misc/debounce.js, src/misc/getbrowserlanguage.js, src/print/Service.js, src/services/popup.js
And some minor whitespaces fixes
=> Add missing ngInject in 'factory'

src/geolocation/extraModule.js, src/map/extraModule.js, src/map/module.js, src/statemanager/extraModule.js, src/statemanager/module.js
For: https://jira.camptocamp.com/browse/GSGMF-197
Some 'extra' that we've 'missed' in ngeo.
=> Add extraModule for some ngeo 'pack'

src/print/Service.js, src/print/VectorEncoder.js
Extract vector handling from the print service.
=> Split ngeo print service

src/message/Notification.js
Without this fix, the desktop app won't run (runtime error).
=> Fix typo (fixes broken master)

contribs/gmf/src/directives/partials/print.html
Fixes #3345, allow print generation button to be translatable.
=> Print button translation

contribs/gmf/src/controllers/abstract.js
When `functionalities.default_basemap` is empty or invalid.
=> Fix background layer selection when gmfUser functionalities is empty

contribs/gmf/src/services/permalink.js, contribs/gmf/src/services/treemanager.js, src/utils.js
=>  Some fix for the permalink 

contribs/gmf/src/directives/search.js
=> Update color on searched points

contribs/gmf/apps/mobile_alt/js/controller.js, contribs/gmf/options/gmfx.js, contribs/gmf/src/controllers/abstractdesktop.js, contribs/gmf/src/controllers/abstractmobile.js, contribs/gmf/src/services/snapping.js
fixes #2544 
And also optimize the snapping computation (unrelated to the pixel ratio)
=> Add new mapPixelRatio option

contribs/gmf/src/layertree/timesliderComponent.js
I don't understand why I've not saw that before...
=> Fix path to layertree's timesliderComponent

contribs/gmf/src/directives/partials/timeslider.html, contribs/gmf/src/directives/timeslider.js, src/services/wmstime.js
=> Localize and format by resolution timersliders diplayed values

src/services/wmstime.js
=> Prefers default years on 4 digits (WMS-T)

contribs/gmf/src/directives/editfeature.js
=> Use feature instead of this.feature

contribs/gmf/src/directives/mouseposition.js
For: #3344
Was not working if the application doesn't set its language.
=> Fix gmf mousePosition

contribs/gmf/src/directives/partials/featurestyle.html, src/services/featurehelper.js
=> Fix draw issues

contribs/gmf/src/directives/partials/share.html, contribs/gmf/src/directives/share.js
=> Fix share directive error message display

examples/attributes.html, examples/attributes.js
I was unsure, whether the example did properly work. This adds a visual log, which displays all changes to the feature.
=> Provide visual feedback for feature changes in attributes example

contribs/gmf/src/mobile/measure/lengthComponent.js
=> Fix mistyped parameter name

externs/mapfish-print-v3.js
=> Add useNativeAngle attribute to print externs

buildtools/webpack-migration, buildtools/webpack.prod.js, package.json
To get this PullRequest https://github.com/schmod/babel-plugin-angularjs-annotate/pull/37
=> Use camptocamp babel-plugin-angularjs-annotate

contribs/gmf/apps/mobile_alt/index.html, contribs/gmf/apps/mobile_alt/js/controller.js, contribs/gmf/src/directives/mobilemeasurelength.js
=> Fix mobilemeasurelength sketchstyle 2.2

.travis.yml
It don't relay save time and create sometimes some errors...
=> Disable the npm cache

package.json
=> chore(package): update uglifyjs-webpack-plugin to version 1.1.8

buildtools/webpack-migration, buildtools/webpack.commons.js, contribs/gmf/src/disclaimer/component.js, contribs/gmf/src/gmf.js, contribs/gmf/src/layertree/timesliderComponent.js, contribs/gmf/src/objectediting/component.js, contribs/gmf/src/query/windowComponent.js, examples/measure.js, src/download/service.js, src/filter/RuleHelper.js, src/filters.js, src/grid/component.js, src/message/displaywindowComponent.js, src/message/popupcomponent.js, src/misc/datepickerComponent.js, src/profile/d3Elevation.js, src/profile/elevationComponent.js
For https://jira.camptocamp.com/browse/GSGMF-200
=> WIP Require external lib where used

src/olcs/Service.js
=> Fix olcs es6 modules

.gitignore, .travis.yml, Makefile, buildtools/templatecache-webpack.mako.js, buildtools/webpack-migration, buildtools/webpack.commons.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/layertree/timesliderComponent.js, contribs/gmf/test/spec/all.js, contribs/gmf/test/spec/beforeeach.js, karma-conf-webpack.js, src/googlestreetview/component.js, src/grid/component.js, src/map/FeatureOverlay.js, src/map/LayerHelper.js, test/spec/all.js, test/spec/directives/layertree.spec.js, test/spec/services/printutils.spec.js, test/spec/services/wfspermalink.spec.js
=> Activate and fix the tests that runs on webpack

contribs/gmf/src/authentication/component.html, contribs/gmf/src/authentication/component.js
=> Debug authentification

contribs/gmf/examples/displayquerygrid.js, contribs/gmf/examples/displayquerywindow.js, contribs/gmf/examples/partials/queryresult.html, contribs/gmf/src/backgroundlayerselector/component.js, contribs/gmf/src/objectediting/component.js, contribs/gmf/src/profile/component.js, contribs/gmf/src/query/windowComponent.js, examples/backgroundlayer.js, examples/backgroundlayerdropdown.js, examples/bboxquery.js, examples/colorpicker.js, examples/layertree.js, examples/locationsearch.js, examples/mapquery.js, examples/measure.js, examples/partials/backgroundlayer.html, examples/partials/backgroundlayerdropdown.html, examples/partials/measuretools.html, examples/partials/queryresult.html, examples/search.js, src/grid/component.js
and better comments indentation
=> Stop using controllerAs in examples

contribs/gmf/src/services/syncLayertreeMap.js, contribs/gmf/src/services/themesservice.js, src/services/layerHelper.js
=> Use the matrixSet value from the WMTS layer config

.travis.yml
It became difficult to transform that...
=> Fix openlayers version before partial named style

contribs/gmf/less/contextualdata.less
=> Make sure the lines from the contextual menu are never wrapped

package.json
=> chore(package): update uglifyjs-webpack-plugin to version 1.2.2

package.json
=> chore(package): update karma-webpack to version 2.0.11

contribs/gmf/src/filters/filterselectorcomponent.js, contribs/gmf/src/import/importdatasourceComponent.js, contribs/gmf/src/import/wmsCapabilityLayertreeComponent.js, contribs/gmf/src/import/wmtsCapabilityLayertreeComponent.js, contribs/gmf/src/layertree/datasourceGroupTreeComponent.js, contribs/gmf/src/map/mousepositionComponent.js, contribs/gmf/src/permalink/shareComponent.js, contribs/gmf/src/raster/component.js, contribs/gmf/src/theme/selectorComponent.js, src/editing/attributescomponent.js, src/filter/component.js, src/filter/rulecomponent.js, src/googlestreetview/component.js, src/grid/component.js, src/message/displaywindowComponent.js
https://jira.camptocamp.com/browse/GSGMF-281
=> Inject the templateUrl value into the components

buildtools/webpack.gmfexamples.js, contribs/gmf/examples/authentication.js, contribs/gmf/examples/backgroundlayerselector.js, contribs/gmf/examples/contextualdata.js, contribs/gmf/examples/datepicker.js, contribs/gmf/examples/displayquerygrid.js, contribs/gmf/examples/displayquerywindow.js, contribs/gmf/examples/drawfeature.js, contribs/gmf/examples/editfeature.js, contribs/gmf/examples/editfeatureselector.js, contribs/gmf/examples/elevation.js, contribs/gmf/examples/featurestyle.js, contribs/gmf/examples/filterselector.js, contribs/gmf/examples/importdatasource.js, contribs/gmf/examples/layertree.js, contribs/gmf/examples/layertreeadd.js, contribs/gmf/examples/mobilemeasure.js, contribs/gmf/examples/mouseposition.js, contribs/gmf/examples/objectediting.js, contribs/gmf/examples/objecteditinghub.js, contribs/gmf/examples/permalink.js, contribs/gmf/examples/print.js, contribs/gmf/examples/profile.js, contribs/gmf/examples/search.js, contribs/gmf/examples/share.js, contribs/gmf/examples/simple.js, contribs/gmf/examples/themeselector.js, contribs/gmf/examples/timeslider.js, contribs/gmf/examples/wfspermalink.js, contribs/gmf/examples/xsdattributes.js
https://jira.camptocamp.com/browse/GSGMF-219
=> Don't load mainmodule in examples

package.json
by fixing the version of rollup-plugin-commonjs
=> Workaround to fix the master

buildtools/webpack.commons.js, buildtools/webpack.prod.js, test/spec/beforeeach.js
=> Fix moment integration

contribs/gmf/apps/desktop_alt/less/main.less, contribs/gmf/less/displayquerywindow.less, contribs/gmf/options/gmfx.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/layertree/component.js, contribs/gmf/src/query/windowComponent.html, contribs/gmf/src/query/windowComponent.js, src/message/displaywindowComponent.html, src/message/displaywindowComponent.js
Fix GSGMF-300
window.gmfx.OpenPopup should be provided by a service. But for now, I let it like this, with a fixme in the layertree
=> Improve displaywindowComponent

src/ol-ext/format/wfsattribute.js
Fix GEO-1054
Fix: #3522 
No demo for now.
=> Better parsing of wfs attributes (= better filters)

contribs/gmf/src/directives/backgroundlayerselector.js
Add missing @export to backgroundlayerselector directive.
=> Add missing @export to backgroundlayerselector

package.json
We don't need to do a commit on master to the dev releases
=> Bump the version to 2.3.0

docs/how_to_migrate_from_2.2_to_2.3.md
GSGMF-298
That's only about documentation. So please, **don't add too much review-comments** in this PR. If something is incorrect or not understandable, please **add directly your corrections within a new commit**.
Thanks !
=> How to migrate from 2.2 to 2.3

package.json
This reverts commit e49aea75265bcba41b37ac3f198c8cbe508b6c62.
Taken by error in #3687
=> Revert "Do the release 2.3.0-dev.5"

package.json
=> chore(package): update walk to version 2.3.13

contribs/gmf/src/search/component.js
GSGMF-385
Missing "?" in bindings create a warning in the console, and a problem on usage.
=> Better doc and bindings for gmf search

contribs/gmf/src/editing/editFeatureComponent.html, src/message/modalcomponent.js
FIX GSGMF-379
The ng-switch commented the modal before it was closed = modal persist
=> Close the edition modal before to comment it

src/measure/azimut.js
=> Fix azimut

buildtools/create-es6-package, docs/how_to_migrate_from_2.2_to_2.3.md
For GSGMF-391
Should I commit somethings elsewhere (add dependencies ?, describe the "adapt 'less' things") ? See  https://jira.camptocamp.com/browse/GSEPF-47 to know what I've done directly in the final project.
=> Load CSS through webpack

contribs/gmf/src/authentication/component.html, contribs/gmf/src/authentication/component.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/datasource/ExternalDataSourcesManager.js, contribs/gmf/src/datasource/WFSAliases.js, contribs/gmf/src/editing/editFeatureComponent.js, contribs/gmf/src/layertree/timesliderComponent.js, contribs/gmf/src/mobile/navigation/component.js, contribs/gmf/src/objectediting/Manager.js, contribs/gmf/src/search/component.js, docs/how_to_migrate_from_2.2_to_2.3.md, src/datasource/OGC.js, src/map/component.js, src/map/resizemap.js, src/map/scaleselector.js, src/message/popupcomponent.js, src/misc/btnComponent.js, src/misc/controlComponent.js, src/misc/datepickerComponent.js, src/misc/filereaderComponent.js, src/misc/sortableComponent.js, src/print/Utils.js, src/profile/elevationComponent.js, src/rule/rule.js, src/search/searchdirective.js
=> Fix typos in migration doc and source code

src/misc/sortableComponent.js
=> Correctly reset the sortable

buildtools/webpack.commons.js
=> Use the recommanded babel preset babel-preset-env

package.json
=> chore(package): update uglify-js to version 3.3.18

Makefile, package.json
=> Update FileSaver.js to version 1.3.8

package.json
=> chore(package): update google-closure-library to version 20180405.0.0

buildtools/webpack.ngeoexamples.js, examples/layertree.js
Fix https://jira.camptocamp.com/browse/GSGMF-311
=> Don't requires to copy the partials

contribs/gmf/src/authentication/component.js
Client part for: GEO-694
Do you have a better message (aim: the user must know that it's not a server error) ?
=> Adapt login error message to disable accounts

buildtools/deploy.sh
=> Fix lib location in gh-pages

.travis.yml, contribs/gmf/apps-webpack/desktop/index.html, contribs/gmf/apps/desktop_alt/index.html, contribs/gmf/apps/mobile_alt/index.html, contribs/gmf/apps/oeedit/index.html, contribs/gmf/apps/oeview/index.html
https://jira.camptocamp.com/browse/GSGMF-426
=> Fix transifex send

contribs/gmf/less/displayquerywindow.less
=> Fix search window in mobile mode

contribs/gmf/src/controllers/AbstractDesktopController.js
Remove conflict between jquery-ui tooltips and bootstrap tooltips.
=> Remove conflict with jquery-ui tooltip and bootstrap tooltip

src/directives/datepicker.js, src/directives/partials/datepicker.html
=> Fix the minDate and maxDate initialization in the datepicker option object

contribs/gmf/examples/featurestyle.js, contribs/gmf/src/disclaimer/component.js, contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/editing/editFeatureComponent.js, contribs/gmf/src/layertree/TreeManager.js, contribs/gmf/src/layertree/component.js, contribs/gmf/src/permalink/Permalink.js, src/draw/Controller.js, src/editing/exportfeaturescomponent.js, src/interaction/modify.js, src/layertree/Controller.js, src/misc/btnComponent.js, src/statemanager/Wfspermalink.js
Just some code cleanup.
It seems the 'this' is not defined in webpack build, so lots of code is breaking ... This give back the context of 'this' using ES6 arrow functions.
=> Use arrow functions for forEach loops

src/directives/partials/rule.html, src/directives/rule.js, src/rule/rule.js
=> Fix rules operator translation

src/ol-ext/format/xsdattribute.js
=> Add missing double support

buildtools/webpack.gmfapps.js, package.json
And remove extra `.html` in webpack server
=> Change debug port to 3000

buildtools/webpack.commons.js, contribs/gmf/src/layertree/timeSliderComponent.js, examples/colorpicker.html, examples/displaywindow.js, examples/googlestreetview.html, examples/layertree.js, examples/modifycircle.js, examples/rotate.js, examples/search.js, src/filter/component.js, src/filter/ruleComponent.js, src/grid/component.js, src/interaction/Modify.js, src/interaction/ModifyCircle.js, src/interaction/Rotate.js, src/map/BackgroundLayerMgr.js, src/map/scaleselector.js, src/measure/azimut.js, src/message/Disclaimer.js, src/message/displaywindowComponent.js, src/misc/colorpickerComponent.js, src/misc/datepickerComponent.js, src/routing/RoutingComponent.js, src/routing/RoutingFeatureComponent.js
For now, following examples are fixed in this PR:
- datepicker
- displaywindow
- layerorder
- backgrounddropdown
- rotate
- scaleselector
- colorpicker
- drawFeature
- googlestreetview
- search
- layertree
=> Fix ngeo examples

buildtools/deploy.sh
Removes more than 5000 lines of logs
=> Use quiet logs

contribs/gmf/src/permalink/shareComponent.js
Added missing import used for GMF share component and example.
=> Fix GMF share component and example

buildtools/webpack.commons.js, package.json
=> Fix simple3d example and switch to OL-Cesium 2.0

contribs/gmf/src/profile/module.js
=> Typo in profile module name

README.md, docs/developer-guide.md, docs/guidelines.md
GSGMF-459
Better Readme and up-to-date doc.
See it here: https://github.com/ger-benjamin/ngeo/tree/doc_target
(Not that I've kept that: https://github.com/ger-benjamin/ngeo/blob/doc_target/docs/guidelines.md#property-renaming)
=> Doc target

src/interaction/Measure.js
=> Fix measure of area

Makefile, buildtools/webpack.commons.js, buildtools/webpack.dev.js, buildtools/webpack.gmfapps.js, buildtools/webpack.prod.js
Replace https://github.com/camptocamp/ngeo/pull/3865
Visible here:
http://camptocamp.github.io/ngeo/webpack/examples/contribs/gmf/apps/desktop.html
=> Webpack assets fixies

src/misc/AutoProjection.js
=> Remove useless log in autoprojection

contribs/gmf/src/less/vars.less, contribs/gmf/src/query/window.less
Header is at z-index: 1030.
So I've created a "above-all" value at 9999.
=> Diplaywindow above header and iframe use all height

src/routing/RoutingService.js
See https://jira.camptocamp.com/browse/GSGMF-464.
=> Use https for routing

contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/oeedit/index.html.ejs, contribs/gmf/apps/oeview/index.html.ejs, contribs/gmf/src/permalink/shareComponent.js
See https://jira.camptocamp.com/browse/GSGMF-460.
=> Fix sharing permalink and cleanup some code

buildtools/webpack.commons.js, examples/offline.html, examples/offline.js, examples/offline.less, src/mainmodule.js, src/offline/.eslintrc.yaml, src/offline/component.html, src/offline/component.js, src/offline/module.js
Component and example structure + full menuing for GSLUX-77
(No icon for yet, because adding a font in an example with current stateof this branch can be complicated)
=> Offline basis

Makefile, buildtools/webpack.commons.js, buildtools/webpack.gmfapps.js, contribs/gmf/apps/desktop_alt/less/main.less, contribs/gmf/apps/desktop_alt/less/theme.less, contribs/gmf/src/controllers/desktop-theme.less, contribs/gmf/src/controllers/desktop.less, contribs/gmf/src/less/vars.less
inspired by: https://stackoverflow.com/questions/36130555/webpack-less-loader-override-variables-for-node-modules
An alternative can be: https://github.com/webpack-contrib/less-loader/issues/229
=> Add theme support

src/filter/ruleComponent.js, src/filter/rulecomponent.html, src/misc/datepickerComponent.js
See https://jira.camptocamp.com/browse/GSGMF-462.
=> Fix datepicker

contribs/gmf/apps/desktop/index.html.ejs
Was only added for desktop_alt... Fix the share popup for desktop interface.
=> Add missing ng-if for share popup in desktop interface

contribs/gmf/apps/desktop/index.html.ejs
Backport #3904 into 2.3 branch.
=> [2.3] Add missing ng-if to desktop interface

contribs/gmf/examples/share.html
This PR fixes the GMF example with the ng-if...
=> Fix modal in GMF share example

contribs/gmf/src/controllers/desktop.less, contribs/gmf/src/query/window.less, src/filter/rulecomponent.html
This remove the white line in the bottom of the window
=> Remove line-height in the query window results

contribs/gmf/src/editing/editFeatureSelectorComponent.js
=> Stop edit mode when leaving edit component

src/offline/NetworkStatus.js, src/offline/ServiceManager.js, src/offline/component.js, src/offline/module.js
A basic concept to link ngeo-offline to apps-offline
See also https://github.com/Geoportail-Luxembourg/geoportailv3/pull/2042
=> Add an offline services manager to link ngeo and apps

contribs/gmf/src/contextualdata/component.js
=> Fix the contextualdata popover position

options/ngeox.js, src/offline/DefaultConfiguration.js, src/offline/Downloader.js, src/offline/ServiceManager.js, src/offline/TilesDownloader.js, src/offline/component.js, src/offline/utils.js
See https://jira.camptocamp.com/browse/GSLUX-84.
=> Implement basic offline downloader

options/ngeox.js, src/offline/DefaultConfiguration.js, src/offline/Downloader.js, src/offline/Restorer.js, src/offline/ServiceManager.js, src/offline/component.js, src/offline/module.js
For now only restore the extent.
=> Introduce restorer

src/misc/php-date-formatter.js
Backport https://github.com/kartik-v/php-date-formatter/pull/20
=> Phpdate format es6

contribs/gmf/src/layertree/component.js, src/map/LayerHelper.js
Partially fix https://jira.camptocamp.com/browse/GSGMF-488
=> Fix layer graphic with legend rule

src/offline/Configuration.js, src/offline/TilesDownloader.js
=> Offline fixes

src/offline/Configuration.js, src/offline/Downloader.js, src/offline/Mode.js, src/offline/component.js
The info is now stored in the configuration.
In addition, reload the page after a clear if we were in offline mode.
With this PR, the download performance is now great again.
=> Rework the hasOfflineData mechanism

contribs/gmf/src/search/component.js
Fix https://jira.camptocamp.com/browse/GSGMF-564
=> Removes unwanted hardcoded mobile interface

contribs/gmf/src/query/grid.less
GSGMF-565
The best I've found, It works well, but I'm not 100% sure to be able to explain the bug.
=> Fix position of the query grid (app)

contribs/gmf/src/layertree/component.html
=> Update legend on (map resolution) change

.github/ISSUE_TEMPLATE.md
Related PR: https://github.com/camptocamp/c2cgeoportal/pull/3933
=> The issues should be reported on Jira

buildtools/travis-npm-publish.sh
Release will be prefixed by version- to avoid error
Daily will be latest
=> Fix the npm tags

contribs/gmf/src/services/permalink.js, src/ol-ext/format/featurehash.js, test/spec/ol-ext/format/featurehash.spec.js
=> Allow default values for features properties in ngeo.format.FeatureHash

options/ngeox.js, src/offline/Downloader.js
Add zoom range that is used for offline data.
This range can be used to restrict view after data restore.
=> Add zooms range in offline data

Makefile
~~I'm on a next problem (with mobile.less)...~~
Was an error in my project
Please review
=> Fix serve mobile

contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/controllers/desktop.less, contribs/gmf/src/controllers/mobile.less, contribs/gmf/src/query/window.less, src/message/displaywindowComponent.html, src/message/displaywindowComponent.js
GSGMF-571
\+ (3rd commit) a fix for the "squashed" view of the querywindow (mobile only)
Done
=> Fix info window size n position

src/offline/Configuration.js, src/offline/SerializerDeserializer.js, src/offline/utils.js
See https://jira.camptocamp.com/browse/GSLUX-125.
=> Workaround some wms edge effects

src/offline/component.js, src/utils.js
GSLUX-124
I think we can't retrieve the orginal extent. so I take the projection extent. I think it makes no difference.
=> Invert polygon (donut) to show offline extent

buildtools/webpack.plugin.js
See current error: https://travis-ci.org/camptocamp/c2cgeoportal/builds/419559157#L8069
=> Be able to have e.-g.  in publicPath

contribs/gmf/src/layertree/common.scss, src/message/displaywindowComponent.html
=> Fix two more icons (css / Font awesome)

contribs/gmf/src/sass/popover.scss, src/message/popoverComponent.js
GSGMF-418
Resolves also the time-sliders in popup display issue :-)
=> Fix popover bs4

contribs/gmf/src/layertree/common.scss, contribs/gmf/src/layertree/desktop.scss
=> Correct layertree icons margins

contribs/gmf/examples/lidarprofile.js, contribs/gmf/src/lidarprofile/Manager.js
This PR fixes the GMF LIDAR example
=> Fix gmf lidar example

contribs/gmf/src/layertree/component.html
See https://jira.camptocamp.com/browse/GSGMF-625
=> fixes distored images in IE11 by wrapping img in div

README.md
Update the README to give instructions how to run the GMF examples and applications.
=> README instructions for GMF

contribs/gmf/externs/gmf-themes.js, contribs/gmf/src/datasource/Manager.js, options/ngeox.js, src/datasource/OGC.js, src/filter/RuleHelper.js, src/query/Querent.js
Add dimensions_filters for handling dimensions through OGC filters with QGIS server.
ngeo part of https://github.com/camptocamp/aeroportdelyon_sig/issues/399
related with c2geoportal part : https://github.com/camptocamp/c2cgeoportal/pull/4125
=> Add GmfLayer.dimensions_filters

contribs/gmf/src/print/component.js
https://jira.camptocamp.com/browse/GEO-1445
=> Workaround for IE11 in print rotation slider

src/geolocation/mobile.js
https://sentry.camptocamp.com/geo/geomapfish-demo/issues/143420
=> Fix geolocation error function binding

buildtools/svg-viewbox-loader.js
This is needed for IE11 support
=> Set inline svg width

contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs, contribs/gmf/src/controllers/mobile-nav.scss, contribs/gmf/src/layertree/component.html
see https://github.com/camptocamp/ngeo/issues/2601
and https://jira.camptocamp.com/browse/GSGMF-605
=> Gmf mobile keep text in header

src/services/filters.js
opt_localize parameter doesn't exist anymore (always true)
=> Update doc for number filter

contribs/gmf/src/sass/base.scss
https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop.html
=> Force jqueryui resizable handle bellow the popover

contribs/gmf/src/layertree/component.html
=> Don't use ng-class with fa-spin

src/profile/d3Elevation.js
=> Fix defined in d3

contribs/gmf/src/raster/component.js
=> Use prototype for array concat

contribs/gmf/src/layertree/SyncLayertreeMap.js, contribs/gmf/src/theme/Themes.js
=> Add WMS styles management (in treeview and background layers)

contribs/gmf/src/sass/base.scss, src/Menu.js
=> Nicer menu

buildtools/webpack.commons.js, karma-conf.js, package.json, webpack.config.js
The second time of webpack run for desktop will get 17s. instead of 24s.
=> Hard source webpack plugin

api/dist/apihelp.html, api/src/Map.js, api/src/Themes.js
Support WMS overlays in JS api.
@fredj Have a quick check and see if I'm on the right track, please.
=> Support WMS overlays

api/dist/apihelp.html, api/src/Map.js, api/src/Querent.js
Support the recenterOnObjects method in the JS API.
=> Fix 693 - Add recenterOnObjects in JS API

contribs/gmf/src/datasource/Manager.js
This happen on a theme switch after adding an external layer
=> id is undefined on external layer

.gitignore, .travis.yml, api/src/constants.js, buildtools/deploy.sh, buildtools/webpack.api.js
demo: https://camptocamp.github.io/ngeo/api_build/api/apihelp.html
=> API build and gh-pages update

src/message/displaywindowComponent.html, src/message/displaywindowComponent.js
Actually @ger-benjamin did that... I leave the complete explanation up to him...
FIX: GEO-1113
=> Improve display window template management

package.json
=> chore(package): update @fortawesome/fontawesome-free to version 5.6.3

package.json
=> chore(package): update loader-utils to version 1.2.3

package.json
=> chore(package): update webpack-dev-server to version 3.1.14

package.json, test/spec/all.js
=> chore(package): update d3-array to version 2.0.2

contribs/gmf/src/lidarprofile/Manager.js, contribs/gmf/src/lidarprofile/Plot.js, contribs/gmf/src/lidarprofile/Utils.js, src/profile/elevationComponent.js
=> Simplify d3 import

contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs
Fix https://jira.camptocamp.com/browse/GSGMF-759
=> Don't display the message if redirect URL is empty

contribs/gmf/src/authentication/Service.js, contribs/gmf/src/datasource/OGC.js, contribs/gmf/src/editing/EditFeature.js, contribs/gmf/src/map/mousepositionComponent.js, contribs/gmf/src/objectediting/toolsComponent.js, contribs/gmf/src/permalink/Permalink.js, contribs/gmf/src/permalink/ShareService.js, contribs/gmf/src/print/component.js, contribs/gmf/src/profile/component.js, contribs/gmf/src/query/gridComponent.js, contribs/gmf/src/search/component.js, contribs/gmf/src/theme/Themes.js, src/statemanager/WfsPermalink.js
=> Fix the type defs

contribs/gmf/examples/editfeatureselector.js, src/profile/elevationComponent.js
fix https://jira.camptocamp.com/browse/GSGMF-514
=> Update the profile documentation

src/map/scaleselector.js, src/olcs/Manager.js
Requires: https://github.com/openlayers/ol-cesium/pull/692
=> Fix olcs typedef

package.json
=> chore(package): update d3 to version 5.8.2

.travis.yml
Result: https://camptocamp.github.io/ngeo/GSGMF-734/apidoc/
=> Deploy the apidoc

contribs/gmf/src/contextualdata/component.js, contribs/gmf/src/contextualdata/contextualdata.scss, contribs/gmf/src/sass/fullscreenpopup.scss, src/message/popoverComponent.js, src/message/popupcomponent.html
Bootstrap popover class names have changed between version 3 and 4.  This patch fixes the contextual data popover that is being shown on right-click in the gmf desktop app.
=> Fix gmf-contextualdata popover

contribs/gmf/examples/displayquerygrid.css, contribs/gmf/src/query/gridComponent.html
The selection text is not correctly align in the result grid:
=> Fix selection text alignment

contribs/gmf/examples/url.js, examples/url.js
Fix mapfishprint ngeo and gmf examples
=> Add missing OGC server

contribs/gmf/src/query/windowComponent.html
demo: https://camptocamp.github.io/ngeo/GSGMF-758/examples/contribs/gmf/apps/mobile.html
=>  Only activate swipe up/down on the collapse button

contribs/gmf/options/gmfx.js, contribs/gmf/src/print/component.js
Fix: https://jira.camptocamp.com/browse/GSGMF-778
=> Don't send datasource when it's not available

contribs/gmf/src/backgroundlayerselector/component.js
=> Use undefined to check opacity value

src/filter/RuleHelper.js
The WFS FeatureType don't do any distinction detween date ans date-time.
We already have a date only selector
But we do datetime query.
Fix: https://jira.camptocamp.com/browse/GSGMF-770
=> Fix filter on date

package.json
=> chore(package): update angular-gettext-tools to version 2.3.16

package.json
=> chore(package): update angular-gettext-tools to version 2.4.1

contribs/gmf/apps/desktop/Controller.js, contribs/gmf/apps/desktop/sass/desktop.scss, contribs/gmf/apps/mobile/Controller.js, contribs/gmf/apps/mobile/sass/mobile.scss
Use the same behavior ad in the _alt interfaces
Fix strange issue that the demo don't have any css
=> Be able to add some css in the projects

contribs/gmf/src/objectediting/component.js, src/editing/exportfeaturesComponent.js
Simplify the code by using the `getType` function instead of `instanceof`
=> Use getType instead of instanceof

contribs/gmf/src/query/gridComponent.html
As title says.
Fixes https://jira.camptocamp.com/browse/GSGMF-796
=> Add missing 'dropdown' class in query grid component

buildtools/check-example.js
To try to solve thoes errors:
https://travis-ci.org/camptocamp/ngeo/builds/498639028
https://travis-ci.org/camptocamp/ngeo/builds/498695069
https://travis-ci.org/camptocamp/ngeo/builds/498695040
=> Incrase the timeout

contribs/gmf/src/authentication/Service.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/permalink/Permalink.js, contribs/gmf/src/print/component.js, contribs/gmf/src/theme/Themes.js, contribs/gmf/test/spec/services/themesservice.spec.js, contribs/gmf/test/spec/services/treemanager.spec.js
=> Use 'roles' instead of 'role_id'

package.json
=> chore(package): update @types/googlemaps to version 3.30.18

contribs/gmf/src/print/component.js
https://jira.camptocamp.com/browse/GSGMF-816
=> Don't send unexisting fields to the print

contribs/gmf/examples/drawfeature.js, contribs/gmf/examples/editfeature.js, contribs/gmf/examples/editfeatureselector.js, contribs/gmf/examples/filterselector.js, contribs/gmf/examples/importdatasource.js, contribs/gmf/src/controllers/bootstrap.js, examples/disclaimer.js, examples/notification.js, examples/popupservice.js, src/message/popoverComponent.js
https://jira.camptocamp.com/browse/GSGMF-832
https://camptocamp.github.io/ngeo/ie-tooltip/examples/contribs/gmf/apps/desktop_alt.html
=>  Fix tooltip in IE 

package.json
=> Readd popper required by bootstrap

contribs/gmf/src/print/component.js, src/map/LayerHelper.js
https://jira.camptocamp.com/browse/GEO-1908
=> Print WMST to WMS layer opacity

src/profile/d3Elevation.js
https://stackoverflow.com/questions/19787925/create-a-d3-axis-without-tick-labels
=> Don't add y labels twice

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/iframe_api/index.html.ejs, contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs, contribs/gmf/apps/oeedit/index.html.ejs, contribs/gmf/apps/oeview/index.html.ejs
Apps on IE11 won't start as theme.js is using this values() property, so we need to add the polyfill.
=> Add missing polyfill for Object.values

contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/editing/editFeatureComponent.js, src/filter/ruleComponent.js
Icon is: https://fontawesome.com/icons/arrows-alt?style=solid
=> Fix move icon code

src/print/Service.js
Small API enhancement with no impact.
=> Allow overriding vector encoder

contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs
https://jira.camptocamp.com/browse/GSGMF-897
=> Don't see the desktop redirect on phone on landscape

contribs/gmf/src/print/component.js
=> Don't print QGIS layer legend URL at 300 DPI

package.json
To fix monday issue
See: https://github.com/webpack/webpack-cli/issues/870
=> Rollback webpack-cli to version 3.3.0

package.json
=> chore(package): update @types/cesium to version 1.54.4

contribs/gmf/src/index.js, contribs/gmf/src/permalink/Permalink.js
Fix: https://jira.camptocamp.com/browse/GSGMF-965
=> Store the background opacity in the permalink

api/dist/apihelp/data.txt, api/src/Map.js
backport #4882 for the 2.4 branch
=> api: reverse to order of the coordinates to be compatible with the old api

contribs/gmf/apps/desktop_alt/Controller.js, src/misc/filters.js
Fix: https://jira.camptocamp.com/browse/GSGMF-991
=> Test more null values

src/misc/FeatureHelper.js
Fix: https://sentry.camptocamp.com/geo/geomapfish-demo/issues/148790/
=> No error on no geom

contribs/gmf/src/layertree/common.less, contribs/gmf/src/layertree/component.html
=> Add back legend opacity change on layer activation

buildtools/travis-npm-publish.sh
To have the auto upgrade working again...
=> Fix publishing latest version

contribs/gmf/src/controllers/bootstrap.js, src/grid/component.js
The constant has been removed from OpenLayers
=> Don't use TOUCH from ol/has

contribs/gmf/apps/iframe_api/index.html.ejs, contribs/gmf/src/controllers/iframe_api.scss, contribs/gmf/src/controllers/mobile.scss
Fix issues with scalebar on API iframe and map in mobile apps.
=> GSGMF-1024: fix gmf apps

contribs/gmf/src/sass/input-range.scss
This reverts commit b9b48847603353a144c24001dbf2016b6de90339.
=> Revert "Group common css values"

contribs/gmf/src/print/component.js
And group the two functions into one
=> Check the input value with 'string' instead of 'number'

buildtools/webpack.commons.js, contribs/gmf/src/objectediting/toolsComponent.js
To test: https://camptocamp.github.io/ngeo/ir/examples/contribs/gmf/apps/oeedit.html
=> Fix object editing interface on ie

buildtools/check-example.js
=> Add --no-sandbox argument

contribs/gmf/src/layertree/timeSliderComponent.js
This PR allows the map to be updated while sliding the time slider, instead of only when the slider is released.
=> GSGMF-1041: Timeslider improvement

src/map/LayerHelper.js
Fix https://jira.camptocamp.com/browse/GSGMF-1079
=> Fix import WMS layer

contribs/gmf/src/datasource/Manager.js, contribs/gmf/src/datasource/OGC.js, contribs/gmf/src/editing/Snapping.js, contribs/gmf/src/themes.js, src/datasource/OGC.js, src/filter/RuleHelper.js, src/query/Querent.js
=> Fix alternate geometry name

contribs/gmf/apps/desktop/Controller.js, contribs/gmf/src/controllers/AbstractDesktopController.js
As mentionnned in @arnaud-morvan comment in my previous PR:
https://github.com/camptocamp/ngeo/commit/eabe6c7fc694b9b928ebd1c65ce7e4bc71b71e3e#r34795341
=> Move snapping values to AbstractController

contribs/gmf/apps/desktop/Controller.js, contribs/gmf/apps/desktop_alt/Controller.js
Also add restricted extent on desktop interface
=> Fix zoom to scale

api/index.js
Fix https://jira.camptocamp.com/browse/GSGMF-1082
=> Use the interface api for the api

api/src/Map.js
=> Fix exlusion condition in api query

contribs/gmf/src/backgroundlayerselector/component.js, src/map/BackgroundLayerMgr.js
https://jira.camptocamp.com/browse/GSGMF-1102
=> Don't download tiles for a completely transparent layer

Makefile, README.md, api/index.js, api/src/Themes.js, api/src/constants.js
GSGMF-1103
Server part: https://github.com/camptocamp/c2cgeoportal/pull/5262
=> Translate layers names in API layer switcher

contribs/gmf/src/layertree/timeSliderComponent.js, contribs/gmf/src/profile/component.js, contribs/gmf/src/query/gridComponent.js, contribs/gmf/test/spec/directives/displayquerygrid.spec.js, contribs/gmf/test/spec/directives/displayquerywindow.spec.js, src/datasource/DataSource.js, src/misc/swipe.js, src/routing/RoutingComponent.js, src/search/createGeoJSONBloodhound.js, src/search/createLocationSearchBloodhound.js, test/spec/services/csvdownload.spec.js, tsconfig.json
Fix https://jira.camptocamp.com/browse/GSGMF-1106
=> Fix filter attributes

contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/layertree/TreeManager.js, contribs/gmf/src/theme/Manager.js
https://jira.camptocamp.com/browse/GSGMF-1104
=> Do not throw an error when no default theme in functionalities

api/src/constants.js, contribs/gmf/apps/desktop/Controller.js, contribs/gmf/apps/desktop/contextualdata.html, contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/apps/iframe_api/Controller.js, contribs/gmf/apps/iframe_api/contextualdata.html, contribs/gmf/apps/mobile/Controller.js, contribs/gmf/apps/mobile_alt/Controller.js, contribs/gmf/apps/oeedit/Controller.js, contribs/gmf/apps/oeedit/contextualdata.html, contribs/gmf/apps/oeedit/index.html.ejs, contribs/gmf/src/contextualdata/component.js, contribs/gmf/src/controllers/AbstractAPIController.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/controllers/AbstractMobileController.js, src/search/createGeoJSONBloodhound.js, src/source/AsitVD.js
https://jira.camptocamp.com/browse/GSGMF-968
=> Use projection 2056 by default

api/src/Map.js, api/src/Themes.js, contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/src/permalink/Permalink.js, src/filter/ruleComponent.js, src/interaction/DrawAzimut.js, test/spec/services/print.spec.js
=> Remove OL ts-ignore

contribs/gmf/src/drawing/drawFeatureComponent.js, contribs/gmf/src/editing/editFeatureComponent.js, src/draw/Controller.js
https://jira.camptocamp.com/browse/GSEPF-274
https://jira.camptocamp.com/browse/GSEPF-275
=> Fix escape key

.travis.yml
Do we want notification on slack?
=> Add notifications

contribs/gmf/src/sass/map.scss, src/Popover.js
=> Simplify and fix ngeo Popover

contribs/gmf/src/authentication/component.js
And clear password fields after failed attempts.
https://jira.camptocamp.com/browse/GSGMF-1065
Note that after password change, fields are already cleared.
=> Clear login and password after successful login

src/datasource/WMSGroup.js
Fix: https://jira.camptocamp.com/browse/GEO-2308
=> Fix reenhable external WMS layer

contribs/gmf/src/authentication/Service.js, contribs/gmf/src/authentication/component.js
changes for https://github.com/camptocamp/c2cgeoportal/pull/5410
=> Change url and params for password change

contribs/gmf/src/import/importdatasourceComponent.js
https://jira.camptocamp.com/browse/GSGMF-1138
=> Add translation for ng-options list

src/print/Mask.js
https://jira.camptocamp.com/browse/GSGMF-1135
=> Fix drawing not visible when print panel opened

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/iframe_api/index.html.ejs, contribs/gmf/apps/oeedit/index.html.ejs, contribs/gmf/src/controllers/AbstractAPIController.js, contribs/gmf/src/sass/map.scss
To have the map swipe bellow all the buttons
=> Move zoom buttons outside of the ol element

contribs/gmf/src/query/windowComponent.js
https://camptocamp.github.io/ngeo/resizable_handles/examples/contribs/gmf/apps/desktop.html
=> Use all window resize handles

contribs/gmf/apps/desktop_alt/sass/desktop_alt.scss, contribs/gmf/apps/desktop_alt/sass/vars_desktop_alt.scss, contribs/gmf/src/controllers/desktop.scss, contribs/gmf/src/sass/vars_only.scss
=> Fix theme selector on desktop alt

src/print/VectorEncoder.js
https://jira.camptocamp.com/browse/GSGMF-1141
=> GSGMF-1141: Fix print with filters

src/print/Service.js
Printed with this fix:
[GeoMapFish_2019-11-26_10-08-35.pdf](https://github.com/camptocamp/ngeo/files/3891416/GeoMapFish_2019-11-26_10-08-35.pdf)
=> GSGMF-1151: Fix error on arcgis layers when printing

contribs/gmf/src/authentication/component.html
Fix: https://jira.camptocamp.com/browse/GSGMF-1146
=> Add first login message on 2fa

src/print/Service.js, src/print/mapfish-print-v3.js, test/spec/services/print.spec.js
See: https://jira.camptocamp.com/browse/GSGMF-1162
=> Fix print custom scale

contribs/gmf/src/profile/component.html, contribs/gmf/src/profile/profile.scss, contribs/gmf/src/query/grid.scss, contribs/gmf/src/query/gridComponent.html, contribs/gmf/src/query/window.scss, contribs/gmf/src/query/windowComponent.html, contribs/gmf/src/query/windowComponent.js
Implements the WFS query loading spinner.
https://jira.camptocamp.com/browse/GSGMF-1168
=> Add spinner for WFS query window

contribs/gmf/src/controllers/desktop.scss, contribs/gmf/src/controllers/mobile-nav.scss, contribs/gmf/src/floor/floor.scss, contribs/gmf/src/query/window.scss, contribs/gmf/src/sass/map.scss, contribs/gmf/src/sass/typeahead.scss, contribs/gmf/src/sass/vars_only.scss, contribs/gmf/src/search/search.scss
Fix: https://jira.camptocamp.com/browse/GSGMF-1169
Backport: #5075
=> Create scss variable for the default border style

contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/mobile_alt/index.html.ejs, contribs/gmf/apps/oeedit/index.html.ejs, contribs/gmf/examples/search.html, contribs/gmf/src/search/component.js
And fix the search placeholder
=> Really set clearbutton default to true

buildtools/webpack.commons.js, contribs/gmf/apps/desktop/Controller.js, contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/apps/iframe_api/Controller.js, contribs/gmf/apps/mobile/Controller.js, contribs/gmf/apps/mobile_alt/Controller.js, contribs/gmf/apps/oeedit/Controller.js, contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/controllers/AbstractMobileController.js, contribs/gmf/src/controllers/desktop.scss, contribs/gmf/src/controllers/mobile-nav.scss, contribs/gmf/src/controllers/mobile.scss, contribs/gmf/src/controllers/vars_desktop.scss, contribs/gmf/src/controllers/vars_mobile.scss, src/sass/font.scss
Put all vars on the top
Put all the other controllers scss on the bottom
Fix: https://jira.camptocamp.com/browse/GSGMF-1185
=> Fix scss instructions order

src/routing/RoutingFeatureComponent.js
https://jira.camptocamp.com/browse/GSGMF-1182
=> Routing: Fix center on select result

contribs/gmf/src/print/component.js, src/print/Mask.js
Fix: https://jira.camptocamp.com/browse/GSGMF-1176
=> Fix print mask rotation

src/misc/FeatureHelper.js
https://jira.camptocamp.com/browse/GSGMF-1181
=> Fix permalink when no color is provided

contribs/gmf/src/query/window.scss
=> Vertically align 'Result x/y' at bottom of display window result mobile

contribs/gmf/src/search/component.js
=> Additional search actions

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/apps/iframe_api/index.html.ejs, contribs/gmf/apps/mobile/index.html.ejs, contribs/gmf/src/authentication/Service.js, contribs/gmf/src/authentication/component.html, contribs/gmf/src/authentication/component.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/test/spec/beforeeach.js
Alternate of #5449 without modal window
=> Fix force password change cancel, no modal

src/filter/rulecomponent.html, src/measure/azimut.js
Use circle with 16 points
Fix: https://jira.camptocamp.com/browse/GSGMF-1202
=> Filters: check circle complexity

src/editing/exportfeaturesComponent.js
To take the `disabled` state into account
demo: https://camptocamp.github.io/ngeo/GSGMF-1205/examples/contribs/gmf/apps/desktop.html
=> Fix dropdown-menu in export features

src/filter/ruleComponent.js, src/interaction/Modify.js, src/interaction/ModifyCircle.js
Related to https://github.com/camptocamp/ngeo/pull/5466
=> Same number of points after edit

contribs/gmf/src/query/window.scss
https://jira.camptocamp.com/browse/GSGMF-1213
=> Fix not clickable collapse button in mobile query window

contribs/gmf/apps/mobile/sass/mobile.scss, contribs/gmf/apps/mobile_alt/sass/mobile_alt.scss
The spinner was out of the interface, but working. I fixed the css.
https://jira.camptocamp.com/browse/GSGMF-1193
=> Fix mobile and mobile_alt spinner notification on query

contribs/gmf/src/authentication/component.html, contribs/gmf/src/authentication/component.js
https://jira.camptocamp.com/browse/GSGMF-1214
=> Fix close button on password change modal

src/print/VectorEncoder.js
https://jira.camptocamp.com/browse/GSGMF-1232
=> Fix error handling in vector encoder

contribs/gmf/src/authentication/Service.js, contribs/gmf/src/authentication/component.html, contribs/gmf/src/authentication/component.js
https://jira.camptocamp.com/browse/GSGMF-1241
=> Fix double factor authentication form when changing password

contribs/gmf/src/print/component.js
The aim of this change is to allow the configuration of the default print layout in the print component.
=> Set default layout for print component

contribs/gmf/src/disclaimer/component.js, src/map/LayerHelper.js
Fix https://jira.camptocamp.com/browse/GSGMF-1231
=> Use propertychange to make it working with WMTS layer

CONTRIBUTING.md, DEVELOPING.md, README.md
Backport of https://github.com/camptocamp/c2cgeoportal/pull/5797
=> Add CONTRIBUTING.md and DEVELOPING.md files

contribs/gmf/src/mobile/measure/lengthComponent.js
Fix: https://jira.camptocamp.com/browse/GSGMF-1237
=> Same mobile measure length as in 2.3 and desktop

contribs/gmf/src/search/component.js
=> Use transparence from default style

contribs/gmf/src/datasource/ExternalDataSourcesManager.js, contribs/gmf/src/import/wmsCapabilityLayertreeComponent.js
Fix: https://jira.camptocamp.com/browse/GSGMF-1259
=> Fix adding external layer

contribs/gmf/src/drawing/drawFeatureOptionsComponent.js
=> No Javascript error on first click

src/googlestreetview/component.js
=> No error on click on missing data

api/src/Map.js
=> Set default style on the features

contribs/gmf/src/datasource/ExternalDataSourcesManager.js
Fix: GEO-3141
Port of https://github.com/camptocamp/ngeo/pull/5693
=> Fix for WMTS layer name

api/src/Map.js
=> Keep style of feature when selected

contribs/gmf/src/sass/map.scss
=> Set higher z-index for map messages

contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/src/layertree/component.js
=> Make Width and Heigth for GetLegendGraphic configurable

package.json
See: https://github.com/camptocamp/ngeo/runs/801810347?check_suite_focus=true
=> [security] Update webpack-dev-server 

api/src/Map.js, api/src/Themes.js
=> Localize query result in API

contribs/gmf/src/import/importdatasourceComponent.js
=> Add name to external layer services

src/print/VectorEncoder.js, test/spec/services/print.spec.js
This is an alternative to #6004
=> Use an image to print RegularShape

contribs/gmf/src/layertree/component.html
=> Add layertree icon tooltips

contribs/gmf/src/query/windowComponent.html, contribs/gmf/src/query/windowComponent.js, src/query/MapQuerent.js, src/statemanager/WfsPermalink.js
=> Removes strange and buggy functionality

src/misc/filters.js, test/spec/services/filters.spec.js
=> Don't blink on e.-g. value around 1000

contribs/gmf/src/search/component.js
=> Fix full text search colorpicker never disappears

contribs/gmf/src/datasource/ExternalDataSourcesManager.js, contribs/gmf/src/import/importdatasourceComponent.html, contribs/gmf/src/layertree/component.html, contribs/gmf/src/layertree/component.js
=> Fix Remove all on externals

contribs/gmf/src/layertree/component.html
=> Typo - Use single pipe for translation

.travis.yml
=> Use Chrome addon

package.json
=> Add chokidar requred for webpack dev server in the project

contribs/gmf/src/import/import.scss, contribs/gmf/src/import/importdatasourceComponent.js
=> Removes unwanted scrolls

contribs/gmf/src/permalink/Permalink.js
=> Fix the layers in the permalink

src/routing/RoutingComponent.js, src/routing/routing.html
Some cleaning in the routing component I found during adding per error arrows to this component (see #6225 ).
I keep the cleaning with this PR.
=> Clean routing gsgmf 1361

contribs/gmf/src/drawing/drawFeatureOptionsComponent.js, contribs/gmf/src/drawing/featureStyleComponent.html, contribs/gmf/src/drawing/featureStyleComponent.js, src/draw/Controller.js, src/format/FeatureProperties.js, src/misc/FeatureHelper.js
GSGMF-1361
Add arrow lines of drawing tools (only).
Still TODO: be able to print the arrows
--> Printing routing is also not working
=> Add arrow possibilities to line drawing

contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/dropfile/component.js, contribs/gmf/src/dropfile/dropfile.scss, contribs/gmf/src/dropfile/module.js, contribs/gmf/src/map/component.html, contribs/gmf/src/map/component.js, contribs/gmf/src/print/component.js
=> Drag/Drop Files

contribs/gmf/src/import/importdatasourceComponent.js
=> List of WMS/WMTS services when setting focus on text box

src/print/Service.js
=> Params.STYLES can present but undefined

contribs/gmf/src/layertree/SyncLayertreeMap.js, src/map/LayerHelper.js
Tested on 'ch.astra.hauptstrassennetz'
=> Opacity metadata on WMTS layers

contribs/gmf/apps/desktop/Controller.js, contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/apps/oeedit/Controller.js
Related to: https://github.com/camptocamp/c2cgeoportal/pull/7042
=> Remove no more needed for i18n string collection

Makefile, contribs/gmf/apps/desktop/header.html, contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/header.html, contribs/gmf/apps/desktop_alt/index.html.ejs
GSGMF-1394
The idea is to put the header.html file in the config container to be
able to fully customize the header without rebuilding the application.
=> Be able to customise the header

contribs/gmf/src/layertree/SyncLayertreeMap.js
=> Bug with print

api/dist/apihelp/apihelp.html, api/dist/apihelp/data.txt, api/src/Map.js
Fix GSGMF-1404
Debug 'selectObject' example in api (success callback was applied on the wrong map)
=> Fix selectObject in API

src/interaction/Measure.js, src/interaction/MeasureBaseOptions.js
This is work related to luxembourg geoportal
=> Adding ability to specify a layer in measure.

contribs/gmf/src/controllers/vars_desktop.scss
Alternative of #6438
By defining default value of the variable (same as for all other variable)
=> Add missing variable

contribs/gmf/src/query/window.scss, contribs/gmf/src/query/windowComponent.js
=> Check binding values in the init (querywindow)

contribs/gmf/src/theme/Themes.js, src/map/LayerHelper.js
=> WMTS opacity on background layers

contribs/gmf/src/layertree/timeSliderComponent.js
=> Interval timeslider with PD1

contribs/gmf/apps/desktop/index.html.ejs, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/src/controllers/AbstractDesktopController.js, contribs/gmf/src/controllers/calculateCssVars.js, contribs/gmf/test/spec/controllers/calculateCssVars.spec.js
I have a start of pull request But I don't understand why this pull request brake the query:
https://github.com/camptocamp/ngeo/pull/6660/files
It looks like that everything work fine except the class `gmf-query-grid-active` is not set here https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/apps/desktop_alt/index.html.ejs#L14
If I set it manually it's working ...
=> Fix query grid

src/editing/attributesComponent.js
GSNAT-21 (editing)
Setting default value of checkbox was not working for more than one checkbox because of the error.
=> Set boolean attributes before adding the propertychange listener

.prettierignore, .prettierrc.yaml, src/download/service.js
=> Add UTF-8 BOM

contribs/gmf/src/sass/base.scss
=> Avoid dropdown menus expanding out of viewport

contribs/gmf/src/controllers/AbstractAppController.js
To work with https://github.com/camptocamp/c2cgeoportal/pull/7660
=> Better Sentry preconfiguration

buildtools/webpack.prod.js
To fix https://github.com/camptocamp/c2cgeoportal/pull/7673/checks?check_run_id=1739738884
=> Don't minimize non js files

contribs/gmf/src/controllers/AbstractDesktopController.js
Fix the close of the left panel when using Desktop-version on Android.
=> Fix panel close

src/misc/Time.js
=> Min and max time can be null

contribs/gmf/src/authentication/component.html
=> Fix translate in markup

src/map/scaleselector.js
=> Fix typo in scale-selector log

contribs/gmf/src/authentication/component.js, contribs/gmf/src/backgroundlayerselector/component.js, contribs/gmf/src/backgroundlayerselector/status.js, contribs/gmf/src/controllers/AbstractAppController.js, contribs/gmf/src/search/component.js, contribs/gmf/src/theme/selectorComponent.js
Redo #6778 (closed per accidentally)
=> [Backport 2.6] Ignore permalink on manual background selection

docs/features.md
Fixed 2.5 new features and added 2.6 features
=> 2.5 and 2.6 update

src/print/VectorEncoder.js
=> Typo in print vector encoders

.github/workflows/main.yaml
According https://github.com/camptocamp/c2cgeoportal/blob/master/.github/workflows/ngeo-26.yaml#L7
=> Fix the event name

contribs/gmf/src/raster/component.js, contribs/gmf/src/raster/widgetComponent.html
For GSGMF-1502
That would be strange to have only the loading spinner in the button. I've put `Raster` instead. That's the same behaviors as the next button `Coordinate`. If no data is displayed (like out of CH), it displays `Coordinate`.
=> Better texts for Raster component

contribs/gmf/src/drawing/drawFeatureOptionsComponent.js
=> Fix first segment lenght on mobile

src/query/Querent.js
=> Adapt WFS-version for reading of GML2 results

contribs/gmf/src/controllers/desktop.scss
=> Tools panel fix

contribs/gmf/src/editing/editFeatureComponent.js, contribs/gmf/src/menu/MenuMultiFeature.js
=> Fix point highlight and console error

buildtools/webpack.api.js, buildtools/webpack.config.dll.js, buildtools/webpack.prod.js
=> The IDE was making as unnecessary, but it is necessary

contribs/gmf/src/query/windowComponent.js
=> Mobile query result

api/dist/apihelp/data.txt
Fix GSGMF-1558
I think I didn't need to backport that to 2.5 or less.
=> Move apihelp marker in dist

contribs/gmf/src/search/component.js
=> Do not clear search field

.github/dependabot.yaml
See: https://github.com/camptocamp/ngeo/network/updates
=> Fix duplicated entry in Dependabot configuration

contribs/gmf/examples/search.js, contribs/gmf/src/search/component.js
Also the example was not working.
=> Force update of circle

contribs/gmf/src/datasource/ExternalDataSourcesManager.js, src/datasource/OGC.js
=> External WMS query

src/datasource/OGC.js
=> With permalink upper can be NaN

src/print/VectorEncoder.js
=> Fix undefined text style for geometries imported from KML

contribs/gmf/examples/themeselector.html, contribs/gmf/src/controllers/AbstractAppController.js
=> Fix no theme after logout

contribs/gmf/src/objectediting/Query.js, contribs/gmf/src/print/LegendMapFishPrintV3.js, contribs/gmf/src/theme/Themes.js
Get the right node when the layer is in a subgroup
Fix: GSGMF-1638
=> Fix static legend on printing

contribs/gmf/src/authentication/Service.js, src/store/user.ts
Fix for the new auth component (GSGMF-1651)
In some cases, the server return a user with only some properties (like no username). I've added some checks to be sure to set the model with a complete User object.
One observation:
As RXJS make a good works, I've tried to add back the Observable on the user state (instead of a string) (in my first analyze, I was thinking that observing the state and getting the user's properties can give you only an half object of the user. It's wrong, that was the server's fault). But RXJS works procedural. In the model I set the state before the properties. If I observer the state, and try to get the properties, I get the old properties not the new. So finally I keep the state as a single string.
=> Better check that user exists

contribs/gmf/apps/appmodule.js, contribs/gmf/apps/desktop_alt/index.html.ejs, contribs/gmf/src/authentication/Service.js, src/auth/auth.css, src/auth/component.stories.ts, src/auth/component.ts, src/auth/panel.ts, src/services.js, src/store/user.ts
Implement the missing bits of the first implementation.
Uses the RxJS implementation to set the gmfUser object and get the updates and state.
Fixes few issues with the stories and add missing property to user store.
Untested: change password form.
=> Auth web-component

contribs/gmf/src/print/LegendMapFishPrintV3.js
=> Don't reverse the original array

.gitignore, .storybook/i18next.js, .tx/config.mako, Makefile, buildtools/i18next-parser.config.js, src/localize/i18n.ts
Create English translation file on build so that i18next doesn't throw an error when initializing
=> Fix initialisation i18next

buildtools/convert-translations.py, requirements.txt
[GSGMF-1670](https://jira.camptocamp.com/browse/GSGMF-1670)
=> Add tool to convert translation files

.eslintrc-ts.yaml, buildtools/codeshift-js2ts.js, buildtools/webpack.commons.js, contribs/gmf/src/controllers/bootstrap.js, package.json, src/auth/component.ts, src/store/config.spec.ts, src/store/config.ts
- Make it throw RXJS
- All the config.js will be migrated in store
=> Add a config singleton

contribs/gmf/apps/desktop_alt/Controller.js
Required for c2cgeopotal build
=> The event is unused

contribs/gmf/src/controllers/bootstrap.js, srcapi/store/config.ts
With vite in dev mode we should be able to inject 2 different Javascript...
=> Custom Javascript URL list

buildtools/doc-readme.md
The old one point to a nearly empty page
=> Fix the Theme link

buildtools/webpack.dist.js
see: https://webpack.js.org/guides/public-path/#automatic-publicpath
=> Fix public path

src/canvas/DesktopElement.ts
[GSGMF-1707](https://jira.camptocamp.com/browse/GSGMF-1707)
=> Take into account minimum panel size when resizing

.npmignore
See: https://github.com/camptocamp/c2cgeoportal/runs/4362341148?check_suite_focus=true
=> These files are required by c2cgeoportal

buildtools/webpack.dist.js, contribs/gmf/src/controllers/bootstrap.js
=> Auto is for Webpack 5 => calculate it ourself

src/canvas/DesktopElement.ts
Small fix for #7769 and ticket GSGMF-1708
=> Don't allow moving data panel when it is closed

.github/workflows/main.yaml, package.json
=> Fix peer dependency

src/canvas/DesktopElement.ts
[GSGMF-1717](https://jira.camptocamp.com/browse/GSGMF-1717)
=> Fix footer height

contribs/gmf/apps/desktop_alt/Controller.js, contribs/gmf/src/controllers/AbstractDesktopController.js
Fix: https://jira.camptocamp.com/browse/GSGMF-1715
=> Fix query on unwanted panel

contribs/gmf/src/layertree/SyncLayertreeMap.js, contribs/gmf/src/theme/Themes.js, contribs/gmf/src/themes.js, src/map/LayerHelper.js
=> Add timeout used to fetch the WMTS capabilities

src/auth/service.ts, src/drawing/drawFeatureOptionsComponent.js, src/layertree/Controller.js, src/map/LayerHelper.js, src/objectediting/geom.js, src/profile/drawLineComponent.js, src/theme/Themes.js, src/utils.js, srcapi/store/panels.ts
I suspect that's with Sentry we lost the trace...
=> Throw real exceptions

contribs/gmf/test/spec/services/treemanager.spec.js
Follow #7966 
Should fix unstable tests...
=> Fix weird 575628hashKey addition in tested theme groups

src/message/Disclaimer.js
See also: https://sentry.io/organizations/camptocamp/issues/2922536599/?environment=prod-2-6&project=1854709&query=is%3Aunresolved
=> Fix error on disclaimer not found

contribs/gmf/src/dropfile/component.js
See also: https://sentry.io/organizations/camptocamp/issues/2939475698/?environment=prod-2-6&project=1854709&query=is%3Aunresolved
=> Fix error on drop file

contribs/gmf/src/layertree/component.js
=> Debug open filter panel

.github/workflows/main.yaml
To be able to add it in the c2cgeoportal documentation.
=> Add typedoc export of config in dist

src/controllers/AbstractDesktopController.js
Fix [GSGMF-1718](https://jira.camptocamp.com/browse/GSGMF-1718)
=> Set the print panel closed when we reduce it

src/editing/attributesComponent.js
One more fix for GSGMF-1749.
Better code and avoid "sanitizing" boolean twice
I'll backport it manually in master in #8184
=> Edition: Fix undefined boolean to false

contribs/gmf/src/authentication/Service.js
Fix https://jira.camptocamp.com/browse/GSGMF-1752
=> Add missing reject in deferrableOnSuccessfulLogin

Makefile, buildtools/codeshift-js2ts.js, buildtools/codeshift-removejs.js, buildtools/extract-ngeo-dependencies, buildtools/i18next-parser.config.js, buildtools/webpack.commons.js, docs/guidelines.md, package.json, src/themes.js, srcapi/store/config.ts, tsconfig-eslint.json, tsconfig.json, typedoc.json
https://jira.camptocamp.com/browse/GSGMF-1755
=> Remove all references to contribs/gmf/src

src/lidar/Utils.ts
Fix [GSGMF-1775](https://jira.camptocamp.com/browse/GSGMF-1775)
=> Fix LIDAR PNG export error

src/drawing/featureStyleComponent.html, src/misc/FeatureHelper.js
According to the feedback in [GSGMF-1800](https://jira.camptocamp.com/browse/GSGMF-1800) (point 1)
=> Fix arrows drawing keys for translations

contribs/gmf/examples/options.js, contribs/gmf/src/editing/Snapping.js, contribs/gmf/src/options.js
Fix [GSGMF-1776](https://jira.camptocamp.com/browse/GSGMF-1776)
=> Add gmfSnappingOptions to configure maxFeatures for snapping

src/sass/vars_only.scss
Fix [GSGMF-1808](https://jira.camptocamp.com/browse/GSGMF-1808)
=> Set grid-gutter-width variable in the CSS

contribs/gmf/apps/desktop/index.html.ejs
Blind me forgot an interface ... follow-up of #8439 
2.6 was already fixed in the backport.
=> Makes body element focusable for onKeyDown event (for desktop interface)

src/controllers/AbstractDesktopController.js
Fix [GSGMF-1807](https://jira.camptocamp.com/browse/GSGMF-1807) point 4
=> Correctly disable the LIDAR button when the panel is collapsed

src/auth/PanelElement.ts
Fix both browsers for [GSGMF-1822](https://jira.camptocamp.com/browse/GSGMF-1822)
=> Fix the theme loading message spinner in Auth panel

src/lidar/Manager.ts
Fix [GSGMF-1830](https://jira.camptocamp.com/browse/GSGMF-1830)
Fix as well issue with the droplist "material" on value "couleur" that was bugged.
=> Fix CSV export with undefined packed_color attribute error

src/lidar/Utils.ts
Fix [GSGMF-1831](https://jira.camptocamp.com/browse/GSGMF-1831)
=> Fix error on LIDAR PNG export with depreciated btoa function

src/auth/FormElement.ts
Fix [GSGMF-1824](https://jira.camptocamp.com/browse/GSGMF-1824)
=> Consume event to not redirect the page when clicking on password forgotten link

src/controllers/AbstractDesktopController.js
Fix [GSGMF-1825](https://jira.camptocamp.com/browse/GSGMF-1825)
=> Do not close the auth panel in first login process

src/lidar/PanelElement.ts, src/lidar/Utils.ts
Fix [GSGMF-1836](https://jira.camptocamp.com/browse/GSGMF-1836)
=> Send an alert if the LIDAR graph is empty when exporting in CSV/PNG

src/controllers/mobile.scss
Fix [GSGMF-1829](https://jira.camptocamp.com/browse/GSGMF-1829)
=> Fix z-index of mobile buttons to not be overlapped by swipper element

src/controllers/AbstractDesktopController.js
Fix [GSGMF-1842](https://jira.camptocamp.com/browse/GSGMF-1842)
=> Re-allow the panel to open when logged

src/lidar/Manager.ts
This reverts commit 11ebff55b92e416e45f8791505c6b51135b9d473.
=> Revert "Fix CSV export with undefined packed_color attribute error"

src/auth/FormElement.ts
Fix [GSGMF-1843](https://jira.camptocamp.com/browse/GSGMF-1843)
=> Fix the changePassword form

src/options.js, srcapi/store/config.ts
Fix [GSGMF-1845](https://jira.camptocamp.com/browse/GSGMF-1845)
=> Remove projection option from map object as it is set on the view

src/lidar/PanelElement.ts, src/lidar/Utils.ts
Fix [GSGMF-1858](https://jira.camptocamp.com/browse/GSGMF-1858)
=> Correctly remove the buffer (redline) when closing the LIDAR footer

src/lidar/FooterElement.ts, srcapi/store/config.ts
Because I saw it was missing. :-)
=> Add custom CSS for LIDAR footer web component

srcapi/elements/BaseElement.ts
Fix [GSGMF-1874](https://jira.camptocamp.com/browse/GSGMF-1874)
=> Correctly apply styling for <a> elements in web component default style

contribs/gmf/src/layertree/TreeManager.js
Follow https://github.com/camptocamp/ngeo/pull/8264
=> Sync map during refreshFirstLevelGroups_

src/layertree/TreeManager.js
Implements [GSGMF-1892](https://jira.camptocamp.com/browse/GSGMF-1892)
=> Be able to have second-level group active when added with FTS

src/controllers/desktop.scss, src/filter/rulecomponent.html, src/sass/filters.scss
Fix [GSGMF-1891](https://jira.camptocamp.com/browse/GSGMF-1891)
=> Add labels to number field for directedFilterAttributes

src/filters/filterselectorComponent.js
Fix [GSGMF-1900](https://jira.camptocamp.com/browse/GSGMF-1900)
=> Allow the filter button to open the panel from the layertree

src/permalink/shareComponent.html
=> Fix multiline messages

src/print/LegendMapFishPrintV3.js
Fix [GSGMF-1910](https://jira.camptocamp.com/browse/GSGMF-1910)
=> Fix layer changing order when printing with legend

contribs/gmf/src/options.js, contribs/gmf/src/query/windowComponent.html
See https://jira.camptocamp.com/browse/GEO-6034
=> Add gmfDisplayQueryWindowOptions.displayNullAttributes

src/auth/service.ts, src/print/component.js
[GSGMF-1934](https://jira.camptocamp.com/browse/GSGMF-1934)
=> Add username to print spec

buildtools/i18next-parser.config.js
Empty string is considered by trasifex as nothing to translate...
=> Fix the default value

src/controllers/bootstrap.js
For: https://jira.camptocamp.com/browse/GSTOTAL-10
=> Fix simple bootstrap

.github/workflows/main.yaml, README.md
Add/update pre-commit hooks generated by add-pre-commit-hooks command
=> Add/update pre-commit hooks

src/datasource/Manager.js
=> Allow dimensions to be passed for WMS layers in background group

api/src/Map.js, contribs/gmf/examples/options.js, contribs/gmf/test/spec/beforeeach.js, examples/options.js, src/controllers/AbstractAppController.js, src/layertree/SyncLayertreeMap.js, src/options.js, src/proj/EPSG_2056.js, src/proj/EPSG_21781.js, src/proj/utils.js, src/theme/Themes.js
Server part: https://github.com/camptocamp/c2cgeoportal/pull/10476
=> Fix blurry WMS and WMTS layers

.github/workflows/main.yaml
See: https://securitylab.github.com/research/github-actions-untrusted-input/
=> Fix untrusted input

src/controllers/AbstractAppController.js, src/permalink/Permalink.js, srcapi/store/config.ts
Fix second case of https://jira.camptocamp.com/browse/GSGMF-2009?focusedCommentId=301940&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-301940
=> Constraint map pixel on grid pixel

src/controllers/AbstractAppController.js
This is to get a WMS GetMap aligned to the grid after a zoom.
=> Fix the center on animation end 

src/permalink/Permalink.js
=> Don't put the default value in the layertree

src/auth/FormElement.ts
=> Add OTP field to login request if 2FA is activated

api/src/Map.js
The style should be set to null or a falsy value (see Openlayers doc on [select interaction](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select.html))
=> Do not change style of selected feature

src/datasource/ExternalDataSourcesManager.js, src/datasource/Manager.js, src/datasource/OGC.js, src/options.js, srcapi/store/config.ts
It also needs this configuration:
https://github.com/camptocamp/demo_geomapfish/commit/0ec81ddd8c55553fc016ac712a380a23fed54d05
=> Support application/geo+json

src/controllers/AbstractAppController.js
=> Fix error on search result selection with coordinates search

src/permalink/Permalink.js
Test with: https://camptocamp.github.io/ngeo/refs/pull/9298/merge/examples/contribs/gmf/apps/desktop_alt.html?themes=cadastre&lang=fr&map_x=2632520&map_y=1185430&map_zoom=3&tree_group_opacity_Group=0.65&tree_group_layers_Layers=post_office&tree_group_layers_Layers-exclusive=post_office&tree_group_layers_Group=&tree_group_layers_OSM%20functions=&tree_group_layers_Filters=&baselayer_ref=OSM%20map&theme=Cadastre&tree_enable_asitvd.fond_pourortho=false&dim_FLOOR=*&baselayer_opacity=0&tree_groups=Cadastre%2CBS%20WMTS&tree_enable_ch.swisstopo.dreiecksvermaschung=true
=> Fix open panel on private layer of a public block

src/datasource/ExternalDataSourcesManager.js, src/import/wmtsCapabilityLayertreeComponent.js, src/permalink/Permalink.js
Replacement of the unworking  #9325
See JIRA issue: [GEO-6913](https://jira.camptocamp.com/browse/GEO-6913).
=> Fix WMTS layer opacity from permalink

src/objectediting/component.js
See JIRA issue: [GEO-7330](https://jira.camptocamp.com/browse/GEO-7330).
=> The clone can be null

src/layertree/SyncLayertreeMap.js, src/permalink/Permalink.js
See JIRA issue: [GEO-6913](https://jira.camptocamp.com/browse/GEO-6913).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9355/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9355/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9355/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9355/merge/apidoc/)
=> Fix tree state from permalink

.github/renovate.json5
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9435/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9435/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9435/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9435/merge/apidoc/)
=> Renovate: create a group for Webpack

.github/renovate.json5
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9436/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9436/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9436/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9436/merge/apidoc/)
=> Renovate: Have multiple pull request on different major versions

.github/renovate.json5
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9439/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9439/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9439/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9439/merge/apidoc/)
=> Renovate: Includes more packages in the Webpack group

buildtools/check-example.js
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9465/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9465/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9465/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9465/merge/apidoc/)
=> Don't hide error, no error loop

buildtools/check-example.js
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9468/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9468/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9468/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9468/merge/apidoc/)
=> Avoid unnecessary additional error

.npmignore
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9473/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9473/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9473/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9473/merge/apidoc/)
=> Clean the exported package

.npmignore, package.json
The SCSS files were not copied, remove extra apidoc. 
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9479/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9479/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9479/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9479/merge/apidoc/)
=> Fix package content

src/print/VectorEncoder.js
To test, the KML is in this ticket:
https://camptocamp.atlassian.net/issues/GSSIT-115
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9509/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9509/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9509/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9509/merge/apidoc/)
=> Fix printing KML with Polygon fill to null

src/controllers/common.scss, src/controllers/desktop.scss, src/controllers/mobile.scss
Slow spinner instead of blocked spinner
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9511/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9511/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9511/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9511/merge/apidoc/)
=> Better reduced-motion

package.json
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9513/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9513/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9513/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9513/merge/apidoc/)
=> Don't have duplicated files in dist folder

srcapi/elements/ToolButtonElement.ts
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9522/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9522/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9522/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9522/merge/apidoc/)
=> Fix tooltip/jquery on ngeo standalone

.github/workflows/main.yaml
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9521/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9521/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9521/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9521/merge/apidoc/)
=> Cleanup CI

buildtools/webpack.prod.js
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9524/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9524/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9524/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9524/merge/apidoc/)
=> Fix the mobile and iframe API production build

src/controllers/AbstractAppController.js
See JIRA issue: [GSGMF-2113](https://jira.camptocamp.com/browse/GSGMF-2113).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9572/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9572/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9572/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9572/merge/apidoc/)
[GSGMF-2113]: https://camptocamp.atlassian.net/browse/GSGMF-2113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix north arrow icon

src/lidar/Utils.ts
See JIRA issue: [GSGMF-2124](https://jira.camptocamp.com/browse/GSGMF-2124).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9575/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9575/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9575/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9575/merge/apidoc/)
[GSGMF-2124]: https://camptocamp.atlassian.net/browse/GSGMF-2124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix buffer is not defined

src/canvas/DesktopElement.ts
See JIRA issue: [GSGMF-2117](https://jira.camptocamp.com/browse/GSGMF-2117).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9574/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9574/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9574/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9574/merge/apidoc/)
[GSGMF-2117]: https://camptocamp.atlassian.net/browse/GSGMF-2117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix the close button is behind the title

src/auth/ButtonElement.ts
See JIRA issue: [GSGMF-2122](https://jira.camptocamp.com/browse/GSGMF-2122).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9573/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9573/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9573/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9573/merge/apidoc/)
[GSGMF-2122]: https://camptocamp.atlassian.net/browse/GSGMF-2122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix login icon

src/streetview/MapillaryService.js
Backport of #9553 
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9581/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9581/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9581/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9581/merge/apidoc/)
=> Use geometry field instead of computed_geometry in Mapillary

src/auth/FormElement.ts, src/options.js, srcapi/store/config.ts
See JIRA issue: [GSGGR-267](https://jira.camptocamp.com/browse/GSGGR-267).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9585/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9585/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9585/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9585/merge/apidoc/)
[GSGGR-267]: https://camptocamp.atlassian.net/browse/GSGGR-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a link to user information on OIDC server

src/geolocation/component.js
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9586/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9586/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9586/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9586/merge/apidoc/)
=> Disable tracking based on distance in pixel

Makefile, README.md
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9570/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9570/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9570/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9570/merge/apidoc/)
=> Fix npm install on Ubuntu 24.04

src/canvas/DesktopElement.ts
See JIRA issue: [GSGMF-2123](https://jira.camptocamp.com/browse/GSGMF-2123).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9605/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9605/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9605/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9605/merge/apidoc/)
[GSGMF-2123]: https://camptocamp.atlassian.net/browse/GSGMF-2123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Store the tools panel size

.github/workflows/main.yaml, Makefile
I didn't succeed to build without those new options!
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9617/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9617/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9617/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9617/merge/apidoc/)
=> Be able to build

buildtools/compile-catalog.js
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9618/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9618/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9618/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9618/merge/apidoc/)
=> Add a message to be able to debug c2cgeoportal

Makefile, src/drawing/drawFeatureComponent.js, src/editing/editFeatureComponent.js, src/filter/ruleComponent.js, src/statemanager/WfsPermalink.js
See JIRA issue: [GSGMF-2145](https://jira.camptocamp.com/browse/GSGMF-2145).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9629/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9629/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9629/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9629/merge/apidoc/)
[GSGMF-2145]: https://camptocamp.atlassian.net/browse/GSGMF-2145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Font Awesome moving icon

src/layertree/component.html.js
See JIRA issue: [GSGMF-2149](https://jira.camptocamp.com/browse/GSGMF-2149).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9630/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9630/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9630/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9630/merge/apidoc/)
[GSGMF-2149]: https://camptocamp.atlassian.net/browse/GSGMF-2149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove extra char

src/print/VectorEncoder.js
See also: https://camptocamp.atlassian.net/issues/GSSIT-115
See JIRA issue: [GSGMF-2152](https://jira.camptocamp.com/browse/GSGMF-2152).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9633/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9633/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9633/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9633/merge/apidoc/)
[GSGMF-2152]: https://camptocamp.atlassian.net/browse/GSGMF-2152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix black outline on drawn polygon with annotation

Makefile, src/auth/FormElement.ts
See JIRA issue: [GSGMF-2157](https://jira.camptocamp.com/browse/GSGMF-2157).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9644/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9644/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9644/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9644/merge/apidoc/)
[GSGMF-2157]: https://camptocamp.atlassian.net/browse/GSGMF-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix application context on OIDC login

buildtools/compile-catalog.js
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9651/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9651/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9651/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9651/merge/apidoc/)
=> Add argument to fix c2cgeoportal CI

.github/renovate.json5
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9682/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9682/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9682/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9682/merge/apidoc/)
=> Add version 2.9 in Renovate configuration

.github/workflows/main.yaml
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9698/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9698/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9698/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9698/merge/apidoc/)
=> Clean the branch before writing on it

Makefile, src/print/Service.js
See JIRA issue: [GSAPR-205](https://jira.camptocamp.com/browse/GSAPR-205).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9722/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9722/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9722/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9722/merge/apidoc/)
[GSAPR-205]: https://camptocamp.atlassian.net/browse/GSAPR-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Send optional VERSION from OGCServer URL in print spec

contribs/gmf/apps/desktop_alt/index.html.ejs
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9736/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9736/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9736/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9736/merge/apidoc/)
=> Put the class in the right place

src/print/Service.js
See JIRA issue: [GSGMF-2164](https://jira.camptocamp.com/browse/GSGMF-2164).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9744/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9744/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9744/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9744/merge/apidoc/)
[GSGMF-2164]: https://camptocamp.atlassian.net/browse/GSGMF-2164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Be able to print OGCServer type other

.github/renovate.json5
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9772/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9772/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9772/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9772/merge/apidoc/)
=> Renovate: Separate TypeScript

.github/renovate.json5
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9774/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9774/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9774/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9774/merge/apidoc/)
=> Renovate: Fix Python versions group

src/auth/FormElement.ts, srcapi/store/user.ts
See JIRA issue: [GSGMF-2168](https://jira.camptocamp.com/browse/GSGMF-2168).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9775/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9775/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9775/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9775/merge/apidoc/)
[GSGMF-2168]: https://camptocamp.atlassian.net/browse/GSGMF-2168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Use the display-name in the login panel

.github/ghci.yaml
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9801/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9801/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9801/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9801/merge/apidoc/)
=> Configure GHCI clean module

src/options.js
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9819/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9819/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9819/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9819/merge/apidoc/)
=> Add goodnessOfFit documentation

src/filter/RuleHelper.js
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9842/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9842/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9842/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9842/merge/apidoc/)
=> Expand date boundaries to support broader time ranges

package.json, src/datasource/Helper.js, src/datasource/OGC.js
See JIRA issue: [GSGEOC-436](https://jira.camptocamp.com/browse/GSGEOC-436).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9864/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9864/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9864/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9864/merge/apidoc/)
[GSGEOC-436]: https://camptocamp.atlassian.net/browse/GSGEOC-436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix for non querryable layer

src/query/windowComponent.html.js
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9870/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9870/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9870/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9870/merge/apidoc/)
=> Fix close button icon in query window

src/auth/FormElement.ts, srcapi/store/config.ts
See JIRA issue: [GSGMF-2178](https://jira.camptocamp.com/browse/GSGMF-2178).
[Examples](https://camptocamp.github.io/ngeo/refs/pull/9939/merge/examples/)
[Storybook](https://camptocamp.github.io/ngeo/refs/pull/9939/merge/storybook/)
[API help](https://camptocamp.github.io/ngeo/refs/pull/9939/merge/api/apihelp/apihelp.html)
[API documentation](https://camptocamp.github.io/ngeo/refs/pull/9939/merge/apidoc/)
[GSGMF-2178]: https://camptocamp.atlassian.net/browse/GSGMF-2178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Better message on reset password
